import { UnderlineText, SquareRoot, superscript, subscript, BoldText, ItalicText, Fraction, ShortFraction, LongFraction, MixedFraction, Isotopes } from "@/mathnotation"

export const ENGLISHLANGUAGEA2018 = [

{
instruction: "In each of the following sentences, there is a word underlined and one gap. From the list of words lettered A to D, choose the word that is most nearly opposite in meaning to the underlined word and that will at the same time, correctly fill the gap in the sentence.",
id: "question1",
question: ["1. The ", <UnderlineText key={"1"} text={"wilting"}/>, " plants were _________________ by the recent rains."],
A: "destroyed",
B: "cleared",
C: "revived",
D: "drowned",
answer: "C. revived",
correctLetter: "C",
correctOption: 3,
},

{
id: "question2",
question: ["2. The ", <UnderlineText key={"1"} text={"tranquility"}/>, " of the rural areas contrasts with the _________________ in the cities."],
A: "pollution",
B: "panic",
C: "unease",
D: "noise",
answer: "D. noise",
correctLetter: "D",
correctOption: 4,
},

{
id: "question3",
question: ["3. The ", <UnderlineText key={"1"} text={"greedy"}/>, " man took advantage the woman’s _________________ ."],
A: "naivety",
B: "generosity",
C: "calmness",
D: "vulnerability",
answer: "B. generosity",
correctLetter: "B",
correctOption: 2,
},

{
id: "question4",
question: ["4. While the children were ", <UnderlineText key={"1"} text={"agitated"}/>, " by the news, their parents were very _________________ ."],
A: "indifferent",
B: "happy",
C: "composed",
D: "satisfied.",
answer: "C. composed",
correctLetter: "C",
correctOption: 3,
},

{
id: "question5",
question: ["5. There will not be any more food ", <UnderlineText key={"1"} text={"shortage"}/>, " after the _________________ harvest."],
A: "vast",
B: "satisfactory",
C: "bumper",
D: "average",
answer: "C. bumper",
correctLetter: "C",
correctOption: 3,
},

{
id: "question6",
question: ["6. Do not ", <UnderlineText key={"1"} text={"scatter"}/>, " the books on the table _________________ them neatly on the shelves."],
A: "pack",
B: "keep",
C: "arrange",
D: "mount",
answer: "A. pack",
correctLetter: "A",
correctOption: 1,
},

{
id: "question7",
question: ["7. The manager will ", <UnderlineText key={"1"} text={"lay"}/>, " off the experienced staff and _________________ new ones."],
A: "promote",
B: "accept",
C: "recommend",
D: "engage",
answer: "D. engage",
correctLetter: "D",
correctOption: 4,
},

{
id: "question8",
question: ["8. The chief executive officer is ", <UnderlineText key={"1"} text={"strict"}/>, " with his staff, while the deputy is  _________________"],
A: "co-operate",
B: "nice",
C: "lax",
D: "sympathetic",
answer: "D. sympathetic",
correctLetter: "D",
correctOption: 4,
},

{
id: "question9",
question: ["9. Do not ", <UnderlineText key={"1"} text={"indulge"}/>, " in this malpractice anymore; _________________ from it."],
A: "withdraw",
B: "depart",
C: "resist",
D: "abstain",
answer: "D. abstain",
correctLetter: "D",
correctOption: 4,
},

{
id: "question10",
question: ["10. Rather than _________________ the issues, his comments ", <UnderlineText key={"1"} text={"confused"}/>, " the audience the more."],
A: "resolve",
B: "clarify",
C: "clear",
D: "solve",
answer: "B. clarify",
correctLetter: "B",
correctOption: 2,
},

{
section: "II",
instruction: "From the words lettered A to D, choose the one that best completes each of the following sentences.",
id: "question11",
question: "11. Aba’s mother _________________ her for being rude.",
A: "angered",
B: "rebuked",
C: "incriminated",
D: "abused",
answer: "B. rebuked",
correctLetter: "B",
correctOption: 2,
},

{
id: "question12",
question: "12. Every year, the armed forces _________________ thousands of persons into the army.",
A: "enlists",
B: "hires",
C: "accepts",
D: "admits",
answer: "A. enlists",
correctLetter: "A",
correctOption: 1,
},

{
id: "question13",
question: "13. That pastor always preaches sermons that will win more _________________.",
A: "activists",
B: "adherents",
C: "converts",
D: "convicts",
answer: "C. converts",
correctLetter: "C",
correctOption: 3,
},

{
id: "question14",
question: "14. The children _________________ their laughter when they saw the look on their father’s face.",
A: "constrained",
B: "subjugated",
C: "censored",
D: "suppressed",
answer: "D. suppressed",
correctLetter: "D",
correctOption: 4,
},

{
id: "question15",
question: "15. Lions are _________________ eaters.",
A: "vivacious",
B: "voracious",
C: "veracious",
D: "voluminous",
answer: "B. voracious",
correctLetter: "B",
correctOption: 2,
},

{
id: "question16",
question: "16. A _________________ housewife never cooks more food than is needed.",
A: "frugal",
B: "fruitful",
C: "grudging",
D: "greedy",
answer: "A. frugal",
correctLetter: "A",
correctOption: 1,
},

{
id: "question17",
question: "17. After eating for the tenth time, those boys finally _________________ ",
A: "gave off",
B: "gave up",
C: "rounded up",
D: "rounded off",
answer: "B. gave up",
correctLetter: "B",
correctOption: 2,
},

{
id: "question18",
question: "18. _________________ his inefficiency, he was a successful business man.",
A: "But for",
B: "Except for",
C: "Contrary to",
D: "In spite of",
answer: "D. In spite of",
correctLetter: "D",
correctOption: 4,
},

{
id: "question19",
question: "19. There are certain _________________ between the two accounts of the incidence.",
A: "diversities",
B: "distortions",
C: "discrepancies",
D: "discriminations",
answer: "C. discrepancies",
correctLetter: "C",
correctOption: 3,
},

{
id: "question20",
question: "20. His natural modesty always inclined him to _________________ his own achievements.",
A: "play down",
B: "play back",
C: "play up",
D: "play on",
answer: "C. play up",
correctLetter: "C",
correctOption: 3,
},

{
section: "III",
instruction: "Choose from the alternatives A to D, the one which is nearest in meaning to the underlined word or expression in each sentence.",
id: "question21",
question: ["21. The ", <UnderlineText key={"1"} text={"aftermath"}/>, " of the disaster is still with us."],
A: "cause",
B: "result",
C: "climax",
D: "conclusion",
answer: "B. result",
correctLetter: "B",
correctOption: 2,
},

{
id: "question22",
question: ["22. Mabel’s statement ", <UnderlineText key={"1"} text={"corroborated"}/>, " the evidence before the judge."],
A: "explained",
B: "supported",
C: "collaborated",
D: "contradicted",
answer: "B. supported",
correctLetter: "B",
correctOption: 2,
},

{
id: "question23",
question: ["23. He found the proposal ", <UnderlineText key={"1"} text={"distasteful."}/>, ""],
A: "unappealing",
B: "tasteless",
C: "disagreeable",
D: "discouraging",
answer: "A. unappealing",
correctLetter: "A",
correctOption: 1,
},

{
id: "question24",
question: ["24. They refused to ", <UnderlineText key={"1"} text={"divulge"}/>, " their plans."],
A: "tell",
B: "reveal",
C: "denounce",
D: "voice",
answer: "B. reveal",
correctLetter: "B",
correctOption: 2,
},

{
id: "question25",
question: ["25. The police officers are ", <UnderlineText key={"1"} text={"relentless"}/>, " in their efforts to maintain peace."],
A: "inhumane",
B: "untiring",
C: "answering",
D: "merciless",
answer: "B. untiring",
correctLetter: "B",
correctOption: 2,
},

{
id: "question26",
question: ["26. The opinion expressed by that panelist was quite ", <UnderlineText key={"1"} text={"controversial."}/>, ""],
A: "debatable",
B: "serious",
C: "important",
D: "superficial",
answer: "A. debatable",
correctLetter: "A",
correctOption: 1,
},

{
id: "question27",
question: ["27. The landlord had to ", <UnderlineText key={"1"} text={"eject"}/>, " the tenant from his house."],
A: "expel",
B: "debar",
C: "remove",
D: "evict",
answer: "A. expel",
correctLetter: "A",
correctOption: 1,
},

{
id: "question28",
question: ["28. Selma is a good girl; she is not one of the ", <UnderlineText key={"1"} text={"incorrigibleones."}/>, ""],
A: "stubborn",
B: "hard",
C: "wild",
D: "incredulous",
answer: "A. stubborn",
correctLetter: "A",
correctOption: 1,
},

{
id: "question29",
question: ["29. The students felt ", <UnderlineText key={"1"} text={"dejected"}/>, " when their favourite teacher was transferred."],
A: "rejected",
B: "disappointed",
C: "frustrated",
D: "suppressed",
answer: "B. disappointed",
correctLetter: "B",
correctOption: 2,
},

{
id: "question30",
question: ["30. Hermits are not interested in ", <UnderlineText key={"1"} text={"secular"}/>, " matters."],
A: "physical",
B: "trivial",
C: "worldly",
D: "religious",
answer: "C. worldly",
correctLetter: "C",
correctOption: 3,
},

{
section: "IV",
instruction: "After each of the following sentences, a list of possible interpretations of all or part of the sentence is given. Choose the interpretation you consider most appropriate for each sentence.",
id: "question31",
question: "31. The traders are cashing in on the increased number of buyers to prices. This means that",
A: "the traders brought along a lot cash.",
B: "the traders have more cash to import goods.",
C: "the traders are taking advantage of the numerous buyers.",
D: "the traders have become very rich.",
answer: "C. the traders are taking advantage of the numerous buyers",
correctLetter: "C",
correctOption: 3,
},

{
id: "question32",
question: "32. Although Jones had no leadership abilities, be refused to play second fiddle in the group. This means Jones",
A: "saw himself as leader.",
B: "was made the leader.",
C: "took a subordinate position.",
D: "co-operated with others.",
answer: "B. was made the leader",
correctLetter: "B",
correctOption: 2,
},

{
id: "question33",
question: "33. Koku’s father’s colleagues always recognize him because he is a chip off the old block. This means that Koku is",
A: "not like his father.",
B: "an image of his father",
C: "older than they thought.",
D: "co-operated with others.",
answer: "B. an image of his father",
correctLetter: "B",
correctOption: 2,
},

{
id: "question34",
question: "34. AdjoaAkoto was admonished to paddle her own canoe. This means the AdjoaAkoto should.",
A: "be in charge of the business",
B: "place her interest first.",
C: "manage her own affairs.",
D: "be more serious with life",
answer: "C. manage her own affairs",
correctLetter: "C",
correctOption: 3,
},

{
id: "question35",
question: "35. The opportunity slipped through my fingers. This means that I",
A: "did not make use of it.",
B: "preferred another option.",
C: "expected something better.",
D: "wanted to be more careful.",
answer: "A. did not make use of it",
correctLetter: "A",
correctOption: 1,
},

{
id: "question36",
question: "36. I did all I could to amuse him but he kept a straight face. This means that he",
A: "was not convinced.",
B: "remained adamant.",
C: "refused to laugh.",
D: "did not listen to me",
answer: "A. did not make use of it",
correctLetter: "A",
correctOption: 1,
},

{
id: "question37",
question: "37. Who to lead the group, became our bone of contention. This means",
A: "there was a quarrel.",
B: "there was no consensus.",
C: "there was a postponement.",
D: "there was no appointment",
answer: "B. there was no consensus",
correctLetter: "B",
correctOption: 2,
},

{
id: "question38",
question: "38. The new salary increases were across the board. This means that the increases",
A: "were very impressive.",
B: "affected all workers",
C: " ",
D: " ",
answer: "Z. ", 
correctLetter: "Z",
correctOption: 9,
},
{
id: "question39",
question: "39. The auctioneer sold the Jeep for a song. This means that the Jeep.",
A: "was sold at high price.",
B: "did not attract many bidders.",
C: "was sold very cheaply.",
D: "was sold off very quickly",
answer: "C. was sold very cheaply",
correctLetter: "C",
correctOption: 3,
},

{
id: "question40",
question: "40. Nii Ankrah’s limousine has seen better days. This means that Nii Ankrah’s car",
A: "has been refurbished.",
B: "is now old.",
C: "used to break down.",
D: "has served him well.",
answer: "B. is now old",
correctLetter: "B",
correctOption: 2,
},

{
section: "V",
instruction: "In the following passage, the number gaps indicate missing words. Against each number in the in the list below the passage, four choices are offered in columns lettered A to D. For each numbered gap, choose from the options provided for that number, the word is most suitable to fill the gap.",
passage: "Countries all over the world, rely on their -41- resources for their development. Those resources vary from country to country. The discovery of crude oil -42- in any country is greeted with excitement because it is considered a valuable source of -43- for the government. \NOnce it has been discovered by -44-, who would have been prospecting for it, an oil -45- is drilled until the petroleum reservoir is reached. \NNatural -46-, another valuable resource, may be found at the same time. -47- oil is usually conveyed through a -48- directly to the -49- where it is processed. Here, petrol, diesel, kerosene, liquefied petroleum gas, and lubricants are produced for domestic and industrial use. Scientists have obtained other -50- substances from petroleum, for example, man-made fibres like nylon which may be woven into beautiful fabrics for clothes.",
id: "question41",
question: "41. *********************",
A: "Rich",
B: "Profitable",
C: "Natural",
D: "Vast",
answer: "C. Natural",
correctLetter: "C",
correctOption: 3,
},

{
id: "question42",
question: "42. *********************",
A: "Reserves",
B: "Stocks",
C: "Preserves",
D: "Stores",
answer: "A. Reserves",
correctLetter: "A",
correctOption: 1,
},

{
id: "question43",
question: "43. *********************",
A: "Savings",
B: "Revenue",
C: "Salary",
D: "Accounts",
answer: "B. Revenue",
correctLetter: "B",
correctOption: 2,
},

{
id: "question44",
question: "44. *********************",
A: "Geologists",
B: "Ecologists",
C: "Anthropologists",
D: "Archaeologists",
answer: "A. Geologists",
correctLetter: "A",
correctOption: 1,
},

{
id: "question45",
question: "45. *********************",
A: "Rig",
B: "Well",
C: "Plant",
D: "Hole",
answer: "B. Well",
correctLetter: "B",
correctOption: 2,
},

{
id: "question46",
question: "46. *********************",
A: "Liquid",
B: "Gas",
C: "Carbon",
D: "Chemical",
answer: "B. Gas",
correctLetter: "B",
correctOption: 2,
},

{
id: "question47",
question: "47. *********************",
A: "Undiluted",
B: "Crude",
C: "Unfinished",
D: "Raw",
answer: "B. Tube",
correctLetter: "B",
correctOption: 2,
},

{
id: "question48",
question: "48. *********************",
A: "Tunnel",
B: "Tube",
C: "Hose",
D: "Pipeline",
answer: "D. Pipeline",
correctLetter: "D",
correctOption: 4,
},

{
id: "question49",
question: "49. *********************",
A: "Purifier",
B: "Factory",
C: "Industry",
D: "Refinery",
answer: "D. Refinery",
correctLetter: "D",
correctOption: 4,
},

{
id: "question50",
question: "50. *********************",
A: "Artificial",
B: "Authentic",
C: "Synthetic",
D: "Inferior",
answer: "C. Synthetic",
correctLetter: "C",
correctOption: 3,
},



]