import {UnderlineText, SquareRoot, superscript, subscript, BoldText, ItalicText, Fraction, ShortFraction, LongFraction, MixedFraction, Isotopes } from "@/mathnotation"

export const ENGLISHLANGUAGEA2013 = [


    
{
instruction: "In each of the following sentences, there is a word underlined and one gap. From the list of words lettered A to D, choose the word that is most nearly opposite in meaning to the underlined word and that at the same time, correctly fill the gap in the sentence.",
id: "question1",
question: ["1. The students were ", <UnderlineText key={"1"} text={"angry"}/>, " at his lateness, but were _________________ when he apologised."],
A: "certain",
B: "reassured",
C: "pleased",
D: "quiet",
answer: "C. pleased",
correctLetter: "C",
correctOption: 3,
},

{
id: "question2",
question: ["2. The drains have become _________________ because the road is now ", <UnderlineText key={"1"} text={"wide."}/>, ""],
A: "small",
B: "narrow",
C: "light",
D: "reduced",
answer: "B. narrow",
correctLetter: "B",
correctOption: 2,
},

{
id: "question3",
question: ["3. As they explored the caves, they ", <UnderlineText key={"1"} text={"unearthed"}/>, " previously _________________ artifacts."],
A: "known",
B: "hidden",
C: "sought",
D: "visited",
answer: "B. hidden",
correctLetter: "B",
correctOption: 2,
},

{
id: "question4",
question: ["4. The ", <UnderlineText key={"1"} text={"serenity"}/>, " of the countryside contrasted sharply with the _________________ in the city."],
A: "anxiety",
B: "panic",
C: "struggle",
D: "turmoil",
answer: "D. turmoil",
correctLetter: "D",
correctOption: 4,
},

{
id: "question5",
question: ["5. It is easier to ", <UnderlineText key={"1"} text={"destroy"}/>, " than to _________________ ."],
A: "make",
B: "arrange",
C: "build",
D: "manage",
answer: "C. build",
correctLetter: "C",
correctOption: 3,
},

{
id: "question6",
question: ["6. We are trying to ", <UnderlineText key={"1"} text={"attract"}/>, " them, not to _________________ them."],
A: "dismiss",
B: "refuse",
C: "scorn",
D: "reject",
answer: "D. reject",
correctLetter: "D",
correctOption: 4,
},

{
id: "question7",
question: ["7. We thought that the signature was ", <UnderlineText key={"1"} text={"genuine"}/>, " but it turned out to be_________________ ."],
A: "incorrect",
B: "fake",
C: "false",
D: "wrong",
answer: "B. fake",
correctLetter: "B",
correctOption: 2,
},

{
id: "question8",
question: ["8. Some people live in ", <UnderlineText key={"1"} text={"affluence,"}/>, " others in _________________"],
A: "pain",
B: "poverty",
C: "difficulty",
D: "scarcity",
answer: "B. poverty",
correctLetter: "B",
correctOption: 2,
},

{
id: "question9",
question: ["9. Sometimes life is ", <UnderlineText key={"1"} text={"stormy"}/>, " but at other times it is_________________ .."],
A: "stable",
B: "calm",
C: "clear",
D: "dull",
answer: "A. stable",
correctLetter: "A",
correctOption: 1,
},

{
id: "question10",
question: ["10. We have been advised not to do things that are ", <UnderlineText key={"1"} text={"abominable"}/>, " but things that are _________________"],
A: "pleasant",
B: "strange",
C: "popular",
D: "meaningful",
answer: "A. pleasant",
correctLetter: "A",
correctOption: 1,
},

{
section: "II",
sectiontitle: "From the list of words lettered A to D. choose the one that best completes each of the following sentences.",
id: "question11",
question: "11. The suspect was acquitted and_________________ for lack of evidence.",
A: "left",
B: "dismissed",
C: "discharged",
D: "cleared",
answer: "C. discharged",
correctLetter: "C",
correctOption: 3,
},

{
id: "question12",
question: "12. All the students suffering from flu have been _________________ to the sick bay.",
A: "limited",
B: "confined",
C: "remanded",
D: "restrained",
answer: "B. confined",
correctLetter: "B",
correctOption: 2,
},

{
id: "question13",
question: "13. It was _________________ on GBC news yesterday that the town had fallen.",
A: "proclaimed",
B: "announced",
C: "declared",
D: "said",
answer: "B. announced",
correctLetter: "B",
correctOption: 2,
},

{
id: "question14",
question: "14. The Vice Chancellor was _________________ at a colourful ceremony.",
A: "appointed",
B: "dressed",
C: "installed",
D: "crowned",
answer: "C. installed",
correctLetter: "C",
correctOption: 3,
},

{
id: "question15",
question: "15. He spoke _________________ French and so he couldn’t help them.",
A: "some",
B: "a little",
C: "small",
D: "little",
answer: "B. a little",
correctLetter: "B",
correctOption: 2,
},

{
id: "question16",
question: "16. We detest his _________________ to alcohol.",
A: "wish",
B: "addiction",
C: "taste",
D: "commitment",
answer: "B. addiction",
correctLetter: "B",
correctOption: 2,
},

{
id: "question17",
question: "17. Success _________________ those who work hard.",
A: "encourages",
B: "meets",
C: "stares at",
D: "smiles on",
answer: "D. smiles on",
correctLetter: "D",
correctOption: 4,
},

{
id: "question18",
question: "18. The midfielder _________________ many chances for the winning team.",
A: "produced",
B: "created",
C: "made",
D: "caused",
answer: "B. created",
correctLetter: "B",
correctOption: 2,
},

{
id: "question19",
question: "19. What happened to John is so horrible that he cannot easily_________________ it.",
A: "forego",
B: "forget",
C: "forebear",
D: "forsake",
answer: "B. forget",
correctLetter: "B",
correctOption: 2,
},

{
id: "question20",
question: "20. Egypt is reputed to be the _________________ of civilization.",
A: "source",
B: "cradle",
C: "root",
D: "place",
answer: "C. root",
correctLetter: "C",
correctOption: 3,
},

{
instruction: "Choose from the alternatives lettered A to D the one which is nearest in meaning to the underlined word or expression in each sentence.",
id: "question21",
question: ["21. The fear in his eyes belies his claim of ", <UnderlineText key={"1"} text={"confidence"}/>, ""],
A: "boldness",
B: "firmness",
C: "self-reliance",
D: "faith",
answer: "A. boldness",
correctLetter: "A",
correctOption: 1,
},

{
id: "question22",
question: ["22. The mob challenged Awuni's ", <UnderlineText key={"1"} text={"audacious"}/>, " behaviour."],
A: "capricious",
B: "lenient",
C: "daring",
D: "friendly",
answer: "C. daring",
correctLetter: "C",
correctOption: 3,
},

{
id: "question23",
question: ["23. The economy of the country has remained ", <UnderlineText key={"1"} text={"resilient."}/>, ""],
A: "robust",
B: "powerful",
C: "realistic",
D: "sure",
answer: "A. robust",
correctLetter: "A",
correctOption: 1,
},

{
id: "question24",
question: ["24. Adjoa pursued ", <UnderlineText key={"1"} text={"prudent"}/>, " financial policies in her company."],
A: "clear",
B: "sound",
C: "cooperative",
D: "acceptable",
answer: "B. sound",
correctLetter: "B",
correctOption: 2,
},

{
id: "question25",
question: ["25. In order to reach the zenith of your career, you must cultivate the spirit of ", <UnderlineText key={"1"} text={"persistence"}/>, ""],
A: "consistency",
B: "continuity",
C: "perseverance",
D: "permissiveness",
answer: "C. perseverance",
correctLetter: "C",
correctOption: 3,
},

{
id: "question26",
question: ["26. The innocent boy was ", <UnderlineText key={"1"} text={"lured"}/>, " by his peers into drug addiction."],
A: "dragged",
B: "forced",
C: "invited",
D: "enticed",
answer: "D. enticed",
correctLetter: "D",
correctOption: 4,
},

{
id: "question27",
question: ["27. We must ", <UnderlineText key={"1"} text={"resist"}/>, " oppressors’ rule at all costs."],
A: "remove",
B: "refuse",
C: "oppose",
D: "abhor",
answer: "C. oppose",
correctLetter: "C",
correctOption: 3,
},

{
id: "question28",
question: ["28. The District Commissioner showed his ", <UnderlineText key={"1"} text={"inefficiency"}/>, " when he was transferred to the new district."],
A: "ignorance",
B: "inexperience",
C: "arrogance",
D: "incompetence",
answer: "D. incompetence",
correctLetter: "D",
correctOption: 4,
},

{
id: "question29",
question: ["29. Instead of being ", <UnderlineText key={"1"} text={"aggressive"}/>, " the culprit was conciliatory."],
A: "violent",
B: "assertive",
C: "insistent",
D: "forceful",
answer: "A. violent",
correctLetter: "A",
correctOption: 1,
},

{
id: "question30",
question: ["30. The court awarded ", <UnderlineText key={"1"} text={"damages"}/>, " against the landlord."],
A: "costs",
B: "injury",
C: "punishment",
D: "penalties",
answer: "D. penalties",
correctLetter: "D",
correctOption: 4,
},

{
section: "IV",
sectiontitle: "After each of the following sentences, a list of possible interpretations of all or part of the sentence is given. Choose the interpretation you consider most appropriate for each sentence.",
id: "question31",
question: "31. Adoley took exception to the letter I wrote. This means that Adoley",
A: "was angry at the letter.",
B: "liked the letter.",
C: "received only my letter.",
D: "had all the letters except mine.",
answer: "A. Was angry at the letter",
correctLetter: "A",
correctOption: 1,
},

{
id: "question32",
question: "32. You must leave your footprints on the sands of time. This means that you should",
A: "cover your feet with sand.",
B: "make a name for yourself.",
C: "walk carefully as you grow.",
D: "direct your footsteps towards home",
answer: "B. Make a name for yourself",
correctLetter: "B",
correctOption: 2,
},

{
id: "question33",
question: "33. It was crystal clear that my adversaries framed me up. This means that my adversaries",
A: "wasted my fortune.",
B: "fell into their own trap.",
C: "liked my misfortune.",
D: "got me into trouble.",
answer: "D. Got me into trouble",
correctLetter: "D",
correctOption: 4,
},

{
id: "question34",
question: "34. I could no longer put up with my friend, so I asked him to leave. This means that I",
A: "wanted to reconsider our relationship.",
B: "wanted to change his bad ways.",
C: "could not do anything about his behaviour.",
D: "could no longer accept his had ways.",
answer: "D. Could no longer accept his bad ways",
correctLetter: "D",
correctOption: 4,
},

{
id: "question35",
question: "35. Akorfa has got her head in the clouds . This means that she is",
A: "very proud.",
B: "not practical.",
C: "foolish.",
D: "ambitious.",
answer: "B. not practical",
correctLetter: "B",
correctOption: 2,
},

{
id: "question36",
question: "36. The dispute over wages in the factory has now come to a head. This means it has",
A: "assumed certain proportions.",
B: "reached a critical stage.",
C: "been referred to the manager.",
D: "been settled finally.",
answer: "B. Reached a critical stage",
correctLetter: "B",
correctOption: 2,
},

{
id: "question37",
question: "37. Ahugri nearly jumped down my throat when I suggested going away. This means that he",
A: "was horrified at the suggestion.",
B: "leapt up ready to leave at once.",
C: "was extremely angry with me.",
D: "showed his eagerness to hear more.",
answer: "C. Was extremely angry with me",
correctLetter: "C",
correctOption: 3,
},

{
id: "question38",
question: "38. Pokuaa has always been soft-hearted. This means that she is",
A: "delicate.",
B: "very compassionate.",
C: "cowardly.",
D: "very sensitive.",
answer: "B. Very compassionate",
correctLetter: "B",
correctOption: 2,
},

{
section: "V",
sectiontitle: "From the words or groups of words lettered A to D, choose the one that best completes each of the following sentences.",
id: "question39",
question: "39. She gave him aspirin to calm him down, but it seemed to make him all _________________ restless.",
A: "so",
B: "the most",
C: "the more",
D: "most",
answer: "C. the more",
correctLetter: "C",
correctOption: 3,
},

{
id: "question40",
question: "40. The dog had not had any food_________________ several days, so it was almost mad with hunger.",
A: "during",
B: "for",
C: "before",
D: "since",
answer: "B. for",
correctLetter: "B",
correctOption: 2,
},

{
id: "question41",
question: "41. I had _________________ come in when the telephone rang.",
A: "no sooner",
B: "clearly",
C: "hardly",
D: "no earlier",
answer: "C. hardly",
correctLetter: "C",
correctOption: 3,
},

{
id: "question42",
question: "42. The headmaster punished Oko for _________________ disobedience.",
A: "wilful",
B: "wrong",
C: "willing",
D: "wishful",
answer: "A. willful",
correctLetter: "A",
correctOption: 1,
},

{
id: "question43",
question: "43. Adongo left the party heavily drunk _________________ ’pusher’.",
A: "through",
B: "with",
C: "on",
D: "by",
answer: "B. with",
correctLetter: "B",
correctOption: 2,
},

{
id: "question44",
question: "44. What you said was true;_________________ .it was unkind.",
A: "despite",
B: "so",
C: "since",
D: "nevertheless",
answer: "D. nevertheless",
correctLetter: "D",
correctOption: 4,
},

{
id: "question45",
question: "45. He didn’t invite us in so _________________ words: he just asked whether we were coining,",
A: "much",
B: "many",
C: "few",
D: "plenty",
answer: "B. many",
correctLetter: "B",
correctOption: 2,
},

{
id: "question46",
question: "46. 1 read a book about the _________________ ",
A: "Shiloh King’s daughter.",
B: "King of Shiloh’s daughter.",
C: "Shiloh’s King daughter.",
D: "King’s daughter of Shiloh.",
answer: "B. King of Shilloh’s daughter",
correctLetter: "B",
correctOption: 2,
},

{
id: "question47",
question: "47. The house belongs to _________________ ",
A: "Darkos.",
B: "the Darko’s.",
C: "the Darkos.",
D: "Darkos’.",
answer: "C. the Darkos",
correctLetter: "C",
correctOption: 3,
},

{
id: "question48",
question: "48. I have been doing this exercise _________________ yesterday.",
A: "since",
B: "during",
C: "for",
D: "before",
answer: "A. since",
correctLetter: "A",
correctOption: 1,
},

{
id: "question49",
question: "49. The trader is _________________ Anthony.",
A: "tall as",
B: "as taller as",
C: "more taller than",
D: "not taller than",
answer: "D. not taller than",
correctLetter: "D",
correctOption: 4,
},

{
id: "question50",
question: "50. The author has written many books, _________________ ?",
A: "hadn’t he",
B: "hasn’t he",
C: "didn’t he",
D: "isn’t he",
answer: "B. hasn’t he",
correctLetter: "B",
correctOption: 2,
},

{
id: "question51",
question: "51. People shouldn’t drop litter on the pavement, _________________ ?",
A: "don’t they",
B: "should they",
C: "can they",
D: "shouldn’t they",
answer: "B. should they",
correctLetter: "B",
correctOption: 2,
},

{
id: "question52",
question: "52. They will volunteer, _________________ ?",
A: "won’t they",
B: "don’t they",
C: "can they",
D: "do they",
answer: "A. won’t they",
correctLetter: "A",
correctOption: 1,
}, 

{
id: "question53",
question: "53. You found your cell phone,_________________ ?",
A: "is it",
B: "don’t you",
C: "isn’t it",
D: "didn’t you",
answer: "D. didn’t you",
correctLetter: "D",
correctOption: 4,
},

{
id: "question54",
question: "54. Education enables us to_________________ . difficulties.",
A: "put out for",
B: "put up with",
C: "put in for",
D: "put on with",
answer: "B. put up with",
correctLetter: "B",
correctOption: 2,
},

{
id: "question55",
question: "55. The tiny car picked _________________ speed while overtaking the truck.",
A: "up",
B: "on",
C: "over",
D: "off",
answer: "A. up",
correctLetter: "A",
correctOption: 1,
},

{
id: "question56",
question: "56. The accused admitted_________________ four previous armed robberies.",
A: "for",
B: "to",
C: "in",
D: "at",
answer: "B. to",
correctLetter: "B",
correctOption: 2,
},

{
id: "question57",
question: "57. Ekuba is a very calm lady. I have never seen her _________________ a temper.",
A: "of",
B: "at",
C: "on",
D: "in",
answer: "D. in",
correctLetter: "D",
correctOption: 4,
},

{
id: "question58",
question: "58. I have made a lot of investment but I cannot get returns _________________ it.",
A: "at",
B: "for",
C: "into",
D: "from",
answer: "D. from",
correctLetter: "D",
correctOption: 4,
},

{
id: "question59",
question: "59. You _________________ worked very hard since you obtained the highest marks in the examination.",
A: "needed to have",
B: "could have",
C: "must have",
D: "ought to have",
answer: "C. Must have",
correctLetter: "C",
correctOption: 3,
},

{
id: "question60",
question: "60. He came to the meeting _________________ his serious illness.",
A: "despite",
B: "against",
C: "regarding",
D: "though",
answer: "A. Despite",
correctLetter: "A",
correctOption: 1,
},

{
section: "VI",
sectiontitle: "In the following passage, the numbered gaps indicate missing words. Against each number in the list below the passage, four choices are offered in columns lettered A to D. For each numbered gap, choose from the options provided for that number, the word that is most suitable to fill the gap. In many countries, hydro-electric power 61 have been constructed. This practice has become popular because hydro-power is a major 62 of electricity for industrial and 63 use. In Ghana, for instance, 80% of the power 64 from Akosombo is used by industry, which has become a large consumer of electric 65 In recent years, however, the government has 66 electricity to many rural communities which have now been 67 to the national power 68. It has become necessary, as a result, for the government to 69 a programme aimed at ensuring an effective 70 of electricity to all parts of the country.",
id: "question61",
question: "61. *********************",
A: "Plants",
B: "Reservoirs",
C: "barricades",
D: "dams",
answer: "D. Dams",
correctLetter: "D",
correctOption: 4,
},

{
id: "question62",
question: "62. *********************",
A: "Giver",
B: "Source",
C: "Provider",
D: "store",
answer: "B. Source",
correctLetter: "B",
correctOption: 2,
},

{
id: "question63",
question: "63. *********************",
A: "domestic",
B: "Home",
C: "household",
D: "family",
answer: "A. Derived",
correctLetter: "A",
correctOption: 1,
},

{
id: "question64",
question: "64. *********************",
A: "Derived",
B: "Received",
C: "Generated",
D: "produced",
answer: "C. Generated",
correctLetter: "C",
correctOption: 3,
},

{
id: "question65",
question: "65. *********************",
A: "Fuel",
B: "Energy",
C: "Force",
D: "product",
answer: "B. Energy",
correctLetter: "B",
correctOption: 2,
},

{
id: "question66",
question: "66. *********************",
A: "Spread",
B: "Extended",
C: "Given",
D: "widened",
answer: "B. Extended",
correctLetter: "B",
correctOption: 2,
},

{
id: "question67",
question: "67. *********************",
A: "Joined",
B: "Fixed",
C: "connected",
D: "tied",
answer: "C. Connected",
correctLetter: "C",
correctOption: 3,
},

{
id: "question68",
question: "68. *********************",
A: "Centre",
B: "Station",
C: "Depot",
D: "grid",
answer: "D. Grid",
correctLetter: "D",
correctOption: 4,
},

{
id: "question69",
question: "69. *********************",
A: "Manufacture",
B: "Make",
C: "Produce",
D: "develop",
answer: "D. Develop",
correctLetter: "D",
correctOption: 4,
},

{
id: "question70",
question: "70. *********************",
A: "Allocation",
B: "Distribution",
C: "Sharing",
D: "delivery",
answer: "B. Distribution",
correctLetter: "B",
correctOption: 2,
},

{
section: "I",
sectiontitle: "CHARLES DICKENS: Oliver Twist",
id: "question71",
question: "71. Mr. Monks meets Mr. and Mrs. Bumble in",
A: "the marketplace.",
B: "the original workhouse.",
C: "a secluded public house.",
D: "an old factory building.",
answer: "Z. zzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question72",
question: "72. Mr. Monks pays £25 for the gold locket and then",
A: "sells it for £50.",
B: "pawns it for £15.",
C: "drops it into the river.",
D: "gives it to Nancy.",
answer: "Z. zzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
instruction: "Read the following extract and answer questions 73 to 76. \n“What the devil’s this?” said a man, bursting out of a beer-shop with a white dog at his heels. “Young Oliver! Come home to your poor mother, you young dog! Come home directly.”",
id: "question73",
question: "73. The speaker is",
A: "the beadle Mr. Bumble.",
B: "very drunk and merry.",
C: "no other than Fagin",
D: "supporting the kidnapping of Oliver.",
answer: "Z. zzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question74",
question: "74. The next moment, the man takes the books from Oliver and",
A: "knocks him on the head.",
B: "tears them up.",
C: "throws the books away.",
D: "puts them into his coat pocket.",
answer: "Z. zzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question75",
question: "75. Just before the man’s intervention",
A: "Nancy had been pretending to be Oliver’s sister.",
B: "Fagin had been angry that Oliver was at large.",
C: "Mr. Sikes had fought with the Jews.",
D: "Oliver had owned up and bolted.",
answer: "Z. zzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question76",
question: "76. All this happened because",
A: "Mr. Sikes had threatened to kill Oliver.",
B: "Oliver had taken the wrong route.",
C: "Mr. Brownlow had rejected Oliver.",
D: "the Dodger had found where Sikes was.",
answer: "Z. zzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
instruction: "Read the following extract and answer questions 77 to 80. “This preliminary proceeding laying bare his head, the expert lady, clasping him tightly round the throat with one hand, inflicted a shower of blows (dealt with singular vigour and dexterity) upon it with the other.”",
id: "question77",
question: "77. Why is the “expert lady” doing this? She has",
A: "been beaten brutally by Bumble.",
B: "failed to procure Bumble’s sympa thy through weeping.",
C: "decided to end her marriage to Bumble.",
D: "become drunk on Bumble’s hidden rum.",
answer: "Z. zzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question78",
question: "78. Before this incident, it is obvious that Mr. Bumble",
A: "has been promoted.",
B: "is in comfortable retirement.",
C: "has been deserted by Mrs. Corney.",
D: "is no longer Beadle.",
answer: "Z. zzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question79",
question: "79. The incident occurs as Mr. Bumble is",
A: "about to go out.",
B: "asleep.",
C: "drinking port.",
D: "returning from town.",
answer: "Z. zzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question80",
question: "80. After this treatment, Mr. Bumble",
A: "faints in bed.",
B: "begins to cry.",
C: "goes to town.",
D: "breaks up with the expert lady.",
answer: "Z. zzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},



]