import {UnderlineText, SquareRoot, superscript, subscript, BoldText, ItalicText, Fraction, ShortFraction, LongFraction, MixedFraction, Isotopes } from "@/mathnotation"

export const ENGLISHLANGUAGEA2007 = [

{
section: "1",
instruction: "In each of the following sentences, there is a word underlined and one gap . From the list of words lettered A to D, choose the word that is most nearly opposite in meaning to the underlined word and that will, at the same time, correctly fill the gap in the sentence.",
id: "question1",
question: ["1. Akosua took a ", <UnderlineText key={"1"} text={"firm"}/>, " stand on the matter, never _________________ at all."],
A: "lingering",
B: "unsure",
C: "wavering",
D: "delaying",
answer: "C. wavering",
correctLetter: "C",
correctOption: 3,
},

{
id: "question2",
question: ["2. In times of crises, it is more sensible to be _________________ than ", <UnderlineText key={"1"} text={"agitated."}/>, ""],
A: "happy",
B: "calm",
C: "confident",
D: "quiet",
answer: "B. calm",
correctLetter: "B",
correctOption: 2,
},

{
id: "question3",
question: ["3. Your speech should be _________________ not ", <UnderlineText key={"1"} text={"long-winded."}/>, ""],
A: "simple",
B: "brief",
C: "abridged",
D: "edited",
answer: "B. brief",
correctLetter: "B",
correctOption: 2,
},

{
id: "question4",
question: ["4. Though it was meant to _________________ them, my gift rather ", <UnderlineText key={"1"} text={"angered"}/>, " them."],
A: "soften",
B: "appease",
C: "reward",
D: "disarm",
answer: "B. appease",
correctLetter: "B",
correctOption: 2,
},

{
id: "question5",
question: ["5. Neither your ", <UnderlineText key={"1"} text={"insults"}/>, " nor your _________________ can affect my decision on the matter."],
A: "regards",
B: "flatteries",
C: "compliments",
D: "favours",
answer: "B. flatteries",
correctLetter: "B",
correctOption: 2,
},

{
id: "question6",
question: ["6. It is _________________ not ", <UnderlineText key={"1"} text={"optional"}/>, " for members of tne community to participate in communal labour."],
A: "essential",
B: "obligatory",
C: "forceful",
D: "compelling",
answer: "B. obligatory",
correctLetter: "B",
correctOption: 2,
},

{
id: "question7",
question: ["7. You should _________________ rather than ", <UnderlineText key={"1"} text={"condemn"}/>, " me for my efforts."],
A: "admire",
B: "cheer",
C: "commend",
D: "acclaim",
answer: "C. commend",
correctLetter: "C",
correctOption: 3,
},

{
section: "II",
instruction: "From the list of words lettered A to D, choose the one that best completes each of the following sentences.",
id: "question8",
question: "8. No one should _________________ with the good work of the prefects.",
A: "mingle",
B: "intercede",
C: "interfere",
D: "mediate",
answer: "C. interfere",
correctLetter: "C",
correctOption: 3,
},

{
id: "question9",
question: "9. There is a _________________ now between the two warring parties.",
A: "recess",
B: "halt",
C: "truce",
D: "break",
answer: "C. truce",
correctLetter: "C",
correctOption: 3,
},

{
id: "question10",
question: "10. Adwoa is studying too _________________ for my liking.",
A: "intensely",
B: "keenly",
C: "fiercely",
D: "hungrily",
answer: "A. intensely",
correctLetter: "A",
correctOption: 1,
},

{
id: "question11",
question: "11. The manager gave his messenger a _________________ look when she reported late for work.",
A: "powerful",
B: "stern",
C: "demanding",
D: "queer",
answer: "B. stern",
correctLetter: "B",
correctOption: 2,
},

{
id: "question12",
question: "12. The police have _________________ the mystery of Ama's sudden disappearance.",
A: "understood",
B: "revealed",
C: "discovered",
D: "unravelled",
answer: "D. unravelled",
correctLetter: "D",
correctOption: 4,
},

{
id: "question13",
question: "13. The teachers were _________________ by the principal's indifference to staff matters.",
A: "disgusted",
B: "disconcerted",
C: "thrilled",
D: "motivated",
answer: "A. disgusted",
correctLetter: "A",
correctOption: 1,
},

{
id: "question14",
question: "14. My father is _________________ with the desire of my studying Medicine at the university.",
A: "infatuated",
B: "possessed",
C: "adamant",
D: "obsessed",
answer: "D. obsessed",
correctLetter: "D",
correctOption: 4,
},

{
id: "question15",
question: "15. It is easy to get _________________ for beauty contests in this country.",
A: "encouragement",
B: "aid",
C: "promotion",
D: "sponsorship",
answer: "D. sponsorship",
correctLetter: "D",
correctOption: 4,
},

{
id: "question16",
question: "16. Clever politicians know how to _________________ their supporters to win their votes.",
A: "mislead",
B: "manoeuvre",
C: "manage",
D: "manipulate",
answer: "D. manipulate",
correctLetter: "D",
correctOption: 4,
},

{
id: "question17",
question: "17. The captain of the sinking ship sent _________________ signals to other ships on the sea",
A: "distracted",
B: "distress",
C: "distant",
D: "distressed",
answer: "B. distress",
correctLetter: "B",
correctOption: 2,
},

{
id: "question18",
question: "18. The dissatisfied workers not only grumbled but also worked _________________ .",
A: "perfunctorily",
B: "peremptorily",
C: "perversely",
D: "pertly",
answer: "A. perfunctorily",
correctLetter: "A",
correctOption: 1,
},

{
section: "II",
instruction: "Choose from the alternatives lettered A to D the one which is nearest in meaning to the underlined word or expression in each sentence.",
id: "question19",
question: ["19. The memorandum of understanding stipulates that the amount should be paid within three months."],
A: "states",
B: "shows",
C: "allows",
D: "witnesses",
answer: "A. states",
correctLetter: "A",
correctOption: 1,
},

{
id: "question20",
question: ["20. I am afraid my ruling on this matter is ", <UnderlineText key={"1"} text={"irrevocable."}/>, ""],
A: "unchanging",
B: "severe",
C: "unchangeable",
D: "certain",
answer: "C. unchangeable",
correctLetter: "C",
correctOption: 3,
},

{
id: "question21",
question: ["21. Her popularity has ", <UnderlineText key={"1"} text={"waned."}/>, ""],
A: "declined",
B: "descended",
C: "degenerated",
D: "deteriorated",
answer: "A. declined",
correctLetter: "A",
correctOption: 1,
},

{
id: "question22",
question: ["22. Adzo was not ", <UnderlineText key={"1"} text={"daunted"}/>, " by the task ahead."],
A: "alarmed",
B: "haunted",
C: "discouraged",
D: "dominated",
answer: "C. discouraged",
correctLetter: "C",
correctOption: 3,
},

{
id: "question23",
question: ["23. We are prepared to support any ideas which catch our ", <UnderlineText key={"1"} text={"fancy."}/>, ""],
A: "imagination",
B: "desire",
C: "mood",
D: "thought",
answer: "A. imagination",
correctLetter: "A",
correctOption: 1,
},

{
id: "question24",
question: ["24. Don't be surprised at the ", <UnderlineText key={"1"} text={"zeal"}/>, " Toby has shown."],
A: "courage",
B: "strength",
C: "enthusiasm",
D: "joy",
answer: "C. enthusiasm",
correctLetter: "C",
correctOption: 3,
},

{
id: "question25",
question: ["25. Is Kwaku sure that he has ", <UnderlineText key={"1"} text={"tremendous"}/>, " support in the party?"],
A: "considerable",
B: "encouraging",
C: "necessary",
D: "enough",
answer: "A. considerable",
correctLetter: "A",
correctOption: 1,
},

{
id: "question26",
question: ["26. The ", <UnderlineText key={"1"} text={"welfare"}/>, " of their subjects should be the concern of leaders."],
A: "wealth",
B: "happiness",
C: "well-being",
D: "growth",
answer: "C. well-being",
correctLetter: "C",
correctOption: 3,
},

{
id: "question27",
question: ["27. Stealing is considered ", <UnderlineText key={"1"} text={"scandalous"}/>, " in all communities."],
A: "evil",
B: "disgraceful",
C: "unhealthy",
D: "unacceptable",
answer: "B. disgraceful",
correctLetter: "B",
correctOption: 2,
},

{
id: "question28",
question: ["28. We admired her ", <UnderlineText key={"1"} text={"rigorous"}/>, " defence of women's rights."],
A: "eager",
B: "angry",
C: "spirited",
D: "lively",
answer: "C. spirited",
correctLetter: "C",
correctOption: 3,
},

{
id: "question29",
question: ["29. Be ", <UnderlineText key={"1"} text={"wary"}/>, " of the friends you associate with."],
A: "afraid",
B: "sure",
C: "sensible",
D: "careful",
answer: "D. careful",
correctLetter: "D",
correctOption: 4,
},

{
id: "question30",
question: ["30. The fans were ", <UnderlineText key={"1"} text={"ardent"}/>, " in their support for the team."],
A: "fierce",
B: "angry",
C: "passionate",
D: "careful",
answer: "C. passionate",
correctLetter: "C",
correctOption: 3,
},

{
id: "question31",
question: ["31. His scheme is meant to ", <UnderlineText key={"1"} text={"foster"}/>, " good neighbourliness."],
A: "adopt",
B: "help",
C: "promote",
D: "support",
answer: "C. promote",
correctLetter: "C",
correctOption: 3,
},

{
id: "question32",
question: ["32. Students should ", <UnderlineText key={"1"} text={"cultivate"}/>, " the habit of reading for pleasure."],
A: "invent",
B: "nurse",
C: "discover",
D: "develop",
answer: "D. develop",
correctLetter: "D",
correctOption: 4,
},

{
section: "IV",
instruction: "After each of the following sentences, a list of possible interpretations of all or part of the sentence is given. Choose the interpretation you consider most appropriate for each sentence.",
id: "question33",
question: "33. Timothy laughed in my face when I told him I had bought a car. This means that Timothy _________________",
A: "made fun of me.",
B: "smiled broadly.",
C: "joked with me.",
D: "didn't believe me",
answer: "A. made fun of me",
correctLetter: "A",
correctOption: 1,
},

{
id: "question34",
question: "34. Whether to go on strike or not is a black and white issue. This means that the choice _________________",
A: "has its good and bad sides.",
B: "has been made already.",
C: "is quite clear.",
D: "is already written down.",
answer: "C. is quite clear",
correctLetter: "C",
correctOption: 3,
},

{
id: "question35",
question: "35. Adongo is tied to his wife's apron strings. This means that he _________________",
A: "loves his wife very much.",
B: "is under his wife's control.",
C: "can hardly stay away from her.",
D: "often ties his wife's apron around his neck.",
answer: "B. is under his wife's control",
correctLetter: "B",
correctOption: 2,
},

{
id: "question36",
question: "36. Afolabi is a Nigerian to the backbone. This means that he is a Nigeria _________________",
A: "by birth.",
B: "in some ways.",
C: "by adoption.",
D: "in every way.",
answer: "D. in every way",
correctLetter: "D",
correctOption: 4,
},

{
id: "question37",
question: "37. Serwaa dug her own grave when she challenged the chief in public. This means that she _________________",
A: "hid herself in a grave after the challenge.",
B: "went into hiding after challenging the chief.",
C: "offended the chief by digging a grave.",
D: "put herself in trouble by challenging the chief.",
answer: "D. put herself in trouble by challenging the chief",
correctLetter: "D",
correctOption: 4,
},

{
id: "question38",
question: "38. By rejecting the president's directive, Paul has shown that he is his own master. This means that Paul _________________",
A: "listens to no one.",
B: "is stubborn",
C: "opposes the president.",
D: "is independent.",
answer: "D. is independent",
correctLetter: "D",
correctOption: 4,
},

{
id: "question39",
question: "39. Koomson's suggestion at the meeting fell flat. This means that it was _________________",
A: "unwise",
B: "rejected.",
C: "ridiculed.",
D: "shelved",
answer: "B. rejected",
correctLetter: "B",
correctOption: 2,
},

{
id: "question40",
question: "40. Act 191 opened the floodgates to press freedom in the country. This means that the Act _________________ press freedom.",
A: "stifled",
B: "explained",
C: "preceded",
D: "engendered",
answer: "D. engendered",
correctLetter: "D",
correctOption: 4,
},

{
id: "question41",
question: "41. Ali has a chip on his shoulder about his deprivation. This means that he is _________________",
A: "proud",
B: "angry.",
C: "pompous.",
D: "happy.",
answer: "B. angry",
correctLetter: "B",
correctOption: 2,
},

{
id: "question42",
question: "42. The new executives have papered over the cracks in the union. This means that they have _________________ the problem.",
A: "concealed",
B: "exposed",
C: "not noticed",
D: "discussed",
answer: "A. concealed",
correctLetter: "A",
correctOption: 1,
},

{
section: "V",
instruction: "From the words or groups of words lettered A to D, choose the one that best completes each of the following sentences.",
id: "question43",
question: "43. It was _________________ whom they selected.",
A: "he",
B: "him",
C: "his",
D: "himself",
answer: "B. him",
correctLetter: "B",
correctOption: 2,
},

{
id: "question44",
question: "44. Advise her to leave the area _________________ since no one likes her there.",
A: "as a matter of fact",
B: "altogether",
C: "as a priority",
D: "absolutely",
answer: "B. altogether",
correctLetter: "B",
correctOption: 2,
},

{
id: "question45",
question: "45. Can you remember the names of all those _________________ you want to see?",
A: "who",
B: "which",
C: "whoever",
D: "whom",
answer: "D. whom",
correctLetter: "D",
correctOption: 4,
},

{
id: "question46",
question: "46. If they had offended her, she _________________ punished them.",
A: "had to",
B: "would",
C: "will have",
D: "would have",
answer: "D. would have",
correctLetter: "D",
correctOption: 4,
},

{
id: "question47",
question: "47. When they realized that they had a long stay, the soldiers _________________ for the approaching winter.",
A: "turned in",
B: "put up",
C: "dug in",
D: "stayed up",
answer: "D. stayed up",
correctLetter: "D",
correctOption: 4,
},

{
id: "question48",
question: "48. Scarcely had the teacher left the classroom. _________________ the bully sneaked away",
A: "than",
B: "then",
C: "when",
D: "and",
answer: "C. when",
correctLetter: "C",
correctOption: 3,
},

{
id: "question49",
question: "49. I'd rather _________________ Kofi the truth now.",
A: "tells",
B: "is telling",
C: "told",
D: "will tell",
answer: "C. told",
correctLetter: "C",
correctOption: 3,
},

{
id: "question50",
question: "50. Kwame _________________ here by now.",
A: "ought to be",
B: "may have been",
C: "needs to be",
D: "has had to be",
answer: "A. ought to be",
correctLetter: "A",
correctOption: 1,
},

{
id: "question51",
question: "51. In accordance _________________ school rules, you should be in class now.",
A: "to",
B: "by",
C: "with",
D: "of",
answer: "C. with",
correctLetter: "C",
correctOption: 3,
},

{
id: "question52",
question: "52. If Thomas _________________ our leader, no one would disobey him.",
A: "had been",
B: "was",
C: "is",
D: "were",
answer: "D. were",
correctLetter: "D",
correctOption: 4,
},

{
id: "question53",
question: "53. _________________ I want to thank you all for appointing me.",
A: "To end",
B: "In conclusion",
C: "At the end",
D: "Conclusively",
answer: "B. In conclusion",
correctLetter: "B",
correctOption: 2,
},

{
id: "question54",
question: "54. We were surprised _________________ her sudden outburst.",
A: "at",
B: "with",
C: "of",
D: "about",
answer: "A. at",
correctLetter: "A",
correctOption: 1,
},

{
id: "question55",
question: "55. _________________ rich you may be, you cannot buy respect.",
A: "However",
B: "Though",
C: "Whatever",
D: "As",
answer: "A. However",
correctLetter: "A",
correctOption: 1,
},

{
id: "question56",
question: "56. The new chief has no respect for _________________ who supported him.",
A: "we",
B: "us",
C: "ours",
D: "ourselves",
answer: "B. us",
correctLetter: "B",
correctOption: 2,
},

{
id: "question57",
question: "57. Between _________________ , there is perfect understanding.",
A: "him and I",
B: "he and I",
C: "him and me",
D: "he and me",
answer: "C. him and me",
correctLetter: "C",
correctOption: 3,
},

{
id: "question58",
question: "58. The thieves ran into the bush when the police closed _________________ on them.",
A: "at",
B: "in",
C: "up",
D: "around",
answer: "B. in",
correctLetter: "B",
correctOption: 2,
},

{
id: "question59",
question: "59. No one except her friends _________________ her.",
A: "likes",
B: "like",
C: "Have liked",
D: "is liking",
answer: "B. like",
correctLetter: "B",
correctOption: 2,
},

{
id: "question60",
question: "60. We have heard _________________ of your complaints.",
A: "enough",
B: "so much",
C: "any",
D: "those",
answer: "A. enough",
correctLetter: "A",
correctOption: 1,
},

{
id: "question61",
question: "61. Last week I heard Kofi _________________ Amadu that he would visit his parents.",
A: "tell",
B: "told",
C: "to tell",
D: "tells",
answer: "A. tell",
correctLetter: "A",
correctOption: 1,
},

{
section: "VI",
instruction: "In the following passage, the numbered gaps indicate missing words. Against each number in the list below the passage, four choices are offered in columns lettered A to D. For each numbered gap , choose from the options provided for that number, the word that is most suitable to fill the gap. Even after the operation, doctors say Kankam's road to-62-is uncertain, despite his ability to breathe -63-at the moment. All the same, as his -64- as improved slightly, Kankam has begun to - 65- to pain. In addition, his body can now perform -66- functions, even though he is in-67- coma. Since he suffered a -68- stroke last week, doctors can now say Kankam is -69- danger, though a full assessment of brain -70- is yet to be made.",
id: "question62",
question: "62. *********************",
A: "health",
B: "improvement",
C: "recovery",
D: "restoration",
answer: "C. recovery",
correctLetter: "C",
correctOption: 3,
},

{
id: "question63",
question: "63. *********************",
A: "alone",
B: "fast",
C: "unsupported",
D: "unaided",
answer: "D. unaided",
correctLetter: "D",
correctOption: 4,
},

{
id: "question64",
question: "64. *********************",
A: "situation",
B: "condition",
C: "predicament",
D: "status",
answer: "B. condition",
correctLetter: "B",
correctOption: 2,
},

{
id: "question65",
question: "65. *********************",
A: "respond",
B: "answer",
C: "reply",
D: "revert",
answer: "A. respond",
correctLetter: "A",
correctOption: 1,
},

{
id: "question66",
question: "66. *********************",
A: "fundamental",
B: "minor",
C: "basic",
D: "easy",
answer: "C. basic",
correctLetter: "C",
correctOption: 3,
},

{
id: "question67",
question: "67. *********************",
A: "deliberate",
B: "induced",
C: "influence",
D: "invoked",
answer: "B. induced",
correctLetter: "B",
correctOption: 2,
},

{
id: "question68",
question: "68. *********************",
A: "great",
B: "heavy",
C: "massive",
D: "serious",
answer: "C. massive",
correctLetter: "C",
correctOption: 3,
},

{
id: "question69",
question: "69. *********************",
A: "outside",
B: "away from",
C: "unaffected by",
D: "out of",
answer: "D. out of",
correctLetter: "D",
correctOption: 4,
},

{
id: "question70",
question: "70. *********************",
A: "injury",
B: "damage",
C: "deterioration",
D: "wreckage",
answer: "B. damage",
correctLetter: "B",
correctOption: 2,
},



]