import { UnderlineText, SquareRoot, superscript, subscript, BoldText, ItalicText, Fraction, ShortFraction, LongFraction, MixedFraction, Isotopes } from "@/mathnotation"

export const ENGLISHLANGUAGEA2004 = [

{
section: "1",
instruction: "In each of the following sentence, there is one word or group of words underlined word and one gap. From the list of words or group of words lettered A to D, choose the one that is most nearly opposito in meaning to the underlined word or group of words and that will, at the hame time, correctly fill the gap in the sentence.",
id: "question1",
question: ["1. The man refused to accept the offer of a job in the ", <UnderlineText key={"2"} text={"rural"}/>, " area; he preferred one in the ____________ area."],
A: "local",
B: "urban",
C: "township",
D: "municipal",
answer: "B. urban",
correctLetter: "B",
correctOption: 2,
},

{
id: "question2",
question: ["2. He is quite an ", <UnderlineText key={"2"} text={"outspoken"}/>, " young man but his father is_____________ "],
A: "humorous",
B: "sober",
C: "taciturn",
D: "silent",
answer: "C. taciturn",
correctLetter: "C",
correctOption: 3,
},

{
id: "question3",
question: ["3. One of the twins was as ", <UnderlineText key={"2"} text={"daring"}/>, " as the other was ____________"],
A: "morose",
B: "timid",
C: "secretive",
D: "rational",
answer: "B. timid",
correctLetter: "B",
correctOption: 2,
},

{
id: "question4",
question: ["4. A gully, which is a ", <UnderlineText key={"2"} text={"natural"}/>, " phenomenon should not be mistaken for a tunnel, which is  _________________________  ."],
A: "supernatural",
B: "false",
C: "artificial",
D: "modern",
answer: "C. artificial",
correctLetter: "C",
correctOption: 3,
},

{
id: "question5",
question: ["5. The crops the farmer ", <UnderlineText key={"2"} text={"planted"}/>, " will be ______________ in three months' time."],
A: "sold",
B: "weeded",
C: "uprooted",
D: "harvested.",
answer: "D. harvested",
correctLetter: "D",
correctOption: 4,
},

{
id: "question6",
question: ["6. He ", <UnderlineText key={"2"} text={"intentionally"}/>, " hid the document but his secretary ______________ burnt them."],
A: "carelessly",
B: "willingly",
C: "accidentally",
D: "foolishly.",
answer: "C. accidentally",
correctLetter: "C",
correctOption: 3,
},

{
id: "question7",
question: ["7. It is curious how Bayo can be so ", <UnderlineText key={"2"} text={"carefree"}/>, " in his ways while his younger brother is so _________________________  ."],
A: "meticulous",
B: "eccentric",
C: "indifferent",
D: "active.",
answer: "A. meticulous",
correctLetter: "A",
correctOption: 1,
},

{
id: "question8",
question: ["8. Personally, I  ", <UnderlineText key={"2"} text={"give in"}/>, " rather easily when it comes to arguments, but Emeka will always ____________ to his opinion."],
A: "hold in",
B: "hold on",
C: "hold up",
D: "hold back.",
answer: "D. hold back",
correctLetter: "D",
correctOption: 4,
},

{
id: "question9",
question: ["9. He didn't lose the fight because of his ", <UnderlineText key={"2"} text={"bravery"}/>, " but for his ____________.. ."],
A: "ignorance",
B: "strength",
C: "cowardice",
D: "rashness.",
answer: "C. cowardice",
correctLetter: "C",
correctOption: 3,
},

{
id: "question10",
question: ["10. If you do not drive with ", <UnderlineText key={"2"} text={"care"}/>, " you may be charged for  _________________________  ."],
A: "recklessness",
B: "drunkenness",
C: "over speeding",
D: "ignorance.",
answer: "A. recklessness",
correctLetter: "A",
correctOption: 1,
},

{
section: "2",
instruction: "From the words or group of words lettered A to D, choose the word or group of words that bost completes each of the following sentences",
id: "question11",
question: "11. When you ______________ an opponent' s point in a debate you must do so politely.",
A: "refute",
B: "rebuke",
C: "reject",
D: "refuse.",
answer: "A. refute",
correctLetter: "A",
correctOption: 1,
},

{
id: "question12",
question: "12. Mr. Collins does not allow his name to be published in connection with his philanthropy because he ____________ publicity.",
A: "wields",
B: "lacks",
C: "detests",
D: "denies.",
answer: "C. detests",
correctLetter: "C",
correctOption: 3,
},

{
id: "question13",
question: "13. I should be as ______________ as Kofi if I were so rejected by a close friend.",
A: "conscious",
B: "timid",
C: "aggrieved",
D: "courteous.",
answer: "C. aggrieved",
correctLetter: "C",
correctOption: 3,
},

{
id: "question14",
question: "14. The press will no longer be free when the new government starts to ____________ the newspaper.",
A: "censure",
B: "edit",
C: "publish",
D: "censor.",
answer: "D. censor",
correctLetter: "D",
correctOption: 4,
},

{
id: "question15",
question: "15. Everyone was disappointed to see the pastor doing those things that were ____________ with the morals he preached.",
A: "complacent",
B: "inconsistent",
C: "conducive",
D: "incompetent",
answer: "B. inconsistent",
correctLetter: "B",
correctOption: 2,
},

{
id: "question16",
question: "16. The boy is mentally unbalanced, so you should be ____________ of his behaviour.",
A: "tolerant",
B: "tolerable",
C: "apologetic",
D: "careful.",
answer: "A. tolerant",
correctLetter: "A",
correctOption: 1,
},

{
id: "question17",
question: "17. The president complained that too many doctors have ____________ for better remuneration.",
A: "repatriated",
B: "exiled",
C: "emigrated",
D: "immigrated.",
answer: "C. emigrated",
correctLetter: "C",
correctOption: 3,
},

{
id: "question18",
question: "18. The doctor listened to my heart-beat with a ____________",
A: "microscope",
B: "scalpel",
C: "chronometer",
D: "stethoscope.",
answer: "D. stethoscope",
correctLetter: "D",
correctOption: 4,
},

{
id: "question19",
question: "19. She was ____________ and it was not clear to me what she meant.",
A: "unknown",
B: "unintelligible",
C: "indefinite",
D: "illegible.",
answer: "B. unintelligible",
correctLetter: "B",
correctOption: 2,
},

{
id: "question20",
question: "20. Clara, your writing is difficult to read; you must try to make it ____________.",
A: "easier",
B: "legible",
C: "large",
D: "eligible.",
answer: "B. legible",
correctLetter: "B",
correctOption: 2,
},

{
section: "3",
instruction: "After each of the following sentences, a list of possible interpretations is given. Choose the interpretation that you consider most appropriate for each sentence.",
id: "question21",
question: "21. Despite their newness on the job, the workers were remunerated rather handsomely. This means that _____________ ",
A: "the salaries were poor.",
B: "those paid were handsome in appearance.",
C: "the salaries were attractive,",
D: "the workers were paid by handsome accountants.",
answer: "C. the salaries were attractive,",
correctLetter: "C",
correctOption: 3,
},

{
id: "question22",
question: "22. The plan to upgrade the dispensary to a general hospital did not materialize. This means that ____________ ",
A: "the arrangements did not work out as wished.",
B: "the plan was badly executed.",
C: "it was difficult to obtain the materials.",
D: "the plan did not meet the required specifications.",
answer: "A. the arrangements did not work out as wished",
correctLetter: "A",
correctOption: 1,
},

{
id: "question23",
question: "23. The robbery suspect said he made his earlier confessional statement under duress. This means that he made _____________ ",
A: "because he was forced to,",
B: "in the presence of a judge",
C: "because he took an oath",
D: "with the help of his lawyer.",
answer: "A. because he was forced to,",
correctLetter: "A",
correctOption: 1,
},

{
id: "question24",
question: "24. Despite their unrefined behaviour, the visitors were given preferential treatment. This means that the visitors were_____________ .",
A: "ill-treated because of their coarseness",
B: "treated with caution.",
C: "well-treated despite their crudity.",
D: "attended to first by the doctor.",
answer: "C. well-treated despite their crudity",
correctLetter: "C",
correctOption: 3,
},

{
id: "question25",
question: "25. Onume's father blew his top at the news of his performance in the examination. This means that he _____________ ",
A: "was overjoyed",
B: "whistled loudly",
C: "was very angry",
D: "was impressed.",
answer: "A. was overjoyed",
correctLetter: "A",
correctOption: 1,
},

{
id: "question26",
question: "26. There is no question of either of you getting the job'. The manager said, this means that_____________ .",
A: "the manager would not ask any questions about the job.",
B: "both of them would get the job.",
C: "only one them would get the job",
D: "neither of them would get the job.",
answer: "D. neither of them would get the job",
correctLetter: "D",
correctOption: 4,
},

{
id: "question27",
question: "27. Jumoke knew that her husband had had a drop too many when he asked her to pack out. This means that her husband was",
A: "sleepy.",
B: "confused",
C: "drunk",
D: "joking",
answer: "C. drunk",
correctLetter: "C",
correctOption: 3,
},

{
id: "question28",
question: "28. It was quite impossible for him not to have noticed that Lola had arrived. This means that he",
A: "should have known that Lola had arrived.",
B: "found it impossible to say that Lola had arrived.",
C: "said that Lola had not arrived.",
D: "pretended not to know that Lola had arrived.",
answer: "A. should have known that Lola had arrived",
correctLetter: "A",
correctOption: 1,
},

{
id: "question29",
question: "29. My father advised us not to go with the crowd. This means that he advised us not to _____________ .",
A: "stay in the crowd.",
B: "have many friends",
C: "travel with many people.",
D: "be unduly influenced by others",
answer: "D. be unduly influenced by others",
correctLetter: "D",
correctOption: 4,
},

{
id: "question30",
question: "30. We would grant your request if we had money. This means that",
A: "we have the money but will not grant your request.",
B: "we have the money and will grant your request",
C: "we will have the money and will grant your request",
D: "we do not have the money and cannot grant your request.",
answer: "D. we do not have the money and cannot grant your request",
correctLetter: "D",
correctOption: 4,
},

{
section: "4",
instruction: "From the words or group of words lettered A to D below each of the following sentences, choose the word or group of words that is noarost in moaning to the underlined word or group of words ah it is uhed in the sentence",
id: "question31",
question: ["31. The government has approved a new salary structure as an ", <UnderlineText key={"2"} text={"incentive"}/>, " for workers"],
A: "a reward",
B: "an encouragement",
C: "a package",
D: "an advance.",
answer: "B. an encouragement",
correctLetter: "B",
correctOption: 2,
},

{
id: "question32",
question: ["32. The accident victim was bleeding ", <UnderlineText key={"2"} text={"profusely."}/>, ""],
A: "slowly.",
B: "excessively",
C: "extremely",
D: "abundantly.",
answer: "B. excessively",
correctLetter: "B",
correctOption: 2,
},

{
id: "question33",
question: ["33. They have tried to ", <UnderlineText key={"2"} text={"circumvent"}/>, " the restriction on the importation of scarce commodities."],
A: "bypass",
B: "confront",
C: "oppose.",
D: "challenge.",
answer: "A. bypass",
correctLetter: "A",
correctOption: 1,
},

{
id: "question34",
question: ["34. The company had satisfied itself that the project was ", <UnderlineText key={"2"} text={"feasible"}/>, " before embarking on it."],
A: "easy",
B: "attractive",
C: "capable",
D: "practicable.",
answer: "D. practicable",
correctLetter: "D",
correctOption: 4,
},

{
id: "question35",
question: ["35. Though there is no riot on the campus, the students are ", <UnderlineText key={"2"} text={"restive."}/>, ""],
A: "quiet.",
B: "chaotic",
C: "restless",
D: "busy",
answer: "C. restless",
correctLetter: "C",
correctOption: 3,
},

{
id: "question36",
question: ["36. The persecutor was accused of ", <UnderlineText key={"2"} text={"obstructing"}/>, " justice."],
A: "hindering",
B: "retarding",
C: "stopping",
D: "interrupting",
answer: "A. hindering",
correctLetter: "A",
correctOption: 1,
},

{
id: "question37",
question: ["37. The man preaches ", <UnderlineText key={"2"} text={"humility"}/>, " without matching it with action."],
A: "salvation",
B: "honesty",
C: "kindness",
D: "modesty",
answer: "D. modesty",
correctLetter: "D",
correctOption: 4,
},

{
id: "question38",
question: ["38. Mr. Haruna plays the piano with great ", <UnderlineText key={"2"} text={"dexterity."}/>, ""],
A: "wisdom",
B: "pride",
C: "force",
D: "skill",
answer: "D. skill",
correctLetter: "D",
correctOption: 4,
},

{
id: "question39",
question: ["39. The college officer insisted that I show him my ", <UnderlineText key={"2"} text={"credentials"}/>, " before I could be registered"],
A: "books",
B: "qualifications",
C: "statements",
D: "identity.",
answer: "B. qualifications",
correctLetter: "B",
correctOption: 2,
},

{
id: "question40",
question: ["40. Amina said that she married a ", <UnderlineText key={"2"} text={"doting"}/>, " man."],
A: "loving",
B: "uncaring",
C: "funny",
D: "nagging.",
answer: "A. loving",
correctLetter: "A",
correctOption: 1,
},

{
section: "5",
instruction: "From the words or group of words lettered A to D, choose the word or group of words that bost completes each of the following sentences",
id: "question41",
question: "41. A loyal citizen ought not to abstain ____________ voting.",
A: "in",
B: "against",
C: "from",
D: "by",
answer: "C. from",
correctLetter: "C",
correctOption: 3,
},

{
id: "question42",
question: "42. She set ____________ preparing lunch when I came.",
A: "on",
B: "at",
C: "about",
D: "for.",
answer: "C. about",
correctLetter: "C",
correctOption: 3,
},

{
id: "question43",
question: "43. The ____________ engineer designed a new machine.",
A: "brilliant Nigerian young",
B: "Nigerian brilliant young",
C: "young Nigerian brilliant",
D: "brilliant young Nigerian.",
answer: "D. brilliant young Nigerian",
correctLetter: "D",
correctOption: 4,
},

{
id: "question44",
question: "44. ___________ were asked to represent the school at the quiz competition.",
A: "I and Ngozi",
B: "Ngozi and me",
C: "Ngozi and I",
D: "Myself and Ngozi",
answer: "C. Ngozi and I",
correctLetter: "C",
correctOption: 3,
},

{
id: "question45",
question: "45. I am not going to the standing with you as I ____________ that team play before.",
A: "am seeing",
B: "have seen",
C: "had seen",
D: "was seeing.",
answer: "C. had seen",
correctLetter: "C",
correctOption: 3,
},

{
id: "question46",
question: "46. I won't be able to come to the party as the day's work has tired me _____________ .",
A: "through",
B: "down",
C: "out",
D: "on",
answer: "C. out",
correctLetter: "C",
correctOption: 3,
},

{
id: "question47",
question: "47. It's been rough so far, ______________ ?",
A: "hasn't it",
B: "hadn't it",
C: "isn't it",
D: "wasn't it",
answer: "C. isn't it",
correctLetter: "C",
correctOption: 3,
},

{
id: "question48",
question: "48. The suspect ____________ when I entered the office.",
A: "has been questioned",
B: "have been questioned",
C: "was being questioned",
D: "is being questioned",
answer: "C. was being questioned",
correctLetter: "C",
correctOption: 3,
},

{
id: "question49",
question: "49. Ada had only ______________ time to spend with her family before the plane took oft",
A: "a little",
B: "small",
C: "little",
D: "small",
answer: "A. a little",
correctLetter: "A",
correctOption: 1,
},

{
id: "question50",
question: "50. The calculations looked ____________ simple that he thought he would not get any of them wrong",
A: "very",
B: "quite",
C: "so",
D: "much",
answer: "B. quite",
correctLetter: "B",
correctOption: 2,
},

{
id: "question51",
question: "51. The story she was reading made her ____________ .",
A: "laughed",
B: "to laugh",
C: "laugh",
D: "laughing",
answer: "C. laugh",
correctLetter: "C",
correctOption: 3,
},

{
id: "question52",
question: "52. _____________ people turned out for the rally because of the poor publicity.",
A: "Few",
B: "Quite a few",
C: "Only fewer",
D: "A few",
answer: "D. A few",
correctLetter: "D",
correctOption: 4,
},

{
id: "question53",
question: "53. The two brothers fell out and refused to live ____________ the same roof.",
A: "inside",
B: "beneath",
C: "in",
D: "under",
answer: "D. under",
correctLetter: "D",
correctOption: 4,
},

{
id: "question54",
question: "54. The teacher asked, ______________ will have the courage to try and lift that heavy log?",
A: "Whom",
B: "Which",
C: "Who",
D: "Whomever.",
answer: "C. Who",
correctLetter: "C",
correctOption: 3,
},

{
id: "question55",
question: "55. My friend and I quarrelled last week and haven't ____________ yet.",
A: "made it out",
B: "made it up",
C: "made out",
D: "made it",
answer: "B. made it up",
correctLetter: "B",
correctOption: 2,
},

{
id: "question56",
question: "56. After two years of courtship, Jide is ____________ Nkechi next Sunday.",
A: "getting married to",
B: "marrying",
C: "to marry to",
D: "being married by",
answer: "A. getting married to",
correctLetter: "A",
correctOption: 1,
},

{
id: "question57",
question: "57. The visitor was very uncomfortable because of his ______________ nose.",
A: "runny",
B: "watery",
C: "flowing",
D: "running",
answer: "A. runny",
correctLetter: "A",
correctOption: 1,
},

{
id: "question58",
question: "58. My friend's car has ______________ to a halt",
A: "grinded",
B: "grounded",
C: "ground",
D: "grind",
answer: "C. ground",
correctLetter: "C",
correctOption: 3,
},

{
id: "question59",
question: "59. It's time we ____________ for the party.",
A: "leave",
B: "left",
C: "have to leave",
D: "will leave",
answer: "B. left",
correctLetter: "B",
correctOption: 2,
},

{
id: "question60",
question: "60. Bassey was ______________ by the girl's story.",
A: "taken away",
B: "taken on",
C: "taken in",
D: "taken up",
answer: "C. taken in",
correctLetter: "C",
correctOption: 3,
},

{
id: "question61",
question: "61. ____________, you should put in some effort to show that you are interested",
A: "However you are tired",
B: "However tired you are",
C: "However tired are you",
D: "However are you tired",
answer: "B. However tired you are",
correctLetter: "B",
correctOption: 2,
},

{
id: "question62",
question: "62. ______________, ride a bicycle but he also drives a car.",
A: "He not only does",
B: "Not only he does",
C: "He only does not",
D: "Not only does he.",
answer: "D. Not only does he",
correctLetter: "D",
correctOption: 4,
},

{
id: "question63",
question: "63. Our plans for the trip fell ______________ because we had no money.",
A: "down",
B: "through",
C: "off",
D: "out.",
answer: "B. through",
correctLetter: "B",
correctOption: 2,
},

{
id: "question64",
question: "64. My brother ____________ studying in England for two years now.",
A: "is",
B: "has been",
C: "was",
D: "had been",
answer: "B. has been",
correctLetter: "B",
correctOption: 2,
},

{
id: "question65",
question: "65. I am not going to the cinema tonight, neither ____________ you.",
A: "would",
B: "are",
C: "do",
D: "have.",
answer: "B. are",
correctLetter: "B",
correctOption: 2,
},

{
id: "question66",
question: "66. No sooner had we started the journey ____________ we had a flat tyre.",
A: "then",
B: "that",
C: "when",
D: "than",
answer: "D. than",
correctLetter: "D",
correctOption: 4,
},

{
id: "question67",
question: "67. In this letter there ____________ good news about your elder brother.",
A: "is some",
B: "are",
C: "is a",
D: "are some",
answer: "A. is some",
correctLetter: "A",
correctOption: 1,
},

{
id: "question68",
question: "68. There were men on the job day and night all the time that this hotel ____________ .",
A: "was building",
B: "was being built",
C: "was built",
D: "is being built",
answer: "B. was being built",
correctLetter: "B",
correctOption: 2,
},

{
id: "question69",
question: "69. I shall have to start work ______________ I can after leaving school.",
A: "so soon as",
B: "as soon",
C: "so soon that",
D: "as soon as.",
answer: "D. as soon as",
correctLetter: "D",
correctOption: 4,
},

{
id: "question70",
question: "70. Mary and Jane are always fighting _____________ .",
A: "each other",
B: "themselves",
C: "another.",
D: "the other.",
answer: "A. each other",
correctLetter: "A",
correctOption: 1,
},

{
id: "question71",
question: "71. Don't let him bully you; you must stand up ______________ him!",
A: "for",
B: "before",
C: "to",
D: "against.",
answer: "C. to",
correctLetter: "C",
correctOption: 3,
},

{
id: "question72",
question: "72. The plane ____________ at 2.0' clock yesterday.",
A: "take off",
B: "took up",
C: "take up",
D: "took off.",
answer: "D. took off",
correctLetter: "D",
correctOption: 4,
},

{
id: "question73",
question: "73. It was a long time before his surprise wore  ____________ .",
A: "out",
B: "off",
C: "through",
D: "down",
answer: "B. off",
correctLetter: "B",
correctOption: 2,
},

{
id: "question74",
question: "74. The bananas weren't ____________ ripe enough to use today.",
A: "almost",
B: "scarcely",
C: "nearly",
D: "hardly",
answer: "D. hardly",
correctLetter: "D",
correctOption: 4,
},

{
id: "question75",
question: "75. I'm sorry I can't find ______________ of the two books you lent me.",
A: "neither",
B: "each",
C: "either",
D: "any",
answer: "A. neither",
correctLetter: "A",
correctOption: 1,
},

{
id: "question76",
question: "76. When she visited us we asked her if she ____________ pounded yam for launch.",
A: "want",
B: "wants",
C: "wanted",
D: "has wanted",
answer: "C. wanted",
correctLetter: "C",
correctOption: 3,
},

{
section: "6",
instruction: "In the following passages, the numbered gaps indicate missing words. Against each number in the list below each pasage, four options are offered in columns lettered A to D, choose the word that is the most suitablo to fill the numbered gap in the passages",
passage: "Oil is perhaps the most sought - after of all -77-. However, a major difficulty in its -78- is that oil 79- are very often found below the sea -80-. As a result, the search for oil is very expensive, and unless oil is found there in -81- quantities the companies or governments involved are liable to lose heavily. Therefore, before -82- starts, extensive surveys are carried out to see how much oil, or -83- gas the rock formation is likely to yield. If the results are favourable an oil rig is towed into position. The rig consists of a main -84- on which the men work and a derrick which supports the drill. This drill goes down thousands of feet until oil or a -85- of gas is reached. The next stage is to transport the gas or oil to the shore. In the case of gas this is normally done by laying a -86- below the sea, but oil on reaching the top of the well is more often transported in its -87- state by -88-. On shore it is - 89- into different fuels or it is treated chemically to turn it into a variety of -90- materials such as polythene.",
id: "question77",
question: "77. *********************",
A: "products",
B: "commodities",
C: "liquids",
D: "natural resources",
answer: "D. natural resources",
correctLetter: "D",
correctOption: 4,
},

{
id: "question78",
question: "78. *********************",
A: "manufacture",
B: "exploitation",
C: "research",
D: "investigation",
answer: "B. exploitation",
correctLetter: "B",
correctOption: 2,
},

{
id: "question79",
question: "79. *********************",
A: "fields",
B: "plants",
C: "mines",
D: "holes",
answer: "A. fields",
correctLetter: "A",
correctOption: 1,
},

{
id: "question80",
question: "80. *********************",
A: "surface",
B: "shelf",
C: "shore",
D: "bed",
answer: "C. shore",
correctLetter: "C",
correctOption: 3,
},

{
id: "question81",
question: "81. *********************",
A: "usable",
B: "saleable",
C: "commercial",
D: "practical",
answer: "C. commercial",
correctLetter: "C",
correctOption: 3,
},

{
id: "question82",
question: "82. *********************",
A: "mining",
B: "prospecting",
C: "drilling",
D: "digging",
answer: "B. prospecting",
correctLetter: "B",
correctOption: 2,
},

{
id: "question83",
question: "83. *********************",
A: "natural",
B: "Oceanic",
C: "flammable",
D: "household",
answer: "A. natural",
correctLetter: "A",
correctOption: 1,
},

{
id: "question84",
question: "84. *********************",
A: "ramp",
B: "foundation",
C: "scaffold",
D: "platform.",
answer: "D. platform",
correctLetter: "D",
correctOption: 4,
},

{
id: "question85",
question: "85. *********************",
A: "pocket",
B: "marsh",
C: "balloon",
D: "stratum",
answer: "D. stratum",
correctLetter: "D",
correctOption: 4,
},

{
id: "question86",
question: "86. *********************",
A: "cable",
B: "tunnel",
C: "pipeline",
D: "channel",
answer: "C. pipeline",
correctLetter: "C",
correctOption: 3,
},

{
id: "question87",
question: "87. *********************",
A: "raw",
B: "crude",
C: "liquid",
D: "impure",
answer: "B. crude",
correctLetter: "B",
correctOption: 2,
},

{
id: "question88",
question: "88. *********************",
A: "tanker",
B: "boat",
C: "transporter",
D: "tug",
answer: "A. tanker",
correctLetter: "A",
correctOption: 1,
},

{
id: "question89",
question: "89. *********************",
A: "made",
B: "refined",
C: "produced",
D: "manufactured.",
answer: "C. produced",
correctLetter: "C",
correctOption: 3,
},

{
id: "question90",
question: "90. *********************",
A: "processed",
B: "industrial",
C: "artificial",
D: "synthetic.",
answer: "D. synthetic",
correctLetter: "D",
correctOption: 4,
},



]