export const ANIMALHUSBANDRYA2018 = [

{
id: "question1",
question:  "1. Hay could be described as forage material which has been",
A: "dried",
B: "fermented",
C: "humidified",
D: "Wilted",
answer: "A. dried",
correctLetter: "A",
correctOption: 1,
},

{
id: "question2",
question:  "2. Which of the following farm animals is a non ruminant herbivore?",
A: "Chicken",
B: "Goat",
C: "Rabbit",
D: "Sheep",
answer: "C. Rabbit",
correctLetter: "C",
correctOption: 3,
},

{
id: "question3",
question:  "3. In the alimentary canal of poultry, grit is found in the",
A: "caecum",
B: "crop",
C: "gizzard",
D: "proventriculus",
answer: "C. gizzard",
correctLetter: "C",
correctOption: 3,
},

{
id: "question4",
question:  "4. Micro ties in the rumen of farm animals aid in the fermentation of",
A: "cellulose",
B: "fats",
C: "proteins",
D: "vitamins",
answer: "A. cellulose",
correctLetter: "A",
correctOption: 1,
},

{
id: "question5",
question:  "5. A wedge-shaped body conformation in cattle is a desirable feature of",
A: "beef cattle",
B: "dairy cattle",
C: "exotic cattle",
D: "work bull",
answer: "B. dairy cattle",
correctLetter: "B",
correctOption: 2,
},

{
id: "question6",
question:  "6. Trocar and canula are equipment used in the treatment of",
A: "bloat",
B: "mastitis",
C: "milk fever",
D: "tetanus",
answer: "A. bloat",
correctLetter: "A",
correctOption: 1,
},

{
id: "question7",
question:  "7. Which of the following activities is associated with light in poultry production?",
A: "Development of comb",
B: "Feather development in chicks",
C: "Hatching",
D: "Egg laying in hens",
answer: "D. Egg laying in hens",
correctLetter: "D",
correctOption: 4,
},

{
id: "question8",
question:  "8. Which of the following plants species are legumes?  \nI. Andropogon sp  \nII. Centrosema sp  \nIll. Pueraria sp",
A: "I and II only",
B: "I and III only",
C: "II and III only",
D: "I, II and III only",
answer: "C. II and III only",
correctLetter: "C",
correctOption: 3,
},

{
id: "question9",
question:  "9. Aspergillosis could be contracted through the ingestion of",
A: "dry grass",
B: "mouldy grains",
C: "fresh pasture",
D: "lush legume",
answer: "B. mouldy grains",
correctLetter: "B",
correctOption: 2,
},

{
id: "question10",
question:  "10. Ruminant production is widely practiced in the northern regions than the southern regions of West Africa because",
A: "of all year rainfall in the north",
B: "there are no good herdsmen in the south",
C: "of unfavourable cultural practices in the south",
D: "the north has fewer diseases than the south",
answer: "D. the north has fewer diseases than the south",
correctLetter: "D",
correctOption: 4,
},

{
id: "question11",
question:  "11. Which of the following factors is not a reason for culling in sheep production?",
A: "incidence of diseases",
B: "Demand for lambs",
C: "Deformity in animals",
D: "Low fertility",
answer: "B. Demand for lambs",
correctLetter: "B",
correctOption: 2,
},

{
id: "question12",
question:  "12. The main climatic factor which directly influences milk production in cow is",
A: "pressure",
B: "rainfall",
C: "relative humidity",
D: "temperature",
answer: "C. relative humidity",
correctLetter: "C",
correctOption: 3,
},

{
id: "question13",
question:  "13. Which of the following statements about snails are correct?  \nI. They are hermaphrodites  \nII. They have radula  \nIII. The body is divided into two parts",
A: "I and II only",
B: "I and III only",
C: "II and III only",
D: "I, II and III",
answer: "D. I, II and III",
correctLetter: "D",
correctOption: 4,
},

{
id: "question14",
question:  "14. A castrated pig is called",
A: "barrow",
B: "capon",
C: "steer",
D: "whether",
answer: "A. barrow",
correctLetter: "A",
correctOption: 1,
},

{
id: "question15",
question:  "15. Which of the following nutrients is tested by using sodium hydroxide and copper sulphate solution?",
A: "Carbohydrate",
B: "Fat",
C: "Protein",
D: "Vitamin",
answer: "C. Protein",
correctLetter: "C",
correctOption: 3,
},

{
id: "question16",
question:  "16. The incidence of pests and diseases in farm animals is usually highest in",
A: "Semi-arid regions",
B: "humid regions",
C: "arid regions",
D: "cold regions",
answer: "B. humid regions",
correctLetter: "B",
correctOption: 2,
},

{
id: "question17",
question:  "17. Which of the following activities are carried out when dressing chicken?  \nI. Scalding  \nII. Singeing  \nIII. Slaughtering",
A: "I and II only",
B: "I and III only",
C: "II and III only",
D: "I, II and III",
answer: "D. I, II and III",
correctLetter: "D",
correctOption: 4,
},

{
id: "question18",
question:  "18. A function of the liver in farm animals is",
A: "production of vitamin D",
B: "production of milk",
C: "maintenance of acid base balance",
D: "deamination of excess protein",
answer: "D. deamination of excess protein",
correctLetter: "D",
correctOption: 4,
},

{
id: "question19",
question:  "19. Which of the following organs are part of the oviduct of hen?  \nI. Infandibulum  \nII. Isthmus  \nIII. Ovaries",
A: "I and II only",
B: "I and III only",
C: "II and III only",
D: "I, II and III",
answer: "A. I and II only",
correctLetter: "A",
correctOption: 1,
},

{
id: "question20",
question:  "20. One of the ways of preventing overlaying in piglets is to",
A: "tether heavy sows",
B: "provide iron dextran",
C: "Provide rail guards",
D: "cull sows that normally lie on piglets",
answer: "C. Provide rail guards",
correctLetter: "C",
correctOption: 3,
},

{
id: "question21",
question:  "21. The recommended breeding ratio of males to females in grasscutter production is",
A: "l:2",
B: "l:4",
C: "l:7",
D: "2:5",
answer: "A. 1:2",
correctLetter: "A",
correctOption: 1,
},

{
id: "question22",
question:  "22. Which of the following factors affect the hatchability of eggs?  \nI. Colour of eggs  \nII. Disease  \nIII. Nutrition",
A: "I and II only",
B: "II and III only",
C: "II and III only",
D: "I, II and III",
answer: "B. II and III only",
correctLetter: "B",
correctOption: 2,
},

{
id: "question23",
question:  "23. Tick infestation of cattle could be effectively controlled by",
A: "fumigation",
B: "handpicking",
C: "regular dipping",
D: "regular deworming",
answer: "C. regular dipping",
correctLetter: "C",
correctOption: 3,
},

{
id: "question24",
question:  "24. If the space required by a bird in a poultry house is 0.25m², determine the number of birds that could occupy a space measuring 20 m by 16 m",
A: "80",
B: "160",
C: "320",
D: "1280",
answer: "C. 320",
correctLetter: "C",
correctOption: 3,
},

{
id: "question25",
question:  "25. One of the signs which associated with the approach of parturition in goats is",
A: "cessation of heat",
B: "frequent urination",
C: "swelling of abdomen",
D: "reddening of the vulva",
answer: "D. reddening of the vulva",
correctLetter: "D",
correctOption: 4,
},

{
id: "question26",
question:  "26. The quality of rice straw fed to animals could be improved by treating it with",
A: "water",
B: "sulphuric acid",
C: "magnesium chloride",
D: "urea",
answer: "D. urea",
correctLetter: "D",
correctOption: 4,
},

{
id: "question27",
question:  "27. Which of the following ingredients are sources of fats and oils in animal diet?  \nI. Groundnut cake  \nII. Palm kernel cake  \nIII. Blood meal",
A: "I and II only",
B: "I and III only",
C: "II and III only",
D: "I, II and III",
answer: "A. I and II only",
correctLetter: "A",
correctOption: 1,
},

{
id: "question28",
question:  "28. Poultry houses should generally be oriented in",
A: "north-south direction",
B: "east-west direction",
C: "north-east direction",
D: "south-west direction",
answer: "B. east-west direction",
correctLetter: "B",
correctOption: 2,
},

{
id: "question29",
question:  "29. The most important climatic factor which influences the distribution of animals in Ghana is",
A: "daylength",
B: "rainfall",
C: "relative humidity",
D: "wind",
answer: "B. rainfall",
correctLetter: "B",
correctOption: 2,
},

{
id: "question30",
question:  "30. The daily water intake of an ewe is 3.50 litres. If its water intake increase by 45% when it becomes pregnant, determine its new daily water intake",
A: "1.58 litres",
B: "4.20 litres",
C: "5.68 litres",
D: "6.16 litres",
answer: "B. 4.20 litres",
correctLetter: "B",
correctOption: 2,
},

{
id: "question31",
question:  "31. Which of following organs could be found in the visceral hump of edible snails  \nI. Digestive Organs  \nII. Excretory organs  \nIII. Reproductive organs",
A: "I and II only",
B: "I and III only",
C: "II and III only",
D: "I, II and III",
answer: "D. I, II and III",
correctLetter: "D",
correctOption: 4,
},

{
id: "question32",
question:  "32. The instrument illustrated is called",
A: "Burdizzo",
B: "elastrator",
C: "dehorning machine",
D: "artificial vagina",
answer: "B. elastrator",
correctLetter: "B",
correctOption: 2,
},

{
id: "question33",
question:  "33. The instrument is used for",
A: "castration",
B: "dehorning",
C: "deworming",
D: "semen collection",
answer: "A. castration",
correctLetter: "A",
correctOption: 1,
},

{
id: "question34",
question:  "34. The part of the instrument labeled I is called",
A: "rubber tube",
B: "warm water",
C: "water valve",
D: "outer jacket",
answer: "C. water valve",
correctLetter: "C",
correctOption: 3,
},

{
id: "question35",
question:  "35. The part of the instrument labeled II contains",
A: "warm oil",
B: "warm water",
C: "grease",
D: "perfume",
answer: "B. warm water",
correctLetter: "B",
correctOption: 2,
},

{
id: "question36",
question:  "36. The correct sequence of arrangement of the vertebrae from the anterior to the posterior end of the vertebral column is",
A: "cervical, lumbar, thoracic, sacral and caudal",
B: "cervical, thoracic, lumbar, sacral and caudal",
C: "thoracic, cervical, sacral, caudal and lumbar",
D: "thoracic, cervical, lumbar, sacral and caudal",
answer: "B. cervical, thoracic, lumbar, sacral and caudal",
correctLetter: "B",
correctOption: 2,
},

{
id: "question37",
question:  "37. Using a bull to cow ratio of 1 :25, determine the number of cows that could be served by 40 bulls",
A: "40",
B: "65",
C: "1000",
D: "1040",
answer: "B. 65",
correctLetter: "B",
correctOption: 2,
},

{
id: "question38",
question:  "38. Which of the following statements about ostriches are correct?  \nI. They are unable to fly  \nII. They produce hide  \nIII. They are hardy",
A: "I and III only",
B: "I and IIl only",
C: "II and III only",
D: "I, II and III",
answer: "D. I, II and III",
correctLetter: "D",
correctOption: 4,
},

{
id: "question39",
question:  "39. What do the hormones progesterone and oestrogen have in common? They",
A: "are required sexual reproduction",
B: "store blood glucose as glycogen",
C: "cause a rise in blood pressure",
D: "stimulate growth",
answer: "A. are required for sexual reproduction",
correctLetter: "A",
correctOption: 1,
},

{
id: "question40",
question:  "40. If ewe gets pregnant on 1st March, determine the likely date of lambing",
A: "29th May",
B: "29th June",
C: "1st August",
D: "1st September",
answer: "B. 29th June",
correctLetter: "B",
correctOption: 2,
},

{
id: "question41",
question:  "41. Fibrous feeds could be utilized by ruminants because",
A: "feed stays in their intestine for a long time",
B: "their rumen secretes enzyme that digest fibre",
C: "their rumen harbours microorganisms that digest fibre",
D: "they have the capacity to regurgitate",
answer: "C. their rumen harbours microorganisms that digest fibre",
correctLetter: "C",
correctOption: 3,
},

{
id: "question42",
question:  "42. Which of the following activities are effective in controlling tapeworms in cattle production  \nI. Regular drenching and drugs  \nII. Feeding animals with balanced diet  \nIII. Cooking meat properly",
A: "I and II only",
B: "I and III only",
C: "II and III only",
D: "I, II and III",
answer: "B. I and III only",
correctLetter: "B",
correctOption: 2,
},

{
id: "question43",
question:  "43. Piglets are normally injected with iron dextran in order to prevent",
A: "anaemia",
B: "anthrax",
C: "influenza",
D: "tetanus",
answer: "A. anaemia",
correctLetter: "A",
correctOption: 1,
},

{
id: "question44",
question:  "44. Which of the following combination of plants will constitute a good pasture?",
A: "Andropogen gayanus, Panicum maximum, Cynodon dactylon",
B: "Centrosema pubescens, Pueraria, phaseoloides, Stylosanthes sp",
C: "Imperata cylindrical, Centrosema pubescens, Andropogen gayanus",
D: "Panicum maximum, Pueraria, phaseoloides, Andropogen gayanus",
answer: "B. Centrosema pubescens, Pueraria phaseoloides, Stylosanthes sp",
correctLetter: "B",
correctOption: 2,
},

{
id: "question45",
question:  "45. The freshy cut forage fed to livestock in their housing units is referred to as",
A: "hay",
B: "silage",
C: "soilage",
D: "straw",
answer: "C. soilage",
correctLetter: "C",
correctOption: 3,
},

{
id: "question46",
question:  "46. The most important source of carbohydrate in livestock fed in West Africa is",
A: "maize",
B: "rice bran",
C: "sorghum",
D: "wheat bran",
answer: "A. maize",
correctLetter: "A",
correctOption: 1,
},

{
id: "question47",
question:  "47. Which of the following forage crops is a legume?",
A: "Panicum maximum",
B: "Imperata cylindrical",
C: "Cynodon dactylon",
D: "Calapogonium mucunoides",
answer: "D. Calapogonium mucunoides",
correctLetter: "D",
correctOption: 4,
},

{
id: "question48",
question:  "48. In which part of the stomach of ruminants do bacteria and fungi exist in large quantities",
A: "Abomasum",
B: "Omasum",
C: "Reticulum",
D: "Rumen",
answer: "D. Rumen",
correctLetter: "D",
correctOption: 4,
},

{
id: "question49",
question:  "49. Hay is fed to a dry cow primarily for the purpose of",
A: "growth",
B: "maintenance",
C: "production",
D: "weaning",
answer: "B. maintenance",
correctLetter: "B",
correctOption: 2,
},

{
id: "question50",
question:  "50. In the digestive system of turkeys, grinding of feed takes place in the",
A: "crop",
B: "duodenum",
C: "gizzard",
D: "proventriculus",
answer: "C. gizzard",
correctLetter: "C",
correctOption: 3,
},


]