export const CERAMICSA2016 = [

{
id: "question1",
question:  "1. Searching for clay is termed",
A: "carting.",
B: "digging.",
C: "investigating.",
D: "prospecting.",
answer: "D. Prospecting",
correctLetter: "D",
correctOption: 4,
},

{
id: "question2",
question:  "2. Ceramics is derived from the Greek word",
A: "keramic",
B: "Keramik.",
C: "Keramiko.",
D: "Keramus.",
answer: "A. Keramic",
correctLetter: "A",
correctOption: 1,
},

{
id: "question3",
question:  "3. Ceramic tiles mounted on walls are",
A: "collages.",
B: "murals.",
C: "slabs.",
D: "vases.",
answer: "B. Murals",
correctLetter: "B",
correctOption: 2,
},

{
id: "question4",
question:  "4. Clay is said to be gritty when it contains too much",
A: "feldspar.",
B: "salt.",
C: "sand",
D: "water.",
answer: "C. Sand",
correctLetter: "C",
correctOption: 3,
},

{
id: "question5",
question:  "5. Sedimentary clays are more suitable for the production of",
A: "earthenware.",
B: "insulators.",
C: "porcelain.",
D: "refractories.",
answer: "A. Earthenware",
correctLetter: "A",
correctOption: 1,
},

{
id: "question6",
question:  "6. Kiln firing is preferred to open firing because",
A: "less heat is obtained",
B: "more pots are fire",
C: "more heat is retained",
D: "flash bum is obtained",
answer: "C. More heat is retained",
correctLetter: "C",
correctOption: 3,
},

{
id: "question7",
question:  "7. The upward and downward movement of clay on the wheel,",
A: "makes clay more plastic",
B: "makes clay more porous.",
C: "removes remaining air bubbles.",
D: "turns the wheel head faster.",
answer: "C. Removes remaining air bubbles",
correctLetter: "C",
correctOption: 3,
},

{
id: "question8",
question:  "8. The best way to prevent cracking of incised pot is to",
A: "cut the side gently inwards.",
B: "leave the cut-out section.",
C: "lift cut-out gently inward",
D: "press the side gently outwards.",
answer: "A. Cut the side gently inwards",
correctLetter: "A",
correctOption: 1,
},

{
id: "question9",
question:  "9. Identify the state in which clay will be a suitable material for trailing.",
A: "Bisque",
B: "Bonedry",
C: "Leatherhard",
D: "Slip",
answer: "C. Leatherhard",
correctLetter: "C",
correctOption: 3,
},

{
id: "question10",
question:  "10. Breathing in clay dust can cause a disease called",
A: "diarrhoea",
B: "malaria",
C: "pneumonia",
D: "silicosis.",
answer: "D. Silicosis",
correctLetter: "D",
correctOption: 4,
},

{
id: "question11",
question:  "11. The most essential ingredients in a glaze are",
A: "alumina, flux and manganese.",
B: "alumina, flux and silica",
C: "clay, silica and alumina",
D: "manganese, alumina and silica",
answer: "B. Alumina, flux, and silica",
correctLetter: "B",
correctOption: 2,
},

{
id: "question12",
question:  "12. Identify a decorative technique done after the glost state.",
A: "Misima",
B: "Sgraffito",
C: "Sprigging",
D: "Transfer",
answer: "D. Transfer",
correctLetter: "D",
correctOption: 4,
},

{
id: "question13",
question:  "13. Fire clay is mainly used for the production of",
A: "pyrometric cones.",
B: "refractory bricks.",
C: "sanitary wares.",
D: "sewerage pipes.",
answer: "B. Refractory bricks",
correctLetter: "B",
correctOption: 2,
},

{
id: "question14",
question:  "14. Uniform consistency in clay is obtained by",
A: "kneading.",
B: "pinching.",
C: "rolling.",
D: "washing.",
answer: "A. Kneading",
correctLetter: "A",
correctOption: 1,
},

{
id: "question15",
question:  "15. Which finishing technique requires the use of a kidney?",
A: "Embossing",
B: "Incising",
C: "Smoothing",
D: "Texturing",
answer: "C. Smoothing",
correctLetter: "C",
correctOption: 3,
},

{
id: "question16",
question:  "16. To prevent dunting,",
A: "apply glaze in powder form.",
B: "open kiln after it has cooled down.",
C: "polish wares before firing.",
D: "use only slip glazes for decoration.",
answer: "B. Open kiln after it has cooled down",
correctLetter: "B",
correctOption: 2,
},

{
id: "question17",
question:  "17. Plastic clay is also described as",
A: "fat.",
B: "lean.",
C: "porous.",
D: "short.",
answer: "A. Fat",
correctLetter: "A",
correctOption: 1,
},

{
id: "question18",
question:  "18. To facilitate centring on the potter’s wheel,",
A: "add sufficient water to clay ball.",
B: "allow clay ball to rotate slowly.",
C: "mix clay ball with grog.",
D: "press clay ball firmly.",
answer: "A. Add sufficient water to clay ball",
correctLetter: "A",
correctOption: 1,
},

{
id: "question19",
question:  "19. Select a reason for scoring parts of objects.",
A: "Decorating the ware",
B: "Ensuring quick drying",
C: "Preventing cracks",
D: "Wedging effectively",
answer: "C. Preventing cracks",
correctLetter: "C",
correctOption: 3,
},

{
id: "question20",
question:  "20. Which of these materials is the most suitable for making a sketch model?",
A: "Aluminium",
B: "Cemeur",
C: "Kaolin",
D: "Plasticine",
answer: "D. Plasticine",
correctLetter: "D",
correctOption: 4,
},

{
id: "question21",
question:  "21. Why is plaster of Paris a most preferable material for mould making?",
A: "Ability to absorb moisture",
B: "Ability to retain water",
C: "Gives smooth surfaces",
D: "Has a long life span",
answer: "C. Gives smooth surfaces",
correctLetter: "C",
correctOption: 3,
},

{
id: "question22",
question:  "22. To prevent crawling,",
A: "apply glaze thick.",
B: "burnish wares well.",
C: "expel air bubbles.",
D: "wash wares clean.",
answer: "A. Apply glaze thick",
correctLetter: "A",
correctOption: 1,
},

{
id: "question23",
question:  "23. Which colour is obtained by the addition of copper oxide to a glaze?",
A: "Blue",
B: "Brown",
C: "Green",
D: "Red",
answer: "C. Green",
correctLetter: "C",
correctOption: 3,
},

{
id: "question24",
question:  "24. Correcting pinholing in a glaze requires",
A: "addition of flux to the glaze.",
B: "composing glaze to fit the body.",
C: "removing all traces of oil on the ware.",
D: "wedging clay to expel all air bubbles.",
answer: "C. Removing all traces of oil on the ware",
correctLetter: "C",
correctOption: 3,
},

{
id: "question25",
question:  "25. How is the cost of producing a set of bowls determined?",
A: "Expenditure on materials use",
B: "Fixed cost plus profit.",
C: "Market price, less the profit margin.",
D: "variable cost plus overhead cost.",
answer: "A. Expenditure on materials used",
correctLetter: "A",
correctOption: 1,
},

{
id: "question26",
question:  "26. Select the reason why water pots are not glaze",
A: "Pot must be porous enough to facilitate cooling",
B: "Pot will not survive glost firing",
C: "Water may be poisoned by the glaze",
D: "Water will cause the glaze to peel off.",
answer: "A. Pot must be porous enough to facilitate cooling",
correctLetter: "A",
correctOption: 1,
},

{
id: "question27",
question:  "27. Which of the following are parts of a firewood kiln?",
A: "Ash pit and chimney",
B: "Chimney and stilt",
C: "Firebox and pyrometer",
D: "Stilt and pyrometer",
answer: "A. Ash pit and chimney",
correctLetter: "A",
correctOption: 1,
},

{
id: "question28",
question:  "28. Dipper is used during throwing to",
A: "clean the ware.",
B: "check the base of ware.",
C: "measure the ware.",
D: "mop up excess water.",
answer: "D. Mop up excess water",
correctLetter: "D",
correctOption: 4,
},

{
id: "question29",
question:  "29. To ensure even thickness of wall during throwing,",
A: "add more water.",
B: "hands should be steady.",
C: "keep cutting the rim.",
D: "reduce speed of the wheel.",
answer: "B. Hands should be steady",
correctLetter: "B",
correctOption: 2,
},

{
id: "question30",
question:  "30. Grog is added to plastic clay to",
A: "change the colour.",
B: "lower maturing temperature.",
C: "increase shrinkage.",
D: "reduce porosity.",
answer: "B. Lower maturing temperature",
correctLetter: "B",
correctOption: 2,
},

{
id: "question31",
question:  "31. The three stages of greenware are",
A: "bone-dry, glost and bisque.",
B: "bone-dry, wet and glost.",
C: "wet, leatherhard and bisque.",
D: "wet, leatherhard and bonedry.",
answer: "D. Wet, leatherhard, and bonedry",
correctLetter: "D",
correctOption: 4,
},

{
id: "question32",
question:  "32. Which of the following is the chemical formula for lead carbonate?",
A: "CaC03",
B: "Na2C03",
C: "MgC03",
D: "PbCO3",
answer: "D. PbCO3",
correctLetter: "D",
correctOption: 4,
},

{
id: "question33",
question:  "33. Select the correct order for making modelled objects lighter.",
A: "Cut, seal joints and scoop",
B: "Cut, scoop and seal joints",
C: "Scoop, cut and seal joints",
D: "Scoop, seal joints and cut",
answer: "A. Cut, seal joints, and scoop",
correctLetter: "A",
correctOption: 1,
},

{
id: "question34",
question:  "34. The appropriate tool used during luting is a",
A: "cutting pin.",
B: "cutting wire.",
C: "fork.",
D: "spoon.",
answer: "C. Fork",
correctLetter: "C",
correctOption: 3,
},

{
id: "question35",
question:  "35. Flat wares are packed conveniently by using",
A: "bratts.",
B: "cranks.",
C: "props.",
D: "staggars.",
answer: "D. Staggars",
correctLetter: "D",
correctOption: 4,
},

{
id: "question36",
question:  "36. A traditional potter uses a com cob for",
A: "burnishing.",
B: "decorating.",
C: "firing.",
D: "texturing.",
answer: "B. Decorating",
correctLetter: "B",
correctOption: 2,
},

{
id: "question37",
question:  "37. Which of the following materials is used during smoking of pots?",
A: "Dried leaves",
B: "Green leaves",
C: "Palm kernel",
D: "Dry twigs",
answer: "B. Green leaves",
correctLetter: "B",
correctOption: 2,
},

{
id: "question38",
question:  "38. Peephole is to thermocouple is to",
A: "hydrometer.",
B: "hygrometer.",
C: "pyrometer.",
D: "thermometer",
answer: "C. Pyrometer",
correctLetter: "C",
correctOption: 3,
},

{
id: "question39",
question:  "39. Select the type of water that will still remain in clay ware after pre-heating.",
A: "Bonded",
B: "Physical",
C: "Plasticity",
D: "Pore",
answer: "A. Bonded",
correctLetter: "A",
correctOption: 1,
},

{
id: "question40",
question:  "40. Kiln atmospheres favourable for producing desirable effects in a glaze include",
A: "convection and radiation.",
B: "pre-heating and convection.",
C: "reduction and oxidation.",
D: "water smoking and reduction.",
answer: "C. Reduction and oxidation",
correctLetter: "C",
correctOption: 3,
},


]