export const ECONOMICSA2011 = [

{
id: "question1",
question:  "1. Which of the following activities is dominated by large scale production in West Africa?",
A: "Housing",
B: "Fisheries",
C: "Food production",
D: "Mining",
answer: "D. Mining",
correctLetter: "D",
correctOption: 4,
},

{
id: "question2",
question:  "2. Economic resources are limited in",
A: "poor countries.",
B: "rich countries.",
C: "developed countries.",
D: "all countries.",
answer: "D. all countries.",
correctLetter: "D",
correctOption: 4,
},

{
id: "question3",
question:  "3. Which of the following is not an advantage of the capitalist system?",
A: "Availability of variety of commodities",
B: "Lower prices clue to competition",
C: "Better quality of production",
D: "Unequal distribution of income",
answer: "D. Unequal distribution of income",
correctLetter: "D",
correctOption: 4,
},

{
id: "question4",
question:  "4. The diagram which shows the relationship between two variables is a",
A: "bar chart.",
B: "pie chart.",
C: "graph.",
D: "pictogram.",
answer: "C. Graph.",
correctLetter: "C",
correctOption: 3,
},

{
id: "question5",
question:  "5. The relationship between price and quantity demanded is",
A: "direct.",
B: "linear.",
C: "inverse.",
D: "diverse.",
answer: "C. inverse.",
correctLetter: "C",
correctOption: 3,
},

{
id: "question6",
question:  "6. The concept which measures how responsive consumers arc to changes in the price of a product is",
A: "utility.",
B: "differentiation.",
C: "standardization.",
D: "elasticity.",
answer: "D. elasticity.",
correctLetter: "D",
correctOption: 4,
},

{
id: "question7",
question:  "7. The fall in the price of a good causes the poor to buy less of such good. This is",
A: "a refutation of the law of demand.",
B: "a confirmation of consumer behaviour.",
C: "an exception to the law of demand.",
D: "the basic law of consumer behaviour.",
answer: "C. an exception to the law of demand.",
correctLetter: "C",
correctOption: 3,
},

{
id: "question8",
question:  "8. If the demand for a commodity decreases as income increases, it is said to be",
A: "an inferior good.",
B: "luxury good.",
C: "normal good.",
D: "a capital good.",
answer: "A. an inferior good.",
correctLetter: "A",
correctOption: 1,
},

{
id: "question9",
question:  "9. If sugar is complementary to tea, a rise in the price of sugar will",
A: "decrease the demand for tea.",
B: "increase the demand for lea.",
C: "leave the demand for tea unchanged.",
D: "make the supply of tea constant.",
answer: "A. decrease the demand for tea.",
correctLetter: "A",
correctOption: 1,
},

{
id: "question10",
question:  "10. The ease of substitution is an important determinant of",
A: "elasticity.",
B: "income.",
C: "inflation",
D: "foreign exchange.",
answer: "A. elasticity.",
correctLetter: "A",
correctOption: 1,
},

{
id: "question11",
question:  "11. Supply of a commodity is not affected by changes in",
A: "technology,",
B: "time,",
C: "income,",
D: "weather.",
answer: "C. income,",
correctLetter: "C",
correctOption: 3,
},

{
id: "question12",
question:  "12. Elasticity of supply is measured by the ratio of the",
A: "change in price to the change in quantity.",
B: "change in quantity to the change in price.",
C: "percentage change in price to the percentage change in quantity.",
D: "percentage change in quantity to the percentage change in price.",
answer: "D. percentage change in quantity to the percentage change in price.",
correctLetter: "D",
correctOption: 4,
},

{
id: "question13",
question:  "13. Which of the following can have a backward-bending supply curve?",
A: "Milk",
B: "Cars",
C: "Capital",
D: "Labour",
answer: "D. Labour",
correctLetter: "D",
correctOption: 4,
},

{
id: "question14",
question:  "14. As price rises, producers supply more; and as price falls, producers supply less. This is",
A: "a change in supply,",
B: "an increase in supply,",
C: "a decrease in supply,",
D: "a change in quantity supplied.",
answer: "D. a change in quantity supplied.",
correctLetter: "D",
correctOption: 4,
},

{
id: "question15",
question:  "15. Price has no effect on demand if",
A: "supply is perfectly elastic,",
B: "demand is perfectly inelastic,",
C: "demand is perfectly elastic,",
D: "supply is perfectly inelastic.",
answer: "C. demand is perfectly elastic.",
correctLetter: "C",
correctOption: 3,
},

{
id: "question16",
question:  "16. All consumers are expected to maximize",
A: "utility.",
B: "efficiency.",
C: "profit.",
D: "investments.",
answer: "A. utility.",
correctLetter: "A",
correctOption: 1,
},

{
id: "question17",
question:  "17. Which of the following best describes utility? The satisfaction",
A: "derived from consuming an additional unit of a commodity",
B: "given up for manufactured goods",
C: "derived from consuming a good or service",
D: "derived by those addicted to the consumption of certain goods",
answer: "C. derived from consuming a good or service",
correctLetter: "C",
correctOption: 3,
},

{
id: "question18",
question:  "18. The marginal utility curve slopes",
A: "downwards from left to right.",
B: "upwards from right to left.",
C: "downwards from right to left.",
D: "upwards from left to right.",
answer: "A. downwards from left to right.",
correctLetter: "A",
correctOption: 1,
},

{
id: "question19",
question:  "19. Yam can be regarded as a capital good if it is",
A: "saved for future consumption.",
B: "sold at a high price.",
C: "used in the production of more yams.",
D: "consumed outside the area where it was produced.",
answer: "C. used in the production of more yams.",
correctLetter: "C",
correctOption: 3,
},

{
id: "question20",
question:  "20. Which of the following factors of production earns profit?",
A: "Labour",
B: "Land",
C: "Entrepreneur",
D: "Capital",
answer: "C. Entrepreneur",
correctLetter: "C",
correctOption: 3,
},

{
id: "question21",
question:  "21. Which of the following shows the existence of economies of scale? When",
A: "economic task can be divided among a number of workers",
B: "workers in the firm are given the opportunity to do what they are best at",
C: "the expansion of the firm lowers the unit cost of production",
D: "various stages of production can be allocated to different workers",
answer: "C. the expansion of the firm lowers the unit cost of production",
correctLetter: "C",
correctOption: 3,
},

{
id: "question22",
question:  "22. The law of diminishing returns is a short run phenomenon because",
A: "the marginal product can be negative.",
B: "at least one factor is fixed.",
C: "the marginal product can be varied.",
D: "at least all factors can be varied.",
answer: "B. at least one factor is fixed.",
correctLetter: "B",
correctOption: 2,
},

{
id: "question23",
question:  "23. Which of the following is true about total cost?",
A: "It rises with the level of output",
B: "It declines when diseconomy of scale sets in",
C: "It declines when input price rises",
D: "It rises with the level of profit",
answer: "A. It rises with the level of output",
correctLetter: "A",
correctOption: 1,
},

{
id: "question24",
question:  "24. Which of the following cost declines continuously as output increases?",
A: "Total Cost",
B: "Average Cost",
C: "Average Fixed Cost",
D: "Average Variable Cost",
answer: "C. Average Fixed Cost",
correctLetter: "C",
correctOption: 3,
},

{
id: "question25",
question:  "25. A public limited liability company is owned by the",
A: "government of the country.",
B: "shareholders of the enterprise.",
C: "directors of the enterprise.",
D: "workers of the enterprise.",
answer: "B. shareholders of the enterprise.",
correctLetter: "B",
correctOption: 2,
},

{
id: "question26",
question:  "26. In the event of a limited liability company going into liquidation, each shareholder",
A: "may lose only what was invested.",
B: "loses nothing.",
C: "loses what was invested and his private property.",
D: "loses his financial investment and cash holdings.",
answer: "A. may lose only what was invested.",
correctLetter: "A",
correctOption: 1,
},

{
id: "question27",
question:  "27. Public corporations in West Africa are set up to",
A: "show that the government can do business.",
B: "make profit only.",
C: "provide welfare services for the people.",
D: "provide jobs for the politicians only.",
answer: "C. provide welfare services for the people.",
correctLetter: "C",
correctOption: 3,
},

{
id: "question28",
question:  "28. A firm’s profit is the",
A: "difference between total revenue and price.",
B: "amount by which total cost exceeds total revenue.",
C: "amount by which total revenue exceeds total cost.",
D: "total cost plus total revenue.",
answer: "C. amount by which total revenue exceeds total cost.",
correctLetter: "C",
correctOption: 3,
},

{
id: "question29",
question:  "29. In which of the following market situations does advertising have no place?",
A: "Perfect competition",
B: "duopoly",
C: "Monopolistic competition",
D: "Oligopoly",
answer: "A. Perfect competition",
correctLetter: "A",
correctOption: 1,
},

{
id: "question30",
question:  "30. A monopolist maximizes profit at an output level where",
A: "marginal cost equals price.",
B: "marginal cost equals marginal revenue.",
C: "marginal cost equals average cost.",
D: "total cost equals price.",
answer: "B. marginal cost equals marginal revenue.",
correctLetter: "B",
correctOption: 2,
},

{
id: "question31",
question:  "31. If an increase in price of a product brings about an increase in total revenue, the demand for the product is",
A: "fairly elastic.",
B: "fairly inelastic.",
C: "unitary elastic.",
D: "infinitely elastic.",
answer: "B. fairly inelastic.",
correctLetter: "B",
correctOption: 2,
},

{
id: "question32",
question:  "32. One of the arguments against the presence of middlemen in the distribution chain is",
A: "cause increase in the prices of goods.",
B: "are commissioned agents.",
C: "can be found almost any where.",
D: "grade and blend goods.",
answer: "A. cause increase in the prices of goods.",
correctLetter: "A",
correctOption: 1,
},

{
id: "question33",
question:  "33. The rate of natural increase in population can be obtained by",
A: "comparing the death rate with the birth rate.",
B: "subtracting emigration from immigration.",
C: "calculating the crude birth rate.",
D: "estimating the mortality rale",
answer: "A. comparing the death rate with the birth rate.",
correctLetter: "A",
correctOption: 1,
},

{
id: "question34",
question:  "34. A country’s population is denoted in year 2000 by P1 and in 2010 by P2. Given that 13 – Birth rate, D = Death rate, I = Immigration, H = Emigration, P2=",
A: "D – B + I – E",
B: "E – I – D + B.",
C: "P1 – D + B + E – I",
D: ". P1 + B – D + 1 – E",
answer: "D. . P1 + B – D + 1 – E",
correctLetter: "D",
correctOption: 4,
},

{
id: "question35",
question:  "35. One effect of minimum wage is",
A: "increase in the number of people employed.",
B: "fall in the wage rate paid to workers.",
C: "reduction of the number of people employed.",
D: "reduction on the number of people willing to work.",
answer: "C. reduction of the number of people employed.",
correctLetter: "C",
correctOption: 3,
},

{
id: "question36",
question:  "36. Subsistence farming means producing food crops mainly",
A: "for export.",
B: "for sale.",
C: "for the immediate family.",
D: "to satisfy the economy.",
answer: "C. for the immediate family.",
correctLetter: "C",
correctOption: 3,
},

{
id: "question37",
question:  "37. Cocoa in West Africa is produced in",
A: "subsistence farms,",
B: "peasant farms,",
C: "state farms,",
D: "expatriate farms.",
answer: "B. peasant farms,",
correctLetter: "B",
correctOption: 2,
},

{
id: "question38",
question:  "38. Which of the following industries is likely to be located near the market?",
A: "Bread",
B: "Steel",
C: "Car",
D: "Sugar",
answer: "A. Bread",
correctLetter: "A",
correctOption: 1,
},

{
id: "question39",
question:  "39. Which of the following sectors’ contribution to the GDP is likely to fall as the economy develops?",
A: "Primary",
B: "Secondary",
C: "Utilities",
D: "Services",
answer: "A. Primary",
correctLetter: "A",
correctOption: 1,
},

{
id: "question40",
question:  "40. Intermediate transactions are excluded from the calculation of the national income because",
A: "their values cannot be accurately calculated.",
B: "their values are unstable.",
C: "there is the need to avoid double counting.",
D: "there is the need to inflate the aggregate.",
answer: "C. there is the need to avoid double counting.",
correctLetter: "C",
correctOption: 3,
},

{
id: "question41",
question:  "41. The standard of living of a developing country can be retarded by a heavy expenditure on",
A: "human capital.",
B: "economic infrastructure.",
C: "consumer goods.",
D: "national defence.",
answer: "C. consumer goods.",
correctLetter: "C",
correctOption: 3,
},

{
id: "question42",
question:  "42. National Income Statistics are used for the following except to",
A: "indicate the overall living standard in a country.",
B: "determine population growth rate in a country.",
C: "assist the government to plan the economy.",
D: "properly compare the national growth of several countries.",
answer: "B. determine population growth rate in a country.",
correctLetter: "B",
correctOption: 2,
},

{
id: "question43",
question:  "43. Cheques are not considered as part of money supply because",
A: "they are issued in different forms by commercial banks.",
B: "their quantity docs not have any impact on money supply.",
C: "their validity is limited to six months.",
D: "they are not printed by the central bank.",
answer: "D. they are not printed by the central bank.",
correctLetter: "D",
correctOption: 4,
},

{
id: "question44",
question:  "44. A high speculative demand for money is associated with",
A: "low interest rate.",
B: "high interest rate.",
C: "low level of income.",
D: "high level of unemployment.",
answer: "A. low interest rate.",
correctLetter: "A",
correctOption: 1,
},

{
id: "question45",
question:  "45. The management of exchange rates is the responsibility of",
A: "merchant banks.",
B: "commercial banks.",
C: "mortgage banks.",
D: "central banks.",
answer: "D. central banks.",
correctLetter: "D",
correctOption: 4,
},

{
id: "question46",
question:  "46. Indirect taxes are levied on",
A: "revenue.",
B: "expenditure.",
C: "income.",
D: "traders.",
answer: "B. expenditure.",
correctLetter: "B",
correctOption: 2,
},

{
id: "question47",
question:  "47. The effect of tax upon the demand and supply situation can be demonstrated by moving",
A: "supply curve to the right.",
B: "supply curve vertically upwards.",
C: "demand curve to the right.",
D: "demand curve vertically upwards.",
answer: "B. supply curve vertically upwards.",
correctLetter: "B",
correctOption: 2,
},

{
id: "question48",
question:  "48. International trade is definitely not",
A: "multilateral trade.",
B: "unilateral trade.",
C: "bilateral trade.",
D: "trade among West African countries.",
answer: "B. unilateral trade.",
correctLetter: "B",
correctOption: 2,
},

{
id: "question49",
question:  "49. Dumping is considered to be a form of",
A: "conditional sale.",
B: "price discrimination.",
C: "black marketing.",
D: "product differentiation.",
answer: "B. price discrimination.",
correctLetter: "B",
correctOption: 2,
},

{
id: "question50",
question:  "50. An unfavourable balance of trade means that a country’s",
A: "total receipts exceed total payments",
B: "total imports exceed the total exports.",
C: "invisible imports exceed the invisible exports.",
D: "visible imports exceed the visible exports",
answer: "B. total imports exceed the total exports.",
correctLetter: "B",
correctOption: 2,
},


]