import { SquareRoot, superscript, subscript, BoldText, ItalicText, Fraction, ShortFraction, LongFraction, MixedFraction, Isotopes } from "@/mathnotation"

const path = "@/assets/images/pastquestions-figures/coremathematics/coremathematicsA/coremathematics-"

export const COREMATHEMATICSA2003 = [

{
id: "question1",
question: "1. List all the numbers of the set {x : x -4 < x ≤ 2} where x is an integer.",
A: "{-3,-2,-1,0, 1, 2}",
B: "{-4,-3,-2,-1,0, 1, 2}",
C: "{-4,-3,-2,-1, 0, 1,2}",
D: "{-3,-2,-1,0, 1}",
answer: "A. {-3,-2,-1,0, 1, 2}",
correctLetter: "A",
correctOption: 1,
},

{
id: "question2",
question: "2. What property is shown by XU (Y ∩ Z) = (X U Y) ∩ (X U Z), where X, Y and Z are sets?",
A: "The associative property",
B: "The commutative property",
C: "The distributive property",
D: "The equivalence property",
answer: "C. The distributive property",
correctLetter: "C",
correctOption: 3,
},

{
id: "question3",
question: "3. Consider the following statements: \nS1: People who complain are the very people who are unwilling to help. \nS2: Anyone who is unwilling to help deserves to be dismissed from his job. \nWhich of the following statements is a valid deduction form of S1 and S2?",
A: "Kofi deserves to be dismissed from his job Kofi is unwilling to help",
B: "Kofi deserves to be dismissed from his job > Kofi complains",
C: "Kofi is willing to help Kofi deserves to be dismissed from his job",
D: "Kofi complains Kofi deserves to be dismissed from his job.",
answer: "D. Kofi complains Kofi deserves to be dismissed from his job",
correctLetter: "D",
correctOption: 4,
},

{
id: "question4",
question: "4. Simplify 2/3 + 2/5 - 7/15",
A: "23/15",
B: "11/15",
C: "3/5",
D: "2/5",
answer: "C. 3/5",
correctLetter: "C",
correctOption: 3,
},

{
id: "question5",
question: "5. Find the sum of the following. numbers 322₅, 114₅ and 324₅",
A: "1220₅",
B: "1310₅",
C: "1313₅",
D: "1320₅",
answer: "D. 1320₅",
correctLetter: "D",
correctOption: 4,
},

{
id: "question6",
question: "6. If 23 + 14 = a (mod 5), find a.",
A: "0",
B: "1",
C: "2",
D: "3",
answer: "C. 2",
correctLetter: "C",
correctOption: 3,
},

{
id: "question7",
question: "7. Evaluate (576)½ leaving your answer as a product of prime factors.",
A: "2x32",
B: "22 x3",
C: "23 x 3",
D: "24 x 3",
answer: "C. 23 x 3",
correctLetter: "C",
correctOption: 3,
},

{
id: "question8",
question: "8. Write 0.024561, correct to 3 significant figures.",
A: "0.03",
B: "0.025",
C: "0.0246",
D: "0.0245",
answer: "C. 0",
correctLetter: "C",
correctOption: 3,
},

{
id: "question9",
question: "9. The total enrolment in a school is 432. The ratio of the number of boys to the number of girls is 5: 4. How many more boys than girls are in the school?",
A: "22",
B: "48",
C: "86",
D: "108",
answer: "B. 48",
correctLetter: "B",
correctOption: 2,
},

{
id: "question10",
question: "10. A man earns 3,840,000.00 per annum and pays an income tax of #48,000.00 per month. What percentage of his salary does he pay as income tax?",
A: "7.0%",
B: "12.5%",
C: "15.0%",
D: "17.6%",
answer: "C. 15",
correctLetter: "C",
correctOption: 3,
},

{
id: "question11",
question: "11. Solve the equation 3x/5 + 2 = (x − 2)/3",
A: "-40",
B: "-20",
C: "-10",
D: "-5",
answer: "C. -10",
correctLetter: "C",
correctOption: 3,
},

{
id: "question12",
instruction: "12. Which of the illustrations on the number lines below represent the truth set of the inequality 3x -  9 ≥ 12 (x - 3)?",
question: " ",
A: " ",
B: " ",
C: " ",
D: " ",
answer: "B.  ",
correctLetter: "B",
correctOption: 2,
questionFigure: require(path + "2003-A-Q-12.png"),
imageRatio: 0.55,
},

{
id: "question13",
question: "13. A train travelling at 105 km h-1 goes through a tunnel 1575 m long. Calculate in seconds, the time a passenger on a train spends inside the tunnel.",
A: "4s",
B: "15s",
C: "24s",
D: "54s",
answer: "D. 54s",
correctLetter: "D",
correctOption: 4,
},

{
id: "question14",
question: "14. Find the value of the expression a³ + 2ab² + b³, when a = 2 and b = -1",
A: "3",
B: "5",
C: "11",
D: "13",
answer: "C. 11",
correctLetter: "C",
correctOption: 3,
},

{
id: "question15",
instruction: "15. Which of the following mapping define(s) a function?",
question: " ",
A: "I only",
B: "II only",
C: "I and III only",
D: "II and III only",
answer: "A. I only",
correctLetter: "A",
correctOption: 1,
questionFigure: require(path + "2003-A-Q-15.png"),
imageRatio: 1,
},

{
id: "question16",
question: "16. Expand (2x - 3)(x + 7).",
A: "2x² -11x - 21",
B: "2x² -3x - 21",
C: "2x² + 3x - 21",
D: "2x² + 11x - 21",
answer: "D. 2x² + 11x - 21",
correctLetter: "D",
correctOption: 4,
},

{
id: "question17",
question: "17. A sector of a circle of radius 14 cm subtends an angle of 54 at the centre. Find the length of the arc. [Take π = 22/7]",
A: "0.9 cm",
B: "6.6 cm",
C: "13.2 cm",
D: "92.4 cm",
answer: "C. 13",
correctLetter: "C",
correctOption: 3,
},

{
id: "question18",
instruction: "18. What is the rule for the following",
question: " ",
A: "1 - 2x",
B: "3 - 2x",
C: "1 + 2x",
D: "3 + 2x",
answer: "B. 3-2x",
correctLetter: "B",
correctOption: 2,
questionFigure: require(path + "2003-A-Q-18.png"),
imageRatio: 0.34,
},

{
id: "question19",
question: "19. If t = (𝑎 − 𝑚) / (1 + 𝑎𝑚), express a in terms of t and m",
A: "a = (𝑚 + 𝑡) / (1 − 𝑚𝑡)",
B: "a = (𝑚 + 𝑡) / (1 + 𝑚𝑡)",
C: "a = (𝑚 − 𝑡) / (1 + 𝑚𝑡)",
D: "a =  𝑚𝑡 / (1 − 𝑚𝑡)",
answer: "A. a = m+t/1-mt",
correctLetter: "A",
correctOption: 1,
},

{
id: "question20",
question: "20. Solve the simultaneous equations 2x - 5y = 1 and x - 2y = 3.",
A: "x = 13, y = 5",
B: "x = 8, y =3",
C: "x = 5.5, y =2",
D: "x = 17/9, y = -5/17",
answer: "A. x = 13, y = 5",
correctLetter: "A",
correctOption: 1,
},

{
instruction: "Use the following information to answer Questions 21 and 22 \nA woman takes a loan of ¢16,200,000.00 for one year at an interest of 4½% per annum. The loan together with the interest is to be paid in twelve equal monthly instalments.",
id: "question21",
question: "21. Calculate the interest on the loan",
A: "¢573,000.00",
B: "¢729,000.00",
C: "¢1,458,000.00",
D: "¢2,268,000.00",
answer: "B. ¢729,000",
correctLetter: "B",
correctOption: 2,
},

{
id: "question22",
question: "22. Calculate how much she pays each month",
A: "¢1,302,231.00",
B: "¢1,410,750.00",
C: "¢1,471,000.00",
D: "¢1,539,000.00",
answer: "B. ¢1,410,750",
correctLetter: "B",
correctOption: 2,
},

{
id: "question23",
question: "23. What is the equation of the straight line which passes through the point (2, 3) and has gradient 2?",
A: "y = 2x - 1",
B: "y = 2x - 2",
C: "y = 2x + 1",
D: "y = 2x + 2",
answer: "A. y =2x -1",
correctLetter: "A",
correctOption: 1,
},

{
id: "question24",
question: "24. Find the truth set of x² - 3x - 10 = 0 .",
A: "{x: x = 2, 5}",
B: "{x: x = 2, -5}",
C: "{x: x = -2, 5}",
D: "{x: x = -2,-5}",
answer: "C. {x : x = -2, 5}",
correctLetter: "C",
correctOption: 3,
},

{
id: "question25",
question: "25. Simplify log₁₀2.25 + 4log₁₀2 - 2log₁₀0.6",
A: "2.0",
B: "9.05",
C: "10.0",
D: "15.0",
answer: "A. 2",
correctLetter: "A",
correctOption: 1,
},

{
id: "question26",
question: "26. The bearing of a point S from another point T is 258°. Find the bearing of T rot S.",
A: "12o",
B: "78o",
C: "102o",
D: "168o",
answer: "B. 78o",
correctLetter: "B",
correctOption: 2,
},

{
id: "question27",
question: "27. If q = [−4, -8], r = [1, 4] and s = r - q, find |s|",
A: "5.0",
B: "10.9",
C: "12.0",
D: "13.0",
answer: "D. 13",
correctLetter: "D",
correctOption: 4,
},

{
id: "question28",
question: "28. Two squares P and Q have sides 2½ cm and 7½ respectively. Express the area of P as a fraction of the area of Q.",
A: "3/100",
B: "9/100",
C: "7/10",
D: "9/10",
answer: "B. 9/100",
correctLetter: "B",
correctOption: 2,
},

{
id: "question29",
question: "29. Express the vector (3.4 km, 043°) in component form.",
A: "[2.3, 2.5]",
B: "[2.3, 3.4]",
C: "[2.5, 2.3]",
D: "[3.2, 2.5]",
answer: "A. [2",
correctLetter: "A",
correctOption: 1,
},

{
id: "question30",
question: "30. The image of the point (2, 4) under a translation by the vector p is (5, 3). Find the vector p.",
A: "[1, 1]",
B: "[7, 7]",
C: "[-3, 3 ]",
D: "[3, -1 ]",
answer: "D. [3 −1]",
correctLetter: "D",
correctOption: 4,
},

{
instruction: "Use the following information to answer Questions 31 to 33. \nA pie chart was drawn to represent the monthly car sales for the period January to June 2003. The angles of the six sectors of the pie chart are 50°, 54°, 73°, 70°, 59 and 54. \nThe total number of cars sold during the given period was 511,200.",
id: "question31",
question: "31. Calculate the number of cars sold in January",
A: "71,000",
B: "76,6800",
C: "99,400",
D: "103,660",
answer: "A. 71,000",
correctLetter: "A",
correctOption: 1,
},

{
id: "question32",
question: "32. What was the highest number of cars sold during the period?",
A: "71,000",
B: "83,780",
C: "99,4000",
D: "103,660",
answer: "D. 103,660",
correctLetter: "D",
correctOption: 4,
},

{
id: "question33",
question: "33. What was the mean number of cars sold from January to June?",
A: "42,600",
B: "82,500",
C: "85,200",
D: "102,240",
answer: "C. 85,200",
correctLetter: "C",
correctOption: 3,
},

{
id: "question34",
question: "34. The total age of two sisters is 108years. One is 18 years older than the other. Find the ratio of the age of the older to that of the younger.",
A: "2:1",
B: "7:5",
C: "7:6",
D: "9:7",
answer: "B. 7:5",
correctLetter: "B",
correctOption: 2,
},

{
id: "question35",
question: "35. If 1 cm3 of a metal weighs 7.3 gm, express in kilogrammes the weight of 210 cm3 of the metal.",
A: "1.533 kg",
B: "15.33 kg",
C: "153.3 kg",
D: "1533.0 kg",
answer: "A. 1",
correctLetter: "A",
correctOption: 1,
},

{
id: "question36",
question: "36. Write 3 / (x + 1) - 2 / (x - 1) as a single fraction.",
A: "(x − 1) / (x² − 1)",
B: "(x − 1) / (x² + 1)",
C: "(5x − 1) / (x² − 1)",
D: "(x − 5) / (x² − 1)",
answer: "D. x - 5/x²-1",
correctLetter: "D",
correctOption: 4,
},

{
id: "question37",
question: "37. A trader sold an article at a profit of 22½%. If the selling price was 147,000.00, find the cost price.",
A: "¢113,925.00",
B: "$120,000.00",
C: "$180,075.00",
D: "¢190,000.00",
answer: "B. $120,000",
correctLetter: "B",
correctOption: 2,
},

{
id: "question38",
question: "38. A bag contains 36 marbles which are identical. 10 are red, 12 green and the remaining yellow. A marble is selected at random from the bag. What is the probability that the selected marble is yellow?",
A: "1/18",
B: "5/18",
C: "7/18",
D: "11/18",
answer: "C. 7/18",
correctLetter: "C",
correctOption: 3,
},

{
id: "question39",
question: "39. Find the image of the point A (2, 3) under a reflection in the line x = 4.",
A: "(2, 7)",
B: "(3, 6)",
C: "(6, 3)",
D: "(8, 3)",
answer: "C. (6, 3)",
correctLetter: "C",
correctOption: 3,
},

{
id: "question40",
question: "40. The line 3y + px - 6 = 0 passes through the point (3, 4). Find p.",
A: "-6",
B: "-2",
C: "-½",
D: "-1/60",
answer: "B. -2",
correctLetter: "B",
correctOption: 2,
},

{
id: "question41",
question: "41. A right pyramid has a square base of side 5 cm. Each sloping edge is 6 cm long. Find, correct to 2 decimal places, the height of the pyramid.",
A: "3.12 cm",
B: "4.85 cm",
C: "5.39 cm",
D: "5.45 cm",
answer: "B. 4",
correctLetter: "B",
correctOption: 2,
},

{
id: "question42",
question: "42. A man standing 40 m from a vertical pole observes that the angle of elevation of the top of the pole is 18'. Assuming that his eye is 1.8 m above the base of the pole, calculate correct to the nearest metre the height of the pole.",
A: "11 m",
B: "14 m",
C: "15 m",
D: "18 m",
answer: "C. 15 m",
correctLetter: "C",
correctOption: 3,
},

{
id: "question43",
instruction: "In the diagram XYZ is a triangle. If ∠XYZ = 48°, ∠YZX = 32° and |XY| = 10 cm, ",
question: "43. which of the following expressions is equal to |XZ|.",
A: "10sin32° / sin48°",
B: "10𝑠i𝑛32⁰ / 𝑠i𝑛48⁰",
C: "10𝑠i𝑛32⁰ / 10𝑠i𝑛48⁰",
D: "10𝑠i𝑛48⁰ / 𝑠i𝑛32⁰",
answer: "D. 10 sin48⁰/sin32⁰",
correctLetter: "D",
correctOption: 4,
questionFigure: require(path + "2003-A-Q-43.png"),
imageRatio: 1,
},

{
id: "question44",
question: "44. If 5p - 24 = 3(p + q), find p/q, where q ≠ 0",
A: "2/5",
B: "5/8",
C: "3/2",
D: "5/2",
answer: "D. 5/2",
correctLetter: "D",
correctOption: 4,
},

{
id: "question45",
instruction: "45. What is the modal age of the students?",
question: " ",
A: "15 years",
B: "18 years",
C: "19 years",
D: "21 years",
answer: "B. 18 years",
correctLetter: "B",
correctOption: 2,
questionFigure: require(path + "2003-A-Q-45.png"),
imageRatio: 0.22,
},

{
id: "question46",
question: "46. If a student is selected at random, what is the probability that he/she is at least 19 years old?",
A: "1/4",
B: "9/40",
C: "9/20",
D: "19/40",
answer: "C. 9/20",
correctLetter: "C",
correctOption: 3,
},

{
id: "question47",
instruction: "In the diagram PQRS is a trapezium. SRI/ PQ. |PS|=|QR| = 13 cm and |SR| = 7 cm. The parallel sides are 12 cm apart.",
question: "47. Find |PQ|",
A: "12 cm",
B: "17 cm",
C: "19 cm",
D: "20 cm",
answer: "B. 17 cm",
correctLetter: "B",
correctOption: 2,
questionFigure: require(path + "2003-A-Q-47.png"),
imageRatio: 1,
},

{
id: "question48",
question: "48. The diameter of a ₅ hundred cedis coin is 2.3cm and its thickness is 0.3 cm. Find, corect to 3 significant figures, the volume of the metal used.",
A: "1.25 cm3",
B: "2.49 cm3",
C: "4.33 cm3",
D: "4.98 cm3",
answer: "A. 1",
correctLetter: "A",
correctOption: 1,
},

{
id: "question49",
instruction: "",
question: "49. In the diagram MV and OP are parallel lines. Find the value of y.",
A: "55°",
B: "65°",
C: "75°",
D: "130°",
answer: "A. 55°",
correctLetter: "A",
correctOption: 1,
questionFigure: require(path + "2003-A-Q-49.png"),
imageRatio: 1,
},

{
id: "question50",
question: "50. The sum of the interior angles of a regular polygon is 900°. Find the number of sides of the polygon",
A: "6",
B: "7",
C: "8",
D: "9",
answer: "B. 7",
correctLetter: "B",
correctOption: 2,
},


]