import { SquareRoot, superscript, subscript, BoldText, ItalicText, Fraction, ShortFraction, LongFraction, MixedFraction, Isotopes } from "@/mathnotation"

const path = "@/assets/images/pastquestions-figures/coremathematics/coremathematicsA/coremathematics-"


export const COREMATHEMATICSA2010 = [

{
id: "question1",
question: "1. If a = 2³·² and b = 2⁴·⁵, find log₂a + log₂b",
A: "1.3",
B: "1.4",
C: "7.7",
D: "14.4",
answer: "C. 7",
correctLetter: "C",
correctOption: 3,
},

{
id: "question2",
instruction: "2. Which of the following lines represents the inequality 3 < x ≤ 7?",
question: " ",
A: " ",
B: " ",
C: " ",
D: " ",
answer: "B.  ",
correctLetter: "B",
correctOption: 2,
questionFigure: require(path + "2010-A-Q-2.png"),
imageRatio: 0.43,
},

{
id: "question3",
question: "3. Factorize the expression 3 - X - 2x²",
A: "(2x - 3)(1 - x)",
B: "(2x - 3)(x - 1)",
C: "(2x + 3)(1 - x)",
D: "(2x + 3)(1 + x)",
answer: "C. (2x + 3)(1-x)",
correctLetter: "C",
correctOption: 3,
},

{
id: "question4",
question: "4. Find the range of the distribution",
A: "10",
B: "9",
C: "7",
D: "5",
answer: "A. 10",
correctLetter: "A",
correctOption: 1,
},

{
id: "question5",
question: "5. Find the mode of the distribution",
A: "3",
B: "4",
C: "5",
D: "6",
answer: "C. 5",
correctLetter: "C",
correctOption: 3,
},

{
id: "question6",
question: "6. What is the median of the distribution?",
A: "6",
B: "5",
C: "4",
D: "3",
answer: "C. 4",
correctLetter: "C",
correctOption: 3,
},

{
id: "question7",
question: "7. A bag contains 3 red and 5 white balls. Two balls are picked at random, one after the other with replacement. What is the probability that the two balls have the same colour?",
A: "15/32",
B: "17/32",
C: "13/28",
D: "15/28",
answer: "B. 17/32",
correctLetter: "B",
correctOption: 2,
},

{
id: "question8",
question: "8. Express 112₇ as a number in base four",
A: "322",
B: "321",
C: "232",
D: "223",
answer: "A. 322",
correctLetter: "A",
correctOption: 1,
},

{
id: "question9",
question: "9. Find the value of (81)^(¹/₂) x (27)^(-¹/₃) x (32)^(¹/₅)",
A: "54",
B: "18",
C: "12",
D: "6",
answer: "D. 6",
correctLetter: "D",
correctOption: 4,
},

{
id: "question10",
question: "10. A man borrowed GH¢65,000.00 from a bank and paid an amount of GH¢78,000.00. If the rate of simple interest was 5% per annum, calculate how long the man borrowed the money.",
A: "3.3 years",
B: "4.0 years",
C: "16.7 years",
D: "24.0 years",
answer: "B. 4",
correctLetter: "B",
correctOption: 2,
},

{
instruction: "The diagram below is the graph of y = 2x² + 3x - 2 Use the graph to answer Questions 11 and 12",
id: "question11",
question: "11. What are the roots of the quadratic equation 2x² + 3x - 2 = 0?",
A: "0.5, 2",
B: "-0.5, 2",
C: "-2, -2",
D: "-2",
answer: "D. -2, 0",
correctLetter: "D",
correctOption: 4,
questionFigure: require(path + "2010-A-Q-11.png"),
imageRatio: 1,
},

{
id: "question12",
question: "12. The minimum value of y is approximately equal to",
A: "-0.5",
B: "-2.0",
C: "-2.5",
D: "-3.0",
answer: "D. -3",
correctLetter: "D",
correctOption: 4,
},

{
id: "question13",
question: "13. Calculate the perimeter of a regular octagon of side 12 cm.",
A: "66 cm",
B: "72 cm",
C: "84 cm",
D: "96 cm",
answer: "D. 96 cm",
correctLetter: "D",
correctOption: 4,
},

{
id: "question14",
question: "14. Thomas bought a computer set on a hire purchase for N 250,000. He pays N 100,000 as deposit and is allowed to pay the balance in eight equal instalments. How much is one instalment",
A: ". N 12,500",
B: "N 15,780",
C: "N 18,750",
D: "N31,250",
answer: "C. N 18,750",
correctLetter: "C",
correctOption: 3,
},

{
id: "question15",
question: "15. Find the two consecutive integers such that three times the smaller integer added to two times the greater integer equals 42",
A: "6 and 7",
B: "7 and 8",
C: "8 and 9",
D: "9 and 10",
answer: "C. 8 and 9",
correctLetter: "C",
correctOption: 3,
},

{
id: "question16",
question: "16. Given that y varies inversely as x and y = 6 when x = 3, find the value of y when x = 9.",
A: "4",
B: "3",
C: "2",
D: "1",
answer: "C. 2",
correctLetter: "C",
correctOption: 3,
},

{
id: "question17",
question: "17. If cos y = ¾ where 0 ≤ y ≤ 90°, find y",
A: "40.5°",
B: "41.4°",
C: "45.4°",
D: "46.1°",
answer: "B. 41",
correctLetter: "B",
correctOption: 2,
},

{
id: "question18",
question: "18. Expand 3(3y-1)(6y- 5).",
A: "54y² - 63y + 15",
B: "54y² - 63y - 15",
C: "54y² + 27y + 15",
D: "54y² - 27y - 15",
answer: "A. 54y² - 63y + 15",
correctLetter: "A",
correctOption: 1,
},

{
id: "question19",
question: "19. Simplify: (1/m) − n / (m² + mn)",
A: "𝑚/(𝑚 − 𝑛)",
B: "1/(𝑚 − 𝑛)",
C: "𝑚/(𝑚 + 𝑛)",
D: "1/(𝑚 + 𝑛)",
answer: "D. 1/m+n",
correctLetter: "D",
correctOption: 4,
},

{
id: "question20",
question: "20. If Sn = 2n² - 3n, evaluate S6",
A: "4",
B: "10",
C: "18",
D: "54",
answer: "D. 54",
correctLetter: "D",
correctOption: 4,
},

{
instruction: "Use the diagram to answer Questions 21 and 22.",
id: "question21",
question: "21. What is the value of x in the diagram?",
A: "125°",
B: "55°",
C: "50°",
D: "40°",
answer: "B. 55°",
correctLetter: "B",
correctOption: 2,
questionFigure: require(path + "2010-A-Q-21.png"),
imageRatio: 1,
},

{
id: "question22",
question: "22. What is the value of y in the diagram?",
A: "50°",
B: "55°",
C: "75°",
D: "125°",
answer: "C. 75°",
correctLetter: "C",
correctOption: 3,
},

{
id: "question23",
question: "23. If y + 3x = 1 and x - y = 2, find the value of x.",
A: "1/2",
B: "3/4",
C: "1",
D: "114 D.",
answer: "B. 3/4",
correctLetter: "B",
correctOption: 2,
},

{
id: "question24",
question: "24. Solve for x if x/2 - 1/5 = x/3 + 1/4",
A: "3.7",
B: "2.7",
C: "0.5",
D: "0.3",
answer: "B. 2",
correctLetter: "B",
correctOption: 2,
},

{
id: "question25",
question: "25. Make z the subject of the relation z = ³√((ax -R) / (z + bz))",
A: "z = (ax - R) / (k³(R + bx))",
B: "z = ((a + bx)k³) / (R - ax)",
C: "z = (ax - k³bx) / (k³)",
D: "z = (ax - R -k³bx) / (k³)",
answer: "D. z = (ax-R-k3bx)/k3",
correctLetter: "D",
correctOption: 4,
},

{
id: "question26",
question: "26. For what values of x is (6x² -17x + 12) / (6x² + x - 12) undefined?",
A: "4/3 and -3/2",
B: "-4/3 and -3/2",
C: "8 and -9",
D: "8 and 9",
answer: "A. 4/3 and -3/2",
correctLetter: "A",
correctOption: 1,
},

{
id: "question27",
question: "27. Mr. Kofi spent 1/10 of his income on a shirt and serviced his loan with 1/3 of the remainder. If his income is GH¢30,000.00, how much is left?",
A: "GH¢11,000.00",
B: "GH¢ 13,000.00",
C: "GH¢ 16,000.00",
D: "GH¢18,000.00",
answer: "D. GH¢18,000",
correctLetter: "D",
correctOption: 4,
},

{
id: "question28",
question: "28. An arc of length 22 cm subtends an angle of 270° at the centre of the circle. Find the radius of the circle. (Take π= 22/7)",
A: "9²/₃ cm",
B: "9¹/₃ cm",
C: "7¹/₃ cm",
D: "4²/₃ cm",
answer: "D. 4²/₃ cm",
correctLetter: "D",
correctOption: 4,
},

{
id: "question29",
question: "29. Three of the angles of a hexagon are 2mo each. The others are 3mo, 5mo and mo respectively. Find mo",
A: "36",
B: "48",
C: "80",
D: "96",
answer: "B. 48",
correctLetter: "B",
correctOption: 2,
},

{
id: "question30",
question: "30. From the top of a building 12 m high, the angle of depression of a cat on the ground level is 60°. How far is the cat from the foot of the building?",
A: "6.00 cm",
B: "6.93 cm",
C: "10.39 cm",
D: "20.7 cm",
answer: "D. 20",
correctLetter: "D",
correctOption: 4,
},

{
id: "question31",
question: "31. Calculate the area, in cm 2, of an equilateral triangle of side 6 cm",
A: "9√3",
B: "7√3",
C: "5√3",
D: "3√3",
answer: "A. 9√3",
correctLetter: "A",
correctOption: 1,
},

{
id: "question32",
question: "32. Find the largest integer n, such that - 4n > 5 - n",
A: "-3",
B: "-2",
C: "2",
D: "3",
answer: "B. -2",
correctLetter: "B",
correctOption: 2,
},

{
id: "question33",
question: "33. A car travels at 120 km/h. Find the distance it covers in 15 seconds",
A: "0. 5m",
B: "5.0m",
C: "50.0 m",
D: "500.0 m",
answer: "D. 500",
correctLetter: "D",
correctOption: 4,
},

{
id: "question34",
question: "34. In the diagram, |PS| = 2 cm, |PT| = 3 cm, |PQ| = 5 cm and |QR|= 8 cm. Find |ST|.",
A: "2³/₅ cm",
B: "3¹/₅ cm",
C: "3¹/₂ cm",
D: "5¹/₄ cm",
answer: "B. 3 1/5 cm",
correctLetter: "B",
correctOption: 2,
questionFigure: require(path + "2010-A-Q-34.png"),
imageRatio: 1.0,
},

{
id: "question35",
question: "35. In the diagram above, WXY is an equilateral triangle. WUX = 130°. Find the value of angle UXY.",
A: "35°",
B: "40°",
C: "45°",
D: "50°",
answer: "A. 35°",
correctLetter: "A",
correctOption: 1,
questionFigure: require(path + "2010-A-Q-35.png"),
imageRatio: 1.0,
},

{
id: "question36",
question: "36. What value of m will make the expression x2 - 3/4x + m a perfect square?",
A: "3/2",
B: "9/16",
C: "3/8",
D: "9/64",
answer: "D. 9/64",
correctLetter: "D",
correctOption: 4,
},

{
id: "question37",
question: "37. In the figure, 0 is the centre of the circle. |OX| = |OY| and ∠OXQ = ∠OYS = 90°. Which of the following is/are correct? \nI.	|PQ|= |RS| \nII.	|PX| = |XQ| \nIII. |RY| = |YS|",
A: "I only",
B: "I and II only",
C: "II and III only",
D: "I, II and III",
answer: "C. II and III only",
correctLetter: "C",
correctOption: 3,
questionFigure: require(path + "2010-A-Q-37.png"),
imageRatio: 1,
},

{
id: "question38",
question: "38. In the diagram above, △PQR is inscribed in a circle centre 0, |PQ| = |QR| and ∠PRQ = 64°. Find ∠POR",
A: "76°",
B: "92°",
C: "104°",
D: "128°",
answer: "C. 104°",
correctLetter: "C",
correctOption: 3,
questionFigure: require(path + "2010-A-Q-38.png"),
imageRatio: 1,
},

{
id: "question39",
question: "39. A solid cylinder has radius 0.84 m and length 2 m. Calculate the area covered by the cylinder in 2 revolutions.",
A: "2.82π m²",
B: "4.42π m²",
C: "5.64π m²",
D: "6.72π m²",
answer: "D. 6",
correctLetter: "D",
correctOption: 4,
},

{
id: "question40",
question: "40. An arc XY of a circle radius 7 cm subtends an angle of 135° at the centre. Calculate the area of the major sector, correct to one decimal place. (Take π = 22/7)",
A: "27.5 cm²",
B: "5.5 cm²",
C: "77.8 cm²",
D: "96.3 cm²",
answer: "D. 96",
correctLetter: "D",
correctOption: 4,
},

{
id: "question41",
question: "41. Express 3 m 24 cm in kilometres, leaving the answer in standard form",
A: "3.24 x 10-4 km",
B: "3.24 x 10-3 km",
C: "3.24 x 10-2 km",
D: "3.24 x 10-1 km",
answer: "B. 3",
correctLetter: "B",
correctOption: 2,
},

{
id: "question42",
question: "42. The base of a parallelogram is twice its perpendicular height. If the area is 128 cm 2 calculate the length of the base",
A: "32 cm",
B: "24 cm",
C: "16 cm",
D: "8 cm",
answer: "C. 16 cm",
correctLetter: "C",
correctOption: 3,
},

{
id: "question43",
instruction: "In the diagram above, X and y are finite sets. ",
question: "43. Which of the following statements is true?",
A: "X' n Y = Y",
B: "X n Y' = U.",
C: "X' n Y = X",
D: "Y n X = X.",
answer: "A. X' n Y = Y",
correctLetter: "A",
correctOption: 1,
questionFigure: require(path + "2010-A-Q-43.png"),
imageRatio: 1,
},

{
id: "question44",
question: "44. An empty rectangular tank is 2.5 m long and 1.2 m wide. If 300 litres of water is poured into it, calculate the height of the water level",
A: "0.6 m",
B: "0.4 m",
C: "0.2 m",
D: "0.1 m",
answer: "A. 0",
correctLetter: "A",
correctOption: 1,
},

{
id: "question45",
question: "45. In the diagram, 0 is the centre of the circle. What is the value of the angle marked x?",
A: "60°",
B: "45°",
C: "30°",
D: "15°",
answer: "B. 45°",
correctLetter: "B",
correctOption: 2,
questionFigure: require(path + "2010-A-Q-45.png"),
imageRatio: 1,
},

{
id: "question46",
question: "46. The bearing of the point P from Q is 306°. Find the bearing of Q from P",
A: "036°",
B: "054°",
C: "126°",
D: "180°",
answer: "B. 054°",
correctLetter: "B",
correctOption: 2,
},

{
id: "question47",
question: "47. In the diagram, ∠YXZ = ∠XKZ = 90°, |YK| = 4 cm and |XK| = 6 cm. Calculate |KZ|",
A: "9.0 cm",
B: "8.0 cm",
C: "7.5 cm",
D: "6.5 cm",
answer: "A. 9",
correctLetter: "A",
correctOption: 1,
questionFigure: require(path + "2010-A-Q-47.png"),
imageRatio: 1,
},

{
id: "question48",
question: "48. Simplify : (√48 + 3) / √3",
A: "4 + √3",
B: "(4 + √3)/3",
C: "3 + 4√3",
D: "(4 + √3)/9",
answer: "A. 4 + √3",
correctLetter: "A",
correctOption: 1,
},

{
id: "question49",
question: "49. The two line segments MN and LN intersect each other at the point N. What is the locus of the point Ton the plane which moves such that its distance from MN is equal to its distance from LN?",
A: "The bisector of angle LNM",
B: "The bisector of angle NLM",
C: "A line parallel to MN and LN",
D: "The perpendicular bisector of LN and MN",
answer: "A. The bisector of angle LNM",
correctLetter: "A",
correctOption: 1,
},

{
id: "question50",
question: "50. A sector which subtends an angle 150° was cut off from a circle with radius 6.0 cm .. The remainder is folded with its straight edges just touching each other to form a cone. Calculate the radius of the cone",
A: "10.3 cm",
B: "6.0 cm",
C: "3.5 cm",
D: "2.5 cm",
answer: "C. 3",
correctLetter: "C",
correctOption: 3,
},

]