import { SquareRoot, superscript, subscript, BoldText, ItalicText, Fraction, ShortFraction, LongFraction, MixedFraction, Isotopes } from "@/mathnotation"

const path = "@/assets/images/pastquestions-figures/coremathematics/coremathematicsA/coremathematics-"

export const COREMATHEMATICSA2006 = [

{
id: "question1",
question: "1. Evaluate (0.13)³ correct to three significant figures.",
A: "0.002",
B: "0.003",
C: "0.00219",
D: "0.00220",
answer: "D. 0",
correctLetter: "D",
correctOption: 4,

},

{
id: "question2",
question: "2. A student reads the length of a pole as 5.05 m when the correct length is 5.00 m. Calculate his percentage error.",
A: "10%",
B: "5.00%",
C: "1.01%",
D: "1%",
answer: "D. 1%",
correctLetter: "D",
correctOption: 4,
},

{
id: "question3",
question: "3. Evaluate (111₂ + 101₂)(111₂ -101₂)",
A: "10₂",
B: "110₂",
C: "1100₂",
D: "11000₂",
answer: "D. 11000₂",
correctLetter: "D",
correctOption: 4,
},

{
id: "question4",
question: "4. The length and width of a rectangle are in the ratio 5:2. If the perimeter is 70 cm, calculate the length of the rectangle.",
A: "25 cm",
B: "24 cm",
C: "23 cm",
D: "21 cm",
answer: "A. 25 cm",
correctLetter: "A",
correctOption: 1,
},

{
id: "question5",
instruction: "In the diagram, PQR is a tangent to the circle at Q, ∠YQR = 54° and ∠XYQ = 41°.",
question: "5. Find the size of ∠XQ.",
A: "95°",
B: "85°",
C: "54°",
D: "36°",
answer: "B. 85°",
correctLetter: "B",
correctOption: 2,
questionFigure: require(path + "2006-A-Q-5.png"),
imageRatio: 1.0,
},

{
id: "question6",
question: "6. A certain number x is multiplied by 5. Another number that is 6 less than x is also multiplied by 5. By how much is the first product greater than the second?",
A: "5",
B: "6",
C: "25",
D: "30",
answer: "D. 30",
correctLetter: "D",
correctOption: 4,
},

{
id: "question7",
question: "7. If x = y and z > y, which of the following must be true? \nI. x < z \nII. x = z \nIII. x > z",
A: "I only",
B: "II only",
C: "III only",
D: "I and III only",
answer: "A. I only",
correctLetter: "A",
correctOption: 1,
},

{
id: "question8",
question: "8. If the mean of p, q, r, s and t is 10, calculate the mean of p + 1, q + 2, r + 3, s + 4 and t + 5.",
A: "12",
B: "13",
C: "14",
D: "15",
answer: "B. 13",
correctLetter: "B",
correctOption: 2,
},

{
id: "question9",
question: "9. A bag contains 12 blue and 8 red balls. If 2 balls are picked at random from the bag without replacement, what is the probability that they are both blue?",
A: "9/25",
B: "33/95",
C: "1/2",
D: "33/100",
answer: "B. 33/95",
correctLetter: "B",
correctOption: 2,
},

{
id: "question10",
question: "10. The diagonals of a rhombus are 7.2 cm and 6.3 cm long. Calculate the area of the rhombus.",
A: "17.01 cm²",
B: "22.68 cm²",
C: "45.36cm²",
D: "68.04 cm²",
answer: "B. 22",
correctLetter: "B",
correctOption: 2,
},

{
id: "question11",
question: "11. A postcard 8 cm by 6 cm is enlarged such that the longer side becomes 12 cm long. If the shorter side is also enlarged in the same proportion, what is the ratio of the ₂ areas?",
A: "4:3",
B: "9:4",
C: "3:2",
D: "4:1",
answer: "B. 9:4",
correctLetter: "B",
correctOption: 2,
},

{
id: "question12",
question: "12. Obtain an equation whose roots are 1²/₃ and −1²/₃",
A: "3x + 5 = 0",
B: "3x - 5 = 0",
C: "9x² - 25 = 0",
D: "9x² + 25 = 0",
answer: "C. 9x² - 25 = 0",
correctLetter: "C",
correctOption: 3,
},

{
id: "question13",
question: "13. Solve the quadratic equation 4y² + 5y - 21 = 0.",
A: "y = 3 or 1 3/4",
B: "y = 3 or -1 3/4",
C: "y = -3 or 1 3/4",
D: "y = -3 or -1 3/4",
answer: "C. y = -3 or 1 3/4",
correctLetter: "C",
correctOption: 3,
},

{
id: "question14",
instruction: "In the diagram, POR is a diameter, ∠QPR = a° and ∠PRS = (4a + 12)°.",
question: "14. Find the value of a.",
A: "19.5",
B: "26",
C: "42",
D: "78",
answer: "B. 26",
correctLetter: "B",
correctOption: 2,
questionFigure: require(path + "2006-A-Q-14.png"), 
imageRatio: 1,
},

{
id: "question15",
question: "15. If X and Y are independent outcomes of an event, then the probability Pr(X or ) is given by",
A: "Pr(X) x Pr(Y)",
B: "Pr(X) ÷ Pr(Y)",
C: "Pr(X) + Pr(Y)",
D: "Pr(X) - Pr(Y)",
answer: "C. Pr(X) + Pr(Y)",
correctLetter: "C",
correctOption: 3,
},

{
id: "question16",
question: "16. Kofi invested a sum of ¢3,000 at the rate of 3½ % per annum simple interest. How much does his money amount to at the end of the sixth year?",
A: "¢3,105",
B: "¢3,540",
C: "¢3,630",
D: "¢3,930",
answer: "C. ¢3,",
correctLetter: "C",
correctOption: 3,
},

{
id: "question17",
question: "17. A journey made at an average speed of 40 km per hour took 2½ hours. How long would it take if the same journey was made at an average speed of 50 km per hour?",
A: "45 minutes",
B: "1 hour 15 minutes",
C: "2 hours",
D: "3 hours 712",
answer: "B. 2 hours",
correctLetter: "B",
correctOption: 2,
},

{
D: "minutes",
answer: "B. 2 hours",
correctLetter: "B",
correctOption: 2,
},

{
id: "question18",
question: "18. For what value(s) of y is 1/y +	1/(y + 1) undefined?",
A: "0 only",
B: "1/2 only",
C: "1 only",
D: "0 and 1 only",
answer: "D. 0 and 1 only",
correctLetter: "D",
correctOption: 4,
},

{
id: "question19",
question: "19. Simplify the expression	(x + 𝑦) / (x⁻¹ + 𝑦⁻¹)",
A: "x/y",
B: "xy",
C: "y/x",
D: "1/y",
answer: "B. xy",
correctLetter: "B",
correctOption: 2,
},

{
id: "question20",
instruction: "In the diagram, |PT|=|ST|, |QU|= |RU| |PQ| = |RS| = 16 cm and |TU| = 11cm.",
question: "20. Calculate the area of the shaded region.",
A: "80 cm²",
B: "96 cm²",
C: "160 cm²",
D: "162 cm²",
answer: "D. 162 cm²",
correctLetter: "D",
correctOption: 4,
questionFigure: require(path + "2006-A-Q-20.png"),
imageRatio: 1.0,
},

{
id: "question21",
instruction: "21. Which of the following inequalities is represented on the number line?",
question: " ",
A: "-3 < x < 3",
B: "3 ≤ x < 3",
C: "-3 ≤ x ≤ 3",
D: "-3 < x ≤ 3",
answer: "B. 3 ≤ x < 3",
correctLetter: "B",
correctOption: 2,
questionFigure: require(path + "2006-A-Q-21.png"),
imageRatio: 0.27,
},

{
id: "question22",
question: "22. Given that $1 = ¥115 and £l = $1.67, find, correct to the nearest pound, the value of 5,000.",
A: "£l6",
B: "£26",
C: "£43",
D: "£73",
answer: "B. £26",
correctLetter: "B",
correctOption: 2,
},

{
id: "question23",
instruction: "In the diagram, O is the centre of the circle.",
question: "23. |SN|=|NM| and <LMS = 34°, find x",
A: "34°",
B: "56°",
C: "68°",
D: "90°.",
answer: "C. 68°",
correctLetter: "C",
correctOption: 3,
questionFigure: require(path + "2006-A-Q-23.png"),
imageRatio: 1.0,
},

{
id: "question24",
question: "24. Kofi, Kate and Ladi shared an amount of ¢4,747.00 in the ratio 20 : 15 : 12 respectively. What is Kate's share?",
A: "¢2020.00",
B: "¢1515.00",
C: "¢1212.00",
D: "¢1010.00",
answer: "B. ¢1515",
correctLetter: "B",
correctOption: 2,
},

{
id: "question25",
question: "25. ₂ variables P and Q are connected by a linear relation of the form P = kO + c where c and k are constants. If Q=6 when P = 1 and Q 24 when P = 10, find the equation connecting Pand .Q",
A: "P = ¹/₂Q - 2",
B: "P = ¹/₂Q + 2",
C: "p = (Q − 2)/2",
D: "(Q + 2)/2",
answer: "A. P = ½Q - 2",
correctLetter: "A",
correctOption: 1,
},

{
instruction: "The diagram below is the graph of a quadratic function Use the information to answer Questions 26 and 27.",
id: "question26",
question: "26. What is the equation of the curve?",
A: "y = 2x² + x - 6",
B: "y = x² + 2x - 6",
C: "y = x² + 3x - 3",
D: "y = 2x² + 3x + 6",
answer: "A. y = 2x² + x - 6",
correctLetter: "A",
correctOption: 1,
questionFigure: require(path + "2006-A-Q-26.png"),
imageRatio: 1,
},

{
id: "question27",
question: "27. What is the minimum value of y?",
A: "-2",
B: "-3",
C: "-6.2",
D: "-6.4",
answer: "C. -6",
correctLetter: "C",
correctOption: 3,
},

{
id: "question28",
instruction: "In the diagram, O is the centre of the circle of radius 8 cm and ∠YKZ = 60°.",
question: "28. Calculate the length of the minor arc YZ. [Take π = 22/7]",
A: "6.7 cm",
B: "8.38 cm",
C: "16.76 cm",
D: "33.5 cm",
answer: "C. 16",
correctLetter: "C",
correctOption: 3,
questionFigure: require(path + "2006-A-Q-28.png"),
imageRatio: 1.0,
},

{
id: "question29",
question: "29. Find the value of m + n from the sequence 1 x 5, 3 x 9, 5 x 13, 7 x 17, m x n...",
A: "24",
B: "29",
C: "30",
D: "39",
answer: "C. 30",
correctLetter: "C",
correctOption: 3,
},

{
id: "question30",
instruction: "The pie chart shows the budget of a worker who earned 6,000 in the month of November, 2001.",
question: "30. What is the angle of the sector representing food?",
A: "36°",
B: "84°",
C: "108°",
D: "120°",
answer: "C. 108°",
correctLetter: "C",
correctOption: 3,
questionFigure: require(path + "2006-A-Q-30.png"),
imageRatio: 1,
},

{
id: "question31",
question: "31. If d = ³√((P + K²)/(Q - d³)) express P in terms of K, Q and d.",
A: "(dQ - K²)/(1 + d³)",
B: "(1 + d³)/(d³Q - K²)",
C: "(1 + d³)/(Q)",
D: "d³Q + K²",
}, 

{
id: "question32",
instruction: "In the diagram, |ST| = 18cm, |PQ| = 6cm, |RP| = x and PS = y.",
question: "32. Find the ratio x:y.",
A: "2:1",
B: "1:3",
C: "3:1",
D: "1:2",
answer: "B. 1:3",
correctLetter: "B",
correctOption: 2,
questionFigure: require(path + "2006-A-Q-32.png"),
imageRatio: 1,
},

{
id: "question33",
instruction: "In the diagram, |PS|=3 cm, |SQ| =5 cm, |QR| = 12 cm, ST//PU and SP//TU.",
question: "33. Calculate PU",
A: "6 cm",
B: "5.5 cm",
C: "5 cm",
D: "4.5 cm",
answer: "D. 4",
correctLetter: "D",
correctOption: 4,
questionFigure: require(path + "2006-A-Q-33.png"),
imageRatio: 1,
},

{
id: "question34",
question: "34. The exterior angles of a pentagon are x°, 2x°, 3x°, 4x° and 2x. What is the size of the largest angle?",
A: "60°",
B: "90°",
C: "120°",
D: "150°",
answer: "C. 120°",
correctLetter: "C",
correctOption: 3,
},

{
id: "question35",
question: "35. If X = {2, 3}, which of the following represents all the possible subsets of X?",
A: "{2, 3}",
B: "{}, {2}, {3}",
C: "(2}, (3}, {2,3}",
D: "{},12},{13},{12, 3}",
answer: "D. {},{12},{13},{12, 3}",
correctLetter: "D",
correctOption: 4,
},

{
id: "question36",
question: "36. Find the values of x and y that satisfy the equations: 2x + y = 3 and ˣ/₂ - 2y = 3",
A: "x = 1, y = 2",
B: "x = -1, y = 2",
C: "x = 2, y = 1",
D: "x = 2, y = -1",
answer: "D. x = 2, y = -1",
correctLetter: "D",
correctOption: 4,
},

{
id: "question37",
question: "37. If 4.95 x 10ⁿ = 0.0495, find the value of n.",
A: "2",
B: "1",
C: "-1",
D: "-2",
answer: "D. -2",
correctLetter: "D",
correctOption: 4,
},

{
id: "question38",
question: "38. A pole 10 m high stands on the same horizontal level with a tree. From the top of the pole, the angle of elevation of a bird on top of the tree is 36°. If the pole and the tree are 220 m apart, calculate the height of the tree",
A: "129.3 m",
B: "139.3 m",
C: "149.3 m",
D: "169.8 m",
answer: "A. 129",
correctLetter: "A",
correctOption: 1,
},

{
id: "question39",
question: "39. If w = -3, x = 14, y = 17 and z = -2, evaluate",
A: "23/27",
B: "31/27",
C: "-23/27",
D: "-31/27",
answer: "A. 23/27",
correctLetter: "A",
correctOption: 1,
},

{
id: "question40",
question: "40. A cone is made from a sector of a circle of radius 14 cm and angle 90°. What is the area of the curved surface of the cone? [Take π=22/7]",
A: "154 cm²",
B: "77 cm²",
C: "38 cm²",
D: "36 cm²",
answer: "C. 38 cm²",
correctLetter: "C",
correctOption: 3,
},

{
id: "question41",
question: "41. Two points X and Y are respectively 20 km north and 9 km east of a point O. Find, correct to the nearest degree, the bearing of X from Y",
A: "156o",
B: "246o",
C: "294o",
D: "336o",
answer: "B. 246o",
correctLetter: "B",
correctOption: 2,
},

{
id: "question42",
instruction: "In the diagram, JKL and JOMN are straight lines, ∠MKL = 102°, ∠JOK = 80° and |OJ| = |OK|",
question: "42. Find ∠JMK.",
A: "80°",
B: "52°",
C: "50°",
D: "22°",
answer: "B. 52°",
correctLetter: "B",
correctOption: 2,
questionFigure: require(path + "2006-A-Q-42.png"),
imageRatio: 1,
},

{
id: "question43",
question: "43. Evaluate (49^(²/₃) ÷ (49)^(¹/₆)) / ((¹/₇)^(⁻⁷/₆) × (¹/₇)^(¹/₆))",
A: "0",
B: "1",
C: "7",
D: "49",
answer: "C. 7",
correctLetter: "C",
correctOption: 3,
},

{
id: "question44",
instruction: "In the diagram |TR| = |TS| and LTRS= 60°. ",
question: "44. Find the value of y",
A: "30",
B: "45",
C: "60",
D: "120",
answer: "C. 60",
correctLetter: "C",
correctOption: 3,
questionFigure: require(path + "2006-A-Q-44.png"),
imageRatio: 1,
},

{
id: "question45",
question: "45. Given that θ = 60° and B = 30°, evaluate (𝑠i𝑛𝐵 + 𝑐o𝑠𝜃)/(𝑐o𝑠𝐵) leaving your answer in surd form.",
A: "3√3",
B: "1 + 2√3",
C: "√3",
D: "1 - 2√3",
answer: "C. √3",
correctLetter: "C",
correctOption: 3,
},

{
id: "question46",
instruction: "In the diagram P00 is a straight line. ∠XOP = ∠XOY and ∠ZOQ = ∠ZOY ",
question: "46. Find ∠XOZ.",
A: "120°",
B: "90°",
C: "60°",
D: "30°",
answer: "B. 90°",
correctLetter: "B",
correctOption: 2,
questionFigure: require(path + "2006-A-Q-46.png"),
imageRatio: 1,
},

{
id: "question47",
question: "47. Find the value of n if (𝑙og₁₀𝑛)/(𝑙og₁₀64) = ¹/₂",
A: "4",
B: "8",
C: "16",
D: "24",
answer: "C. 16",
correctLetter: "C",
correctOption: 3,
},

{
id: "question48",
question: "48. If 8ˣ = 2√2, find the value of x.",
A: "3/2",
B: "1",
C: "½",
D: "- ½",
answer: "C. ½",
correctLetter: "C",
correctOption: 3,
},

{
id: "question49",
question: "49. In a community of 400 people, the 80th percentile age is 60 years while the 15th percentile age is 10 years. How many of the people are approximately between 10 and 60 years",
A: "200",
B: "260",
C: "280",
D: "380",
answer: "B. 260",
correctLetter: "B",
correctOption: 2,
},

{
id: "question50",
question: "50. The volume of a right pyramid is 144 cm³. If the height is 12 cm, find the base area",
A: "72 cm²",
B: "48 cm²",
C: "36 cm²",
D: "24 cm²",
answer: "C. 36 cm²",
correctLetter: "C",
correctOption: 3,
},

]