import { SquareRoot, superscript, subscript, BoldText, ItalicText, Fraction, ShortFraction, LongFraction, MixedFraction, Isotopes } from "@/mathnotation"

const path = "@/assets/images/pastquestions-figures/coremathematics/coremathematicsA/coremathematics-"

export const COREMATHEMATICSA2022 = [

{
id: "question1",
question: "1. A bag contains 32 blue, 28 black and 20 red identical balls of same size. If	ball is picked at random, what is the probability that it is not red?",
A: "1/4",
B: "2/5",
C: "3/5",
D: "-3/4",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question2",
question: "2. Metuh is nine times as old as his cousin, Fafa. In six years time, he will be five times as old as Fafa. Find Fafa's present age.",
A: "5 years",
B: "6 years",
C: "7 years",
D: "8 years",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question3",
question: "3. The area of a sector of a circle is 40 cm². If the sector subtends an angle of 140° at the centre, find the area of the circle.",
A: "l 02.86 cm²",
B: "111.56 cm²",
C: "120.38 cm²",
D: "132.06 cm²",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question4",
question: "4. The interior angle of a regular polygon is twice the exterior angle. How many sides has the polygon?",
A: "S",
B: "6",
C: "8",
D: "9",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question5",
question: "5. Consider the following statements: \nM· Helena studies hard; \nN: Helena passes her examination. \nIf M => N, which ?fthe following is a v lid conclusion?",
A: "If Helena does not study hard, then she will pass her examination.",
B: "If Helena does not study hard, then she will not pass her examination.",
C: "If Helena passes her examination, then she had not studied hard.",
D: "If Helena does not pass her examination then she had not studied hard.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question6",
question: "6. The probabilities of three·independent events X, Y and Z occurring are 1/2, 2/3, and 1/4 respectively. What is the probability that only events X and Z are occurring?",
A: "1/24",
B: "3/24",
C: "1/8",
D: "3/4",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question7",
question: "7. A die is rolled once. Find the probability of obtaining anumber less than 3.",
A: "1/6",
B: "5/6",
C: "2/3",
D: "1/3",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question8",
question: "8. The bearing of a point P from a point Q is 065°. What is the bearing of Q from P?",
A: "115°",
B: "155°",
C: "245°",
D: "295°",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question9",
question: "9. The exterior angles of a quadrilateral are 61°, 76° , (x + I 0)0 and (2x + 45)0. Find the value of x.",
A: "45",
B: "60",
C: "66",
D: "56",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question10",
instruction: "If the area of the trapezium MNOP is 300 cm², ",
question: "10. find the value of x.",
A: "15 cm",
B: "12 cm",
C: "10cm",
D: "20cm",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
questionFigure: require(path + "2022-A-Q-10.png"),
imageRatio: 1,
},

{
id: "question11",
question: "11. The graph of y = x² + 4x - 6 is drawn and a linear graph is drawn on the axes such thnt the intersection of the two graphs gives the solution to the equation ; x² + 4x - 6 = 0. Find the equation for the linear graph.",
A: "x= I",
B: "x=-1",
C: "y=-1",
D: "y= 1",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question12",
question: "12. Dina and Rose were given OH¢ 875.08 to be shared in the ratio 3: 2 respectively. If Rose shared her part of the money between Efua and Amain the ratio 1 : 2 respectively, how much was Ama's share?",
A: "OH¢ l16.68",
B: "OH¢ 175.02",
C: "OH¢ 233.35",
D: "GH¢ 340.32",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question13",
question: "13. The arc of a circle 50 cm long subtends an angle 75°at the centre of the circle. Find, correct to three significant figures, the radius of the circle. [Take 7t = 27/7  ]",
A: "76.4 cm",
B: "61.2 cm",
C: "38.2 cm",
D: "8.74 cm",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question14",
question: "14. If 17 = 3 mod x , find the least value of x.",
A: "3",
B: "5",
C: "7",
D: "9",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question15",
question: "15. Evaluate ((53,000,000) × (0.002)) / 0.0004	and express the answer in standard form.",
A: "2.65 X 10⁻⁸",
B: "2.65 X 10⁷",
C: "2.65 X 10⁻⁷",
D: "2.65 X 10⁻⁸",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question16",
question: "16. If  A= 1h (a+ b), make a the subject of the relation.",
A: ".",
B: ".",
C: ".",
D: ".",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question17",
question: "17. Express, correct to two significant figures, () .",
A: "0.036",
B: "0.035",
C: "0.030",
D: "0.040",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question18",
question: "18. Sirnplify:",
A: ".",
B: ".",
C: ".",
D: ".",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question19",
question: "19. Evaluate tan 30° - 2sin 60° .",
A: ".",
B: ".",
C: ".",
D: ".",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question20",
question: "20. Find the number of even integers between 11 and 97.",
A: "43",
B: "44",
C: "45",
D: "53",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question21",
question: "21. If y varies as the squ e of x, y = 3 when x = -J2.find the value of y when x = 2.",
A: "2",
B: "4",
C: "5",
D: "6",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question22",
question: "22. Given that 6log (x + 4) = log 64, find the value of x.",
A: "4",
B: "2",
C: "-2",
D: "-4",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question23",
question: "23. If23x = 11 lltwo, find the value ofx.",
A: "5",
B: "6",
C: "7",
D: "8",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question24",
question: "24. In the diagram P,Q,R,S are points on the circle. If L.PQS = 32° and LPRQ = 61°, find LQPS.",
A: "32°",
B: "61°",
C: "87°",
D: "90°",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
questionFigure: require(path + "2022-A-Q-24.png"),
imageRatio: 1,
},

{
id: "question25",
question: "25. Given that P = x - -1  and q = x2 +--¼, express q in terms of p.",
A: "q=(p2+2)",
B: "q = (p-	2)2",
C: "q=(p+ 2)2",
D: "q=(p2 -2)",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question26",
question: "26. A car, mo es !It. an average speed Qf 30 kmh-1. How long 9qes. it take to cover 200.metres?",
A: "2.4 seco.nds	,.",
B: "24 seconds",
C: "144 seconds",
D: "240 seconds",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question27",
question: "27. The length of a rectangular lawn is 3 cm longer than the width. If the perimeter is 42 cm, find the width.	•,'",
A: "6cm",
B: "9cm",
C: "12 cm",
D: "15 cm",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question28",
question: "28. If	9y+l=( ) find y",
A: "4/5",
B: "-4/5",
C: "1",
D: "-4",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question29",
question: "29. A woman buys 3 exercise books at GH¢ 0.4 each and 9 exercise books at GH¢ 0.2 each. What is the average cost of an exercise book?",
A: "OH¢ 0.35",
B: "OH¢ 0.30",
C: "OH¢ 0.22",
D: "GH¢ 0.25",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question30",
question: "30. The shadow of a vertical pole is 50 cm. If the height of the pole is 2 m, find, correct to the nearest degree, the angle of elevation of the sun from the ground level.",
A: "45°",
B: "56°",
C: "60°",
D: "76°",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question31",
question: "31. In a class of30 students, 18 take Mathematics, Stake both Mathematics and Biology and 8 take neither Mathematics nor Biology. Find the number of students that taJce Biology.",
A: "6",
B: "8",
C: "9",
D: "13",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question32",
question: "32. Simplify",
A: ".",
B: ".",
C: ".",
D: ".",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question33",
question: "33. Find the values of x for which 'h.2- l3x + 15	is not defined.",
A: "5.	3/2",
B: "1,	11/15",
C: "2, 15",
D: "13, 15",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question34",
question: "34. In the diagram PQ is the diameter of ci clel'fQR with centre O and RS meets PQ at S. If LRQP = 64° end LRSQ = 36°, find'4PRS.",
A: "22°",
B: "18°",
C: "16°",
D: "10°",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
questionFigure: require(path + "2022-A-Q-34.png"),
imageRatio: 1,
},

{
id: "question35",
question: "35. If , find x :y",
A: "5:3",
B: "4:1",
C: "3:5",
D: "1:4",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question36",
question: "36. Find the equation of the line passing through P(4, I) and parallel lo 2x + Sy= -10.",
A: "Sx+ 2y= 13",
B: "5x-2y = 10",
C: "2x-  Sy= 10",
D: "2x+ Sy= 13",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question37",
question: "37. Simplify: s-¼--(11 +2 ).",
A: "3 9/24",
B: "3 17/24",
C: "3 19/24",
D: "3 15/24",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question38",
question: "38. One side of a rectangle is 8 cm and the diagonal is 10 cm. Calculate the area of the rectangle.",
A: "60 cm²",
B: "48 cm²",
C: "40 cm²",
D: "24c m²",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question39",
question: "39. Given that",
A: ".",
B: ".",
C: ".",
D: ".",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question40",
question: "40. Given that 4x + 6y = 5 and 2x + 4y = 3, find the value of (x +2y).",
A: "-1 1/2",
B: "-1",
C: "1",
D: "1 1/2",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question41",
question: "41. Find the 11th term of	1",
A: "8",
B: "6",
C: "4",
D: "2",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question42",
question: "42. A market woman demands GH¢ 15.00 for a tin of local rice. After some bargaining with a customer, she sells 5 tins for GH¢ 66.00. By.what percentage.did-she reduce her original price?",
A: "15 %",
B: "6%",
C: "9%",
D: "12%",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
instruction: "The mass of some market women in kg are: 83, 47, 62, 49, 55, 72, 58 and 62. Use the in/ormation to answer questions 43 and 44.",
id: "question43",
question: "43. Find the range.",
A: "21",
B: "36",
C: "46",
D: "52",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question44",
question: "44. Find the mean.",
A: "45",
B: "55",
C: "61",
D: "71",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question45",
question: "45. Find the truth set of (3 + x) .(1-x) > 9 - x2.",
A: "{x:x> 3}",
B: "{x:x> -3}",
C: "{x:.x<3}.",
D: "{x:·x <-3}",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question46",
question: "46. Simplify",
A: ".",
B: ".",
C: ".",
D: ".",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question47",
question: "47. Find the value of y in the diagram.",
A: "30°",
B: "21°",
C: "20°",
D: "10°",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
questionFigure: require(path + "2022-A-Q-47.png"),
imageRatio: 1,
},

{
id: "question48",
question: "48. In the diagram,0 is the centre of the ;;,cle PQR, IPSI - I PQI and LRQS-	23°. Find the value of x.",
A: "23°",
B: "38°",
C: "46°",
D: "67°",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
questionFigure: require(path + "2022-A-Q-48.png"),
imageRatio: 1,
},

{
id: "question49",
question: "49. In the diagram, MN// PQ.	 Find the-value of (x + y).",
A: "90°",
B: "60°",
C: "40°",
D: "30°",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
questionFigure: require(path + "2022-A-Q-49.png"),
imageRatio: 1,
},

{
id: "question50",
question: "50. In the diagram, EFGH are points on a circle centre P. If LEFG = 142° and LFGP :., 63''. find LFEP.",
A: "63°",
B: "76°",
C: "79°",
D: "89°",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
questionFigure: require(path + "2022-A-Q-50.png"),
imageRatio: 1,
},


]