import { SquareRoot, superscript, subscript, BoldText, ItalicText, Fraction, ShortFraction, LongFraction, MixedFraction, Isotopes } from "@/mathnotation"

const path = "@/assets/images/pastquestions-figures/coremathematics/coremathematicsA/coremathematics-"

export const COREMATHEMATICSA2016 = [

{
id: "question1",
question: "1. If 23ₙ +1O1ₙ = 130ₙ find the value of n.",
A: "7",
B: "6",
C: "5",
D: "4",
answer: "D. 4",
correctLetter: "D",
correctOption: 4,
},

{
id: "question2",
question: "2. Simplify: ((10√3)/√5 - √15)²",
A: "1/60",
B: "5/72",
C: "1/10",
D: "1 7/10",
answer: "C. 1/10",
correctLetter: "C",
correctOption: 3,
},

{
id: "question6",
question: "6. On a map, 1 cm represents 5 km. Find the area on the map that represents 100 km²",
A: "2 cm²",
B: "4 cm²",
C: "8 cm²",
D: "16 cm²",
answer: "B. 4 cm²",
correctLetter: "B",
correctOption: 2,
},

{
id: "question7",
question: "7. Simplify: (3ⁿ - 1 × 27ⁿ + 1) / (81ⁿ)",
A: "3²ⁿ",
B: "9",
C: "3ⁿ",
D: "3ⁿ⁺¹",
answer: "B. 9",
correctLetter: "B",
correctOption: 2,
},

{
id: "question8",
question: "8. What sum of money will amount to D10,400.00 in 5 years at 6% simple interest?",
A: "D8,000.00",
B: "D10,000.00",
C: "D12,000.00",
D: "D16,000.00",
answer: "D. D8,000",
correctLetter: "D",
correctOption: 4,
},

{
id: "question9",
instruction: "9. Which of the following number lines illustrates the solution of the inequality 4 ≤ ½ (2x -1) < 5?",
question: " ",
A: " ",
B: " ",
C: " ",
D: " ",
answer: "D. ",
correctLetter: "D",
correctOption: 4,
questionFigure: require(path + "2016-A-Q-09.png"),
imageRatio: 0.45,
},

{
id: "question10",
question: "10. The roots of a quadratic equation are 4/3 and 3/7. Find the equation.",
A: "21x² - 19x - 12 = 0",
B: "21x² + 37x - 12 = 0",
C: "21x² - x + 12 = 0",
D: "21x² + 7x - 4 = 0",
answer: "A. 21x² - 19x - 12 = 0",
correctLetter: "A",
correctOption: 1,
},

{
id: "question11",
question: "11. Find the values of y for which the expression (y² - 9y + 18) / (y² + 4y - 21)	is undefined.",
A: "6, -7",
B: "3, -6",
C: "3, - 7",
D: "-3, - 7",
answer: "C. 3, - 7",
correctLetter: "C",
correctOption: 3,
},

{
id: "question12",
question: "12. Given that 2x + y = 7 and 3x - 2y = 3, by how much is 7x greater than 10?",
A: "1",
B: "3",
C: "7",
D: "17",
answer: "C. 7",
correctLetter: "C",
correctOption: 3,
},

{
id: "question13",
question: "13. Simplify: 2/(1 - x) - 1/x",
A: "(x + 1) / (x(1 - x))",
B: "(3x + 1) / (x(1 - x))",
C: "(3x - 1) / (x(1 - x))",
D: "(x - 1) / (x(1 - x))",
answer: "B. 3x+1/x(1-x)",
correctLetter: "B",
correctOption: 2,
},

{
id: "question14",
question: "14. Make s the subject of the relation: p = s + (sm²)/nr",
A: "s = (mrp)/(nr + m²)",
B: "s = (nr + m²)/(mrp)",
C: "s = (nrp)/(mr + ²)",
D: "s = (nrp)/(nr + m²)",
answer: "D. ****",
correctLetter: "D",
correctOption: 4,
},

{
id: "question15",
question: "15. Factorize: (2x + 3y)² - (x - 4y)²",
A: "(3x - y)(x + 7y)",
B: "(3x + y)(2x - 7y)",
C: "(3x + y)(x - 7y)",
D: "(3x - y)(2x + 7y)",
answer: "A. (3x - y)(x + 7y)",
correctLetter: "A",
correctOption: 1,
},

{
id: "question16",
question: "16. The curved surface area of a cylinder, 5 cm high, is 110 cm². Find the radius of its base. [Take π = 22/7]",
A: "2.6 cm",
B: "3.5 cm",
C: "3.6 cm",
D: "7.0 cm",
answer: "B. 3",
correctLetter: "B",
correctOption: 2,
},

{
id: "question17",
question: "17. The volume of a pyramid with height 15 cm is 90 cm². If its base is a rectangle with dimensions x cm by 6 cm, find the value of x .",
A: "3",
B: "5",
C: "6",
D: "8",
answer: "A. 3",
correctLetter: "A",
correctOption: 1,
},

{
id: "question18",
instruction: "In the diagram YW is a tangent to the circle at X, |UV| = |VX| and ∠VXW = 50°. ",
question: "18. Find the value ∠UXY.",
A: "70°",
B: "80°",
C: "105°",
D: "110°",
answer: "B. 80°",
correctLetter: "B",
correctOption: 2,
questionFigure: require(path + "2016-A-Q-18.png"),
imageRatio: 1,
},

{
id: "question19",
instruction: "In the diagram, PF, QT, RG intersect at S and PQ//RG. If ∠SPQ = 113° and ∠RST = 22°, find ∠PSQ.",
question: "19. Calculate the value of angle PTR.",
A: "22°",
B: "45°",
C: "67°",
D: "89°",
answer: "B. 45°",
correctLetter: "B",
correctOption: 2,
questionFigure: require(path + "2016-A-Q-19.png"),
imageRatio: 1,
},

{
id: "question20",
question: "20. In the diagram, O is the centre of the circle, ∠XOZ = (10m)° and ∠XWZ = m°. Calculate the value of m.",
A: "30",
B: "36",
C: "40",
D: "72",
answer: "A. 30",
correctLetter: "A",
correctOption: 1,
},

{
id: "question21",
question: "21. Kweku walked 8 m up a slope and was 3 m above the ground. If he walks 12 m further up the slope, how far above the ground will he be?",
A: "4.5 m",
B: "6.0 m",
C: "7.5 m",
D: "9.0 m",
answer: "C. 7",
correctLetter: "C",
correctOption: 3,
},

{
id: "question22",
instruction: "In the diagram, TS is a tangent to the circle at S. |PR|=|RS| and ∠PQR=ll7°.",
question: "22. Calculate ∠PST.",
A: "54°",
B: "44°",
C: "34°",
D: "27°",
answer: "A. 54°",
correctLetter: "A",
correctOption: 1,
questionFigure: require(path + "2016-A-Q-22.png"),
imageRatio: 1,
},

{
id: "question23",
instruction: "In the diagram PR\\SV\\WY, TX\\QY, ∠PQT = 48° and ∠TXW = 60°. ",
question: "23. Find ∠TQU.",
A: "120°",
B: "108°",
C: "72°",
D: "60°",
answer: "C. 72°",
correctLetter: "C",
correctOption: 3,
questionFigure: require(path + "2016-A-Q-23.png"),
imageRatio: 1,
},

{
id: "question24",
question: "24. Calculate the gradient of the line PQ.",
A: "3/5",
B: "2/3",
C: "3/2",
D: "5/3",
answer: "Z. ",
correctLetter: "Z",
correctOption: 9,
}, 

{
id: "question25",
question: "25. Calculate the length PQ.",
A: "4√11",
B: "4√10",
C: "2√17",
D: "2√13",
answer: "Z. ",
correctLetter: "Z",
correctOption: 9,
}, 

{
id: "question26",
instruction: "A straight line passes through the points P(l , 2) and Q(5, 8). Use this information to answer questions 24 and 25.",
question: "26. In the diagram, TX is perpendicular to UW, |UX| = 1 cm and |TX| = |WX| = ✓3 cm. Find ∠UTW.",
A: "135°",
B: "105°",
C: "75°",
D: "60°",
answer: "C. 75°",
correctLetter: "C",
correctOption: 3,
questionFigure: require(path + "2016-A-Q-26.png"),
imageRatio: 1,
},

{
id: "question27",
question: "27. If cos ⍬ = x and sin 60° = x + 0.5, 0° ≤ ⍬ ≤ 90°, find, correct to the nearest degree, the value of ⍬.",
A: "66°",
B: "67°",
C: "68°",
D: "69°",
answer: "D. 69°",
correctLetter: "D",
correctOption: 4,
},

{
    id: "question28",
    instruction: "The table shows the ages of students in a club. Use it to answer questions 28",
question: "28. How many students are in the club?",
A: "50",
B: "55",
C: "60",
D: "65",
answer: "A. 50",
correctLetter: "A",
correctOption: 1,
questionFigure: require(path + "2016-A-Q-28.png"),
imageRatio: 0.25,
},

{
id: "question29",
question: "29. Find the median age.",
A: "13",
B: "14",
C: "15",
D: "16",
answer: "B. 14",
correctLetter: "B",
correctOption: 2,
},

{
id: "question30",
instruction: "The figure is a pie chart which represents the expenditure of a family in a year. If the total income of the family was Le 10,800,000.00, ",
question: "30. how much was spent on food?",
A: "Le 2,250,000.00",
B: "Le 2,700,000.00",
C: "Le 3,600,000.00",
D: "Le 4,500,000.00",
answer: "C. Le 3,600,000",
correctLetter: "C",
correctOption: 3,
questionFigure: require(path + "2016-A-Q-30.png"),
imageRatio: 1,
},

{
id: "question31",
question: "31. A fair die is thrown two times. What is the probability that the sum of the scores is at least 1O?",
A: "5/36",
B: "1¹/₆",
C: "5⁵/₁₈",
D: "2/3",
answer: "B. 1 1/6",
correctLetter: "B",
correctOption: 2,
},

{
id: "question32",
question: "32. The marks of eight students in a test are: 10, 4, 5, 3, 14 , 13, 16 and 7. Find the range .",
A: "16",
B: "14",
C: "13",
D: "11",
answer: "C. 13",
correctLetter: "C",
correctOption: 3,
},

{
id: "question33",
question: "33. If log₂(3x - 1) = 5, find x.",
A: "2.00",
B: "3.67",
C: "8.67",
D: "11.00",
answer: "D. 11",
correctLetter: "D",
correctOption: 4,
},

{
id: "question34",
question: "34. A sphere of radius r cm has the same volume as a cylinder of radius 3 cm and height 4 cm . Find the value of r.",
A: "2/3",
B: "2",
C: "3",
D: "6",
answer: "C. 3",
correctLetter: "C",
correctOption: 3,
},


{
id: "question35",
question: "35. Express 1975 correct to 2 significant figures.",
A: "20",
B: "1900",
C: "1980",
D: "2000",
answer: "D. 2000",
correctLetter: "D",
correctOption: 4,
},

{
id: "question36",
instruction: "In the diagram MOPQ is a trapezium -with QP//MO, MQ//NP, NQ//OP, /QP/ = 9 cm and the height of triangle QNP = 6 cm.",
question: "36. Calculate the area of the trapezium.",
A: " 96 cm²",
B: " 90 cm²",
C: " 81 cm²",
D: " 27 cm²",
answer: " ",
correctLetter: " ",
correctOption: 0,
questionFigure: require(path + "2016-A-Q-36.png"),
imageRatio: 1,
},

{
id: "question37",
instruction: "37. The perimeter of a sector of a circle of radius 21 cm is 64 cm. Find the angle of the sector. [Take π = 22/7]", 
A: "70°",
B: "60°",
C: "55°",
D: "42°",
answer: "Z. ",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question38",
instruction: "38. Determine M ∩ N from the Venn diagram.",
question: " ",
A: "{f, g}",
B: "{e}",
C: "{c, f, g}",
D: "{e, f, g}",
answer: "A. {f, g}",
correctLetter: "A",
correctOption: 1,
questionFigure: require(path + "2016-A-Q-38.png"),
imageRatio: 1,
},

{
id: "question39",
question: "39. If 20(mod 9) is equivalent to y(mod 6), find y.",
A: "1",
B: "2",
C: "3",
D: "4",
answer: "B. 2",
correctLetter: "B",
correctOption: 2,
},

{
id: "question40",
question: "40. Simplify: ((p - r)² - r²) / (2p² - 4pr)",
A: "1/2",
B: "p - 2r",
C: "1/(p-2r)",
D: "2p/(p-2r)",
answer: "A. ½",
correctLetter: "A",
correctOption: 1,
},

{
id: "question41",
instruction: "In diagram, O is the centre of the circle, ∠QPS = 100°, ∠PSQ = 60° and ∠QSR = 80°.",
question: "41. Calculate ∠SQR.",
A: " ",
B: " ",
C: " ",
D: " ",
answer: " ",
correctLetter: " ",
correctOption: 0,
questionFigure: require(path + "2016-A-Q-41.png"),
imageRatio: 1,
},

{
id: "question43",
question: "43. The relation y = x² + 2x + k passes through the point (2, 0). Find the value of k.",
A: "-8",
B: "-4",
C: "4",
D: "8",
answer: "A. -8",
correctLetter: "A",
correctOption: 1,
},

{
id: "question44",
question: "44. Find the next three terms of the sequence: 0, 1, 1, 2, 3, 5, 8, ...",
A: "13, 19, 23",
B: "9, 11, 13",
C: "11, 15, 19",
D: "13, 21, 34",
answer: "D. 13, 21, 34",
correctLetter: "D",
correctOption: 4,
},

{
id: "question45",
instruction: "45. Find the lower quartile of the distribution illustrated by the cumulative frequency curve.",
question: " ",
A: "17.5",
B: "19.0",
C: "27.5",
D: "28.0",
answer: "B. 19",
correctLetter: "B",
correctOption: 2,
questionFigure: require(path + "2016-A-Q-45.png"),
imageRatio: 1,
},

{
id: "question46",
question: "46. The ratio of the exterior angle to the interior angel of a regular polygon is 1:11. How many sides has the polygon?",
A: "30",
B: "24",
C: "18",
D: "12",
answer: "B. 24",
correctLetter: "B",
correctOption: 2,
},

{
id: "question47",
question: "47. Halima is n years old. Her brother's age is 5 years more than half of her age. How old is her brother?",
A: "n/2 + 5/2",
B: "n/2 − 5",
C: "5 - n/2",
D: "n/2 + 5",
answer: "D. n/2 + 5",
correctLetter: "D",
correctOption: 4,
},

{
id: "question48",
instruction: "In the diagram MN is a chord of a circle KMN centre O and radius 10 cm. If ∠MON = 140°, ",
question: "48. find, correct to the nearest cm, the length of the chord MN.",
A: "19 cm",
B: "18 cm",
C: "17 cm",
D: "12 cm",
answer: "A. 19 cm",
correctLetter: "A",
correctOption: 1,
questionFigure: require(path + "2016-A-Q-48.png"),
imageRatio: 1,
},

{
id: "question49",
question: "49. An object is 6 m away from the base of a mast. If the angle of depression of the object from the top of the mast is 50°, find, correct to 2 decimal places, the height of the mast.",
A: "8.60 m",
B: "7.83 m",
C: "7.51 m",
D: "7.15 m",
answer: "D. 7",
correctLetter: "D",
correctOption: 4,
},

{
id: "question50",
instruction: "50. From the diagram, which of the following is true?",
question: " ",
A: "m + n + p = 180°",
B: "m + n = 180°",
C: "m= p + n",
D: "n = m + p",
answer: "D. n = m + p",
correctLetter: "D",
correctOption: 4,
questionFigure: require(path + "2016-A-Q-50.png"),
imageRatio: 1,
},

]