import { SquareRoot, superscript, subscript, BoldText, ItalicText, Fraction, ShortFraction, LongFraction, MixedFraction, Isotopes } from "@/mathnotation"

const path = "@/assets/images/pastquestions-figures/coremathematics/coremathematicsA/coremathematics-"

export const COREMATHEMATICSA2021 = [

{
id: "question1",
question: "1. correct 0.007985 to three significant figures.",
A: "0.0109",
B: "0.0800",
C: "0.00799",
D: "0.008",
answer: "C. 0",
correctLetter: "C",
correctOption: 3,
},

{
id: "question2",
question: "2. Simplify: (11₂)²",
A: "1001₂",
B: "1101₂",
C: "101₂",
D: "10001₂",
answer: "A. 1001₂",
correctLetter: "A",
correctOption: 1,
},

{
id: "question3",
question: "3. Solve: 2^(√2x+1) = 32",
A: "13",
B: "24",
C: "12",
D: "11",
answer: "C. 12",
correctLetter: "C",
correctOption: 3,
},

{
id: "question4",
question: "4. If log₁₀2 = m and log₁₀3 = n, find log₁₀24 in terms of m and n.",
A: "3m + n",
B: "m + 3n",
C: "4mn",
D: "3mn",
answer: "A. 3m + n",
correctLetter: "A",
correctOption: 1,
},

{
id: "question5",
question: "5. Find the 5th term of the sequence 2, 5, 10, 17 ?",
A: "22",
B: "24",
C: "36",
D: "26",
answer: "D. 26",
correctLetter: "D",
correctOption: 4,
},

{
id: "question6",
question: "6. If p = {-3 < x < 1} and Q = {-1 < x < 3}, where x is a real number, find P n Q.",
A: "0",
B: "-3, -2, -1, 0 and 1",
C: "-2, -1 and 0",
D: "-1, 0 and 1",
answer: "A. 0",
correctLetter: "A",
correctOption: 1,
},

{
id: "question7",
question: "7. Factorize 6pq - 3rs - 3ps + 6qr",
A: "3(r - p)(2q + s)",
B: "3(p + r)( 2q - 2q - s)",
C: "3(2q - s)(p + r)",
D: "3(r - p)(s - 2q)",
answer: "B. 3(p + r)(2q - s)",
correctLetter: "B",
correctOption: 2,
},

{
id: "question8",
question: "8. What number should be subtrcted from the sum of 2¹/₆ and 2⁷/₁₂ to give 3¹/₄ ?",
A: "¹/₃",
B: "1¹/₂",
C: "1¹/₆",
D: "¹/₂",
answer: "B. 112",
correctLetter: "B",
correctOption: 2,
},

{
id: "question9",
question: "9. Mensah is 5 years old and joyce is thrice as old as mensah. In how many years will joyce be twice as old as Mensah?",
A: "3 years",
B: "10 years",
C: "5 years",
D: "15 years",
answer: "C. 5 years",
correctLetter: "C",
correctOption: 3,
},

{
id: "question10",
question: "10. If 16 × 2ˣ⁺¹ = 4ˣ * 8¹⁻ˣ, find the value of x.",
A: "-4",
B: "4",
C: "1",
D: "-1",
answer: "D. -1",
correctLetter: "D",
correctOption: 4,
},

{
id: "question11",
question: "11. The circumference of a circular track is 9km. A cyclist rides round it a number of times and stops after covering a distance of 302km. How far is the cyclist from the starting point?",
A: "5km",
B: "6km",
C: "7km",
D: "3km",
answer: "A. 5km",
correctLetter: "A",
correctOption: 1,
},

{
id: "question12",
question: "12. Simplify 2√7 - 14/√7 + 7/21",
A: "√21 / 21",
B: "7 (√21 / 21)",
C: "√21 / 7",
D: "3√21",
answer: "C. √213",
correctLetter: "C",
correctOption: 3,
},

{
id: "question13",
question: "13. If 4x + 2y = 16 and 6x - 2y = 4 , find the value of (y - x).",
A: "8",
B: "2",
C: "4",
D: "6",
answer: "B. 2",
correctLetter: "B",
correctOption: 2,
},

{
id: "question14",
instruction: "In the diagram, ∠ABC and ∠BCD are right angles, ∠BAD = t and ∠EDF = 70°.",
question: "14. Find the value of t.",
A: "70°",
B: "165°",
C: "140°",
D: "110°",
answer: "D. 110°",
correctLetter: "D",
correctOption: 4,
questionFigure: require(path + "2021-A-Q-14.png"),
imageRatio: 1,
},

{
id: "question15",
question: "15. The sum of the interior angles of a regular polygon with k sides is (3k-10) right angles. Find the size of the exterior angle?",
A: "60°",
B: "40°",
C: "90°",
D: "120°",
answer: "A. 60°",
correctLetter: "A",
correctOption: 1,
},

{
id: "question16",
question: "16. Make u the subject in x = (2u - 3) / (3u + 2)",
A: "u = (2x + 3) / (3x - 2)",
B: "u = (2x - 3) / (3x - 2)",
C: "u = (2x + 3) / (2 - 3x)",
D: "u = (2x + 3) / (3x + 2)",
answer: "C. U = (2𝑥 + 3)(2 - 3𝑥)",
correctLetter: "C",
correctOption: 3,
},

{
id: "question17",
question: "17. A trader paid import duty of 38 kobo in the naira on the cost of an engine. If a total of #22,800.00 was paid as import duty, calculate the cost of the engine.",
A: "#60,000.00",
B: "#120,000.00",
C: "#24,000.00",
D: "#18,000.00",
answer: "A. #60,000",
correctLetter: "A",
correctOption: 1,
},

{
id: "question18",
question: "18. The height of an equilateral triangle of side is 10√3 cm. calculate its perimeter.",
A: "20cm",
B: "60cm",
C: "40cm",
D: "30cm",
answer: "B. 60cm",
correctLetter: "B",
correctOption: 2,
},

{
id: "question19",
question: "19. In △LMN, |LM| = 6cm, ∠LNM = x and sin x = sin x = 3/5. Find the area of △LMN",
A: "60cm²",
B: "48cm²",
C: "24cm²",
D: "30cm²",
answer: "B. 48cm²",
correctLetter: "B",
correctOption: 2,
},

{
id: "question20",
instruction:"Consider the statements: \nP = All students offering Literature(L) also offer History(H); \nQ = Students offering History(H) do not offer Geography(G). ",
question: "20. Which of the Venn diagram correctly illustrate the two statements?",
A: "A",
B: "B",
C: "C",
D: "D",
answer: "C. ****",
correctLetter: "C",
correctOption: 3,
questionFigure: require(path + "2021-A-Q-20.png"),
imageRatio: 1,
},

{
id: "question21",
question: "21. Find The quadratic equation whose roots are -2q and 5q.",
A: "3x² + 3qx - 10q²",
B: "x² + 3qx + 10q²",
C: "x² - 3qx + 10q²",
D: "x² - 3qx - 10q²",
answer: "D. x² - 3qx - 10q² =0",
correctLetter: "D",
correctOption: 4,
},

{
id: "question22",
question: "22. If tanθ = 3/4, 180° < θ < 270°, find the value of cosθ.",
A: "4/5",
B: "3/5",
C: "-4/5",
D: "-3/5",
answer: "C. -45",
correctLetter: "C",
correctOption: 3,
},

{
id: "question23",
question: "23. If 2/(x - 3) + 3/(x - 2) = p / ((x - 3)(x - 2)), find p",
A: "5 - x",
B: "- (x + 5)",
C: "13 - x",
D: "- (5x - 13)",
answer: "A. (5 – x)",
correctLetter: "A",
correctOption: 1,
},

{
id: "question24",
question: "24. The diagonal of a rhombus are 12cm and 5cm. calculate its perimeter",
A: "26cm",
B: "24cm",
C: "17cm",
D: "34cm",
answer: "A. 26cm",
correctLetter: "A",
correctOption: 1,
},

{
id: "question25",
instruction: "In the diagram, △XYZ is produced to T. if |XY| = |ZY| and ∠XYT = 40°",
question: "25. find ∠XZT",
A: "110°",
B: "130°",
C: "140°",
D: "180°",
answer: "A. 110°",
correctLetter: "A",
correctOption: 1,
},

{
id: "question26",
instruction: "A solid brass cube is melted and recast as a solid cone of height h and base radius r. If the height of the cube is h, ",
question: "26. find r in terms of h.",
A: "r = h",
B: "r = √(3h/π)",
C: "r = πh",
D: "r = h√3/π",
answer: "C. r = ℎ√3𝜋",
correctLetter: "C",
correctOption: 3,
},

{
id: "question27",
question: "27. Which of the following is not an exterior angle of a regular polygon?",
A: "66°",
B: "72°",
C: "24°",
D: "15°",
answer: "A. 66°",
correctLetter: "A",
correctOption: 1,
},

{
id: "question28",
question: "28. From a point T, a man moves 12km due west and then moves 12km due south to another point Q. Calculate the bearing of T from Q.",
A: "225°",
B: "315°",
C: "045°",
D: "135°",
answer: "C. 045°",
correctLetter: "C",
correctOption: 3,
},

{
id: "question29",
question: "29. In the diagram O is the centre of the circle PQRS, ∠PQR = 72° and OR is parallel to PS. Find .",
A: "18°",
B: "108°",
C: "54°",
D: "36°",
answer: "D. 36°",
correctLetter: "D",
correctOption: 4,
},

{
id: "question30",
question: "30. A trapezium of parallel sides 10cm and 21cm and height 8cm is inscribed in a circle of radius 7cm. calculate the area of the region not covered by the trapezium. π =22/7",
A: "84cm²",
B: "80cm²",
C: "30cm²",
D: "94cm²",
answer: "B. 30cm²",
correctLetter: "B",
correctOption: 2,
},

{
id: "question31",
question: "31. Find, correct to two decimal, the mean of",
A: "3.71",
B: "3.70",
C: "3.69",
D: "3.72",
answer: "A. 3",
correctLetter: "A",
correctOption: 1,
},

{
id: "question32",
question: "32. A cyclist moved at a speed of Xkm/h for 2 hours. He then increased his speed by 2 km/h for the next 3 hours. If the total distance covered is 36 km, calculate his initials speed.",
A: "12km/h",
B: "3km/h",
C: "4km/h",
D: "6km/h",
answer: "D. 6km/h",
correctLetter: "D",
correctOption: 4,
},

{
id: "question33",
instruction: "Use the figure below to answer a´question 33",
question: "33. find the value of (x + y)",
A: "215°",
B: "70°",
C: "135°",
D: "145°",
answer: "A. 215°",
correctLetter: "A",
correctOption: 1,
questionFigure: require(path + "2021-A-Q-33.png"),
imageRatio: 1,
},

{
id: "question34",
instruction: "In the diagram, MP is a tangent to the circle NQR, ∠NQR, ∠PNQ = 64 and | RQ| = | RN|.",
question: "34.  Find the angle marked t.",
A: "130°",
B: "115°",
C: "58°",
D: "68°",
answer: "C. 58°",
correctLetter: "C",
correctOption: 3,
questionFigure: require(path + "2021-A-Q-34.png"),
imageRatio: 1,
},

{
id: "question35",
question: "35. Find the first quartile of 7, 8, 7, 9, 11, 8, 7, 9, 6 and 8.",
A: "8.5",
B: "7.0",
C: "7.5",
D: "8.0",
answer: "B. 7",
correctLetter: "B",
correctOption: 2,
},

{
id: "question36",
instruction:"In the diagram, PQRS is a circle. ",
question: "36. find the value of x.",
A: "50°",
B: "30°",
C: "80°",
D: "100°",
answer: "A. 50°",
correctLetter: "A",
correctOption: 1,
questionFigure: require(path + "2021-A-Q-36.png"),
imageRatio: 1,
},

{
id: "question37",
question: "37. A cone has a base radius of 8cm and height 11cm. calculate , correct to 2d.p, the curved surface area",
A: "341.98cm²",
B: "276.57cm²",
C: "201.14cm²",
D: "477.71cm²",
answer: "A. 341",
correctLetter: "A",
correctOption: 1,
},

{
id: "question38",
question: "38. Given that sin x = 3/5, 0 ≤ x ≤ 90, evaluate (tanx + 2cosx)",
A: "2¹¹/₂₀",
B: "¹¹/₂₀",
C: "2⁷/₂₀",
D: "¹/₂₀",
answer: "B. 2720",
correctLetter: "B",
correctOption: 2,
},

{
id: "question39",
question: "39. In the diagram, line EC is a diameter of the circle ABCDE. If angle ABC equals 158°, find ∠ADE",
A: "112",
B: "90",
C: "68",
D: "22",
answer: "C. 68O",
correctLetter: "C",
correctOption: 3,
},

{
id: "question40",
instruction: "The table shows the height of 37 players of a basketball team calculates",
question: "40. correct to one decimal place the mean height of the players.",
A: "163.0",
B: "162.0",
C: "160.0",
D: "165.0",
answer: "A. 163",
correctLetter: "A",
correctOption: 1,
questionFigure: require(path + "2021-A-Q-40.png"),
imageRatio: 0.21,
},

{
id: "question41",
question: "41. XY is a line segments with the coordinates X (-8,- 12) and Y(p, q). if the midpoint of XY is (-4, -2) find the coordinates of Y.",
A: "(-6, -2)",
B: "(0, 8)",
C: "(4, 10)",
D: "(0, 4)",
answer: "B. (0, 8)",
correctLetter: "B",
correctOption: 2,
},

{
id: "question42",
question: "42. 500 tickets were sold for a concert tickets for adults and children were sold at $4.50 and $3.00 respectively if the total receipts for the concerts was $1987.50 how many tickets for adults were sold?",
A: "325",
B: "235",
C: "175",
D: "400",
answer: "A. 325",
correctLetter: "A",
correctOption: 1,
},

{
id: "question43",
question: "43. The distance d between two villages east more than 18 KM but not more than 23KM. which of these inequalities represents the statements?",
A: "18 ≤ d ≤ 23",
B: "18 < d < 23",
C: "18 ≤ d < 23",
D: "18 < d ≤ 23",
answer: "D. 18 < d ≤ 23",
correctLetter: "D",
correctOption: 4,
},

{
id: "question44",
instruction: "The pie chart represents the distribution of fruits on display in the shop",
question: "44. if there are 60 apples on display how many oranges are there?",
A: "80",
B: "270",
C: "120",
D: "90",
answer: "D. 90",
correctLetter: "D",
correctOption: 4,
questionFigure: require(path + "2021-A-Q-44.png"),
imageRatio: 1,
},

{
id: "question45",
question: "45. A box contains 40 identical balls of which 10 are red and 12 are blue. if a ball is selected at random from the box what is the probability that it is neither red nor blue?",
A: "9/20",
B: "3/10",
C: "1/4",
D: "11/20",
answer: "A. 920",
correctLetter: "A",
correctOption: 1,
},

{
id: "question46",
question: "46. A fair die is tossed twice what is the probability of get a sum of at least 10.",
A: "5/36",
B: "2/3",
C: "5/18",
D: "1/6",
answer: "D. 16",
correctLetter: "D",
correctOption: 4,
},

{
id: "question47",
question: "47. A man will be (x+10)years old in 8years time. If 2 years ago he was 63 years., find the value of x",
A: "55",
B: "63",
C: "57",
D: "67",
answer: "B. 63",
correctLetter: "B",
correctOption: 2,
},

{
id: "question48",
question: "48. The equation of a line is given as 3 x - 5y = 7. Find its gradient (slope)",
A: "5/3",
B: "3/5",
C: "−3/5",
D: "− 5/3",
answer: "B. 35",
correctLetter: "B",
correctOption: 2,
},

{
id: "question49",
question: "49. For what value of x is (4 − 2x)/(x + 1) undefined.",
A: "2",
B: "-1",
C: "1",
D: "-2",
answer: "B. -1",
correctLetter: "B",
correctOption: 2,
},


]