export const GEOGRAPHYA2006 = [

{
id: "question1",
question:  "1. 1 cm on the map represents",
A: "0.5km",
B: "1.0km",
C: "2.0km",
D: "7.0km",
answer: "B. 1.0km",
correctLetter: "B",
correctOption: 2,
},

{
id: "question2",
question:  "2. The symbol △1058 west of Gbabo is a",
A: "survey pillar",
B: "benchmark",
C: "spot height",
D: "trigonometrical station",
answer: "C. spot height",
correctLetter: "C",
correctOption: 3,
},

{
id: "question3",
question:  "3. River Selifu flows towards the",
A: "East",
B: "West",
C: "South-west",
D: "North-west",
answer: "B. West",
correctLetter: "B",
correctOption: 2,
},

{
id: "question4",
question:  "4. Which of the following pairs of letters are represented by letters P and Q?",
A: "Spur and escarpment",
B: "Escarpment and conical hill",
C: "Uniform slope and knoll",
D: "Spur and knoll",
answer: "A. Spur and escarpment",
correctLetter: "A",
correctOption: 1,
},

{
id: "question5",
question:  "5. Which of the following does not influence the location of settlement in the mapped area?",
A: "Drainage",
B: "Relief",
C: "Communication lines",
D: "Mining activities.",
answer: "C. Communication lines",
correctLetter: "C",
correctOption: 3,
},

{
id: "question6",
question:  "6. The feature represented by M on the map is a",
A: "Plateau",
B: "Col",
C: "Watershed",
D: "Spur",
answer: "B. Col",
correctLetter: "B",
correctOption: 2,
},

{
id: "question7",
question:  "7. Which of the following towns is not visible from Agbobu?",
A: "Aga",
B: "Ojembe",
C: "Ngeibutu",
D: "Teju",
answer: "B. Ojembe",
correctLetter: "B",
correctOption: 2,
},

{
id: "question8",
question:  "8. The contour interval on the map is",
A: "50m",
B: "100m",
C: "150m",
D: "200m",
answer: "B. 100m",
correctLetter: "B",
correctOption: 2,
},

{
id: "question9",
question:  "9. Which of the following pairs of activities are most likely to be practiced in the mapped area?",
A: "Mining and pastoral farming",
B: "Quarrying and forestry",
C: "Pastoral farming and quarrying",
D: "Pastoral farming and forestry",
answer: "B. Quarrying and forestry",
correctLetter: "B",
correctOption: 2,
},

{
id: "question10",
question:  "10. The distance along the first-class road from the junction at Teju to the junction at Aghobuis approximately",
A: "8.3km",
B: "7.0km",
C: "6.5km",
D: "4.4km",
answer: "B. 7.0km",
correctLetter: "B",
correctOption: 2,
},

{
id: "question11",
question:  "11. Which of the following planets is closest to the sun?",
A: "Jupiter",
B: "Venus",
C: "Mercury",
D: "Mars",
answer: "C. Mercury",
correctLetter: "C",
correctOption: 3,
},

{
id: "question12",
question:  "12. The plane surface on which the planets revolve are the planes of the",
A: "Solstice",
B: "Equinox",
C: "Elliptic",
D: "Aphelion",
answer: "C. Elliptic",
correctLetter: "C",
correctOption: 3,
},

{
id: "question13",
question:  "13. Lines of longitude are",
A: "Drawn from west to east",
B: "Used in determining local time.",
C: "Called parallel lines.",
D: "Used in calculating distances.",
answer: "B. Used in determining local time.",
correctLetter: "B",
correctOption: 2,
},

{
id: "question14",
question:  "14. An aircraft takes off from town A (longitude 20oE) at 12:00 hours on a direct flight to town B(longitude 20oW).What will be the local time in town B at take off?",
A: "8:30am",
B: "9:20am",
C: "8:20pm",
D: "9:30pm",
answer: "B. 9:20am",
correctLetter: "B",
correctOption: 2,
},

{
id: "question15",
question:  "15. The approximate distance between town X, latitude 10oN and town Y located on latitude 13oN is",
A: "554.2km",
B: "333.3km",
C: "233.4km",
D: "113.2km",
answer: "B. 333.3km",
correctLetter: "B",
correctOption: 2,
},

{
id: "question16",
question:  "16. A line joining places of equal atmospheric pressure is called an",
A: "Isopach",
B: "Isobar",
C: "Isotherm",
D: "Isohyets",
answer: "B. Isobar",
correctLetter: "B",
correctOption: 2,
},

{
id: "question17",
question:  "17. The instrument consists of a small metal box which contains very little air. The top of this box bends slightly under the influence of any change in atmospheric pressure. The above best describes",
A: "A mercury barometer",
B: "An aneroid barometer",
C: "A hygrometer",
D: "An altimeter",
answer: "B. An aneroid barometer",
correctLetter: "B",
correctOption: 2,
},

{
id: "question18",
question:  "18. The innermost layer of the earth is the",
A: "Mantle",
B: "Hydrosphere",
C: "Core",
D: "Lithosphere",
answer: "C. Core",
correctLetter: "C",
correctOption: 3,
},

{
id: "question19",
question:  "19. Which of the following is a process of river erosion?",
A: "Solution",
B: "Siltation",
C: "Corrosion",
D: "Gravitation",
answer: "C. Corrosion",
correctLetter: "C",
correctOption: 3,
},

{
id: "question20",
question:  "20. All the following are characteristics of the upper course of a river except",
A: "Waterfall",
B: "High velocity",
C: "Lateral erosion",
D: "Presence of interlocking spurs",
answer: "C. Lateral erosion",
correctLetter: "C",
correctOption: 3,
},

{
id: "question21",
question:  "21. The shallow water zone adjoining the coast is the",
A: "Abyssal plain",
B: "Continental slope",
C: "Oceanic plateau",
D: "Continental shelf",
answer: "D. Continental shelf",
correctLetter: "D",
correctOption: 4,
},

{
id: "question22",
question:  "22. Which of the following is a product of wave erosion?",
A: "Fjord",
B: "Spit",
C: "Cliff",
D: "Ria",
answer: "C. Cliff",
correctLetter: "C",
correctOption: 3,
},

{
id: "question23",
question:  "23. The area marked X is a",
A: "Misfit",
B: "Pirated stream",
C: "Wind gap",
D: "Beheaded stream",
answer: "C. Wind gap",
correctLetter: "C",
correctOption: 3,
},

{
id: "question24",
question:  "24. River Koko is a",
A: "Pirating stream",
B: "Wind gap",
C: "Misfit",
D: "Beheaded stream",
answer: "A. Pirating stream",
correctLetter: "A",
correctOption: 1,
},

{
id: "question25",
question:  "25. River Ole is",
A: "A beheaded stream",
B: "The elbow of capture",
C: "A pirating stream",
D: "A wind gap",
answer: "A. A beheaded stream",
correctLetter: "A",
correctOption: 1,
},

{
id: "question26",
question:  "26. The disintegration of rocks by physical, biological and chemical process in situ is known as",
A: "Weathering",
B: "Erosion",
C: "Deposition",
D: "Transportation",
answer: "A. Weathering",
correctLetter: "A",
correctOption: 1,
},

{
id: "question27",
question:  "27. Recumbent fold results from",
A: "Tensional forces.",
B: "Persistent compressional forces,",
C: "Volcanic eruption.",
D: "Faulting.",
answer: "B. Persistent compressional forces",
correctLetter: "B",
correctOption: 2,
},

{
id: "question28",
question:  "28. Which of the following is not true of igneous rocks? They are",
A: "Stratified.",
B: "Crystalline.",
C: "Non-fossilized,",
D: "Impervious",
answer: "A. Stratified.",
correctLetter: "A",
correctOption: 1,
},

{
id: "question29",
question:  "29. Which of the following is an extrusive volcanic landform?",
A: "Dyke",
B: "Crater",
C: "Lapolith",
D: "Phacolith",
answer: "B. Crater",
correctLetter: "B",
correctOption: 2,
},

{
id: "question30",
question:  "30. The slender-looking pendant (hanging) structure from the roof of a cavern is called",
A: "Doline",
B: "Stalactite.",
C: "Uvula.",
D: "Stalagmite.",
answer: "B. Stalactite.",
correctLetter: "B",
correctOption: 2,
},

{
id: "question31",
question:  "31. Geysers are usually associated with",
A: "Volcanic activity,",
B: "Earthquake.",
C: "Faulting.",
D: "Folding.",
answer: "B. Earthquake.",
correctLetter: "B",
correctOption: 2,
},

{
id: "question32",
question:  "32. A feature of the desert made of tabular masses with layers of soft rock underlying more resistant rocks characterised by ridges and furrows refers to",
A: "Zeugens.",
B: "Ventifacts.",
C: "Barchans.",
D: "Rock pedestals.",
answer: "A. Zeugens.",
correctLetter: "A",
correctOption: 1,
},

{
id: "question33",
question:  "33. Which of the following is not an important factor in soil formation?",
A: "Debris",
B: "Parent material",
C: "Time",
D: "Micro-organism",
answer: "A. Debris",
correctLetter: "A",
correctOption: 1,
},

{
id: "question34",
question:  "34. Desert temperatures are high during the day because of the",
A: "Absence of cloud cover.",
B: "Presence of cloud cover.",
C: "Presence of ocean currents.",
D: "Distance of deserts from the sea.",
answer: "A. Absence of cloud cover.",
correctLetter: "A",
correctOption: 1,
},

{
id: "question35",
question:  "35. Environmental pollution includes all the following except",
A: "Soil pollution.",
B: "Noise pollution.",
C: "Desert encroachment.",
D: "Emission of dangerous gases.",
answer: "C. Desert encroachment.",
correctLetter: "C",
correctOption: 3,
},

{
id: "question36",
question:  "36. The term ecosystem means the",
A: "Close relationship and interaction between the elements within an environment.",
B: "Ecological background of natural systems.",
C: "Inter dependence within land economy.",
D: "Ecological systems of environmental stability.",
answer: "A. Close relationship and interaction between the elements within an environment.",
correctLetter: "A",
correctOption: 1,
},

{
id: "question37",
question:  "37. A plant community dominated by numerous species growing together is called",
A: "Association.",
B: "Consociation.",
C: "Micro-flora.",
D: "Primary succession.",
answer: "A. Association.",
correctLetter: "A",
correctOption: 1,
},

{
id: "question38",
question:  "38. The vegetation type characterized by evergreen broad-leaved trees arranged in layers is the",
A: "Tropical savanna.",
B: "Mediterranean.",
C: "Equatorial forest.",
D: "Veldt.",
answer: "C. Equatorial forest.",
correctLetter: "C",
correctOption: 3,
},

{
id: "question39",
question:  "39. Air transport is not a common mode of transportation in Africa because",
A: "Few countries in Africa own airports.",
B: "Africans are afraid of travelling by air.",
C: "It is expensive to travel by air.",
D: "Airport tax rate is very high in Africa.",
answer: "A. Few countries in Africa own airports.",
correctLetter: "A",
correctOption: 1,
},

{
id: "question40",
question:  "40. Which of the following can least alter the balance in anecosystem?",
A: "Urban population explosion.",
B: "Rapid deforestation.",
C: "The rapid expansion of cities.",
D: "The practice of subsistence farming.",
answer: "C. The rapid expansion of cities.",
correctLetter: "C",
correctOption: 3,
},

{
id: "question41",
question:  "41. An African country which produces and exports fruits in large quantities in winter is",
A: "Gabon.",
B: "The Guinea.",
C: "South Africa.",
D: "Nigeria.",
answer: "C. South Africa.",
correctLetter: "C",
correctOption: 3,
},

{
id: "question42",
question:  "42. Which of the following is not a requirement for the development of hydro-electricity?",
A: "Sufficient volume of water",
B: "Heavy capital outlay",
C: "Large thermal plants",
D: "Steep rive gradient",
answer: "C. Large thermal plants",
correctLetter: "C",
correctOption: 3,
},

{
id: "question43",
question:  "43. Lumbering is very important occupation in the",
A: "Savanna regions of West Africa.",
B: "Equatorial forest of West Africa.",
C: "Monsoon forest of South East Asia.",
D: "Desert region of North Africa.",
answer: "C. Monsoon forest of South East Asia.",
correctLetter: "C",
correctOption: 3,
},

{
id: "question44",
question:  "44. There is low traffic on African rivers because",
A: "Africans are usually afraid of travelling on rivers.",
B: "Most African rivers flow over steep plateau edges.",
C: "There are not bulky goods in Africa.",
D: "Africa timber is not ideal for shipbuilding.",
answer: "B. Most African rivers flow over steep plateau edges.",
correctLetter: "B",
correctOption: 2,
},

{
id: "question45",
question:  "45. Buying and selling within a national boundary is called",
A: "Export trade.",
B: "Internal trade.",
C: "International trade.",
D: "Bilateral trade.",
answer: "B. Internal trade.",
correctLetter: "B",
correctOption: 2,
},

{
id: "question46",
question:  "46. A settlement pattern where houses are arranged along lines of communication is described as",
A: "Isolated.",
B: "Dispersed.",
C: "Linear.",
D: "Nodal.",
answer: "C. Linear.",
correctLetter: "C",
correctOption: 3,
},

{
id: "question47",
question:  "47. Which of the following is an example of a local craft industry?",
A: "Ship building",
B: "Pottery",
C: "Textiles",
D: "Iron and steel",
answer: "B. Pottery",
correctLetter: "B",
correctOption: 2,
},

{
id: "question48",
question:  "48. All the following are problems resulting from the growth of urban centres except",
A: "Adequate road",
B: "High crime rate",
C: "Traffic congestion",
D: "Inadequate housing",
answer: "A. Adequate road",
correctLetter: "A",
correctOption: 1,
},

{
id: "question49",
question:  "49. Aport’s hinter land is",
A: "The central part of a port.",
B: "An out port.",
C: "The area which is served by a port.",
D: "The port’s cargo shed.",
answer: "C. The area which is served by a port.",
correctLetter: "C",
correctOption: 3,
},

{
id: "question50",
question:  "50. The movement of people from a village to a farm settlement may be described as",
A: "Urban-rural migration.",
B: "Rural-urban migration.",
C: "Rural-rural migration.",
D: "Urban-urban migration.",
answer: "C. Rural-rural migration.",
correctLetter: "C",
correctOption: 3,
},


]