export const BIOLOGYA2017 = [

{
id: "question1",
question:  "1. Which of the following groups of animal do not possess a nervous system?",
A: "Porifera",
B: "Cnidaria",
C: "Platyhelminthes",
D: "Nematoda",
answer: "A. Porifera",
correctLetter: "A",
correctOption: 1,
},

{
id: "question2",
question:  "2. The structural similarities in Paramecium and Euglena are in the",
A: "shape of locomotory organs",
B: "blunt anterior and pointed posterior",
C: "presence of micro and mega nuclei in both",
D: "presence of anterior and posterior contractile vacuoles",
answer: "B. blunt anterior and pointed posterior",
correctLetter: "B",
correctOption: 2,
},

{
id: "question3",
question:  "3. Which of the following organisms cannot exist freely on its own?",
A: "Chlamydomonas",
B: "Amoeba",
C: "Paramecium",
D: "Plasmodium",
answer: "D. Plasmodium",
correctLetter: "D",
correctOption: 4,
},

{
id: "question4",
question:  "4. The Arthropod in the diagram is not an insect because it",
A: "has a big head which is almost equal to the thorax",
B: "has eight legs and no wings",
C: "does not have visible eyes on its head",
D: "has head, thorax and abdomen",
answer: "D. has head, thorax and abdomen",
correctLetter: "D",
correctOption: 4,
},

{
id: "question5",
question:  "5. Which of the following cell organelles is the site for the production of ATP?",
A: "Lysosome",
B: "Nucleus",
C: "Mitochondrion",
D: "Ribosome",
answer: "C. Mitochondrion",
correctLetter: "C",
correctOption: 3,
},

{
id: "question6",
question:  "6. An example of osmosis in plants is the",
A: "movement of water through the xylem",
B: "loss of water vapour from the stomata",
C: "translocation of food through the phloem",
D: "absorption of water from the soil by the root",
answer: "D. absorption of water from the soil by the root",
correctLetter: "D",
correctOption: 4,
},

{
id: "question7",
question:  "7. The organism that can carry out both autotrophic and heterotrophic modes of nutritions is",
A: "Chlamydomonas",
B: "Eudorina",
C: "Euglena",
D: "Spirogyra",
answer: "D. Spirogyra",
correctLetter: "D",
correctOption: 4,
},

{
id: "question8",
question:  "8. The diagram represents the bones of the",
A: "upper arm",
B: "lower arm",
C: "upper leg",
D: "lower leg",
answer: "B. lower arm",
correctLetter: "B",
correctOption: 2,
},

{
id: "question9",
question:  "9. Which of the labelled parts articulates with the head of the trochlea to form a hinge joint?",
A: "I",
B: "II",
C: "III",
D: "IV",
answer: "B. II",
correctLetter: "B",
correctOption: 2,
},

{
id: "question10",
question:  "10. The labelled part that provides surface for the attachment of the triceps is",
A: "I",
B: "II",
C: "III",
D: "IV",
answer: "C. III",
correctLetter: "C",
correctOption: 3,
},

{
id: "question11",
question:  "11. The diagram below illustrates the transverse section of a",
A: "dicotyledonous root",
B: "monocotyledonous root",
C: "dicotyledonous stem",
D: "monocotyledonous stem",
answer: "C. dicotyledonous stem",
correctLetter: "C",
correctOption: 3,
},

{
id: "question12",
question:  "12. Which of the following actions does not occur during exhalation in man?",
A: "Thoracic cavity decreases in volume",
B: "Diaphragm flattens",
C: "Ribs move down and in",
D: "Air pressure increases in the thoracic cavity",
answer: "B. Diaphragm flattens",
correctLetter: "B",
correctOption: 2,
},

{
id: "question13",
question:  "13. Which of the following substances is found in the part labelled Il only?",
A: "Lipid",
B: "Protein",
C: "Salts",
D: "Water",
answer: "B. Protein",
correctLetter: "B",
correctOption: 2,
},

{
id: "question14",
question:  "14. The part which contains lowest concentration of urea is labelled",
A: "I",
B: "II",
C: "III",
D: "IV",
answer: "C. III",
correctLetter: "C",
correctOption: 3,
},

{
id: "question15",
question:  "15. Which of the following substances is greater in concentration in the part labelled IV when compared to that part labelled II?",
A: "Lipid",
B: "Glucose",
C: "Urea",
D: "Uric acid",
answer: "C. Urea",
correctLetter: "C",
correctOption: 3,
},

{
id: "question16",
question:  "16. Deamination of amino acids in the liver produces",
A: "Blood sugar",
B: "Glycogen",
C: "Bile",
D: "Urea",
answer: "D. Urea",
correctLetter: "D",
correctOption: 4,
},

{
id: "question17",
question:  "17. Which of the following glands also serves as an exocrine gland?",
A: "Ovary",
B: "Pancreas",
C: "Adrenal gland",
D: "Thyroid gland",
answer: "B. Pancreas",
correctLetter: "B",
correctOption: 2,
},

{
id: "question18",
question:  "18. Which of the following sequences is the correct route of the transmission of impulses along a reflex arc?",
A: "Receptor > sensory neurone > synapse > intermediate neurone > synapse motor neurone > effector",
B: "Receptor > motor neurone > synapse > intermediate neurone > synapse > sensory neurone > effector",
C: "Effector > intermediate neurone > synapse > motor neurone > synapse > sensory neurone > receptor",
D: "Effector > motor neurone > synapse > sensory neurone > synapse > intermediate neurone > receptor",
answer: "A. Receptor > sensory neurone > synapse > intermediate neurone > synapse motor neurone > effector",
correctLetter: "A",
correctOption: 1,
},

{
id: "question19",
question:  "19. When viewing an object close to the human eye, the",
A: "The eye lens becomes thin",
B: "The ciliary muscles relax",
C: "Suspensory ligaments become taut",
D: "Eye lens becomes flat",
answer: "D. Eye lens becomes flat",
correctLetter: "D",
correctOption: 4,
},

{
id: "question20",
question:  "20. The part labelled I is",
A: "acrosome",
B: "nucleus",
C: "mitochondrion",
D: "tail",
answer: "A. acrosome",
correctLetter: "A",
correctOption: 1,
},

{
id: "question21",
question:  "21. The function of the part labelled II is to",
A: "fuse with the ovum during fertilization",
B: "generate the energy for the sperm to swim to the fallopian tube",
C: "help the sperm to swim forward",
D: "dissolve the membrane of the egg during fertilization",
answer: "C. help the sperm to swim forward",
correctLetter: "C",
correctOption: 3,
},

{
id: "question22",
question:  "22. Which of the following types of placentation is not common amongst syncarpous pistils?",
A: "marginal",
B: "axile",
C: "peal",
D: "free central",
answer: "A. marginal",
correctLetter: "A",
correctOption: 1,
},

{
id: "question23",
question:  "23. The complex energy-rich organic matter which living organisms need for life is",
A: "water",
B: "air",
C: "food",
D: "mineral salts",
answer: "C. food",
correctLetter: "C",
correctOption: 3,
},

{
id: "question24",
question:  "24. Which of the following processes are associated with photosynthesis? \nI. Energy from sunlight is absorbed \nII. Carbon dioxide is evolved \nIII. Oxygen is given off \nIV. Glucose is synthesized",
A: "I and II only",
B: "I, II and IV only",
C: "I, III and IV only",
D: "I, II, III and IV",
answer: "C. I, III and IV only",
correctLetter: "C",
correctOption: 3,
},

{
id: "question25",
question:  "25. Which of the following functions is associated with calcium in plants? Formation of",
A: "cell wall",
B: "ribosomes",
C: "proteins",
D: "cell membrane",
answer: "A. cell wall",
correctLetter: "A",
correctOption: 1,
},

{
id: "question26",
question:  "26. The dentition belongs to a",
A: "Rabbit",
B: "Cat",
C: "Frog",
D: "Man",
answer: "D. Man",
correctLetter: "D",
correctOption: 4,
},

{
id: "question27",
question:  "27. The function of the teeth labelled X is",
A: "Biting and grasping",
B: "Chewing and grinding",
C: "Tearing and grasping",
D: "Chewing and tearing",
answer: "C. Tearing and grasping",
correctLetter: "C",
correctOption: 3,
},

{
id: "question28",
question:  "28. The teeth which are absent in the young of the organism is",
A: "W",
B: "X",
C: "Y",
D: "Z",
answer: "C. Y",
correctLetter: "C",
correctOption: 3,
},

{
id: "question29",
question:  "29. The number of individuals that the environment can support over a long period of time is its",
A: "growth rate",
B: "total capacity",
C: "population capacity",
D: "carrying capacity",
answer: "C. population capacity",
correctLetter: "C",
correctOption: 3,
},

{
id: "question30",
question:  "30. A good site for secondary succession would be",
A: "a sand dune",
B: "a bare jock",
C: "a land that just had forest tire",
D: "a stretch of barren land",
answer: "C. a land that just had forest tire",
correctLetter: "C",
correctOption: 3,
},

{
id: "question31",
question:  "31. A population which exceeds its carrying capacity and then collapses is represented graphically by a",
A: "bell-shaped curve",
B: "linear curve",
C: "sigmoid curve",
D: "skewed curve",
answer: "A. bell-shaped curve",
correctLetter: "A",
correctOption: 1,
},

{
id: "question32",
question:  "32. The natural dwelling place of an organism is called its",
A: "ecological niche",
B: "habitat",
C: "population",
D: "environment",
answer: "B. habitat",
correctLetter: "B",
correctOption: 2,
},

{
id: "question33",
question:  "33. Which of the following ecological factors will result in food shortage?",
A: "Drought",
B: "Low rate of reproduction",
C: "Emigration",
D: "Topography",
answer: "A. Drought",
correctLetter: "A",
correctOption: 1,
},

{
id: "question34",
question:  "34. Soil permeability refers to",
A: "how easily water passes through the soil",
B: "the proportion of air in the soil",
C: "the proportion of water the soil holds",
D: "how well water rises up the soil",
answer: "A. how easily water passes through the soil",
correctLetter: "A",
correctOption: 1,
},

{
id: "question35",
question:  "35. Which of the following groups of organisms do not have members that can be called autotrophs?",
A: "Protists",
B: "Mosses",
C: "Chlorophytes",
D: "Fungi",
answer: "D. Fungi",
correctLetter: "D",
correctOption: 4,
},

{
id: "question36",
question:  "36. Which of the following pyramids gives the most accurate picture of the relationships between the organisms at the various trophic levels in a food chain? A pyramid of",
A: "numbers",
B: "energy",
C: "biomass",
D: "size",
answer: "D. size",
correctLetter: "D",
correctOption: 4,
},

{
id: "question37",
question:  "37. Which of the following statements is not associated with pyramids of energy?",
A: "Efficiency of energy transfer between trophic levels can be studied",
B: "Comparisons of pyramids for different ecosystems can be made",
C: "More accurate comparisons of trophic levels",
D: "Representation of numbers of organisms at different trophic levels.",
answer: "B. Comparisons of pyramids for different ecosystems can be made",
correctLetter: "B",
correctOption: 2,
},

{
id: "question38",
question:  "38. Which of the following materials is not easily biodegradable?",
A: "Polythene bag",
B: "Cotton bag",
C: "Hides and skin bag",
D: "Paper bag",
answer: "A. Polythene bag",
correctLetter: "A",
correctOption: 1,
},

{
id: "question39",
question:  "39. Which of the following pairs of organisms is in a mutualistic relationship?",
A: "Hydra and sea anemone",
B: "Hermit crab and sea anemone",
C: "Dodder plant and cocoa plant",
D: "Mistletoe and kolanut",
answer: "B. Hermit crab and sea anemone",
correctLetter: "B",
correctOption: 2,
},

{
id: "question40",
question:  "40. The establishment of game reserves and parks is a method of",
A: "conserving natural resources",
B: "cultivating game",
C: "controlling pollution",
D: "cultural awareness",
answer: "A. conserving natural resources",
correctLetter: "A",
correctOption: 1,
},

{
id: "question41",
question:  "41. Which of the following is not used in conserving water?",
A: "Afforestation",
B: "Damming",
C: "Deforestation",
D: "Reforestation",
answer: "C. Deforestation",
correctLetter: "C",
correctOption: 3,
},

{
id: "question42",
question:  "42. Which of the following resources cannot be renewed?",
A: "Air",
B: "Petroleum",
C: "Food crop",
D: "Soil",
answer: "C. Food crop",
correctLetter: "C",
correctOption: 3,
},

{
id: "question43",
question:  "43. The type of variation illustrated above is",
A: "continuous variation",
B: "discontinuous variation",
C: "morphological variation",
D: "environmental variation",
answer: "B. discontinuous variation",
correctLetter: "B",
correctOption: 2,
},

{
id: "question44",
question:  "44. Which of the following characters is not a morphological variation?",
A: "shape of the nose",
B: "colour of skin",
C: "colour of hair",
D: "tongue rolling",
answer: "D. tongue rolling",
correctLetter: "D",
correctOption: 4,
},

{
id: "question45",
question:  "45. An apple plant can produce sexually and asexually and it has 110 chromosomes in its leaf cells. How many chromosomes world be in each gamete and somatic cell?",
A: "20 chromosomes in the gametes and 10 in the somatic cells",
B: "40 chromosomes in the gametes and 20 in the somatic cells",
C: "20 chromosomes in the gametes, and 40 in the somatic",
D: "40 chromosomes in the gametes and 40 in the somatic cells",
answer: "C. 20 chromosomes in the gametes, and 40 in the somatic",
correctLetter: "C",
correctOption: 3,
},

{
id: "question46",
question:  "46. Assuming that A is the gene for normal skin colour end is dominant, while a is the gene for albinism and its recessive, what is the likely genotype of the couple which had 50% normal and 50% albino offspring?",
A: "AA, aa",
B: "Aa, aa",
C: "AA, Aa",
D: "Aa, Aa",
answer: "B. Aa, aa",
correctLetter: "B",
correctOption: 2,
},

{
id: "question47",
question:  "47. Which of the following statements is true about mutation?",
A: "Phenotype is not involved",
B: "Genotype is not involved",
C: "Artificial induction is not possible",
D: "Genotype is involved",
answer: "B. Genotype is not involved",
correctLetter: "B",
correctOption: 2,
},

{
id: "question48",
question:  "48. One of the structural adaptations of mammals for movement on land is the development of the",
A: "hollow bones",
B: "pentadactyl limb",
C: "fused thoracic bones",
D: "streamlined body",
answer: "B. pentadactyl limb",
correctLetter: "B",
correctOption: 2,
},

{
id: "question49",
question:  "49. Which of the following traits is not characteristic of social insects?",
A: "All members are identical",
B: "There is division of labour",
C: "The members dwell in the same habitat",
D: "Some members protect the queen",
answer: "A. All members are identical",
correctLetter: "A",
correctOption: 1,
},

{
id: "question50",
question:  "50. The gradual cumulative, adaptive and heritable changes in an organism over a long period of time resulting in new species is called",
A: "adaptation",
B: "survival",
C: "organic evolution",
D: "interspecific competition",
answer: "A. adaptation",
correctLetter: "A",
correctOption: 1,
},


]