import { SquareRoot, superscript, subscript, BoldText, ItalicText, Fraction, ShortFraction, LongFraction, MixedFraction, Isotopes } from "@/mathnotation"

const path = "@/assets/images/pastquestions-figures/coremathematics/coremathematicsA/coremathematics-"


export const COREMATHEMATICSA2008 = [

{
id: "question1",
question: "1. Express the 196650 to the nearest thousand",
A: "196000",
B: "196700",
C: "197000",
D: "200000",
answer: "C. 197000",
correctLetter: "C",
correctOption: 3,
},

{
id: "question2",
question: "2. Express the sum of 200.2 and 4.27 x 10 in standard form.",
A: "4.4702 x 10³",
B: "4.4702 x 10²",
C: "4.4702 x 10⁻²",
D: "4.4702 x 10⁻³",
answer: "A. 4",
correctLetter: "A",
correctOption: 1,
},

{
id: "question3",
question: "3. If P = {x: 0 ≤ x < 9}, Q = {x: 2 < x < 5} and R = {x: 4 ≤ x ≤ 6}, find Pn(Q U R), where x is an integer.",
A: "{4, 5}",
B: "{3,4}",
C: "{3, 4, 5, 6}",
D: "{4, 5, 6}",
answer: "C. {3, 4, 5, 6}",
correctLetter: "C",
correctOption: 3,
},

{
id: "question4",
question: "4. What is the least value of p if 2³ x 3³ x 7 x p is a perfect square?",
A: "7",
B: "21",
C: "42",
D: "63",
answer: "C. 42",
correctLetter: "C",
correctOption: 3,
},

{
id: "question5",
question: "5. Simplify: (¹/₃(2¹/₆ + 5¹/₆) / (1¹/₁₂))",
A: "1³¹/₅₇",
B: "3²¹/₅₇",
C: "7¹/₅₇",
D: "7⁷/₅₇",
answer: "A. 1 31/57",
correctLetter: "A",
correctOption: 1,
},

{
id: "question6",
question: "6. If 32₅ = 101₂ + 12ₙ, find the value of n",
A: "10",
B: "9",
C: "8",
D: "7",
answer: "A. 10",
correctLetter: "A",
correctOption: 1,
},

{
id: "question7",
question: "7. Offei is x years old now. Five years ago, he was half as old as he is now. How old is he now?",
A: "10 years",
B: "5 years",
C: "3¹/₃ years",
D: "2²/₃ years",
answer: "A. 10 years",
correctLetter: "A",
correctOption: 1,
},

{
instruction: "The graphs below are for the functions y = 2x² + 3x - 6 and y = 2x + 1. Use them to answer Questions 8 and 9.",
id: "question8",
question: "8. What are the roots of the equation 2x² +3x-6 0?",
A: "-2.7, 1.2",
B: "-2.4, 1.0",
C: "-2.8, 1.6",
D: "-2.9, 1.8",
answer: "A. -2",
correctLetter: "A",
correctOption: 1,
questionFigure: require(path + "2008-A-Q-8.png"),
imageRatio: 1.0,
},

{
id: "question9",
question: "9. For what values of 2x² + x - 7 = 0?",
A: "x = -2.6 or 1.4",
B: "x = -2.4 or 1.8",
C: "x = -2.2 or 1.6",
D: "x = -2.8 or 1.8",
answer: "C. x = -2",
correctLetter: "C",
correctOption: 3,
},

{
id: "question10",
question: "10. Solve for x from the equation, x/5 + 3 = x/3 + 5",
A: "-15",
B: "-1",
C: "1",
D: "15",
answer: "A. -15",
correctLetter: "A",
correctOption: 1,
},

{
id: "question11",
question: "11. Express as a single fraction",
A: "(2x² + 2x − 2) / (x − 2)( x + 3)",
B: "(4x + 2) / (x − 2)(x + 3)",
C: "(2x² + 2x + 2) / (x − 2)(x + 3)",
D: "(2 − 4x) / (x−2)(x+3)",
answer: "B. (4x+2)/(x-2)(x+3)",
correctLetter: "B",
correctOption: 2,
},

{
id: "question12",
question: "12. By how much does (a + 2b - c) exceeds (2b - a - c)?",
A: "2a + 2b",
B: "2a",
C: "2a + 4b",
D: "4b",
answer: "B. 2a",
correctLetter: "B",
correctOption: 2,
},

{
id: "question13",
question: "13. Factorize 4a² - 60a + 225",
A: "(2a - 15)²",
B: "(2a + 15)(2a - 15)",
C: "(2a + 15)2",
D: "(4a - 15)(a - 15)",
answer: "A. (2a - 15)²",
correctLetter: "A",
correctOption: 1,
},

{
id: "question14",
question: "14. An isosceles triangle is of base 10 cm. If the equal sides are 13 cm each, find the height of the triangle",
A: "√69 cm",
B: "8 cm",
C: "12 cm",
D: "√269 cm",
answer: "C. 12 cm",
correctLetter: "C",
correctOption: 3,
},

{
id: "question15",
question: "15. The hour hand of a clock moves from 3.00 p.m. to 6.00 p.m. If the length of the hour hand is 5 cm, find the area covered by the movement",
A: "28.72 cm²",
B: "20.71 cm²",
C: "19.64 cm²",
D: "19.61 cm²",
answer: "C. 19",
correctLetter: "C",
correctOption: 3,
},

{
id: "question16",
instruction: "In the diagram above, XYZ is a right angled triangle. ",
question: "16. Calculate the area of the triangle.",
A: "130 cm³",
B: "120 cm³",
C: "65 cm³",
D: "60 cm 3",
answer: "B. 120 cm³",
correctLetter: "B",
correctOption: 2,
questionFigure: require(path + "2008-A-Q-16.png"),
imageRatio: 1,
},

{
id: "question17",
instruction: "In the diagram, |S7| = 2 cm, |PT| = 4 cm, |UR| = 3 cm, S // QU and QS//UT. ",
question: "17. Find |PR|",
A: "4 cm",
B: "5 cm",
C: "6 cm",
D: "10 cm",
answer: "D. 10 cm",
correctLetter: "D",
correctOption: 4,
questionFigure: require(path + "2008-A-Q-17.png"),
imageRatio: 1.0,
},

{
id: "question18",
question: "18. Which of the following is not a property of a parallelogram?",
A: "The opposite sides are equal.",
B: "The diagonals bisect each angle",
C: "The opposite angles are equal.",
D: "The diagonals bisect each other",
answer: "B. The diagonals bisect each angle",
correctLetter: "B",
correctOption: 2,
},

{
id: "question19",
instruction: "In the diagram above, XY is parallel to RS, |SY|=|SR, |ZS|=|ZR| and ∠RZK = 100°. ",
question: "19. Calculate <XYR",
A: "20°",
B: "22°",
C: "25°",
D: "50°",
answer: "C. 25°",
correctLetter: "C",
correctOption: 3,
questionFigure: require(path + "2008-A-Q-19.png"),
imageRatio: 1.0,
},

{
id: "question20",
instruction: "In the diagram above, PRS is a straight line, PQ // RT, ∠RPQ =65° and ∠SRQ =102°. ",
question: "20. Find LTRO.",
A: "167°",
B: "143°",
C: "78°",
D: "65°",
answer: "B. 143°",
correctLetter: "B",
correctOption: 2,
questionFigure: require(path + "2008-A-Q-20.png"),
imageRatio: 1,
},

{
id: "question21",
instruction: "In the diagram above, O is the centre of the circle, ∠PSQ = x, ∠PRQ = y and ∠RPQ = z. ",
question: "21. Find a relationship in terms of x and z only",
A: "2x + z = 360°",
B: "x + 2z =180°",
C: "x + z =90°",
D: "z - x = 90°",
answer: "C. x + z =90°",
correctLetter: "C",
correctOption: 3,
questionFigure: require(path + "2008-A-Q-21.png"),
imageRatio: 1,
},

{
id: "question22",
question: "22. If sin5x = cos20°, find the value of x.",
A: "4°",
B: "14°",
C: "15°",
D: "20°",
answer: "B. 14°",
correctLetter: "B",
correctOption: 2,
},

{
id: "question23",
question: "23. If sinθ = 3/5, find the value of 2 sinθ + 3cosθ",
A: "3",
B: "3 1/5",
C: "3 2/5",
D: "3 3/5",
answer: "D. 3 3/5",
correctLetter: "D",
correctOption: 4,
},

{
id: "question24",
question: "24. If tanθ = 1, evaluate sin θ + cos θ, leaving your answer in surd form",
A: "2√2",
B: "1√2 2",
C: "√2",
D: "2",
answer: "C. √2",
correctLetter: "C",
correctOption: 3,
},

{
id: "question25",
instruction: "The following pie chart shows the number of students who graduated from four departments in a university. ",
question: "25. If 1200 students graduated from the Arts Department, how many students graduated from the four departments?",
A: "4800",
B: "4320",
C: "4300",
D: "4000",
answer: "B. 4320",
correctLetter: "B",
correctOption: 2,
questionFigure: require(path + "2008-A-Q-25.png"),
imageRatio: 1,
},

{
id: "question26",
question: "26. Joe bought a small radio at₦800.00 and sold it to Danli at a profit of 5%. Danli then sold it to Chike at a loss of 5%. How much did Chike pay for the radio?",
A: "₦760",
B: "₦780",
C: "₦798",
D: "₦800",
answer: "C. ₦798",
correctLetter: "C",
correctOption: 3,
},

{
id: "question27",
question: "27. X is inversely proportional to Y. If X = -2 when Y = 3, find X when Y = -5.",
A: "-1 1/5",
B: "-5/6",
C: "5/6",
D: "1 1/5",
answer: "D. 1 1/5",
correctLetter: "D",
correctOption: 4,
},

{
id: "question28",
question: "28. Simplify (√6)(2√2) / (√3)³",
A: "3/4",
B: "4√3",
C: "1 1/3",
D: "4√2",
answer: "C. 1 1/3",
correctLetter: "C",
correctOption: 3,
},

{
id: "question29",
question: "29. If (3n - 1)^(¹/₃) = 2, Find n.",
A: "4",
B: "3",
C: "2",
D: "1",
answer: "B. 3",
correctLetter: "B",
correctOption: 2,
},

{
id: "question30",
question: "30. The simple interest on ¢12,000 for 2 years is ¢1200. What is the rate per cent per annum?",
A: "1.00",
B: "2.50",
C: "4.00",
D: "5.00",
answer: "C. 4",
correctLetter: "C",
correctOption: 3,
},

{
id: "question31",
question: "31. Dodo travels at an average speed of 110 km/h. What time does he take to cover a D. distance of 220 km?",
A: "½ hour",
B: "2 hours",
C: "2 ½ hours",
D: "2 hours 45 minutes",
answer: "B. 2 hours",
correctLetter: "B",
correctOption: 2,
},

{
id: "question32",
question: "32. If x - 2 is a factor of 8 - 2bx - x², find b.",
A: "2",
B: "1",
C: "-1",
D: "-2",
answer: "B. 1",
correctLetter: "B",
correctOption: 2,
},

{
id: "question33",
question: "33. Given that u =-2, v = 3 and w = 5 , evaluate u³ + v/2w",
A: "-8.3",
B: "-7.7",
C: "-6.3",
D: "-5.7",
answer: "B. -7",
correctLetter: "B",
correctOption: 2,
},

{
id: "question34",
question: "34. Make t the subject of the relation r = ᵐ√(𝑡/n)",
A: "𝑡 = 𝑟²𝑚/𝑛",
B: "𝑡 = 𝑛𝑟²/𝑚²",
C: "𝑡 = 𝑟²𝑚²/𝑛",
D: "𝑡 = 𝑛𝑟²/𝑚",
answer: "B. t = nr²/m²",
correctLetter: "B",
correctOption: 2,
},

{
id: "question35",
question: "35. For what range of values of x is 3.2 + 1.8x > 2.6x?",
A: "x > 4",
B: "x < 4",
C: "x < -4",
D: "x > 0.4",
answer: "B. x < 4",
correctLetter: "B",
correctOption: 2,
},

{
id: "question36",
question: "36. Which of the following is not a quadratic equation?",
A: "2x² - 3x - 2 = 0",
B: "x³ - 2x² + 1 = 0",
C: "5y² - 6 = 0",
D: "3x² + 8 =0",
answer: "B. x³ -2x² + 1 = 0",
correctLetter: "B",
correctOption: 2,
},

{
id: "question37",
instruction: "37. Represent the inequality 3 ≤ x < 5 on a number line.",
question: " ",
A: " ",
B: " ",
C: " ",
D: " ",
answer: "A.  ",
correctLetter: "A",
correctOption: 1,
questionFigure: require(path + "2008-A-Q-37.png"),
imageRatio: 0.5,
},

{
id: "question38",
question: "38. Find, correct to three significant figures, the diameter of a cone of height 5 cm and volume 150 cm³. (Take π = 22/7)",
A: "9.54 cm",
B: "10.70 cm",
C: "2.68 cm",
D: "3.08 cm",
answer: "B. 10",
correctLetter: "B",
correctOption: 2,
},

{
id: "question39",
question: "39. A sector of a circle radius 18 cm subtends an angle of 100° at the centre. Calculate the perimeter of the sector, leaving your answer in terms of π",
A: "(10π + 18) cm",
B: "(10π + 36) cm",
C: "90πcm",
D: "10π cm",
answer: "B. (10π + 36) cm",
correctLetter: "B",
correctOption: 2,
},

{
id: "question40",
question: "40. On a map, a square field has an area of 2.25 cm² . If the actual perimeter of the field is 900 m, what does 1 cm on the map represent?",
A: "150 m",
B: "400 m",
C: "600 m",
D: "625 m",
answer: "A. 150 m",
correctLetter: "A",
correctOption: 1,
},

{
id: "question41",
instruction: "In the diagram above, |XT| which is the altitude of △XYZ is 60 cm, |YT| = 11 cm and |XZ| = 65 cm. ",
question: "41. Find YZ",
A: "14 cm",
B: "15 cm",
C: "25 cm",
D: "36 cm",
answer: "A. 14 cm",
correctLetter: "A",
correctOption: 1,
questionFigure: require(path + "2008-A-Q-41.png"),
imageRatio: 1,
},

{
id: "question42",
instruction: "The following diagram shows triangle PQR inscribed in a circle. RT is a tangent to the circle at R.",
question: "42.  Find ∠PQR",
A: "76°",
B: "69°",
C: "61°",
D: "57°",
answer: "A. 76°",
correctLetter: "A",
correctOption: 1,
questionFigure: require(path + "2008-A-Q-42.png"),
imageRatio: 1,
},

{
id: "question43",
question: "43. The sum of all the interior and exterior angles of a regular polygon is 1080°. Find the number of sides.",
A: "5",
B: "6",
C: "7",
D: "8",
answer: "C. 6",
correctLetter: "C",
correctOption: 3,
},

{
id: "question44",
question: "44. A boy tossed a fair die once and he obtained a score of 6. Find the probability that he will obtain a score of 6 in the next toss.",
A: "1/3",
B: "1/6",
C: "1/18",
D: "1/36",
answer: "D. 1/36",
correctLetter: "D",
correctOption: 4,
},

{
id: "question45",
question: "45. A number is selected at random from the set of integers 1 to 20 inclusive. What is the probability that the number selected is equal to or greater than 18?",
A: "1/10",
B: "3/20",
C: "17/20",
D: "9/10",
answer: "B. 3/20",
correctLetter: "B",
correctOption: 2,
},

{
id: "question46",
question: "46. The mean of five numbers is 10. If a new number N is added, the mean becomes 12. Find the value of N.",
A: "24",
B: "22",
C: "20",
D: "18",
answer: "B. 22",
correctLetter: "B",
correctOption: 2,
},

{
id: "question47",
question: "47. Which of these is not a measure or dispersion?",
A: "Mean deviation",
B: "Mean",
C: "Range",
D: "Variance",
answer: "B. Mean",
correctLetter: "B",
correctOption: 2,
},

{
id: "question48",
question: "48. In the diagram, PQ // RS, EF // GH, ∠QRS =90°. Find the angle marked x°",
A: "90°",
B: "82°",
C: "45°",
D: "30°",
answer: "C. 45°",
correctLetter: "C",
correctOption: 3,
questionFigure: require(path + "2008-A-Q-48.png"),
imageRatio: 1,
},

{
id: "question49",
question: "49. In the diagram above, q = 60, r + s = 100. Find p.",
A: "40",
B: "60",
C: "100",
D: "140",
answer: "A. 40",
correctLetter: "A",
correctOption: 1,
questionFigure: require(path + "2008-A-Q-49.png"),
imageRatio: 1,
},

{
id: "question50",
question: "50. In the diagram above, PQR is a tangent at Q and TQR = 70°. Find <QST.",
A: "140°",
B: "110°",
C: "70°",
D: "40°",
answer: "B. 110°",
correctLetter: "B",
correctOption: 2,
questionFigure: require(path + "2008-A-Q-50.png"),
imageRatio: 1.0,
},

]