
import { SquareRoot, superscript, subscript, BoldText, ItalicText, Fraction, ShortFraction, LongFraction, MixedFraction, Isotopes } from "@/mathnotation"

const path = "@/assets/images/pastquestions-figures/coremathematics/coremathematicsA/coremathematics-"


export const COREMATHEMATICSA2012 = [

{
id: "question1",
question: "1. If P = {2, 4, 6, 8, 10}, Q = {3, 6, 9, 12, 15} and R = {5, 10, 15, 20, 25}. Find n(P ∩ Q ∩ R).",
A: "0",
B: "1",
C: "2",
D: "3",
answer: "A. 0",
correctLetter: "A",
correctOption: 1,
},

{
id: "question2",
question: "2. Evaluate 2⁰ + 2⁻¹ + 2⁻²",
A: "1/8",
B: "3/4",
C: "1 1/8",
D: "1 3/4",
answer: "D. 1 3/4",
correctLetter: "D",
correctOption: 4,
},

{
id: "question3",
question: "3. The sides of a triangle of perimeter 260 cm are in the ratio 1¹/₂ : 2 : 3. What is the length of the longest side?",
A: "160 cm",
B: "120 cm",
C: "80 cm",
D: "60 cm",
answer: "B. 120 cm",
correctLetter: "B",
correctOption: 2,
},

{
id: "question4",
question: "4. Given that log₁₀y = 1 + 3log₁₀X, express y in terms of x.",
A: "y = 10x³",
B: "y = 10x⁻³",
C: "y = x³",
D: "y = x⁻³",
answer: "A. y = 10⁻³",
correctLetter: "A",
correctOption: 1,
},

{
id: "question5",
question: "5. If X₄ = 145₆ find X.",
A: "1101",
B: "1111",
C: "1010",
D: "1001",
answer: "D. 1001",
correctLetter: "D",
correctOption: 4,
},

{
id: "question6",
question: "6. A sequence is defined by the recurrence relation, Tₙ = 1 + 2Tₙ₋₁ for n ≥ 1. If T₁ = 8, find T₃.",
A: "21",
B: "33",
C: "35",
D: "37",
answer: "C. 35",
correctLetter: "C",
correctOption: 3,
},

{
id: "question7",
question: "7. If 5/6 of a number is 5 greater than 2/3 of it, find the number.",
A: "60",
B: "36",
C: "30",
D: "18",
answer: "C. 30",
correctLetter: "C",
correctOption: 3,
},

{
id: "question8",
question: "8. Which of the following inequalities represented on the number line?",
A: "-3 < y < l",
B: "-3 ≤ y < 1",
C: "-3 < y ≤ l",
D: "1 < y ≤ 3",
answer: "C. -3 < y ≤ l",
correctLetter: "C",
correctOption: 3,
questionFigure: require(path + "2012-A-Q-8.png"),
imageRatio: 0.3,
},

{
id: "question9",
question: "9. Find the value of k if a2 + 6a + k = (a +3)2",
A: "2/9",
B: "9/2",
C: "6",
D: "9",
answer: "D. 9",
correctLetter: "D",
correctOption: 4,
},

{
id: "question10",
question: "10. What are the coordinates of the point where the straight lines x + 3y = -7 and 5x - 2y = 16 intersect?",
A: "(-2, -3)",
B: "(2, -3)",
C: "(-2, 3)",
D: "(2, 3)",
answer: "B. (2, -3)",
correctLetter: "B",
correctOption: 2,
},

{
id: "question11",
question: "11. If (r - 2) and (x + 1) are factors of x² + bx + c = 0, find the value of (b + c).",
A: "-3",
B: "-2",
C: "1",
D: "2",
answer: "A. -3",
correctLetter: "A",
correctOption: 1,
},

{
id: "question12",
question: "12. If p, q, r, s are all positive and  p = √(q² - (r²/s²))	make s the subject of the relation.",
A: "k/3",
B: "(m - k)/3",
C: "r/(√(p² - q²))",
D: "((√(p² - q²)))/r",
answer: "C. s =",
correctLetter: "C",
correctOption: 3,
},

{
id: "question13",
question: "13. Multiply (mk)/(3m + 3k) by (m + k)/m",
A: "k/3",
B: "(m + 3)/3",
C: "(m + k)/3",
D: "mk/3",
answer: "A. k/3",
correctLetter: "A",
correctOption: 1,
},

{
id: "question14",
question: "14. The equation of a straight line is 2x + 3y - 6 = 0. Find the intercept on the y-axis.",
A: "(0, 3)",
B: "(0, 2)",
C: "(2, 0)",
D: "(3, 0)",
answer: "B. (0, 2)",
correctLetter: "B",
correctOption: 2,
},

{
id: "question15",
question: "15. The angle of a sector of a circle of radius 6 cm is 120°. Find the area of the sector in terms of π .",
A: "4π cm²",
B: "8π cm²",
C: "12π cm²",
D: "24π cm²",
answer: "C. 12π cm²",
correctLetter: "C",
correctOption: 3,
},

{
id: "question16",
question: "16. Find the volume, in litres of a cylindrical drum of diameter 28 cm and height 50 cm. (Take π = 22/7).",
A: "31.8 litres",
B: "30.8 litres",
C: "29.8 litres",
D: "28.8 litres",
answer: "B. 30",
correctLetter: "B",
correctOption: 2,
},

{
id: "question17",
question: "17. A pendulum of a clock is 7 cm long and swings through an arc of length 12 cm. Through what angle, corrected to the nearest degree, does the pendulum swing? (Take rr = 22/7).",
A: "72°",
B: "92°",
C: "98°",
D: "118°",
answer: "C. 98°",
correctLetter: "C",
correctOption: 3,
},

{
id: "question18",
question: "18. The lengths of the sides of a triangle, in centimetres, are l, (l + 7) and (l + 8). If its perimeter is 30 cm, find the length of its longest side.",
A: "13 cm",
B: "12 cm",
C: "6 cm",
D: "5 cm",
answer: "A. 12 cm",
correctLetter: "A",
correctOption: 1,
},

{
id: "question19",
question: "19. If the interior angles of a pentagon are 2x, x, 2x, 3x and x, find the value of x.",
A: "30°",
B: "40°",
C: "50°",
D: "60°",
answer: "D. 60°",
correctLetter: "D",
correctOption: 4,
},

{
id: "question20",
question: "20. In the diagram, O is the centre of circle PORS and ∠PQR = 65°. Find the value of the angle x.",
A: "115°",
B: "130°",
C: "230°",
D: "255°",
answer: "C. 230°",
correctLetter: "C",
correctOption: 3,
questionFigure: require(path + "2012-A-Q-20.png"),
imageRatio: 1,
},

{
id: "question21",
instruction: "21. In the diagram, PQ//EG, PHQ is an isosceles triangle and ∠HFG is 130°. ",
question: "Find ∠PHQ.",
A: "110°",
B: "80°",
C: "70°",
D: "55°",
answer: "B. 80°",
correctLetter: "B",
correctOption: 2,
questionFigure: require(path + "2012-A-Q-21.png"),
imageRatio: 1,
},

{
id: "question22",
instruction: "22. In the diagram, FH//YG, ∠EWZ = 70° and ∠YLZ=30°. ",
question: "Find the value of x.",
A: "40°",
B: "60°",
C: "100°",
D: "150°",
answer: "C. 100°",
correctLetter: "C",
correctOption: 3,
questionFigure: require(path + "2012-A-Q-22.png"),
imageRatio: 1,
},

{
id: "question23",
instruction: "23. In the diagram, MN, PQ and RS are three intersecting straight lines.",
question: "Which of the following statements is/are true? \nI.	t = y \nII.	x + y + z + m = 180° \nIII.	x + m + n = 180° \nIV.	x + n = m + z",
A: "II only",
B: "IlI only",
C: "IV only",
D: "I and IV only",
answer: "B. IlI only",
correctLetter: "B",
correctOption: 2,
questionFigure: require(path + "2012-A-Q-23.png"),
imageRatio: 1,
},

{
id: "question24",
question: "24. Which of the following statements is not true of a rectangle?",
A: "The diagonals are equal.",
B: "There are only two lines of symmetry.",
C: "The diagonals bisect each other.",
D: "The diagonals intersect at right angles.",
answer: "D. The diagonals intersect at right angles",
correctLetter: "D",
correctOption: 4,
},

{
id: "question25",
question: "25. The dimensions of a rectangle are 14 cm by 4 cm. Calculate, correct to the nearest degree, the acute angle between its diagonals.",
A: "26°",
B: "32°",
C: "64°",
D: "74°",
answer: "B. 32°",
correctLetter: "B",
correctOption: 2,
},

{
id: "question26",
question: "26. If sin (x -10)° = cos(x+10)°, calculate the value of x.",
A: "90°",
B: "60°",
C: "45°",
D: "40°",
answer: "C. 45°",
correctLetter: "C",
correctOption: 3,
},

{
id: "question27",
question: "27. The bearing of Q from P is 040° and the bearing of R from P is 130°. If |PQ| = r and |PR| = 2r, find |QR|.",
A: "√3r",
B: "√5r",
C: "r√3",
D: "r√5",
answer: "D. r√5",
correctLetter: "D",
correctOption: 4,
},

{
id: "question28",
question: "28. The mean of five numbers is 12. When another number is added, the mean becomes 11. Find the number that was added.",
A: "3",
B: "6",
C: "7",
D: "8",
answer: "B. 6",
correctLetter: "B",
correctOption: 2,
},

{
id: "question29",
question: "29. Two fair dice are thrown together once. What is the probability of getting the sum of 9?",
A: "13/6",
B: "1/18",
C: "1/9",
D: "4/9",
answer: "C. 1/9",
correctLetter: "C",
correctOption: 3,
},

{
instruction: "The bar chart shows the frequency distribution of marks scored by students in a class test. Use it to answer Questions 30 and 31.",
id: "question30",
question: "30. How many students took the test?",
A: "10",
B: "24",
C: "25",
D: "30",
answer: "C. 25",
correctLetter: "C",
correctOption: 3,
questionFigure: require(path + "2012-A-Q-30.png"),
imageRatio: 1,
},

{
id: "question31",
question: "31. What is the median of the distribution?",
A: "2",
B: "4",
C: "6",
D: "8",
answer: "A. 2",
correctLetter: "A",
correctOption: 1,
},

{
id: "question32",
question: "32. If x < 0, solve the equation x² = 3(2x + 9)",
A: "-1",
B: "-3",
C: "-6",
D: "-9",
answer: "B. -3",
correctLetter: "B",
correctOption: 2,
},

{
id: "question33",
question: "33. The ages of five students in a class are 13, 14, 17, 18, and 19. Find the standard deviation of their ages correct to two decimals places.",
A: "2.32",
B: "2.49",
C: "2.55",
D: "2.61",
answer: "A. 2",
correctLetter: "A",
correctOption: 1,
},

{
id: "question34",
question: "34. The dimensions of a cuboid are 20 cm, 30 cm and 60 cm. Find the length of the longest stick that can fit into the cuboid.",
A: "62.5 cm",
B: "65.0 cm",
C: "70.0 cm",
D: "73.3 cm",
answer: "C. 70",
correctLetter: "C",
correctOption: 3,
},

{
id: "question35",
question: "35. Correct 0.081778 to three significant figures.",
A: "0.0810",
B: "0.0817",
C: "0.0818",
D: "0.0820",
answer: "C. 0",
correctLetter: "C",
correctOption: 3,
},

{
id: "question36",
question: "36. The length, I of a simple pendulum varies directly as the square of its period, T. A pendulum of length 99.4 cm has a period of 2 seconds. Find, correct to two decimal places, the length of a pendulum of period 2.5 seconds.",
A: "63.62 cm",
B: "79.52 cm",
C: "124.25 cm",
D: "155.31 cm",
answer: "D. 155",
correctLetter: "D",
correctOption: 4,
},

{
id: "question37",
question: "37. Mr. Nagbe borrowed GH¢8,400 at a simple interest rate of 26¹/₂ % per annum. How much did he pay back after 8 months?",
A: "GH¢8,784.00",
B: "GH¢9,884.00",
C: "GH¢11,780.00",
D: "GH¢12,620.00",
answer: "B. GH¢9,884",
correctLetter: "B",
correctOption: 2,
},

{
id: "question38",
question: "38. Make x the subject of the relation x/q - 2 = x/p",
A: "x = 2pq/(p + q)",
B: "x = pq/(p - q)",
C: "x = pq/(p + q)",
D: "x = 2pq/(p - q)",
answer: "D. x = 2pq/(p + q) ****",
correctLetter: "D",
correctOption: 4,
},

{
id: "question39",
instruction: "39. Find the value of x in the diagram",
question: " ",
A: "120°",
B: "60°",
C: "40°",
D: "30°",
answer: "D. 30°",
correctLetter: "D",
correctOption: 4,
questionFigure: require(path + "2012-A-Q-39.png"),
imageRatio: 1,
},

{
id: "question40",
instruction: "40. Which of the following graphs best illustrates the equation y = x - 2?",
question: " ",
A: " ",
B: " ",
C: " ",
D: " ",
answer: "A. ",
correctLetter: "A",
correctOption: 1,
questionFigure: require(path + "2012-A-Q-40.png"),
imageRatio: 1,
},

{
id: "question41",
question: "41. A straight line passes through the points (1, 6), (3, -2) and (7, y). Find the value of y.",
A: "-18",
B: "-14",
C: "14",
D: "18",
answer: "A. -18",
correctLetter: "A",
correctOption: 1,
},

{
id: "question42",
question: "42. The diagram is a circle with centre O. U, V, W and Y are points on the circle. Find ∠UVW.",
A: "144°",
B: "72°",
C: "40°",
D: "36°",
answer: "B. 72°",
correctLetter: "B",
correctOption: 2,
questionFigure: require(path + "2012-A-Q-42.png"),
imageRatio: 1,
},

{
id: "question43",
instruction: "43. The diagram shows a circle of radius |OZ|= 4 cm. XW is a tangent to the circle at W. If ∠XYO = 120°, ",
question: "find |YZ|",
A: "2.32 cm",
B: "1.84 cm",
C: "0.62 cm",
D: "0.26 cm",
answer: "C. 0",
correctLetter: "C",
correctOption: 3,
questionFigure: require(path + "2012-A-Q-43.png"),
imageRatio: 1,
},

{
id: "question44",
question: "44. A side and a diagonal of a rhombus are 10 cm and 12 cm, respectively. Find its area",
A: "20 cm²",
B: "24 cm²",
C: "48 cm²",
D: "96 cm²",
answer: "D. 96 cm²",
correctLetter: "D",
correctOption: 4,
},

{
instruction: "The graphs are of the relation y = 2x² - x - 3 and y = x + 1. \nUse the graphs to answer Question 45 and 46",
id: "question45",
question: "45. Find the gradient of the curve y = 2x² - x - 3 at the point P, correct to the nearest whole number.",
A: "6",
B: "7",
C: "8",
D: "9",
answer: "B. 7",
correctLetter: "B",
correctOption: 2,
questionFigure: require(path + "2012-A-Q-45.png"),
imageRatio: 1,
},

{
id: "question46",
question: "46. Find the roots of the equation 2x² - 2x - 4 = 0",
A: "x=-l, x=2",
B: "x = 2, x = -1/2",
C: "x=3, x=1",
D: "x=-2, x=-2",
answer: "A. x=-l, x=2",
correctLetter: "A",
correctOption: 1,
},

{
id: "question47",
question: "47. If 8^(x-23) = 2^(x²) , find x.",
A: "-2 or -1",
B: "-2 or 1",
C: "2 or-1",
D: "2 or 1",
answer: "D. 2 or 1",
correctLetter: "D",
correctOption: 4,
},

{
id: "question48",
instruction: "48. In the figure, QR is parallel to ST. If |PT| = 15 cm,",
question: "find |RT|.",
A: "4 cm",
B: "6 cm",
C: "8 cm",
D: "10 cm",
answer: "B. 6 cm",
correctLetter: "B",
correctOption: 2,
questionFigure: require(path + "2012-A-Q-48.png"),
imageRatio: 1,
},

{
id: "question49",
question: "49. In the diagram, |ZY| = XY, ∠WYZ = 65° and ∠XWY = 48°. Find ∠WYX.",
A: "19°",
B: "25°",
C: "45°",
D: "65°",
answer: "A. 19°",
correctLetter: "A",
correctOption: 1,
questionFigure: require(path + "2012-A-Q-49.png"),
imageRatio: 1,
},

{
id: "question50",
question: "50. A tank in the form of a cuboid holds 500 litres of water. If each of its length, breadth and height is reduced by 10 percent, calculate, in litres, the volume of the water in the new tank.",
A: "490.0",
B: "450.0",
C: "364.5",
D: "256.5",
answer: "C. 364",
correctLetter: "C",
correctOption: 3,
},

]