import { SquareRoot, superscript, subscript, BoldText, ItalicText, Fraction, ShortFraction, LongFraction, MixedFraction, Isotopes } from "@/mathnotation"

const path = "@/assets/images/pastquestions-figures/coremathematics/coremathematicsA/coremathematics-"


export const COREMATHEMATICSA2015 = [

{
id: "question1",
question: "1. If {r: 2 ≤ x ≤ 18; x ϵ integer) and 7 + x = 4 (mod 9), find the highest value of x.",
A: "2",
B: "5",
C: "15",
D: "18",
answer: "C. 15",
correctLetter: "C",
correctOption: 3,
},

{
id: "question2",
question: "2. The sum of 11011₂ 11111₂ and 10000₂ is 10m10n0₂. Find the values of m and n.",
A: "m=0, n =0",
B: "m=1, n =0",
C: "m = 0, n =1",
D: "m=1, n =1",
answer: "C. m = 0, n =1",
correctLetter: "C",
correctOption: 3,
},
{
    id: "question3",
question: "3. A trader bought an engine for $15,000.00 outside Nigeria. If the exchange rate is $0.075 to N1.00, how much did the engine cost in naira?",
A: "N 250,000.00",
B: "N 200,000.00",
C: "N 150,000.00",
D: "N 100,000.00",
answer: "Z.  zzzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question4",
question: "4. If (27ˣ × 3⁽¹⁻ˣ⁾) / (9²x) = 1, find the value of x.",
A: "1",
B: "1/2",
C: "-1/2",
D: "-1",
answer: "Z.  zzzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question5",
question: "5. Find the 7th term of the sequence: 2, 5, 10, 17, 26, ...",
A: "37",
B: "48",
C: "50",
D: "63",
answer: "Z.  zzzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question6",
question: "6. Given that logx64 = 3, evaluate xlog₂8.",
A: "6",
B: "9",
C: "12",
D: "24",
answer: "C. 12",
correctLetter: "C",
correctOption: 3,
},

{
id: "question7",
question: "7. If 2ⁿ = y, find 2⁽²⁺ⁿ³⁾",
A: "4y^(¹/₃)",
B: "4y⁻³",
C: "2y^(¹/₃)",
D: "2y⁻³",
answer: "",
correctLetter: "E",
correctOption: 5,
}, 

{
id: "question8",
question: "8. Factorize completely: 6ax - 12by - 9ay + 8bx.",
A: "(2a - 3b)(4x + 3y)",
B: "(3a + 4b)(2x - 3y)",
C: "(3a - 4b)(2x + 3y)",
D: "(2a + 3b)(4x - 3y)",
answer: "B. (3a + 4b)(2x - 3y)",
correctLetter: "B",
correctOption: 2,
},

{
id: "question9",
question: "9. Find the equation whose roots are 3/4 and -4.",
A: "4x2 - 13x + 12 = 0",
B: "4x2 - 13x - 12 = 0",
C: "4x2 + 13x - 12 = 0",
D: "4x2 + 13x + 12 = 0",
answer: "C. 4x2 + 13x - 12 = 0",
correctLetter: "C",
correctOption: 3,
},

{
id: "question10",
question: "10. If m = 4, n = 9 and r = 16, evaluate m/n - 1⁷/₉ - n/r",
A: "1⁵/₁₆",
B: "1¹/₁₆",
C: "5/16",
D: "-37/48",
answer: "D. -37/48",
correctLetter: "D",
correctOption: 4,
},

{
id: "question11",
question: "11. Adding 42 to a given positive number gives the same result as squaring the number. Find the number.",
A: "14",
B: "13",
C: "7",
D: "6",
answer: "C. 7",
correctLetter: "C",
correctOption: 3,
},

{
id: "question12",
question: "12. Ada draws the graphs of y = x² - x - 2 and y = 2x - 1 on the same axes. Which of these equations is she solving?",
A: "x² - x - 3 = 0",
B: "x² - 3x - 1 = 0",
C: "x² - 3x - 3 = 0",
D: "x² + 3x - 1 = 0",
answer: "B. x² - 3x - 1 = 0",
correctLetter: "B",
correctOption: 2,
},

{
id: "question13",
question: "13. The volume of a cone of height 3 cm is 38¹/₂ cm³ . Find the radius of its base. [Take π = 22/7]",
A: "3.0 cm",
B: "3.5 cm",
C: "4.0 cm",
D: "4.5 cm",
answer: "B. 3",
correctLetter: "B",
correctOption: 2,
},

{
id: "question14",
question: "14. A sector of a circle with radius 6 cm subtends an angle of 60° at the centre. Calculate its perimeter in terms of π.",
A: "2(π + 6) cm",
B: "2(π + 3) cm",
C: "2(π + 2) cm",
D: "(π + 12) cm",
answer: "A. 2(π + 6) cm",
correctLetter: "A",
correctOption: 1,
},

{
id: "question15",
question: "15. The dimensions of a rectangular tank are 2 m by 7 m by 11 m. If its volume is equal to that of a cylindrical tank of height 4 cm, calculate the base radius of the cylindrical tank. [Take π = 22/7]",
A: "14 m",
B: "7 m",
C: "3¹/₂ m",
D: "1³/₄",
answer: "C. 3¹/₂ cm",
correctLetter: "C",
correctOption: 3,
},

{
id: "question16",
question: "16. In the diagram, O is the centre of the circle. If PQ//RS and ∠ONS = 140° Find the size of ∠POM",
A: "40°",
B: "50°",
C: "60°",
D: "80°",
answer: "A. 40°",
correctLetter: "A",
correctOption: 1,
questionFigure: require(path + "2015-A-Q-16.png"),
imageRatio: 1,
},

{
id: "question17",
question: "17. In the diagram, PTR is a tangent to the circle centre O. If angle TON= 108°, calculate the size of angle PTN.",
A: "132°",
B: "126°",
C: "108°",
D: "102°",
answer: "B. 126°",
correctLetter: "B",
correctOption: 2,
questionFigure: require(path + "2015-A-Q-17.png"),
imageRatio: 1,
},

{
id: "question18",
question: "18. In the diagram, PQ//RT, QR//SU, ∠PQR = 48° and ∠RTS = x. Find the value of x.",
A: "134°",
B: "132°",
C: "96°",
D: "48°",
answer: "B. 132°",
correctLetter: "B",
correctOption: 2,
questionFigure: require(path + "2015-A-Q-18.png"),
imageRatio: 1,
},

{
instruction: "In the diagram, O is the centre of the circle, RT is a diameter, ∠PQT = 33° and ∠TOS = 76°. Use this diagram to answer questions 19 and 20.",
id: "question19",
question: "19. Calculate the value of angle PTR.",
A: "73°",
B: "67°",
C: "57°",
D: "37°",
answer: "C. 57°",
correctLetter: "C",
correctOption: 3,
questionFigure: require(path + "2015-A-Q-19.png"),
imageRatio: 1,
},

{
id: "question20",
question: "20. Find the size of angle PRS.",
A: "76°",
B: "71°",
C: "38°",
D: "33°",
answer: "B. 71°",
correctLetter: "B",
correctOption: 2,
},

{
instruction: "The table shows some values for a linear graph. Use it to answer questions 21 and 22.",
id: "question21",
question: "21. Find the gradient of the line.",
A: "1",
B: "2",
C: "3",
D: "4",
answer: "B. 2",
correctLetter: "B",
correctOption: 2,
questionFigure: require(path + "2015-A-Q-21.png"),
imageRatio: 0.25,
},

{
id: "question22",
question: "22. What is the value of y when x = 2?",
A: "5",
B: "7",
C: "9",
D: "11",
answer: "B. 7",
correctLetter: "B",
correctOption: 2,
},

{
id: "question23",
question: "23. Given that tan x = 2/3, where 0° ≤ x ≤ 90°, find the value of 2 sin x.",
A: "2√13/13",
B: "3√13/13",
C: "4√13/13",
D: "6√13/13",
answer: "C. 4√13/13",
correctLetter: "C",
correctOption: 3,
},

{
id: "question24",
question: "24. PORS is a square. If X is the midpoint of PQ, calculate, correct to the nearest degree, ∠PXS.",
A: "53°",
B: "55°",
C: "63°",
D: "65°",
answer: "C. 63°",
correctLetter: "C",
correctOption: 3,
},

{
id: "question25",
question: "25. The angle of elevation of an aircraft from a point K on the horizontal ground is 30°. If the aircraft is 800 m above the ground, how far is it from K?",
A: "400.00 m",
B: "692.82 m",
C: "923.76 m",
D: "1,600.00 m",
answer: "D. 1,600",
correctLetter: "D",
correctOption: 4,
},

{
id: "question26",
question: "26. The population of students in a school is 810. If this is represented on a pie chart, calculate the sectoral angle for a class of 72 students.",
A: "32°",
B: "45°",
C: "60°",
D: "75°",
answer: "A. 32°",
correctLetter: "A",
correctOption: 1,
},

{
id: "question27",
question: "27. The scores of twenty students in a test are as follows: 44, 47, 48, 49, 50, 51, 52, 53, 53, 54, 58, 59, 60, 61, 63, 65, 67, 70, 73, 75. Find the third quartile.",
A: "62",
B: "63",
C: "64",
D: "65",
answer: "B. 63",
correctLetter: "B",
correctOption: 2,
},

{
id: "question28",
instruction: "The table shows the distribution of the scores of some students in a test.",
question: "28. Calculate the mean score.",
A: "5.6",
B: "6.2",
C: "6.6",
D: "7.0",
answer: "D. 7",
correctLetter: "D",
correctOption: 4,
questionFigure: require(path + "2015-A-Q-28.png"),
imageRatio: 0.23,
},

{
id: "question29",
instruction: "The probabilities that Kebba, Ebou and Omar will hit a target are 2/3, 3/4, 4/5 respectively.",
question: "29.  Find the probability that only Kebba will hit the target",
A: "2/5",
B: "7/60",
C: "1/30",
D: "1/60",
answer: "C. 1/30",
correctLetter: "C",
correctOption: 3,
},

{
id: "question31",
question: "31. Tom will be 25 years old in n years' time. If he is 5 years younger than Bade, find Bade's present age.",
A: "(30 - n) years",
B: "(20 - n) years",
C: "(25 - n) years",
D: "(30 + n) years",
answer: "Z. ",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question32",
question: "32. If (√2 + √3) / √3 is simplified as m + n√6, find the value of (m + n).",
A: "1/3", 
B: "2/3", 
C: "1¹/₃", 
D: "1²/₃",
answer: "Z. ",
correctLetter: "Z",
correctOption: 9, 
},

{
id: "question30",
question: "30. In the diagram, VW//YZ, /WX/ = 6 cm. /XY/ = 16 cm, /YZ/ = 20 cm and /ZX/ = 12 cm. Calculate /VX/",
A: "3 cm",
B: "4 cm",
C: "6 cm",
D: "8 cm",
answer: "D. 8 cm",
correctLetter: "D",
correctOption: 4,
questionFigure: require(path + "2015-A-Q-30.png"),
imageRatio: 1,
},

{
id: "question33",
instruction: "In the diagram, QT and PR are straight lines. ∠ROS = (3n-20°), ∠POT = 2m, ∠SOT = n. ∠POL = m and ∠QOL is a right angle.",
question: "33. Find the value of n.",
A: "35°",
B: "40°",
C: "55°",
D: "60°",
answer: "A. 35°",
correctLetter: "A",
correctOption: 1,
questionFigure: require(path + "2015-A-Q-33.png"),
imageRatio: 1,
},

{
id: "question34",
question: "34. Make k the subject of the relation T = √((Tk -H) / (k - H))",
A: "k = (H(T² - 1)) / (T² - T)",
B: "k = (HT) / (T - 1)²",
C: "k = (H(T² + 1)) / T",
D: "k = (H(T - 1)) / T",
answer: "A. k = H(T2 - 1)/T2-T",
correctLetter: "A",
correctOption: 1,
},

{
id: "question35",
question: "35. Which of the following is used to determine the mode of a grouped data?",
A: "Bar Chart",
B: "Frequency Polygon",
C: "Ogive",
D: "Histogram",
answer: "D. Histogram",
correctLetter: "D",
correctOption: 4,
},

{
id: "question36", 
question: "36. The area of a rhombus is 110 cm2. If the diagonals are 20 cm and (2x + 1) cm long, find the value of x.",
A: "5.0",
B: "4.0",
C: "3.0",
D: "2.5",
answer: "Z. ",
correctLetter: "Z",
correctOption: 9, 
}, 

{
question:  "37. Simplify: ((3x -y) / (xy)) - ((2x + 3y) / (2xy)) + 1/2",
A: "(4x + 5y - xy) / 2xy",
B: "(5y - 4x + xy) / 2xy",
C: "(5x + 4y - xy) / 2xy",
D: "(4x - 5y + xy) / 2xy",
answer: "Z. ",
correctLetter: "Z",
correctOption: 9, 
},


{
id: "question38",
instruction: "38. Illustrate graphically, the solution of y/2 + 1/8 > 5y/8",
question: " ",
A: " ",
B: " ",
C: " ",
D: " ",
answer: "A. ****",
correctLetter: "A",
correctOption: 1,
questionFigure: require(path + "2015-A-Q-38.png"),
imageRatio: 0.5,
},

{
id: "question39",
question: "39. A farmer use 2/5 of his land to grow cassava, 1/3 of the remainder for yams and the rest for maize. Find the part of the land used for maize.",
A: "2/15",
B: "2/5",
C: "2/3",
D: "4/5",
answer: "B. 2/5",
correctLetter: "B",
correctOption: 2,
},

{
id: "question40",
question: "40. The rate of consumption of petrol by a vehicle varies directly as the square of the distance covered. If 4 litres of petrol is consumed on a distance of 15 km, how far would the vehicle go on 9 litres of petrol?",
A: "22¹/₂ km",
B: "30 km",
C: "33³/₄ km",
D: "45 km",
answer: "A. 22¹/₂ km",
correctLetter: "A",
correctOption: 1,
},

{
id: "question41",
question: "41. A trader bought 100 oranges at 5 for N 40.00 and sold them at 20 for N120.00. Find the profit of loss per cent.",
A: "20% profit",
B: "20% loss",
C: "25% profit",
D: "25% loss",
answer: "D. 25% loss",
correctLetter: "D",
correctOption: 4,
},

{
id: "question42",
instruction: "42. Describe the shaded portion in the diagram.",
question: " ",
A: "P'∩ Q ∩ R'",
B: "(P ∩ R)' ∩ Q",
C: "P' ∩ Q ∩ R",
D: "(P ꓴ Q)' ∩ R",
answer: "A. (P ∩ R)' ∩ Q",
correctLetter: "A",
correctOption: 1,
questionFigure: require(path + "2015-A-Q-42.png"),
imageRatio: 1,
},

{
id: "question43",
question: "43. Find the value of p if ¹/₄p + 3q = 10 and 2p - ¹/₃q = 7",
A: "4",
B: "3",
C: "-3",
D: "-4",
answer: "A. 4",
correctLetter: "A",
correctOption: 1,
},

{
id: "question44",
question: "44. Calculate the mean deviation of 5, 3, 0, 7, 2, 1.",
A: "0.0",
B: "2.0",
C: "2.5",
D: "3.0",
answer: "B. 2",
correctLetter: "B",
correctOption: 2,
},

{
id: "question45",
instruction: "In the diagram, the shaded part is a carpet laid in a room with dimensions 3.5 m by 2.2 m leaving a margin of 0.5 m round it. ",
question: "45. Find the area of the margin.",
A: "4.7 m²",
B: "4.9 m²",
C: "5.7 m²",
D: "5.9 m²",
answer: "A. 4",
correctLetter: "A",
correctOption: 1,
questionFigure: require(path + "2015-A-Q-45.png"),
imageRatio: 1,
},

{
id: "question46",
question: "46. Two angles of a pentagon are in the ratio 2:3. The others are 60° each. Calculate the smaller of the two angles.",
A: "72°",
B: "100°",
C: "120°",
D: "144°",
answer: "D. 144°",
correctLetter: "D",
correctOption: 4,
},

{
id: "question47",
question: "47. A letter is selected from the letters of the English alphabet. What is the probability that the letter selected is from the word MATHEMATICS?",
A: "9/13",
B: "11/26",
C: "4/13",
D: "1/6",
answer: "B. 11/26",
correctLetter: "B",
correctOption: 2,
},

{
id: "question48",
question: "48. In a circle of radius r cm, a chord 16√3 cm long is 10 cm from the centre of the circle. Find, correct to the nearest cm, the value of r.",
A: "22 cm",
B: "17 cm",
C: "16 cm",
D: "15 cm",
answer: "B. 17 cm",
correctLetter: "B",
correctOption: 2,
},

{
id: "question49",
instruction: "Consider the following statements: \nX: Locally manufactured tyres are attractive. \nY: Many locally manufactured tyres do not last long. \nDenoting locally manufactured tyres by M, attractive tyres by R and long lasting tyres by L, ",
question: "49. Which of these Venn diagrams illustrates the statements?",
A: " ",
B: " ",
C: " ",
D: " ",
answer: "A. ****",
correctLetter: "A",
correctOption: 1,
questionFigure: require(path + "2015-A-Q-49.png"),
imageRatio: 1,
},

{
id: "question50",
instruction: "In the diagram, OX bisects ∠YXZ and OZ bisects ∠YZX. If ∠XYZ= 68°.",
question: "50. Calculate the value of ∠XOZ.",
A: "68°",
B: "72°",
C: "112°",
D: "124°",
answer: "D. 124°",
correctLetter: "D",
correctOption: 4,
questionFigure: require(path + "2015-A-Q-50.png"),
imageRatio: 1,
},


]