import { SquareRoot, superscript, subscript, BoldText, ItalicText, Fraction, ShortFraction, LongFraction, MixedFraction, Isotopes } from "@/mathnotation"

const path = "@/assets/images/pastquestions-figures/coremathematics/coremathematicsA/coremathematics-"


export const COREMATHEMATICSA2017 = [

{
id: "question1",
question: "1. Express 0.0000407, correct to 2 significant figures.",
A: "0.0",
B: "0.00004",
C: "0.000041",
D: "0.000407",
answer: "C. 0",
correctLetter: "C",
correctOption: 3,
},

{
id: "question2",
question: "2. If x varies inversely as y and y varies directly as z, what is the relationship between x and y.",
A: "x α z",
B: "x α 1/z",
C: "x α z²",
D: "x α 1/z²",
answer: "B. x α 1/z",
correctLetter: "B",
correctOption: 2,
},

{
    id: "question2",
question: "Evaluate: (3¹/₄ × 1³/₅) / (11¹/₃ - 5¹/₃)",
A: "14/15",
B: "13/15",
C: "4/5",
D: "11/15",
},

{
id: "question4",
instruction: "Fig. 1 and Fig. 2 are the addition and multiplication tables respectively in modulo 5.",
question: "4. Use these tables to solve the equation (n ⨂ 4) +3 = 0(mod 5).",
A: "1",
B: "2",
C: "3",
D: "4",
answer: "C. 3",
correctLetter: "C",
correctOption: 3,
questionFigure: require(path + "2017-A-Q-4.png"),
imageRatio: 1,
},

{
id: "question5",
question: "5. The ages of Tunde and Ola are in the ratio 1:2. If the ratio of Ola's age to Musa's age is 4:5, what is the ratio of Tunde's age to Musa's age?",
A: "1:4",
B: "1:5",
C: "2:5",
D: "5:2",
answer: "C. 2:5",
correctLetter: "C",
correctOption: 3,
},

{
id: "question6",
question: "6. If M = {x:3 ≤ x ≤ 8} and N = {x:8 < x ≤ 12}; which of the following is true? \nI.	8 ϵ M ∩ N \nII.	8 ϵ M ꓴ N \nIII.	M ∩ N = ∅",
A: "III only",
B: "I and Il only",
C: "II and III only",
D: "I, II and III",
answer: "A. III only",
correctLetter: "A",
correctOption: 1,
},

{
id: "question7",
question: "7. Given that a = log7 and b= log2, express log35 in terms of a and b.",
A: "a + b + 1",
B: "ab - 1",
C: "a - b + l",
D: "b - a + 1",
answer: "C. a-b+1",
correctLetter: "C",
correctOption: 3,
},

{
id: "question8",
question: "8. If x = 2/3 and y = -6 evaluate xy - y/x",
A: "0",
B: "5",
C: "8",
D: "9",
answer: "B. 5",
correctLetter: "B",
correctOption: 2,
},

{
id: "question9",
question: "9. Solve the equation 1/5x + 1/x = 3",
A: "1/5",
B: "2/5",
C: "3/5",
D: "4/5",
answer: "B. 2/5",
correctLetter: "B",
correctOption: 2,
},

{
id: "question10",
question: "10. A sum of ₦18,100.00 was shared among 5 boys and 4 girls with each boy taking ₦20.00 more than each girl. Find a boy's share.",
A: "₦1,820.00",
B: "₦2,000.00",
C: "₦2,020.00",
D: "₦2,040.00",
answer: "C. ₦2,020",
correctLetter: "C",
correctOption: 3,
},

{
id: "question11",
question: "11. One factor of 7x² + 33x - 10 is",
A: "7x + 5",
B: "x - 2",
C: "7x - 2",
D: "x - 5",
answer: "C. 7x-2",
correctLetter: "C",
correctOption: 3,
},

{
id: "question12",
question: "12. Solve -¹/₄ < ³/₄(3x - 2) < ¹/₂",
A: "5/9 < x < 8/9",
B: "-8/9 < x < 7/9",
C: "-8/9 < x < 5/9",
D: "-7/9 < x < 8/9",
answer: "A. 5/9 < x < 8/9",
correctLetter: "A",
correctOption: 1,
},

{
id: "question13",
question: "13. Simplify 3x - (p - x) - (r - P)",
A: "2x - r",
B: "2x + r",
C: "4x - r",
D: "2x - 2p - r",
answer: "C. 4x-r",
correctLetter: "C",
correctOption: 3,
},

{
id: "question14",
question: "14. An arc of a circle of radius 7.5 cm is 7.5 cm long. Find, correct to the nearest 24 degree, the angle which the arc subtends at the centre of the circle. [Take n = 22/7]",
A: "29°",
B: "57°",
C: "65°",
D: "115°",
answer: "B. 57°",
correctLetter: "B",
correctOption: 2,
},

{
id: "question15",
question: "15. Water flows out of a pipe at a rate of 40n cm3 per second into an empty cylindrical container of base radius 4 cm. Find the height of water in the container after 4 seconds.",
A: "10 cm",
B: "14 cm",
C: "16 cm",
D: "20 cm",
answer: "A. 10 cm",
correctLetter: "A",
correctOption: 1,
},

{
id: "question16",
question: "16. The dimensions of a water tank are 13 cm, 10 cm and 70 cm. If it is half-filled with water, calculate the volume of water in litres.",
A: "4.55 litres",
B: "7.50 litres",
C: "8.10 litres",
D: "9.55 litres",
answer: "A. 4",
correctLetter: "A",
correctOption: 1,
},

{
id: "question17",
question: "17. If the total surface area of a solid hemisphere is equal to its volume, find the radius.",
A: "3.0 cm",
B: "4.5 cm",
C: "5.0 cm",
D: "9.0 cm",
answer: "A. 3",
correctLetter: "A",
correctOption: 1,
},

{
id: "question18",
question: "18. Which of the following is true about parallelograms?",
A: "Opposite angles are supplementary.",
B: "Opposite angles are complementary.",
C: "Opposite angles are equal",
D: "Opposite angles are reflex angles.",
answer: "A. Opposite angles are supplementary",
correctLetter: "A",
correctOption: 1,
},

{
id: "question19",
instruction: "The diagram shows a circle centre O. If ∠STR = 29°, and ∠RST=46°.",
question: "19. Calculate the value of ∠STO.",
A: "12°",
B: "15°",
C: "29°",
D: "34°",
answer: "B. 15°",
correctLetter: "B",
correctOption: 2,
questionFigure: require(path + "2017-A-Q-19.png"),
imageRatio: 1,
},

{
id: "question20",
instruction: "In the diagram, XY is a straight line. ∠POX = ∠POQ and ∠ROY = ∠QOR.",
question: "20. Find the value of ∠P0Q + ∠ROY.",
A: "60°",
B: "90°",
C: "100°",
D: "120°",
answer: "B.  ",
correctLetter: " ",
correctOption: 0,
questionFigure: require(path + "2017-A-Q-20.png"),
imageRatio: 1,
},

{
id: "question21",
instruction: "The diagram shows a circle centre O. If ∠ZYW = 33°",
question: "21. find ∠ZWX.",
A: "33°",
B: "57°",
C: "90°",
D: "100°",
answer: "B. 57°",
correctLetter: "B",
correctOption: 2,
questionFigure: require(path + "2017-A-Q-21.png"),
imageRatio: 1,
},

{
id: "question22",
instruction: "In the diagram, PQ and PS are tangents to the circle centre 0. If ∠PSQ = m, ∠SPQ = n and ∠SQR = 33°, ",
question: "22. find the value of (m + n).",
A: "103°",
B: "123°",
C: "133°",
D: "143°",
answer: "B. 123°",
correctLetter: "B",
correctOption: 2,
questionFigure: require(path + "2017-A-Q-22.png"),
imageRatio: 1,
},

{
id: "question23",
question: "23. Calculate the gradient (slope) of the line joining points (-1, 1) and (2, -2)",
A: "-1",
B: "-½",
C: "½",
D: "1",
answer: "A. -1",
correctLetter: "A",
correctOption: 1,
},

{
id: "question24",
question: "24. If P(2, 3) and Q(2,-2) are points on a graph, calculate the length PQ.",
A: "6 units",
B: "5 units",
C: "4 units",
D: "2 units",
answer: "D. 2 units",
correctLetter: "D",
correctOption: 4,
},

{
id: "question25",
question: "25. A bearing of 320 expressed as a compass bearing is",
A: "N 50° W",
B: "N 40° W",
C: "N 50° E",
D: "N 40° E",
answer: "B. N 40° W",
correctLetter: "B",
correctOption: 2,
},

{
id: "question26",
question: "26. Given that cos30° = sin 60°= √3/2 and sin30° = cos60° = 1/2, evaluate (tan60° - 1)/(1 - tan30°) 1 - tan30°",
A: "√3 - 2",
B: "2-√3",
C: "√3",
D: "-2",
answer: "C. √3",
correctLetter: "C",
correctOption: 3,
},

{
id: "question27",
question: "27. A stationary boat is observed from a height of 100 m. If the horizontal distance between the observer and the boat is 80 m, calculate correct to two decimal places, the angle of depression of the boat from the point of observation.",
A: "36.87°",
B: "39.70°",
C: "51.34°",
D: "53.13°",
answer: "C. 51",
correctLetter: "C",
correctOption: 3,
},

{
id: "question28",
instruction: "28. The average age of a group of 25 girls is 10 years. If one girl, aged 12 years and 4 months joins the group,",
question: "find, correct to one decimal place, the new average age of the group.",
A: "10.1 years",
B: "9.3 years",
C: "8.7 years",
D: "8.3 years",
answer: "A. 10",
correctLetter: "A",
correctOption: 1,
},

{
id: "question29",
instruction: "The bar chart shows the statistics of the number of passes and failures in an examination in a school from 2001 to 2004.",
question: "29. What is the ratio of the total number of passes to the total number of failures?",
A: "60:13",
B: "10:3",
C: "5:1",
D: "40:13",
answer: "A. 60:13",
correctLetter: "A",
correctOption: 1,
questionFigure: require(path + "2017-A-Q-29.png"),
imageRatio: 1,
},

{
    id: "question30",
    instruction: "The table gives the distribution of marks N obtained by a number of pupils in a class test. Use this information to answer questions 30 P and 31.",
question: "30. Find the median of the distribution.",
A: "4",
B: "3",
C: "2",
D: "1",
answer: "B. 3",
correctLetter: "B",
correctOption: 2,
questionFigure: require(path + "2017-A-Q-30.png"),
imageRatio: 0.23,
},

{
id: "question31",
question: "31. Find the first quartile.",
A: "1.0",
B: "1.5",
C: "2.0",
D: "2.5",
answer: "C. 2",
correctLetter: "C",
correctOption: 3,
},

{
id: "question32",
question: "32. In a class of 45 students, 28 offer Chemistry and 25 offers Biology. If each student offers at least one of the two subjects, calculate the probability that a student selected at random from the class offers Chemistry only.",
A: "2/9",
B: "4/9",
C: "5/9",
D: "7/9",
answer: "B. 4/9",
correctLetter: "B",
correctOption: 2,
},

{
id: "question33",
question: "33. In what number base was the addition 1 + n = 100, where n>0, done?",
A: "n-1",
B: "n",
C: "n+1",
D: "n+1",
answer: "C. n+1",
correctLetter: "C",
correctOption: 3,
},

{
id: "question34",
question: "34. Simplify √2(√6 + 2√2) - 2√3.",
A: "4",
B: "√3+4",
C: "4√2",
D: "4√3+4",
answer: "A. 4",
correctLetter: "A",
correctOption: 1,
},

{
id: "question35",
question: "35. Three exterior angles of a polygon are 30°, 40° and 60°. If the remaining exterior angles are 46° each, name the polygon.",
A: "Decagon",
B: "Nonagon",
C: "Octagon",
D: "Hexagon",
answer: "C. Octagon",
correctLetter: "C",
correctOption: 3,
},

{
id: "question36",
instruction: "In the diagram, NQ//TS, < RTS= 50° and < PRT= 100°. ",
question: "36. Find the value of < NPR.",
A: "110°",
B: "130°",
C: "140°",
D: "150°",
answer: "B. 130°",
correctLetter: "B",
correctOption: 2,
questionFigure: require(path + "2017-A-Q-36.png"),
imageRatio: 1,
},

{
id: "question37",
question: "37. Simplify the expression (a²b⁴ - b⁴a²) / (ab(a + b))",
A: "a² - b²",
B: "b² - a²",
C: "a²b - ab²",
D: "ab² - a²b",
answer: "D. ab² - a²b",
correctLetter: "D",
correctOption: 4,
},

{
id: "question38",
question: "38. Find the 6 term of the sequence:",
A: "-1/3",
B: "-1/5",
C: "-1/15",
D: "-11/5",
answer: "A. -1/3",
correctLetter: "A",
correctOption: 1,
},

{
id: "question39",
question: "39. The diagonal of a square is 60 cm. Calculate its perimeter.",
A: "20√2",
B: "40√2",
C: "90√2",
D: "120√2",
answer: "B. 40√2",
correctLetter: "B",
correctOption: 2,
},

{
id: "question40",
question: "40. The roots of a quadratic equation are -1/2 and 2/3 . Find the equation.",
A: "6x² - x + 2 = 0",
B: "6x² - x - 2 = 0",
C: "6x² + x - 2 = 0",
D: "6x² + x + 2 = 0",
answer: "A. 6x² - x + 2 = 0",
correctLetter: "A",
correctOption: 1,
},

{
id: "question41",
question: "41. Make x the subject of the relation d = √(6/x - y/2)",
A: "x = 6/d² + 12/y",
B: "x =	12/(d²-y)",
C: "x = 12/y – 2d²",
D: "x =	12/(d²+ y)",
answer: "D. x = 12/d² + y",
correctLetter: "D",
correctOption: 4,
},

{
id: "question42",
question: "42. Consider the statements: \np: It is hot. \nq: It is raining \nWhich of the following symbols correctly represents the statement? 'It is raining if and only if it is cold'?",
A: "p⇔~q",
B: "q⇔p",
C: "~p⇔~q",
D: "q⇔~p",
answer: "D. q⇔~p",
correctLetter: "D",
correctOption: 4,
},

{
id: "question43",
question: "43. Given that t = 2-x, find 2x+1 in terms of t.",
A: "2/t",
B: "t/2",
C: "1/2t",
D: "2t",
answer: "A. 2/t",
correctLetter: "A",
correctOption: 1,
},

{
id: "question44",
instruction: "44. Find the value of m in the diagram",
question: " ",
A: "72°",
B: "68°",
C: "44°",
D: "34°",
answer: "C. 44°",
correctLetter: "C",
correctOption: 3,
questionFigure: require(path + "2017-A-Q-44.png"),
imageRatio: 1,
},

{
id: "question45",
question: "45. Two bottles are drawn with replacement from a crate containing 8 Coke, 12 Fanta and 4 Sprite bottles what is the probability that the first is Coke and the second is not Coke?",
A: "1/12",
B: "1/6",
C: "2/9",
D: "3/8",
answer: "Z. zzzzzzzzzzzzz",
correctLetter: "Z. ",
correctOption: 9,
}, 

{
id: "question46",
question: "46. If the simple interest on a certain amount of money saved in a bank for 5 years at 24% per annum is N 500.00, calculate the total amount due after 6 years at the same rate.",
A: "₦ 2,500.00",
B: "₦ 2,600.00",
C: "₦ 4,500.00",
D: "₦ 4,600.00",
},

{
 id: "question47",
question: "47. Calculate the variance of 2, 3, 3, 4, 5, 5, 5, 7,7 and 9.",
A: "2.2",
B: "3.4",
C: "4.0",
D: "4.2",
}, 

{
id: "question48",
question: "48. A circular pond of radius 4m has a path of width 2.5 m round it. Find, correct to 2 decimal places, the area of the path. [Take n = 22/7]",
A: "7.83 m²",
B: "32.29 m²",
C: "50.29 m²",
D: "50.29 m²",
answer: "D. 50",
correctLetter: "D",
correctOption: 4,
},

{
id: "question49",
instruction: "The graph of y = ax² + bx + c is shown in the diagram. Find the minimum value of y. \nThe graph of y = ax² + bx + c is shown in the diagram.",
question: "49. Find the minimum value of y.",
A: "-2.0",
B: "-2.1",
C: "-2.3",
D: "-2.5",
answer: "C. -2",
correctLetter: "C",
correctOption: 3,
questionFigure: require(path + "2017-A-Q-49.png"),
imageRatio: 1,
},

{
id: "question50",
instruction: "In the diagram, RP is a diameter of the circle RSP, RP is produced to T and TS is a tangent to the circle at S. If < PRS = 24°, ",
question: "50. calculate the value of < STR.",
A: "24°",
B: "42°",
C: "48°",
D: "66°",
answer: "B. 42°",
correctLetter: "B",
correctOption: 2,
questionFigure: require(path + "2017-A-Q-50.png"),
imageRatio: 1,
},

]