import { SquareRoot, superscript, subscript, BoldText, ItalicText, Fraction, ShortFraction, LongFraction, MixedFraction, Isotopes } from "@/mathnotation"

const path = "@/assets/images/pastquestions-figures/coremathematics/coremathematicsA/coremathematics-"


export const COREMATHEMATICSA2004 = [

{
id: "question1",
question: "1. Express 0.00096 in standard form.",
A: "9.6 x 10⁻⁵",
B: "9.6 x 10⁻⁴",
C: "9.6 x 10⁻³",
D: "9.6 x 10³",
answer: "B. 9",
correctLetter: "B",
correctOption: 2,
},

{
id: "question2",
question: "2. Express 7.0959, correct to three significant figures.",
A: "7.095",
B: "7.0965",
C: "7.09",
D: "7.10",
answer: "D. 7",
correctLetter: "D",
correctOption: 4,
},

{
id: "question3",
question: "3. If μ ={3, 6, 9, 12, 15, 18, 21, 24, 27} \nN= {3, 6, 9, 12, 15} and \nM= {3, 9, 27}, find (N U M)' where N, M ∈ μ",
A: "{3,6,9, 12, 15}",
B: "{3, 6, 9, 12, 15, 27}",
C: "{6, 12, 15, 27}",
D: "{18, 21, 24}",
answer: "D. {18, 21, 24}",
correctLetter: "D",
correctOption: 4,
},

{
id: "question4",
question: "4. Consider the following statements: \nP: Mercy studies hard. \nQ: Mercy passes her examination. \nIf P => Q, which of the following is a valid conclusion from the statements?",
A: "If Mercy passes her examination, then she had studied hard.",
B: "If Mercy does not pass her examination, then she had not studied hard.",
C: "If Mercy does not study hard, then she will not pass her examination",
D: "If Mercy does not study hard, then she will pass her examination.",
answer: "B. If Mercy does not pass her examination, then she had not studied hard",
correctLetter: "B",
correctOption: 2,
},

{
id: "question5",
question: "5. Arrange in ascending order of magnitude 7/75, 2/5 and 1/3",
A: "2/5, 1/3, 7/75",
B: "1/3, 7/75, 2/5",
C: "1/3, 2/5, 7/75",
D: "7/7, 51/3, 2/5",
answer: "D. 7/7, 51/3, 2/5",
correctLetter: "D",
correctOption: 4,
},

{
id: "question6",
instruction: "6. Which of the following sets is illustrated on the number line below?",
question: " ",
A: "{x:-3 < x < 2}",
B: "{x:-3 ≤ x < 2}",
C: "x :-3 < x ≤ 2}",
D: "{x:-3 ≤ x ≤2}",
answer: "B. {x:-3 ≤ x < 2}",
correctLetter: "B",
correctOption: 2,
questionFigure: require(path + "2004-A-Q-6.png"),
imageRatio: 0.27,
},

{
id: "question7",
question: "7. Which base five numeral is equivalent to (4 x 53) + (0 x 52) + (2x51) + (2 x 5o) base ten?",
A: "402five",
B: "422five",
C: "4022five",
D: "4220five",
answer: "C. 4022five",
correctLetter: "C",
correctOption: 3,
},

{
id: "question8",
question: "8. Simplify 3/√2 − 1/√2",
A: "√2/2",
B: "√2",
C: "⁵/₄√2",
D: "2√2",
answer: "B. √2",
correctLetter: "B",
correctOption: 2,
},

{
id: "question9",
question: "9. If t = p² - 34, calculate the value of t, when p = 4 and q = 9.",
A: "-11",
B: "-43",
C: "11",
D: "43",
answer: "A. -11",
correctLetter: "A",
correctOption: 1,
},

{
id: "question10",
question: "10. Find the range of values of x for which (5 − x) / 3 + 2 < (x − 2)/2",
A: "x < 12/5",
B: "x < 9/2",
C: "x > 28/ 5",
D: "x < 8",
answer: "C. x > 28/5",
correctLetter: "C",
correctOption: 3,
},

{
id: "question11",
question: "11. A meat seller bought 250 kg of meat for $224,000.00. At what price per kg should he retail it in order to make a profit of 25%?",
A: "¢672.00",
B: "¢1,000.00",
C: "¢1,120.00",
D: "¢1,500.00",
answer: "C. ¢1,120",
correctLetter: "C",
correctOption: 3,
},

{
id: "question12",
question: "12. A man invested a certain amount of money in a bank at a simple interest rate of 5% At the end of the year, his total amount in the bank was $840,000.00. per annum. How much did he invest in the bank?",
A: "¢680,000.00",
B: "¢720,000.00",
C: "¢760,000.00",
D: "¢800,000.00",
answer: "D. ¢800,000",
correctLetter: "D",
correctOption: 4,
},

{
id: "question13",
question: "13. Factorise (x + 6)² - 36x²",
A: "(7x - 6)(6 - 5x)",
B: "(7x + 6)(6x - 5)",
C: "(7x + 6)(6 - 5x)",
D: "(7x + 6)(6 + 5x)",
answer: "C. (7x+6)(6-5x)",
correctLetter: "C",
correctOption: 3,
},

{
id: "question14",
question: "14. Find the equation of the line whose gradient is -½ and which passes through the point (7,-2).",
A: "y + 2x-3 = 0",
B: "y + 2x + 3 = 0",
C: "2y + x-3 = 0",
D: "2y + x + 3 = 0",
answer: "C. 2y+x-3 = 0",
correctLetter: "C",
correctOption: 3,
},

{
id: "question15",
question: "15. A circle has a radius of 9 cm. The A. expression 18 cm represents the",
A: "area",
B: "chord",
C: "circumference",
D: "diameter",
answer: "C. circumference",
correctLetter: "C",
correctOption: 3,
},

{
id: "question16",
question: "16. The number of faces of a hexagonal prism is",
A: "7",
B: "8",
C: "9",
D: "12",
answer: "B. 8",
correctLetter: "B",
correctOption: 2,
},

{
id: "question17",
question: "17. The interior angle of a regular polygon is 108°. How many sides has the polygon?",
A: "5",
B: "6",
C: "7",
D: "8",
answer: "A. 5",
correctLetter: "A",
correctOption: 1,
},

{
id: "question18",
question: "18. If x =[−3, 2] and y = [4, -1] calculate 3x - y",
A: "[−13, 7]",
B: "[−13, 5]",
C: "[−5, 7]",
D: "[5, 5]",
answer: "A. [−13, 7]",
correctLetter: "A",
correctOption: 1,
},

{
id: "question19",
question: "19. If x is an acute angle such that cos x = find sin x.",
A: "12/13",
B: "8/13",
C: "5/8",
D: "5/12",
answer: "A. 12/13",
correctLetter: "A",
correctOption: 1,
},

{
id: "question20",
question: "20. Find the value of t in the equation 3 = 42/t - 18",
A: "t = 0.5",
B: "t = 2.0",
C: "t = 2.1",
D: "t = 5.0",
answer: "B. t = 2",
correctLetter: "B",
correctOption: 2,
},

{
id: "question21",
instruction: "21. Calculate the value of x in the diagram above.",
question: " ",
A: "10°",
B: "20°",
C: "30°",
D: "40°",
answer: "B. 20°",
correctLetter: "B",
correctOption: 2,
questionFigure: require(path + "2004-A-Q-21.png"),
imageRatio: 1,
},

{
id: "question22",
instruction: "22. A boy walks a distance of 5 km on a bearing of 240°. Which of the following diagrams shows the direction?",
question: " ",
A: " ",
B: " ",
C: " ",
D: " ",
answer: "D. ***",
correctLetter: "D",
correctOption: 4,
questionFigure: require(path + "2004-A-Q-22.png"),
imageRatio: 1,
},

{
id: "question23",
question: "23. The point (7, 4) lies on the line whose equation is",
A: "y-2x =1",
B: "4x-2y = 38",
C: "4x-3y =16",
D: "2x-3y = 4",
answer: "C. 4x-3y =16",
correctLetter: "C",
correctOption: 3,
},

{
id: "question24",
question: "24. For what value of x is y not defined in the relation y = (2x − 5) / (3x + 2)",
A: "x = 5/2",
B: "x = 2/3",
C: "x = -5/2",
D: "x = -2/3",
answer: "D. x = -2/3",
correctLetter: "D",
correctOption: 4,
},

{
id: "question25",
question: "25. If 15 - px - x² = 0, find p, when x = 3.",
A: "-8",
B: "-2",
C: "2",
D: "8",
answer: "C. 2",
correctLetter: "C",
correctOption: 3,
},

{
id: "question26",
instruction: "26. Which of the following describes accurately the construction below?",
question: " ",
A: "The mediator of MN",
B: "The angle bisector of angle MPN",
C: "The perpendicular through P to MN",
D: "The line through P parallel to MN",
answer: "C. The perpendicular through P to MN",
correctLetter: "C",
correctOption: 3,
questionFigure: require(path + "2004-A-Q-26.png"),
imageRatio: 1,
},

{
id: "question27",
question: "27. Find the image of the point W(2,-3) under a reflection in the line y= -1.",
A: "(2, -1)",
B: "(2, 1)",
C: "(2, 3)",
D: "(2, 4)",
answer: "B. (2, 1)",
correctLetter: "B",
correctOption: 2,
},

{
id: "question28",
question: "28. A rectangle has a perimeter of 54 cm. If the ratio of the length of the rectangle to the width is 5:4, what is the length of the rectangle?",
A: "12 cm",
B: "15 cm",
C: "24 cm",
D: "27 cm",
answer: "B. 15 cm",
correctLetter: "B",
correctOption: 2,
},

{
id: "question29",
question: "29. Make c the subject of the relation (ac + d) / e = p",
A: "c = (e𝑝 − 𝑑) / 𝑎",
B: "c = (𝑑 − e𝑝) / 𝑎",
C: "c = (e𝑝 + 𝑑) / 𝑎",
D: "c = e𝑝/d - a",
answer: "A. c = (ep-d)/a",
correctLetter: "A",
correctOption: 1,
},

{
id: "question30",
question: "30. The mean of six numbers is 10. When another number is added the new mean is 9. Find the number added.",
A: "3",
B: "6",
C: "9.5",
D: "9.9",
answer: "B. 6",
correctLetter: "B",
correctOption: 2,
},

{
id: "question30",
question: "30. The mean of six numbers is 10. When another number is added the new mean is 9. Find the number added.",
A: "3",
B: "6",
C: "9.5",
D: "9.9",
answer: "B. 6",
correctLetter: "B",
correctOption: 2,
},

{
instruction: "The pie chart shows Ghana's exports in a particular year. The total value of exports amounted to ¢301,500.00 \nUse it to answer Questions 31 and 32.",
id: "question31",
question: "31. Find the value of cocoa exported during the year.",
A: "¢50,250,000.00",
B: "¢100,500,000.00",
C: "¢201,000,000.00",
D: "¢217,750,000.00",
answer: "C. ¢201,000,000",
correctLetter: "C",
correctOption: 3,
questionFigure: require(path + "2004-A-Q-31.png"),
imageRatio: 1,
},

{
id: "question32",
question: "32. What percentage of the total exports was timber?",
A: "5.56%",
B: "8.33%",
C: "11.12%",
D: "16.67%",
answer: "A. 5",
correctLetter: "A",
correctOption: 1,
},

{
id: "question33",
question: "33. If P' is the image of P(-2, 4) under a clockwise rotation through 270 about the origin, find the coordinates of P.",
A: "(4,2)",
B: "(4,-2)",
C: "(-4, 2)",
D: "(-4,-2)",
answer: "D. (-4,-2)",
correctLetter: "D",
correctOption: 4,
},

{
id: "question34",
question: "34. A man starts from a point S and walks 1000 m on a bearing of 025°. How far North is he from his starting point?",
A: "423 m",
B: "466m",
C: "906 m",
D: "1104 m",
answer: "C. 906 m",
correctLetter: "C",
correctOption: 3,
},

{
id: "question35",
question: "35. Evaluate log₁₀6 + log₁₀45 - log₁₀ 27.",
A: "0",
B: "1",
C: "1.5",
D: "2",
answer: "B. 1",
correctLetter: "B",
correctOption: 2,
},

{
id: "question36",
question: "36. Find the value of x in the equation 8ˣ = 32",
A: "1/4",
B: "3/5",
C: "5/3",
D: "4",
answer: "C. 5/3",
correctLetter: "C",
correctOption: 3,
},

{
id: "question37",
question: "37. Three business partners Amos, Ben and Cudjoe, share a profit of ¢l1,000,000.00. Amos takes 30% of the profit and the remainder is shared between Ben and Cudjoe in the ratio 4: 3 respectively. How much did Ben receive?",
A: "¢3,000,000.00",
B: "¢3,300,000.00",
C: "¢4,000,000.000",
D: "¢4,400,000.00",
answer: "D. ¢4,400,000",
correctLetter: "D",
correctOption: 4,
},

{
id: "question38",
instruction: "38. Find the rule of mapping",
question: " ",
A: "y= ½ x + 1",
B: "y = x + ½",
C: "y= ½ x",
D: "y = x+1/2",
answer: "D. y = (x+1)/2",
correctLetter: "D",
correctOption: 4,
questionFigure: require(path + "2004-A-Q-38.png"),
imageRatio: 0.35,
},

{
id: "question39",
question: "39. Solve simultaneously the equations 3x + 5y = 21 and 7x - 2y = 8",
A: "x = -2, y = -3",
B: "x = -2, y = 3",
C: "x = 2, y = -3",
D: "x = 2, y = 3",
answer: "D. x = 2,y =3",
correctLetter: "D",
correctOption: 4,
},

{
id: "question40",
question: "40. The sides of a triangle are p cm, (p + 7) cm and (p + 8) cm. Find the length of the hypotenuse if its perimeter is 30 cm.",
A: "5 cm",
B: "6 cm",
C: "12 cm",
D: "13 cm",
answer: "D. 13 cm",
correctLetter: "D",
correctOption: 4,
},

{
id: "question41",
question: "41. A cylinder has diameter 14 cm and height lcm. Calculate the curved surface area of the cylinder. (Take π= 22/7)",
A: "484 cm²",
B: "792 cm²",
C: "968 cm²",
D: "1,694 cm²",
answer: "A. 484 cm²",
correctLetter: "A",
correctOption: 1,

},

{
id: "question42",
instruction: "42. In the diagram O is- the centre of circle MNPQ and angle MNQ = 57. ",
question: "Find the value of y.",
A: "114°",
B: "123°",
C: "237°",
D: "246°",
answer: "D. 246°",
correctLetter: "D",
correctOption: 4,
questionFigure: require(path + "2004-A-Q-42.png"),
imageRatio: 1.0,
},

{
id: "question43",
question: "43. A rhombus has sides of length 13 cm and one of its diagonals is 24 cm long. Find the area of the rhombus.",
A: "120 cm²",
B: "156 cm²",
C: "169 cm²",
D: "240 cm²",
answer: "A. 120 cm²",
correctLetter: "A",
correctOption: 1,
},

{
id: "question44",
instruction: "",
question: "44. Find the value of x in the diagram",
A: "75°",
B: "85°",
C: "95°",
D: "177°",
answer: "B. 85°",
correctLetter: "B",
correctOption: 2,
questionFigure: require(path + "2004-A-Q-44.png"),
imageRatio: 1,
},

{
id: "question45",
question: "45. The median of five numbers is 15. If the numbers are in the ratio 2: 4:5:7: 8, respectively, find the first number.",
A: "3",
B: "5.2",
C: "6",
D: "7.5",
answer: "C. 6",
correctLetter: "C",
correctOption: 3,
},

{
id: "question46",
instruction: "In the figure QRS is an equilateral triangle and ORT is an isosceles triangle. If angle QRT = 47, ",
question: "46. what is the value of y.",
A: "13°",
B: "23°",
C: "30°",
D: "47°",
answer: "A. 13°",
correctLetter: "A",
correctOption: 1,
questionFigure: require(path + "2004-A-Q-46.png"),
imageRatio: 1,
},

{
id: "question47",
question: "47. Mansa chooses a number at random from to 1 to 20 inclusive. What is the probability that the number is divisible by 3?",
A: "3/20",
B: "3/10",
C: "1/5",
D: "1/4",
answer: "B. 3/10",
correctLetter: "B",
correctOption: 2,
},

{
id: "question48",
question: "48. Find the volume of a cylindrical tin of radius 1.25 cm and height 3.5 cm. (Take π= 22/7)",
A: "13.6 cm³",
B: "17.2 cm³",
C: "34.4 cm³",
D: "68.8 cm³",
answer: "B. 17",
correctLetter: "B",
correctOption: 2,
},

{
id: "question49",
question: "49. M is the mid-point of JK. If the o coordinates of J is (-5, 4) and M is (-2, 1), find the coordinates of K.",
A: "(-2, 1)",
B: "(-1, -2)",
C: "(-1, 2)",
D: "(1, -2)",
answer: "D. (1,-2)",
correctLetter: "D",
correctOption: 4,
},

{
id: "question50",
question: "50. Which of the following vectors is parallel to [−4, 12]",
A: "[−1, -3]",
B: "[-3, 1]",
C: "[-1, 3]",
D: "[3, -1]",
answer: "C. [−1, 3]",
correctLetter: "C",
correctOption: 3,
},

]