export const CHRISTIANRELIGIOUSSTUDIESA2018 = [

{
id: "question1",
question:  "1. God created man and asked him to dominate all the following except _________",
A: "Fish of the sea",
B: "Spirit of the earth",
C: "Birds of the air",
D: "Creeping animals",
answer: "B. Spirit of the earth",
correctLetter: "B",
correctOption: 2,
},

{
id: "question2",
question:  "2. Adam called Eve woman because she was _________",
A: "A resemblance of man",
B: "A helper of man",
C: "Mother of mankind",
D: "Made out of man",
answer: "D. Made out of man",
correctLetter: "D",
correctOption: 4,
},

{
id: "question3",
question:  "3. Which of the following experiences did Joseph not go through? He was __________",
A: "Sold into slavery",
B: "Sentenced and Imprisoned",
C: "Cast into a pit",
D: "Molested and Raped",
answer: "D. Molested and Raped",
correctLetter: "D",
correctOption: 4,
},

{
id: "question4",
question:  "4. Joseph earned his brother’s hatred because _______",
A: "He carried ill report of them to Jacob",
B: "He was a dreamer",
C: "Jacob had more love for Joseph",
D: "He did not join them to shepherd the flock",
answer: "B. He was a dreamer",
correctLetter: "B",
correctOption: 2,
},

{
id: "question5",
question:  "5. As Joseph revealed himself to his brothers, he told them that God allowed him to be sold into slavery so as to______________",
A: "Stop the Famine",
B: "Preserve Life",
C: "Punish them",
D: "Seek revenge",
answer: "B. Preserve Life",
correctLetter: "B",
correctOption: 2,
},

{
id: "question6",
question:  "6. The parents of Moses did the following to ensure his survival except__________",
A: "Casting him into a river",
B: "Hiding him for three months",
C: "Putting him in a padded basket",
D: "His sister watching him",
answer: "D. His sister watching him",
correctLetter: "D",
correctOption: 4,
},

{
id: "question7",
question:  "7. The Parents of Moses belonged to the tribe of__________",
A: "Judah",
B: "Benjamin",
C: "Levi",
D: "Ephraim",
answer: "C. Levi",
correctLetter: "C",
correctOption: 3,
},

{
id: "question8",
question:  "8. These are your gods, O Israel, who brought you up out of the land of Egypt! This statement above was a manifestation of Israel's____________",
A: "Unfaithfulness",
B: "Immorality",
C: "Adultery",
D: "Idolatry",
answer: "D. Idolatry",
correctLetter: "D",
correctOption: 4,
},

{
id: "question9",
question:  "9. Before Joshua's appointment as a successor to Moses, he was a___________",
A: "Commander of the army",
B: "Servant in the temple",
C: "Minister to Moses",
D: "Counselor to the Israelites",
answer: "A. Commander of the army",
correctLetter: "A",
correctOption: 1,
},

{
id: "question10",
question:  "10. Deborah, a prophetess who was a judge in Israel was the wife of _____________",
A: "Barak",
B: "Lappidoth",
C: "Joshua",
D: "Sisera",
answer: "B. Lappidoth",
correctLetter: "B",
correctOption: 2,
},

{
id: "question11",
question:  "11. The two sons of Eli were_______________",
A: "Hophni and Phinehas",
B: "Phinehas and Joel",
C: "Joel and Abijah",
D: "Hophni and Abijah",
answer: "A. Hophni and Phinehas",
correctLetter: "A",
correctOption: 1,
},

{
id: "question12",
question:  "12. The Sons of Eli were worthless because they______",
A: "Stole offering from the Lord's house",
B: "Treated the Lord's offering with Contempt",
C: "Seized the Lord's offering from the temple",
D: "Took bribes and perverted justice",
answer: "D. Took bribes and perverted justice",
correctLetter: "D",
correctOption: 4,
},

{
id: "question13",
question:  "13. 'It is the LORD; let him do what seems good to him' This statement by Eli shows that God____________",
A: "Makes the final decision",
B: "Knows Everything",
C: "Is Impartial",
D: "Is the Alpha and Omega",
answer: "A. Makes the final decision",
correctLetter: "A",
correctOption: 1,
},

{
id: "question14",
question:  "14. The direct consequence of the behavior of the sons of Samuel was___________",
A: "Their death in battle",
B: "That Israel rejected God",
C: "The Capture of the ark of God",
D: "Israel's request for a King",
answer: "D. Israel's request for a King",
correctLetter: "D",
correctOption: 4,
},

{
id: "question15",
question:  "15. The elders of Israel went to Samuel to request for a King at___________",
A: "Jerusalem",
B: "Gilgal",
C: "Ramah",
D: "Ziph",
answer: "C. Ramah",
correctLetter: "C",
correctOption: 3,
},

{
id: "question16",
question:  "16. Why did God Command Saul to entirely destroy Amalek?",
A: "They were serving foreign gods",
B: "They opposed the Israelites on the way",
C: "They refuse male circumcision",
D: "They offered false worship to God",
answer: "B. They opposed the Israelites on the way",
correctLetter: "B",
correctOption: 2,
},

{
id: "question17",
question:  "17. God repented that He made Saul King because he__________-",
A: "Utterly destroyed the Amalekites",
B: "Told the Kenites to depart from Amalek",
C: "C Did not perform God's commandments",
D: "D Set up a monument at carmel",
answer: "C. Did not perform God's commandments",
correctLetter: "C",
correctOption: 3,
},

{
id: "question18",
question:  "18. God sent an evil spirit to torment Saul because_______",
A: "He wanted to bring David into Saul's life",
B: "Saul had disobeyed Samuel",
C: "The Lord's spirit had departed from him",
D: "He wanted Saul to enjoy the sound of lyre",
answer: "C. The Lord's spirit had departed from him",
correctLetter: "C",
correctOption: 3,
},

{
id: "question19",
question:  "19. Which of the following people was ready to strike king Saul at the wilderness of Zuph?",
A: "Abishai",
B: "Abner",
C: "Ahimelech",
D: "Joab",
answer: "A. Abishai",
correctLetter: "A",
correctOption: 1,
},

{
id: "question20",
question:  "20. David spares Saul's life at Ziph because David_________",
A: "Recognized the rules of engagement",
B: "Was a man after God's heart",
C: "Wanted to rebuke Abner's negligence",
D: "Recognized Saul as God's anointed",
answer: "D. Recognized Saul as God's anointed",
correctLetter: "D",
correctOption: 4,
},

{
id: "question21",
question:  "21. Prophet Nathan named David Bathsheba's second child________",
A: "Solomon",
B: "Jedidiah",
C: "Absalom",
D: "Adonijah",
answer: "B. Jedidiah",
correctLetter: "B",
correctOption: 2,
},

{
id: "question22",
question:  "22. At Gibeon, Solomon was promised all the following except ________",
A: "Wise and Discerning Mind",
B: "The life of his enemies",
C: "Long and Fulfilling Life",
D: "Riches and Honour",
answer: "B. The life of his enemies",
correctLetter: "B",
correctOption: 2,
},

{
id: "question23",
question:  "23. Elijah Proclaimed drought in Israel as a punishment for ________",
A: "Persecuting the prophets of God",
B: "Worshiping Baal",
C: "Ahab marrying Jezebel",
D: "The Murder of Naboth",
answer: "B. Worshiping Baal",
correctLetter: "B",
correctOption: 2,
},

{
id: "question24",
question:  "24. The contest between Elijah and the Baal Prophets took place on/at_______________",
A: "Mount Sinai",
B: "Mount Carmel",
C: "Brook Cherith",
D: "Brook Kishon",
answer: "B. Mount Carmel",
correctLetter: "B",
correctOption: 2,
},

{
id: "question25",
question:  "25. When Nehemiah received the report about the ruin in Jerusalem, he __________",
A: "Wept, fasted and prayed",
B: "put on sack clothes",
C: "Refused to serve Artaxerxes",
D: "Confronted the King",
answer: "A. Wept, fasted and prayed",
correctLetter: "A",
correctOption: 1,
},

{
id: "question26",
question:  "26. King Nebuchadnezzar issued a decree that no one should speak against the God of Shadrach, Meshach and Abednego because_________",
A: "He is God who destroys",
B: "No other god could deliver like him",
C: "He listens to the cry of the afflicted",
D: "He easily performs miracles",
answer: "B. No other god could deliver like him",
correctLetter: "B",
correctOption: 2,
},

{
id: "question27",
question:  "27. Before Amos became a prophet, he was a _______",
A: "Judge",
B: "Seer",
C: "Tent Maker",
D: "Farmer",
answer: "D. Farmer",
correctLetter: "D",
correctOption: 4,
},

{
id: "question28",
question:  "28. The name of Hosea's daughter 'Not Pitied' means God will_______",
A: "Punish the house of Jehu for the blood of Israel",
B: "No longer have the pity on the house of Israel",
C: "No longer have pity on the house of Judah",
D: "Deny Judah his protective presence",
answer: "B. No longer have the pity on the house of Israel",
correctLetter: "B",
correctOption: 2,
},

{
id: "question29",
question:  "29. Jesus was baptized by John in order to_______",
A: "Confirm John's power",
B: "Please the Jews",
C: "Fulfill all righteousness",
D: "Identify with the sinners",
answer: "C. Fulfill all righteousness",
correctLetter: "C",
correctOption: 3,
},

{
id: "question30",
question:  "30. He will give his Angels charge of you.....and on their hands they will bear you up What reply was given on this occasion?",
A: "You shall not tempt the Lord your God",
B: "Man shall not live by bread alone",
C: "You shall worship the Lord your God",
D: "Only God shall you serve",
answer: "A. You shall not tempt the Lord your God",
correctLetter: "A",
correctOption: 1,
},

{
id: "question31",
question:  "31. Before the call of James and John. Jesus met them helping their Father to__________",
A: "Catch fish in the sea",
B: "Mend the fishing nets",
C: "Collect Tax",
D: "Bury the dead",
answer: "B. Mend the fishing nets",
correctLetter: "B",
correctOption: 2,
},

{
id: "question32",
question:  "32. Whoever does not bear his own cross and come after me, cannot be my disciple This statement means____________",
A: "Discipleship demands total commitment",
B: "A Disciple must carry his cross",
C: "A Disciple must bear his problems alone",
D: "Death on the cross awaits any true Disciple",
answer: "C. A Disciple must bear his problems alone",
correctLetter: "C",
correctOption: 3,
},

{
id: "question33",
question:  "33. The response to Peter's question, Lord how often shall my brother sin against me and i forgive him? Meant that forgiveness is ___________",
A: "Unconditional",
B: "Limitless",
C: "Conditional",
D: "Countable",
answer: "B. Limitless",
correctLetter: "B",
correctOption: 2,
},

{
id: "question34",
question:  "34. The prayer of Jesus at Gethsemane shows that he _________",
A: "Was in severe agony",
B: "Wanted to escape death",
C: "Needed the support of his disciples",
D: "Had been abandoned by God",
answer: "D. Had been abandoned by God",
correctLetter: "D",
correctOption: 4,
},

{
id: "question35",
question:  "35. Which of these did not happen immediately Jesus gave up the ghost?",
A: "The guards were scared and fled",
B: "The Saints were risen",
C: "The Curtain divided into two",
D: "The Earth shook",
answer: "A. The guards were scared and fled",
correctLetter: "A",
correctOption: 1,
},

{
id: "question36",
question:  "36. According to Mark, one of the women who witness the burial of Jesus was Mary, the________",
A: "Sister of Martha",
B: "Mother of Philip",
C: "Mother of Jesus",
D: "Mother of James",
answer: "D. Mother of James",
correctLetter: "D",
correctOption: 4,
},

{
id: "question37",
question:  "37. The prophecy of Peter denying his Master was fulfilled____________",
A: "During Christ's arrest",
B: "During Christ's trial",
C: "On the day of Crucifixion",
D: "On the Resurrection day",
answer: "A. During Christ's arrest",
correctLetter: "A",
correctOption: 1,
},

{
id: "question38",
question:  "38. Judas Iscariot was replaced by_________-",
A: "Nicolaus",
B: "Barsabbas",
C: "Silas",
D: "Matthias",
answer: "D. Matthias",
correctLetter: "D",
correctOption: 4,
},

{
id: "question39",
question:  "39. Ananias and Sapphira were punished because they___________",
A: "Did not live as good couple",
B: "Were greedy and covetous",
C: "Lied to the holy spirit",
D: "Lied to the Apostles",
answer: "B. Were greedy and covetous",
correctLetter: "B",
correctOption: 2,
},

{
id: "question40",
question:  "40. The reason for appointing the seven deacons was to________",
A: "Spread the gospel",
B: "Performed Miracles",
C: "Serve table",
D: "Visit the converts",
answer: "A. Spread the gospel",
correctLetter: "A",
correctOption: 1,
},

{
id: "question41",
question:  "41. I am Jesus, whom you are persecuting; ........ The men who were present with Saul were amazed because they____________",
A: "Experienced the power of God",
B: "Heard the voice of an angel",
C: "Witnessed the appearance of an angel",
D: "Heard the voice but no one saw me",
answer: "D. Heard the voice but no one saw me",
correctLetter: "D",
correctOption: 4,
},

{
id: "question42",
question:  "42. To save Saul's life in Damascus, the Disciples helped him escape_______",
A: "Through the city gate",
B: "By jumping over the city fence",
C: "By disguising himself",
D: "Through a basket over the wall",
answer: "D. Through a basket over the wall",
correctLetter: "D",
correctOption: 4,
},

{
id: "question43",
question:  "43. I was in the city of Joppa praying; and in a trance, I saw a vision.......... What was the outcome of this vision?",
A: "Peter ate forbidden fruit for the first time",
B: "Gentiles were circumcised for the first time",
C: "Peter was praised by believers in Jerusalem",
D: "Gentiles received the word of God",
answer: "D. Gentiles received the word of God",
correctLetter: "D",
correctOption: 4,
},

{
id: "question44",
question:  "44. According to James, a true religion is the one that pays attention to _________",
A: "Orphans and Widows",
B: "Performance of Miracles",
C: "Prosperity of Members",
D: "Praying and Fasting",
answer: "A. Orphans and Widows",
correctLetter: "A",
correctOption: 1,
},

{
id: "question45",
question:  "45. The person used by James to illustrate his teachings on Prayer was____________",
A: "Rahab",
B: "Isaac",
C: "Job",
D: "Elijah",
answer: "D. Elijah",
correctLetter: "D",
correctOption: 4,
},

{
id: "question46",
question:  "46. Peter describes Christians as a chosen race because they__________",
A: "Declare God's wonderful deeds",
B: "Have all been anointed",
C: "Have become born again",
D: "Will be honored in heaven",
answer: "C. Have become born again",
correctLetter: "C",
correctOption: 3,
},

{
id: "question47",
question:  "47. Peter admonished Christians not to use their freedom as _________",
A: "License to disrespect authority",
B: "Pretext for evil",
C: "Reason for discrimination",
D: "Liberty to live carelessly",
answer: "B. Pretext for evil",
correctLetter: "B",
correctOption: 2,
},

{
id: "question48",
question:  "48. The very stone which the builders rejected has become the head of the cornerstone. The head of the cornerstone refers to ________",
A: "Saul of Tarsus",
B: "Simon Peter",
C: "John the Baptist",
D: "Jesus Christ",
answer: "D. Jesus Christ",
correctLetter: "D",
correctOption: 4,
},

{
id: "question49",
question:  "49. According to Peter, Christians should emulate Christ because he_____________",
A: "Suffered for our sins on the cross",
B: "Was crucified unjustly",
C: "Redeemed Christians by his blood",
D: "Provided all our needs",
answer: "C. Redeemed Christians by his blood",
correctLetter: "C",
correctOption: 3,
},


]