export const CHRISTIANRELIGIOUSSTUDIESA2020 = [

{
id: "question1",
question:  "1. The land, the sea and vegetations were created on the",
A: "first day",
B: "second day",
C: "third day",
D: "fourth day",
answer: "C. third day",
correctLetter: "C",
correctOption: 3,
},

{
id: "question2",
question:  "2. Man became a living being when God _______",
A: "formed him from dust",
B: "gave him breath",
C: "spoke to him",
D: "gave him a helpmate",
answer: "B. gave him breath",
correctLetter: "B",
correctOption: 2,
},

{
id: "question3",
question:  "3. The river that flowed out of Eden divided into________",
A: "5",
B: "4",
C: "3",
D: "2",
answer: "B. 4",
correctLetter: "B",
correctOption: 2,
},

{
id: "question4",
question:  "4. Joseph brothers pastured their father's flock near _______",
A: "Bethel",
B: "Shechem",
C: "Hebron",
D: "Peniel",
answer: "B. Shechem",
correctLetter: "B",
correctOption: 2,
},

{
id: "question5",
question:  "5. In his attempt to control the growing population of the Israelites in Egypt, Pharaoh ordered the ______",
A: "Hebrew midwives to kill every Israelite baby boy at birth.",
B: "Egyptian soldiers to bring every Israelite baby boy to the palace",
C: "second in command to ensure a total destruction of the hebrews",
D: "Egyptian midwives to kill every israelite child",
answer: "A. Hebrew midwives to kill every Israelite baby boy at birth.",
correctLetter: "A",
correctOption: 1,
},

{
id: "question6",
question:  "6. Joseph's intelligence was revealed when he _______",
A: "forgave his brothers",
B: "had a prophetic dream",
C: "interpreted Pharaoh's dreams",
D: "married an Egyptian woman",
answer: "C. interpreted Pharaoh's dreams",
correctLetter: "C",
correctOption: 3,
},

{
id: "question7",
question:  "7. Take this child away, and nurse him for me and i will give you your wages. The addressee was ________",
A: "the child's sister",
B: "a professional babysitter",
C: "the child's biological mother",
D: "Pharaoh's daughter",
answer: "C. the child's biological mother",
correctLetter: "C",
correctOption: 3,
},

{
id: "question8",
question:  "8. Moses named his son Gershom to demonstrate that he________",
A: "was an Egyptian Prince",
B: "came to Midian for pastures",
C: "was a stranger in Midian",
D: "loved Jethro and Zipporah",
answer: "C. was a stranger in Midian",
correctLetter: "C",
correctOption: 3,
},

{
id: "question9",
question:  "9. Joshua's daily meditation on the book of the law enabled him to __________",
A: "win Israelites confidence",
B: "lead his people",
C: "overcome the devil",
D: "succeed and prosper",
answer: "B. lead his people",
correctLetter: "B",
correctOption: 2,
},

{
id: "question10",
question:  "10. Jabin the King of Canaan oppressed the Israelites for_______",
A: "10 years",
B: "15 years",
C: "20 years",
D: "25 years",
answer: "C. 20 years",
correctLetter: "C",
correctOption: 3,
},

{
id: "question11",
question:  "11. The recognition of Deborah as an outstanding leader in Israel signifies that______________",
A: "God can choose women as leaders",
B: "only women can be good leaders",
C: "she was good as a judge",
D: "she was the only good leader in Israel",
answer: "A. God can choose women as leaders",
correctLetter: "A",
correctOption: 1,
},

{
id: "question12",
question:  "12. Which of these behaviours was not exhibited by the sons of EIi?",
A: "Treating the offering of God with contempt",
B: "Taking raw meat from the offering",
C: "Taking bribes and perverting justice",
D: "Forcefulý taking meat offered to God",
answer: "C. Taking bribes and perverting justice",
correctLetter: "C",
correctOption: 3,
},

{
id: "question13",
question:  "13. The linen ephod worn by Samuel portrayed him as a_________.",
A: "priest",
B: "king",
C: "seer",
D: "judge",
answer: "C. seer",
correctLetter: "C",
correctOption: 3,
},

{
id: "question14",
question:  "14. According to Samuel the prophet, rebellon is as sinful as _____________",
A: "idolatry",
B: "divination",
C: "sorcery",
D: "witchcraft",
answer: "D. witchcraft",
correctLetter: "D",
correctOption: 4,
},

{
id: "question15",
question:  "15. David rebuked Abner at Ziph because Abner_______",
A: "ignored the Zphiles complaint",
B: "sought to kill David",
C: "failed to protect his master",
D: "was not a seasoned soldier",
answer: "C. failed to protect his master",
correctLetter: "C",
correctOption: 3,
},

{
id: "question16",
question:  "16. David's servants could not report the death of Bathsheba's child to him because they________",
A: "believed God would revive the child",
B: "feared that David could harm himself",
C: "saw it as God's punishment to David",
D: "feared being killed for negligence",
answer: "B. feared that David could harm himself",
correctLetter: "B",
correctOption: 2,
},

{
id: "question17",
question:  "17. The content of the Ark of the covenant was the_______",
A: "books of the prophets",
B: "two tablets of stone",
C: "book of the law",
D: "bread offered to the Lord",
answer: "B. two tablets of stone",
correctLetter: "B",
correctOption: 2,
},

{
id: "question18",
question:  "18. My father chastised you with whips, but I will chastise you with scorpions. This means the speaker ____",
A: "torment the people with scorpions",
B: "sell them into slavery",
C: "punish the people severely",
D: "add to the people's burden",
answer: "D. add to the people's burden",
correctLetter: "D",
correctOption: 4,
},

{
id: "question19",
question:  "19. The task master in charge of forced labour in Israel during the reign of Rehoboam was_______",
A: "Hadab",
B: "Segub",
C: "Adoram",
D: "Absalom",
answer: "C. Adoram",
correctLetter: "C",
correctOption: 3,
},

{
id: "question20",
question:  "20. How did Obadiah demostrate his loyalty to God during the hostile period of his time?",
A: "refused to serve the king's idols",
B: "sent his idolatrous wife away",
C: "hid the prophets in caves",
D: "pulled down the altars of Baal",
answer: "C. hid the prophets in caves",
correctLetter: "C",
correctOption: 3,
},

{
id: "question21",
question:  "21. Is it you, you troubler of Israel? These were the words said by King_______",
A: "Saul to Samuel",
B: "Ahab to Elijah",
C: "Ahab to Elisha",
D: "David to Nathan",
answer: "B. Ahab to Elijah",
correctLetter: "B",
correctOption: 2,
},

{
id: "question22",
question:  "22. Ahab was attracted to Naboth's vineyard because the vineyard was ______",
A: "by the river bank",
B: "near the king's",
C: "beautiful and well kept",
D: "on a fertile soil",
answer: "B. near the king's",
correctLetter: "B",
correctOption: 2,
},

{
id: "question23",
question:  "23. Due to Ahab's greed, Elijah made him aware that his house would be destroyed like that of______",
A: "Baasha the son of Ahijah",
B: "Joash the son of Jeroboam",
C: "Jerubbaal the son of Jeroboam",
D: "Boash the son of Nebat.",
answer: "D. Boash the son of Nebat.",
correctLetter: "D",
correctOption: 4,
},

{
id: "question24",
question:  "24. And when the king heard the words of the book of the law, he rent his clothes. Renting of clothes in Israel was an expression of_________",
A: "joy and happiness",
B: "disappointment and grief",
C: "weakness and dependency",
D: "pity and failure",
answer: "B. disappointment and grief",
correctLetter: "B",
correctOption: 2,
},

{
id: "question25",
question:  "25. During King Josiah's religious reforms, his first attack was on the _________",
A: "prostitutes that came around the temple at night",
B: "priest that offered burnt offerings in the temple",
C: "Canaanite divinities - Baal and Asherah",
D: "sacrifice of children to Molech",
answer: "C. Canaanite divinities - Baal and Asherah",
correctLetter: "C",
correctOption: 3,
},

{
id: "question26",
question:  "26. What was the sin of Manasseh for which God punished Judah under king Jehoiakim?",
A: "Murder",
B: "Theft",
C: "Injustice",
D: "Adultery",
answer: "C. Injustice",
correctLetter: "C",
correctOption: 3,
},

{
id: "question27",
question:  "27. What did the returned Jews give as a sin offering during the dedication of the temple?",
A: "A he-goat for each of the twelve tribes",
B: "Two lambs for each of the twelve tribes",
C: "Many Animals including rams and camels",
D: "Animals like ram and food chops",
answer: "A. A he-goat for each of the twelve tribes",
correctLetter: "A",
correctOption: 1,
},

{
id: "question28",
question:  "28. Shadrach, Meshach and Abednego were punished because they__________",
A: "committed murder in the society",
B: "regularly worshipped their own God",
C: "refused to bow to the golden image",
D: "failed to honour the king",
answer: "C. refused to bow to the golden image",
correctLetter: "C",
correctOption: 3,
},

{
id: "question29",
question:  "29. Amos observed that the Israelites profaned God's name when they__________",
A: "committed idolatry",
B: "committed incest",
C: "refused to offer sacrifice",
D: "discriminate against women",
answer: "B. committed incest",
correctLetter: "B",
correctOption: 2,
},

{
id: "question30",
question:  "30. Amaziah advised Amos to go and prophesy in Judah instead of Bethel because_______",
A: "the king's sanctuary was in Bethel",
B: "Amos was a dresser of sycamore tree",
C: "Jeroboam, Bethel's king was after Amos' life",
D: "the Words of Amos intimidated Judah",
answer: "D. the Words of Amos intimidated Judah",
correctLetter: "D",
correctOption: 4,
},

{
id: "question31",
question:  "31. The Sonship of Jesus was declared during His________",
A: "crucifixion",
B: "temptation",
C: "baptism",
D: "ascension",
answer: "C. baptism",
correctLetter: "C",
correctOption: 3,
},

{
id: "question32",
question:  "32. According to Luke, the third temptation was that Jesus should_________",
A: "jump down from a high mountain",
B: "jump down from the pinnacle of the temple",
C: "command the angels to lift him up",
D: "bow down and worship Satan",
answer: "B. jump down from the pinnacle of the temple",
correctLetter: "B",
correctOption: 2,
},

{
id: "question33",
question:  "33. Who among these was a brother to Peter?",
A: "Matthew",
B: "John",
C: "Andrew",
D: "James",
answer: "C. Andrew",
correctLetter: "C",
correctOption: 3,
},

{
id: "question34",
question:  "34. Which of the following disciples was called from the tax office by Jesus?",
A: "Andrew",
B: "Simon",
C: "Levi",
D: "Judas",
answer: "C. Levi",
correctLetter: "C",
correctOption: 3,
},

{
id: "question35",
question:  "35. The unmerciful servant was punished because he__________",
A: "failed to settle his debt",
B: "disobeyed the king",
C: "embezzled the kings money",
D: "cast his debtor into jail",
answer: "D. cast his debtor into jail",
correctLetter: "D",
correctOption: 4,
},

{
id: "question36",
question:  "36. The one I shall kiss is the man; seize him. The kiss was significant for_________",
A: "honouring Jesus",
B: "confronting Jesus",
C: "protecting Jesus",
D: "identifying Jesus",
answer: "D. identifying Jesus",
correctLetter: "D",
correctOption: 4,
},

{
id: "question37",
question:  "37. The prophecy concerning the denial of Jesus by Peter was fulfilled during the_________",
A: "arrest of Jesus",
B: "trial of Jesus",
C: "agony of Gethsemane",
D: "transfiguration of Jesus",
answer: "B. trial of Jesus",
correctLetter: "B",
correctOption: 2,
},

{
id: "question38",
question:  "38. The High Priest tore his robes during the trial of Jesus because he said Jesus________",
A: "refused to answer",
B: "uttered blasphemous words",
C: "spoke against the temple",
D: "broke their tradition",
answer: "B. uttered blasphemous words",
correctLetter: "B",
correctOption: 2,
},

{
id: "question39",
question:  "39. Simon of Cyrene, who was compelled to carry Jesus' cross, was the father of________",
A: "Barnbas and Gamaliel",
B: "Alexander and Rufus",
C: "Barnabas and Rufus",
D: "Alexander and Barnabas",
answer: "B. Alexander and Rufus",
correctLetter: "B",
correctOption: 2,
},

{
id: "question40",
question:  "40. According to Matthew, the first to see Jesus after His resurrection were the_______________________",
A: "angels that guarded the tomb",
B: "women who went to the tomb",
C: "disciples who were praying",
D: "men travelling to Emmanus",
answer: "B. women who went to the tomb",
correctLetter: "B",
correctOption: 2,
},

{
id: "question41",
question:  "41. The election of Matthias to succeed Judas was_____",
A: "a command from Peter",
B: "the fulfillment of the scripture",
C: "an instruction given by Jesus",
D: "a way of getting more disciples",
answer: "B. the fulfillment of the scripture",
correctLetter: "B",
correctOption: 2,
},

{
id: "question42",
question:  "42. The challenges of discrimination and favouritism in the early church were resolved by _________",
A: "praying for God's intervention",
B: "the study of the scriptures and counselling",
C: "the selection of seven men to serve",
D: "appointing elders to the council of Jerusalem",
answer: "C. the selection of seven men to serve",
correctLetter: "C",
correctOption: 3,
},

{
id: "question43",
question:  "43. The authorities Peter quoted as being fulfilled on the day of Pentecost were___________",
A: "Isaiah and Jeremiah",
B: "Ezekiel and Amos",
C: "Joel and David",
D: "Hosea and John",
answer: "C. Joel and David",
correctLetter: "C",
correctOption: 3,
},

{
id: "question44",
question:  "44. Saul's conversion on the road to Damascus resulted in the ________",
A: "fleeing of the brethren",
B: "churches' poor performance",
C: "outpouring of the spirit",
D: "churches' peaceful growth",
answer: "D. churches' peaceful growth",
correctLetter: "D",
correctOption: 4,
},

{
id: "question45",
question:  "45. Which of these statements was not made by Peter during the second trial of the apostles by the high priest?",
A: "We must always obey God rather than man",
B: "God raised Jesus whom you killed by hanging on a tree",
C: "God exalted Jesus as a leader and Saviour",
D: "We cannot but speak of what we have seen and heard",
answer: "B. God raised Jesus whom you killed by hanging on a tree",
correctLetter: "B",
correctOption: 2,
},

{
id: "question46",
question:  "46. Pure and undefiled religion, according to James, involved all these practices except__________",
A: "visiting orphans in their suffering",
B: "going to church daily",
C: "visiting widows in their affliction",
D: "being unstained from the world",
answer: "B. going to church daily",
correctLetter: "B",
correctOption: 2,
},

{
id: "question47",
question:  "47. James advised that Christians should sing praises when they are_________",
A: "wealthy",
B: "happy",
C: "lonely",
D: "suffering",
answer: "D. suffering",
correctLetter: "D",
correctOption: 4,
},

{
id: "question48",
question:  "48. According to Peter, Christians have become a chosen race so that they may____________",
A: "behave better than the Jews",
B: "not be like the Gentiles",
C: "declare the good works of God",
D: "not remain in sin forever",
answer: "C. declare the good works of God",
correctLetter: "C",
correctOption: 3,
},

{
id: "question49",
question:  "49. For Peter, Christian liberty not be used as a___________",
A: "cover-up for sin",
B: "pretext for love",
C: "way of disrespect",
D: "way of rejecting duties",
answer: "A. cover-up for sin",
correctLetter: "A",
correctOption: 1,
},

{
id: "question50",
question:  "50. According to Peter, the Church elders would receive their rewards______________",
A: "at their death",
B: "during their life's time",
C: "each time they resisted satan",
D: "at Jesus's second comin",
answer: "D. at Jesus's second coming",
correctLetter: "D",
correctOption: 4,
},


]