export const CHRISTIANRELIGIOUSSTUDIESA2013 = [

{
id: "question1",
question:  "1. Eve was to have pains at childbirth because she",
A: "seduced Adam",
B: "conversed with the serpent",
C: "ate of the tree of life",
D: "ate of the tree of good and evil",
answer: "D. ate of the tree of good and evil",
correctLetter: "D",
correctOption: 4,
},

{
id: "question2",
question:  "2. Abram's obligation in his covenant with God was to",
A: "change Sarai's name to Sarah",
B: "walk before God blamelessly",
C: "change his name to Abraham",
D: "offer his son Isaac as a sacrifice",
answer: "B. walk before God blamelessly",
correctLetter: "B",
correctOption: 2,
},

{
id: "question3",
question:  "3. God prepared Joseph for his leadership role in Egypt through",
A: "the love which his father had for him",
B: "the trials and temptations of his earlier years",
C: "his disagreement with his brothers",
D: "His encounter with Potiphar's wife",
answer: "B. the trials and temptations of his earlier years",
correctLetter: "B",
correctOption: 2,
},

{
id: "question4",
question:  "4. By removing his sandals before the burning bush, Moses was showing a sense of",
A: "honour and love",
B: "curiousity and adventure",
C: "humility and respect",
D: "reverence and submissiveness",
answer: "D. reverence and submissiveness",
correctLetter: "D",
correctOption: 4,
},

{
id: "question5",
question:  "5. The twelve spies that were sent by Moses to the promised land were to confirm all the following except",
A: "the type of people in the land",
B: "the fertility of the land",
C: "fortifications of the cities",
D: "availability of grapes in the land",
answer: "D. availability of grapes in the land",
correctLetter: "D",
correctOption: 4,
},

{
id: "question6",
question:  "6. When the people of Israel received the minority report from the spies, they decided to",
A: "Kill Moses for taking them out of Egypt",
B: "go back to Egypt",
C: "choose Caleb as their new leader",
D: "stone the two spies to death",
answer: "B. go back to Egypt",
correctLetter: "B",
correctOption: 2,
},

{
id: "question7",
question:  "7. The purpose of Joshua's address at Shechem was to",
A: "show his love for God",
B: "establish a new covenant with God",
C: "remind Israel of their unfaithfulness",
D: "make Israel trust God",
answer: "C. remind Israel of their unfaithfulness",
correctLetter: "C",
correctOption: 3,
},

{
id: "question8",
question:  "8. God rejected Eli's line of priesthood because",
A: "his children were idolators",
B: "they did not obey the prophets",
C: "Eli and his children took bribes",
D: "his children lust after women at worship",
answer: "D. his children lust after women at worship",
correctLetter: "D",
correctOption: 4,
},

{
id: "question9",
question:  "9. 'It is the Lord, let Him do what seems good to Him'. These were the words of",
A: "Saul",
B: "Samuel",
C: "Moses",
D: "Eli",
answer: "D. Eli",
correctLetter: "D",
correctOption: 4,
},

{
id: "question10",
question:  "10. What reasons were put forward by the Israelites in asking for a king?",
A: "The age of Samuel and the conduct of his sons",
B: "The conduct of Samuel and the strength of the Philistines",
C: "the age of Samuel and the conduct of Eli",
D: "The conduct of Samuel and the age of his sons",
answer: "A. The age of Samuel and the conduct of his sons",
correctLetter: "A",
correctOption: 1,
},

{
id: "question11",
question:  "11. Asa is an example of a parent",
A: "who failed to direct his children's part",
B: "who admonished his children",
C: "whose children perverted justice",
D: "whose children interfered with God's sacrifice",
answer: "A. who failed to direct his children's part",
correctLetter: "A",
correctOption: 1,
},

{
id: "question12",
question:  "12. The contest on Mount Carmel was organized to",
A: "popularize Baal worship",
B: "prove the power of God",
C: "show that God answers by fire",
D: "prove the immortality of Elijah",
answer: "B. prove the power of God",
correctLetter: "B",
correctOption: 2,
},

{
id: "question13",
question:  "13. God promised to punish the house of Ahab and not Ahab himself, because he",
A: "humbled himself",
B: "acted under pressure",
C: "was a righteous man",
D: "acted wisely",
answer: "A. humbled himself",
correctLetter: "A",
correctOption: 1,
},

{
id: "question14",
question:  "14. The worship of 'Host of Heaven' in Judah during Manasseh's reign was an indication that he",
A: "Yahweh's worship has declined",
B: "Judah's king was weak",
C: "Assyrian influence was strong",
D: "Babylonian influence was great",
answer: "C. Assyrian influence was strong",
correctLetter: "C",
correctOption: 3,
},

{
id: "question15",
question:  "15. Who among the following carried out a religious reform in Judah?",
A: "Jehosaphat",
B: "Joshua",
C: "Josiah",
D: "Jehoiachim",
answer: "C. Josiah",
correctLetter: "C",
correctOption: 3,
},

{
id: "question16",
question:  "16. Who among the following carried out a religious reform in Judah?",
A: "Jehosaphat",
B: "Joshua",
C: "Josiah",
D: "Jehoiachim",
answer: "C. Josiah",
correctLetter: "C",
correctOption: 3,
},

{
id: "question17",
question:  "17. Jeremiah's vision of a boiling pot represented",
A: "Judah's sins",
B: "pot of destruction",
C: "invasion from the North",
D: "Judah's rejection",
answer: "C. invasion from the North",
correctLetter: "C",
correctOption: 3,
},

{
id: "question18",
question:  "18. Hosea's daughter was called",
A: "Jezreel",
B: "Not pitied",
C: "Not my people",
D: "Phineas",
answer: "B. Not pitied",
correctLetter: "B",
correctOption: 2,
},

{
id: "question19",
question:  "19. What was Nehemiah's immediate reaction to the news concerning Jerusalem? He",
A: "wept",
B: "prayed",
C: "fainted",
D: "fasted",
answer: "A. wept",
correctLetter: "A",
correctOption: 1,
},

{
id: "question20",
question:  "20. According to Ezekiel, the wicked person should",
A: "be stoned to death",
B: "redeem himself",
C: "be reprimanded by the prophet",
D: "pay for the sins committed",
answer: "B. redeem himself",
correctLetter: "B",
correctOption: 2,
},

{
id: "question21",
question:  "21. The incident in the fiery furnace concerning Shadrach, Meshach and Abednego convinced Nebuchadnezzar that",
A: "they had many gods to save them",
B: "the Jews were very powerful people",
C: "the three Jews were angelic beings",
D: "Yahweh is the only true God",
answer: "D. Yahweh is the only true God",
correctLetter: "D",
correctOption: 4,
},

{
id: "question22",
question:  "22. The opposition to the rebuilding of the temple was resolved by",
A: "constant prayer",
B: "edict issued by Darius",
C: "fighting the opponents",
D: "Ezra's dialogue with opponents",
answer: "B. edict issued by Darius",
correctLetter: "B",
correctOption: 2,
},

{
id: "question23",
question:  "23. All the following took place at the transfiguration of Jesus except that",
A: "a voice was heard from heaven",
B: "a dove came down upon Jesus",
C: "the face of Jesus was changed",
D: "Jesus' clothe became dazzling white",
answer: "B. a dove came down upon Jesus",
correctLetter: "B",
correctOption: 2,
},

{
id: "question24",
question:  "24. Jesus taught in parables in order to",
A: "make known the secrets of the kingdom",
B: "hide the secrets of life from the public",
C: "make his teaching enjoyable",
D: "enable his disciples preach better",
answer: "A. make known the secrets of the kingdom",
correctLetter: "A",
correctOption: 1,
},

{
id: "question25",
question:  "25. According to Luke, Jesus' birth in a manger was due to",
A: "the choice of the parents",
B: "lack of room in Joseph’s family house",
C: "lack of place for them in the inn",
D: "Mary's labour being sudden",
answer: "C. lack of place for them in the inn",
correctLetter: "C",
correctOption: 3,
},

{
id: "question26",
question:  "26. '....you brood of vipers! Who warned you to flee from the wrath to come?' The 'wrath to come' here refers to the",
A: "day of confusion",
B: "judgement day",
C: "rejection by God",
D: "burning furace",
answer: "B. judgement day",
correctLetter: "B",
correctOption: 2,
},

{
id: "question27",
question:  "27. According to Luke, the third temptation of Jesus was that He should",
A: "jump down from the high mountain",
B: "jump from the pinnacle of the temple",
C: "bow and worship him",
D: "order the stone to become bread",
answer: "C. bow and worship him",
correctLetter: "C",
correctOption: 3,
},

{
id: "question28",
question:  "28. The initial evidence that the disciples had received the Holy Spirit was",
A: "performing miracles",
B: "preaching to the people",
C: "speaking in tongues",
D: "praying together",
answer: "C. speaking in tongues",
correctLetter: "C",
correctOption: 3,
},

{
id: "question29",
question:  "29. The gospel which gives prominence to the Holy Spirit in the life of Jesus Christ is",
A: "Mathew",
B: "Mark",
C: "John",
D: "Luke",
answer: "D. Luke",
correctLetter: "D",
correctOption: 4,
},

{
id: "question30",
question:  "30. 'But I say to you, do not resist one who is evil.' This was part of Jesus' teaching on",
A: "humility",
B: "prayer",
C: "retaliation",
D: "violence",
answer: "C. retaliation",
correctLetter: "C",
correctOption: 3,
},

{
id: "question31",
question:  "31. The prayer of Jesus at Gethsemane shows that",
A: "He was in severe agony",
B: "He wanted to escape death",
C: "He needed the support of His disciples",
D: "God had abandoned him",
answer: "A. He was in severe agony",
correctLetter: "A",
correctOption: 1,
},

{
id: "question32",
question:  "32. Pilate referred Jesus to Herod for trial because",
A: "Pilate and Herod were good friends",
B: "Jesus did not cooperate with Pilate",
C: "Jesus lived in the jurisdiction of Herod",
D: "Pilate and Herod were enemies",
answer: "C. Jesus lived in the jurisdiction of Herod",
correctLetter: "C",
correctOption: 3,
},

{
id: "question33",
question:  "33. After the resurrection, the Early Church met to",
A: "determine how to deal with the Sanhendrin",
B: "plan the expansion of the church",
C: "appoint a replacement for Judas Iscariot",
D: "determine the Inclusion of the Gentiles in the church",
answer: "C. appoint a replacement for Judas Iscariot",
correctLetter: "C",
correctOption: 3,
},

{
id: "question34",
question:  "34. The First Martyr among the apostles was",
A: "James",
B: "Phillip",
C: "Peter",
D: "Stephen",
answer: "A. James",
correctLetter: "A",
correctOption: 1,
},

{
id: "question35",
question:  "35. According to the First Council at Jerusalem, the following were binding on a Christian except",
A: "praying always in the temple",
B: "not eating animals that have been strangled",
C: "living a life of chastity",
D: "avoiding food sacrificed to idols",
answer: "A. praying always in the temple",
correctLetter: "A",
correctOption: 1,
},

{
id: "question36",
question:  "36. The appointment of the Seven Deacons highlighted the need for",
A: "sharing responsibility",
B: "distributing gifts among the apostles",
C: "living in peace with one another",
D: "organizing social services",
answer: "A. sharing responsibility",
correctLetter: "A",
correctOption: 1,
},

{
id: "question37",
question:  "37. The laying of hands-on Barnabas and Paul for the First Missionary Journey signifies their being",
A: "blessed",
B: "commissioned",
C: "appointed",
D: "anointed",
answer: "B. commissioned",
correctLetter: "B",
correctOption: 2,
},

{
id: "question38",
question:  "38. What yoke did the Council of Jerusalem say had been difficult for Pharisees and their fathers to bear? The question of",
A: "discipleship",
B: "circumcision",
C: "the cross",
D: "repentance",
answer: "B. circumcision",
correctLetter: "B",
correctOption: 2,
},

{
id: "question39",
question:  "39. Justification by faith according to Paul is",
A: "the state of being a blessed child of God",
B: "acquitted by the one offended",
C: "acquitted from moral sin and satanic oppression",
D: "the state of being acquitted and accepted",
answer: "D. the state of being acquitted and accepted",
correctLetter: "D",
correctOption: 4,
},

{
id: "question40",
question:  "40. Paul in Thessalonian said the signs of the Second Coming of Christ would start with",
A: "condemnation",
B: "rebellion",
C: "earthquake",
D: "darkness",
answer: "B. rebellion",
correctLetter: "B",
correctOption: 2,
},

{
id: "question41",
question:  "41. James teaches that all the following are true causes of unanswered prayers except",
A: "sin",
B: "diligence",
C: "unfaithfulness",
D: "greed",
answer: "B. diligence",
correctLetter: "B",
correctOption: 2,
},

{
id: "question42",
question:  "42. The gifts of the spirit which could be referred to as 'vocal gifts' are",
A: "healing, miracles and faith",
B: "wisdom, knowledge and discernment",
C: "prophecy, tongues and interpretations",
D: "tongues, faith and wisdom",
answer: "C. prophecy, tongues, and interpretations",
correctLetter: "C",
correctOption: 3,
},

{
id: "question43",
question:  "43. Paul believes that the resurrection of the dead would only occur on the",
A: "last day",
B: "triumphant day",
C: "ascension day",
D: "Pentecost day",
answer: "A. last day",
correctLetter: "A",
correctOption: 1,
},

{
id: "question44",
question:  "44. A good citizen according to Peter is one that",
A: "obeys the law of the state and provides for the poor",
B: "provides social services for the needy",
C: "obeys the law of the state and fufills his obligations",
D: "helps to finance the government at all times",
answer: "C. obeys the law of the state and fulfills his obligations",
correctLetter: "C",
correctOption: 3,
},

{
id: "question45",
question:  "45. The primary motive for Christian giving is to",
A: "go to heaven when they die",
B: "reciprocate God's blessing",
C: "support the work of the church",
D: "provide for the servants of God",
answer: "B. reciprocate God's blessing",
correctLetter: "B",
correctOption: 2,
},

{
id: "question46",
question:  "46. According to Paul, God gives us victory over death through",
A: "Adam",
B: "Jesus",
C: "The Holy Spirit",
D: "Angels",
answer: "B. Jesus",
correctLetter: "B",
correctOption: 2,
},

{
id: "question47",
question:  "47. The meaning of reconciliation in Paul's thought is how to",
A: "pay back your debt",
B: "have peace with God and man",
C: "give alms to the needy",
D: "please God with your prayers",
answer: "B. have peace with God and man",
correctLetter: "B",
correctOption: 2,
},

{
id: "question48",
question:  "48. Which of Paul's epistles was written to an individual?",
A: "Romans",
B: "Corinthians",
C: "Colossians",
D: "Philemon",
answer: "D. Philemon",
correctLetter: "D",
correctOption: 4,
},

{
id: "question49",
question:  "49. James urged Christians not to be partial to fulfill the 'royal law'. What is the 'royal law'?",
A: "You shall not commit adultery",
B: "Do good to those who hate you",
C: "You should love your neighbor as yourself",
D: "Pray for those in authority always",
answer: "C. You should love your neighbor as yourself",
correctLetter: "C",
correctOption: 3,
},


]