import {UnderlineText, SquareRoot, superscript, subscript, BoldText, ItalicText, Fraction, ShortFraction, LongFraction, MixedFraction, Isotopes } from "@/mathnotation"

export const ENGLISHLANGUAGEA2012 = [

{
instruction: "In each of the following sentences, there is a word underlined and one gap. From the list of words lettered A to D, choose the word that is most nearly opposite in meaning to the underlined word and that will, at the same time, correctly fill the gap in the sentence.",
id: "question1",
question: ["1. Due to his recklessness, he fell from ", <UnderlineText key={"1"} text={"affluence"}/>, " to _________________"],
A: "deficit.",
B: "liability.",
C: "penury.",
D: "starvation.",
answer: "C. penury",
correctLetter: "C",
correctOption: 3,
},

{
id: "question2",
question: ["2. Older people prefer the ", <UnderlineText key={"1"} text={"serenity"}/>, " of the countryside to the _________________ in the city."],
A: "aggression",
B: "crowding",
C: "struggle",
D: "turmoil",
answer: "B. crowding",
correctLetter: "B",
correctOption: 2,
},

{
id: "question3",
question: ["3. While some people ", <UnderlineText key={"1"} text={"castigate"}/>, " the government, others _________________ it."],
A: "boost",
B: "favour",
C: "laud",
D: "proclaim",
answer: "C. laud",
correctLetter: "C",
correctOption: 3,
},

{
id: "question4",
question: ["4. Ababio declared that he would do only _________________ business and stay away from ", <UnderlineText key={"1"} text={"illegal"}/>, " ones."],
A: "commercial",
B: "justifiable",
C: "legitimate",
D: "outstanding",
answer: "C. legitimate",
correctLetter: "C",
correctOption: 3,
},

{
id: "question5",
question: ["5. It’s strange that someone with such an _________________ smile should have such a ", <UnderlineText key={"1"} text={"repulsive"}/>, " behavior"],
A: "alluring",
B: "amicable",
C: "elusive",
D: "enduring",
answer: "A. alluring",
correctLetter: "A",
correctOption: 1,
},

{
id: "question6",
question: ["6. The public has been advised to note the features of the new currency notes so as to differentiate the ", <UnderlineText key={"1"} text={"fake"}/>, " from the _________________ ones."],
A: "clear",
B: "genuine",
C: "official",
D: "unique",
answer: "B. genuine",
correctLetter: "B",
correctOption: 2,
},

{
id: "question7",
question: ["7. Though the workers see the manager as ", <UnderlineText key={"1"} text={"callous,"}/>, " he is really _________________ "],
A: "considerate.",
B: "effective.",
C: "frank.",
D: "powerful.",
answer: "A. considerate",
correctLetter: "A",
correctOption: 1,
},

{
id: "question8",
question: ["8. The team was ", <UnderlineText key={"1"} text={"hailed"}/>, " in triumph but _________________ when it lost the cup."],
A: "abandoned.",
B: "booed.",
C: "ignored.",
D: "shunned.",
answer: "B. booed",
correctLetter: "B",
correctOption: 2,
},

{
id: "question9",
question:[ "9. Peter was sacked for being ", <UnderlineText key={"1"} text={"negligent"}/>, " while his brother was promoted because he was _________________"],
A: "humble.",
B: "obedient.",
C: "painstaking.",
D: "realistic.",
answer: "C. painstaking",
correctLetter: "C",
correctOption: 3,
},

{
id: "question10",
question: ["10. The FIFA advised all referees to be ", <UnderlineText key={"1"} text={"impartial"}/>, " and not _________________ "],
A: "biased.",
B: "careless.",
C: "ignorant.",
D: "wicked.",
answer: "A. based",
correctLetter: "A",
correctOption: 1,
},

{
section: "2",
instruction: "From the list of words lettered A to D, choose the one that best completes each of the following sentences.",
id: "question11",
question: "11. The president _________________ the bill passed by parliament.",
A: "cancelled",
B: "repealed",
C: "tabled",
D: "vetoed",
answer: "D. vetoed",
correctLetter: "D",
correctOption: 4,
},

{
id: "question12",
question: "12. No one could tell why James _________________ that unprovoked attack on his brother.",
A: "devised",
B: "launched",
C: "managed",
D: "spread",
answer: "B. launch",
correctLetter: "B",
correctOption: 2,
},

{
id: "question13",
question: "13. One of the factions has _________________ its claim to the throne.",
A: "altered",
B: "renounced",
C: "repealed",
D: "revised",
answer: "B. renounced",
correctLetter: "B",
correctOption: 2,
},

{
id: "question14",
question: "14. The African Union has decided not to _________________ any government that comes by way of a coup d’etat.",
A: "face",
B: "mention",
C: "recognize",
D: "vote",
answer: "C. recognize",
correctLetter: "C",
correctOption: 3,
},

{
id: "question15",
question: "15. Though he was a great player, he failed to _________________ in the tournament.",
A: "exult",
B: "flourish",
C: "rise",
D: "shine",
answer: "D. shine",
correctLetter: "D",
correctOption: 4,
},

{
id: "question16",
question: "16. Many people agreed that the _________________ of office of the president should be four years.",
A: "length",
B: "period",
C: "span",
D: "term",
answer: "D. term",
correctLetter: "D",
correctOption: 4,
},

{
id: "question17",
question: "17. The doctor _________________ the disease as measles.",
A: "diagnosed",
B: "discovered",
C: "examined",
D: "investigated",
answer: "A. diagnosed",
correctLetter: "A",
correctOption: 1,
},

{
id: "question18",
question: "18. The manager _________________ the poor performance of the company to inflation.",
A: "assigned",
B: "attributed",
C: "consigned",
D: "described",
answer: "B. attributed",
correctLetter: "B",
correctOption: 2,
},

{
id: "question19",
question: "19. It’s not advisable to build a house there because the area is _________________ to flooding.",
A: "agreeable",
B: "condemned",
C: "prone",
D: "resigned",
answer: "C. prone",
correctLetter: "C",
correctOption: 3,
},

{
id: "question20",
question: "20. The government said the measures were meant to _________________ inflation.",
A: "catch",
B: "check",
C: "defeat",
D: "dismiss",
answer: "B. check",
correctLetter: "B",
correctOption: 2,
},

{
section: "3",
instruction: "Choose from the alternatives lettered A to D the one which is nearest in meaning to the underlined word or expression in each sentence.",
id: "question21",
question: ["21. At last, the ", <UnderlineText key={"1"} text={"infamous"}/>, " armed robber has been caught by the police"],
A: "callous",
B: "dangerous",
C: "notorious",
D: "popular",
answer: "C. notorious",
correctLetter: "C",
correctOption: 3,
},

{
id: "question22",
question: ["22. Some bosses are fond of ", <UnderlineText key={"1"} text={"harassing"}/>, " their staff."],
A: "condemning",
B: "fighting",
C: "intimidating",
D: "mocking",
answer: "C. intimidating",
correctLetter: "C",
correctOption: 3,
},

{
id: "question23",
question: ["23. The woman became ", <UnderlineText key={"1"} text={"despondent"}/>, " after the judge had sentenced her son to jail."],
A: "alarmed",
B: "angered",
C: "dejected",
D: "deserted",
answer: "C. dejected",
correctLetter: "C",
correctOption: 3,
},

{
id: "question24",
question: ["24. Many listeners disliked the ", <UnderlineText key={"1"} text={"haughty"}/>, " manner in which the minister spoke."],
A: "arrogant",
B: "commanding",
C: "harsh",
D: "insulting",
answer: "A. arrogant",
correctLetter: "A",
correctOption: 1,
},

{
id: "question25",
question: ["25. The chairman asked all the members to give their ", <UnderlineText key={"1"} text={"candid"}/>, " opinion on the matter."],
A: "certain",
B: "frank",
C: "kind",
D: "strong",
answer: "B. frank",
correctLetter: "B",
correctOption: 2,
},

{
id: "question26",
question: ["26. Many traditional songs were composed by ", <UnderlineText key={"1"} text={"anonymous"}/>, " authors."],
A: "insignificant",
B: "unknown",
C: "unprofessional",
D: "unwilling",
answer: "B. unknown",
correctLetter: "B",
correctOption: 2,
},

{
id: "question27",
question: ["27. We won the match because our defence was ", <UnderlineText key={"1"} text={"impregnable"}/>, ""],
A: "experienced",
B: "loyal",
C: "powerful",
D: "unbeatable",
answer: "D. unbeatable",
correctLetter: "D",
correctOption: 4,
},

{
id: "question28",
question: ["28. Mr. Adabla couldn’t entrust his business to his first son because of the latter's ", <UnderlineText key={"1"} text={"erratic"}/>, " behavior."],
A: "careless",
B: "extravagant",
C: "inflexible",
D: "unstable",
answer: "D. unstable",
correctLetter: "D",
correctOption: 4,
},

{
id: "question29",
question: ["29. Araba was voted the most ", <UnderlineText key={"1"} text={"outstanding"}/>, " speaker at the conference."],
A: "conspicuous",
B: "persuasive",
C: "remarkable",
D: "respected",
answer: "C. remarkable",
correctLetter: "C",
correctOption: 3,
},

{
id: "question30",
question: ["30. Stanley was caught by Mr. Jones when he tried to ", <UnderlineText key={"1"} text={"mimic"}/>, " him."],
A: "imitate",
B: "mock",
C: "paint",
D: "portray",
answer: "A. imitate",
correctLetter: "A",
correctOption: 1,
},

{
section: "4",
instruction: "After each of the following sentences, a list of possible interpretations of all or part of the sentence is given. Choose the interpretation you consider most appropriate for each sentence.",
id: "question31",
question: "31. The chief was admired because he had his heart in the right place. This means that he was",
A: "happy and healthy:",
B: "humorous.",
C: "submissive.",
D: "kind and generous.",
answer: "D. kind and generous",
correctLetter: "D",
correctOption: 4,
},

{
id: "question32",
question: "32. After Mr. Jalo was dismissed from the board, he decided to keep his distance. This means that he",
A: "became lonely.",
B: "became hostile.",
C: "avoided company.",
D: "decided to travel.",
answer: "B. became hostile",
correctLetter: "B",
correctOption: 2,
},

{
id: "question33",
question: "33. Kofi’s attack on me in public touch a raw nerve. This means that",
A: "Kofi physically assaulted me.",
B: "Kofi upset me.",
C: "I resented what he said.",
D: "I was exposed to ridicule.",
answer: "C. I resented what he said",
correctLetter: "C",
correctOption: 3,
},

{
id: "question34",
question: "34. Though the teacher felt that Aba was not telling the truth, he decided to give her the benefit of the doubt. This means that he",
A: "lost trust in her.",
B: "doubted her statement",
C: "refused to believe her story.",
D: "presumed that she was innocent.",
answer: "D. presumed that she was innocent",
correctLetter: "D",
correctOption: 4,
},

{
id: "question35",
question: "35. The player was in two minds about playing for his motherland. This means that he",
A: "couldn’t decide whether to play.",
B: "had played twice for his country.",
C: "had doubts about his chances of being selected.",
D: "was called up the second time.",
answer: "A. couldn’t decide whether to play",
correctLetter: "A",
correctOption: 1,
},

{
id: "question36",
question: "36. The politician rewarded all those who stood by him during the crisis. This means that be rewarded those who",
A: "respected him",
B: "supported him.",
C: "saved him.",
D: "comforted him.",
answer: "B. supported him",
correctLetter: "B",
correctOption: 2,
},

{
id: "question37",
question: "37. Joojo’s sudden success seems to have gone into his head. This means that be bas become",
A: "conceited",
B: "confused.",
C: "disrespectful.",
D: "uncontrollable.",
answer: "A. conceited",
correctLetter: "A",
correctOption: 1,
},

{
id: "question38",
question: "38. Forecasts say that trade will pick up in the next few months after the slump. This means that",
A: "buyers will buy more goods in the months to come.",
B: "trading will start in the months to come.",
C: "trading will take place in just a few months.",
D: "there will be more shops.",
answer: "A. buyers will buy more goods in the months to come",
correctLetter: "A",
correctOption: 1,
},

{
section: "5",
instruction: "From the words or groups of words lettered A to D, choose the one that best completes each of the following sentences.",
id: "question39",
question: "39. Afua was reduced _________________ tears when she lost the election.",
A: "by",
B: "into",
C: "to",
D: "with",
answer: "C. to",
correctLetter: "C",
correctOption: 3,
},

{
id: "question40",
question: "40. The coach flew _________________ a passion when the referee ignored a glaring penalty for his team.",
A: "by",
B: "into",
C: "over",
D: "through",
answer: "B. into",
correctLetter: "B",
correctOption: 2,
},

{
id: "question41",
question: "41. That tie sets your shirt _________________ very well.",
A: "by",
B: "in",
C: "off",
D: "out",
answer: "D. out",
correctLetter: "D",
correctOption: 4,
},

{
id: "question42",
question: "42. Will you be here for long? No, I _________________.",
A: "will",
B: "won’t",
C: "would",
D: "wouldn’t",
answer: "B. won’t",
correctLetter: "B",
correctOption: 2,
},

{
id: "question43",
question: "43. Kwesi fears dark places, _________________ ?",
A: "hasn’t he",
B: "doesn’t he",
C: "isn’t it",
D: "isn’t he",
answer: "B. doesn’t",
correctLetter: "B",
correctOption: 2,
},

{
id: "question44",
question: "44. The tourists cut short their trip because they were _________________ by the behaviour of the guides.",
A: "put through",
B: "put out",
C: "put off",
D: "put away",
answer: "C. put off",
correctLetter: "C",
correctOption: 3,
},

{
id: "question45",
question: "45. James’ new novel is _________________ interesting than the previous one.",
A: "much so",
B: "much more",
C: "more so",
D: "so much",
answer: "A. much so",
correctLetter: "A",
correctOption: 1,
},

{
id: "question46",
question: "46. The bus _________________ into the rear of my car when I stopped at the traffic lights.",
A: "got",
B: "hit",
C: "ran",
D: "run",
answer: "B. hit",
correctLetter: "B",
correctOption: 2,
},

{
id: "question47",
question: "47. Abu is by far the _________________ intelligent boy in the class.",
A: "best",
B: "more",
C: "most",
D: "much",
answer: "C. most",
correctLetter: "C",
correctOption: 3,
},

{
id: "question48",
question: "48. You dare not complain _________________ ?",
A: "will you",
B: "isn’t it",
C: "dare you",
D: "you dare",
answer: "C. dare you",
correctLetter: "C",
correctOption: 3,
},

{
id: "question49",
question: "49. I wouldn’t have employed you _________________ for your humility.",
A: "but",
B: "however",
C: "if not",
D: "nevertheless",
answer: "A. but",
correctLetter: "A",
correctOption: 1,
},

{
id: "question50",
question: "50. He had hardly stepped out of the house _________________ the good news arrived.",
A: "as",
B: "than",
C: "then",
D: "when",
answer: "A. as",
correctLetter: "A",
correctOption: 1,
},

{
id: "question51",
question: "51. _________________ some strange reason, the headmaster refused to work with his assistant.",
A: "By",
B: "For",
C: "From",
D: "With",
answer: "B. For",
correctLetter: "B",
correctOption: 2,
},

{
id: "question52",
question: "52. With the _________________ of Essien in our team, we are confident of winning the cup.",
A: "like",
B: "liking",
C: "likeness",
D: "likes",
answer: "B. liking",
correctLetter: "B",
correctOption: 2,
},

{
id: "question53",
question: "53. He was advised _________________ skipping meals.",
A: "against",
B: "for",
C: "in",
D: "with",
answer: "D. with",
correctLetter: "D",
correctOption: 4,
},

{
id: "question54",
question: "54. Kwesi and _________________ went through hard times in school.",
A: "her",
B: "him",
C: "I",
D: "me",
answer: "C. I",
correctLetter: "C",
correctOption: 3,
},

{
id: "question55",
question: "55. I told him that the pair of shoes _________________ not match his shirt.",
A: "can",
B: "should",
C: "will",
D: "would",
answer: "D. would",
correctLetter: "D",
correctOption: 4,
},

{
id: "question56",
question: "56. _________________ knows that Kofi won the best student award.",
A: "Anybody",
B: "Anyone",
C: "Everybody",
D: "Someone",
answer: "C. Everybody",
correctLetter: "C",
correctOption: 3,
},

{
id: "question57",
question: "57. The judge ruled that the Martins must leave the house because it wasn’t _________________ ",
A: "his.",
B: "their.",
C: "their’s.",
D: "theirs.",
answer: "D. theirs",
correctLetter: "D",
correctOption: 4,
},

{
id: "question58",
question: "58. John had _________________ for his grandmother before her death.",
A: "developed a special liking",
B: "a special liking developed",
C: "a liking special developed",
D: "developed a liking special",
answer: "A. developed a special liking",
correctLetter: "A",
correctOption: 1,
},

{
id: "question59",
question: "59. _________________ of the two boys wanted to be in the relay team.",
A: "Any",
B: "Anyone",
C: "Neither",
D: "None",
answer: "D. None",
correctLetter: "D",
correctOption: 4,
},

{
id: "question60",
question: "60. Mr. Adams bought an expensive _________________ ",
A: "custom-made black automatic Benz car.",
B: "custom-made automatic black Benz car.",
C: "black custom-made automatic Benz car.",
D: "automatic custom-made black Benz car.",
answer: "C. black custom-made automatic Benz car",
correctLetter: "C",
correctOption: 3,
},

{
section: "6",
passage: "In the following passage, the numbered gaps indicate missing words. Against each number in the list below the passage, four choices are offered in columns lettered A to D. For each numbered gap, choose from the options provided for that number, the word that is most suitable to fill the gap. To achieve rapid development, a country needs a strong –6– government to manage its affairs. The various political –62– that aspire to power should avoid divisive tendencies, see each other as development –63– and work in concert to improve the quality of life of the entire –64-. The government in –65– should create a congenial atmosphere and pursue prudent and transparent –66-. It should get its –67– right and pursue realistic goals and objectives for economic –68-. If the country experiences a –69– in its monetary growth, it is desirable that the national –70– should be shared equitably by all.",
id: "question61",
question: "61. *********************",
A: "authoritative",
B: "central",
C: "controlling",
D: "sensible",
answer: "B. Central",
correctLetter: "B",
correctOption: 2,
},

{
id: "question62",
question: "62. *********************",
A: "companies",
B: "parties",
C: "teams",
D: "units",
answer: "B. Parties",
correctLetter: "B",
correctOption: 2,
},

{
id: "question63",
question: "63. *********************",
A: "associates",
B: "colleagues",
C: "mates",
D: "partners",
answer: "D. Partners",
correctLetter: "D",
correctOption: 4,
},

{
id: "question64",
question: "64. *********************",
A: "citizenry",
B: "inhabitants",
C: "members",
D: "nationals",
answer: "A. Citizenry",
correctLetter: "A",
correctOption: 1,
},

{
id: "question65",
question: "65. *********************",
A: "command",
B: "force",
C: "power",
D: "rule",
answer: "C. Power",
correctLetter: "C",
correctOption: 3,
},

{
id: "question66",
question: "66. *********************",
A: "conditions",
B: "matters",
C: "methods",
D: "policies",
answer: "D. Policies",
correctLetter: "D",
correctOption: 4,
},

{
id: "question67",
question: "67. *********************",
A: "duties",
B: "measures",
C: "priorities",
D: "priorities",
answer: "D. Priorities",
correctLetter: "D",
correctOption: 4,
},

{
id: "question68",
question: "68. *********************",
A: "advancement",
B: "improvement",
C: "movement",
D: "service",
answer: "A. Advancement",
correctLetter: "A",
correctOption: 1,
},

{
id: "question69",
question: "69. *********************",
A: "bonus",
B: "boom",
C: "security",
D: "surplus",
answer: "B. Boom",
correctLetter: "B",
correctOption: 2,
},

{
id: "question70",
question: "70. *********************",
A: "cake",
B: "fortune",
C: "produce",
D: "resources",
answer: "A. Cake",
correctLetter: "A",
correctOption: 1,
},


]