import {UnderlineText, SquareRoot, superscript, subscript, BoldText, ItalicText, Fraction, ShortFraction, LongFraction, MixedFraction, Isotopes } from "@/mathnotation"

export const ENGLISHLANGUAGEA2020 = [

{
section: "1",
instruction: "In each of the following sentences, there is a word underlined and one gap.. From the list of words lettered A to D, choose the word that is most nearly opposite in meaning to the underlined word and that will, at the same time, correctly fill the gap in the sentence.",
id: "question1",
question: ["1. Binetou’s ", <UnderlineText key={"1"} text={"inquisitiveness"}/>, " is in sharp contrast with her sister’s _________________ ."],
A: "calmness",
B: "noisiness",
C: "indifference",
D: "dullness",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question2",
question: ["2. Though at first it appeared an ", <UnderlineText key={"1"} text={"insignificant"}/>, " idea, it turned out to be quite _________________ ."],
A: "remarkable",
B: "successful",
C: "outstanding",
D: "interesting",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question3",
question: ["3. After grasping the ", <UnderlineText key={"1"} text={"fundamental"}/>, " aspects of his job, Kwasi had to cope with more _________________ procedures."],
A: "subsidiary",
B: "advanced",
C: "academic",
D: "secondary",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question4",
question: ["4. The youth prefer discussing ", <UnderlineText key={"1"} text={"contemporary"}/>, " issues to _________________ ones."],
A: "stale",
B: "uninteresting",
C: "archaic",
D: "political",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question5",
question: ["5. As ", <UnderlineText key={"1"} text={"erroneous"}/>, " as it might sound, the Headmaster’s assumption was quite _________________ ."],
A: "wise",
B: "faulty",
C: "precise",
D: "correct",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question6",
question: ["6. Halima likes to dwell on ", <UnderlineText key={"1"} text={"trivial"}/>, " rather than _________________ matters."],
A: "weighty",
B: "popular",
C: "strong",
D: "heavy",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question7",
question: ["7. We all know that Bola is ", <UnderlineText key={"1"} text={"insolent"}/>, " whereas Ade is _________________ ."],
A: "cowardly",
B: "humble",
C: "modest",
D: "respectful",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question8",
question: ["8. A few days after Musa’s _________________ , his sister longed for his ", <UnderlineText key={"1"} text={"departure."}/>, ""],
A: "coming",
B: "entrance",
C: "welcome",
D: "arrival",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question9",
question: ["9. Algebra seems ", <UnderlineText key={"1"} text={"complicated,"}/>, " but with practice it becomes _________________  "],
A: "solved",
B: "achievable",
C: "simple",
D: "accessible",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question10",
question: ["10. Mrs. Agide is ", <UnderlineText key={"1"} text={"unassuming"}/>, " whereas her twin Sister is _________________ "],
A: "boastful",
B: "cheerful",
C: "loud",
D: "rude",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
section: "II",
instruction: "From the words lettered A to D, choose the one that best completes each of the following sentences.",
id: "question11",
question: "11. At Christmas, employees of the Sugar Factory receive huge _________________ .",
A: "benefits",
B: "bonuses",
C: "dividends",
D: "salaries",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question12",
question: "12. The exposed milk in that container has turned _________________ .",
A: "stale",
B: "putrid",
C: "mouldy",
D: "sour",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question13",
question: "13. Not all activists champion _________________ causes.",
A: "concrete",
B: "real",
C: "worthy",
D: "favourable",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question14",
question: "14. The Mayor gave a glowing _________________ at the funeral of the city’s only curator.",
A: "tribute",
B: "statement",
C: "citation",
D: "commendation",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question15",
question: "15. At the end of _________________ , the National Anthem is played on our radio station.",
A: "programming",
B: "transmission",
C: "transition",
D: "production",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question16",
question: "16. The defence counsel was unable to convince the _________________ of John’s innocence.",
A: "jury",
B: "witness",
C: "panel",
D: "plantiff",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question17",
question: "17. Unfortunately, corruption is the _________________ of most African countries.",
A: "venom",
B: "back",
C: "disaster",
D: "bane",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question18",
question: "18. The _________________ results proved that the patient bad hepatitis.",
A: "test",
B: "diagnosis",
C: "probe",
D: "investigation",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question19",
question: "19. The new book has beautiful _________________  which make it attractive.",
A: "illuminations",
B: "demonstrations",
C: "illustrations",
D: "compositions",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question20",
question: "20. Their marriage was finally _________________ after years of hostility.",
A: "separated",
B: "cancelled",
C: "broken",
D: "annulled",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
section: "III",
instruction: "After each of the following sentences, a list of possible interpretations is given. Choose the interpretation that is most appropriate for each sentence.",
id: "question21",
question: "21. Can you Imagine Oka behaving as if he has all the knowledge in the world? This means that Oka ",
A: "is admired by everybody.",
B: "knows so much more than we think.",
C: "respects other people.",
D: "does not really know everything.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question22",
question: "22. Akin is too full of himself. This means that Akin",
A: "talks too much.",
B: "is too proud.",
C: "eats too much.",
D: "is quite annoying.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question23",
question: "23. She slogged her guts out for the examination. This means that",
A: "she failed the examination despite working hard for it.",
B: "passed the examination despite not working hard for it.",
C: "really worked hard for the examination.",
D: "used unfair means to face the examination.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question24",
question: "24. I admire Modou: very few people can stomach all of Adaeze’s insults. This means that Modou",
A: "did the right thing by remaining silent.",
B: "was a weakling.",
C: "had no answers to Adaeze’s insults.",
D: "tolerated Adaeze’s insults.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question25",
question: "25. After months of battling with stroke he is now a shadow of his former self. This means that he",
A: "is vulnerable.",
B: "is now frail.",
C: "is hopeless.",
D: "has almost recovered.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question26",
question: "26. Kura, you can’t be too careful when dealing with Wang. This means that Kura",
A: "has no reason to be suspicious of Wang.",
B: "has to be very careful in his relationship with Wang.",
C: "can fully rely on Wang.",
D: "may feel free in the company of Wang.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question27",
question: "27. Don’t tell me another cock and bull story. This means that the speaker does not want to",
A: "be further deceived.",
B: "hear the same old story.",
C: "hear another drab story.",
D: "be further baffled.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question28",
question: "28. Had he confessed much earlier, she would have trust him. This means that he",
A: "hadn’t confessed earlier on and he wasn’t trusted.",
B: "had confessed much earlier on and he was trusted.",
C: "hadn’t confessed much earlier on and he was trusted.",
D: "had confessed earlier on but wasn’t trusted.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question29",
question: "29. Kola “You really worked hard to win the case”. Didia: “You don’t know the half of it”. This means that",
A: "it wasn’t as difficult as Kola had thought.",
B: "Kola’s statement was not actually correct.",
C: "winning the case didn’t mean much to Kola.",
D: "it was even more difficult than Kola could imagine.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question30",
question: "30. Femi is too clever by half This means that Femi",
A: "hides how clever he really is.",
B: "is not as clever as he thinks.",
C: "pleases everyone he meets.",
D: "displays his cleverness in an annoying way.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
section: "IV",
instruction: "From the words lettered A to D below each of the following sentences, choose the word or group of words that is nearest in meaning to the underlined word as it is used in the sentence.",
id: "question31",
question: ["31. He was such a ", <UnderlineText key={"1"} text={"brilliant"}/>, " footballer!"],
A: "a skillful",
B: "an intelligent",
C: "a dazzling",
D: "an inspired",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question32",
question: ["32. The politician is a ", <UnderlineText key={"1"} text={"fluent"}/>, " speaker."],
A: "insightful",
B: "superficial",
C: "eloquent",
D: "persuasive",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question33",
question: ["33. Everyone has the ", <UnderlineText key={"1"} text={"urge"}/>, " succeed in life."],
A: "desire",
B: "compulsion",
C: "need",
D: "courage",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question34",
question: ["34. When he heard the gunshot, he ran into a ", <UnderlineText key={"1"} text={"thick"}/>, " forest."],
A: "tight",
B: "dense",
C: "deep",
D: "close",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question35",
question: ["35. That was a ", <UnderlineText key={"1"} text={"timely"}/>, " intervention."],
A: "prompt",
B: "accurate",
C: "suitable",
D: "major",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
}, 

{
id: "question36",
question: ["36. David is not only hardworking but also ", <UnderlineText key={"1"} text={"scrupulous."}/>, ""],
A: "daring",
B: "ambitious",
C: "pleasant",
D: "painstaking",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question37",
question: ["37. We really have to be careful because the situation is rather ", <UnderlineText key={"1"} text={"tricky."}/>, ""],
A: "difficult",
B: "trivial",
C: "unexpected",
D: "deceitful",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question38",
question: ["38. I think that his essay is ", <UnderlineText key={"1"} text={"impeccable."}/>, ""],
A: "erroneous",
B: "faultless",
C: "satisfactory",
D: "correct",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question39",
question: ["39. There has been a ", <UnderlineText key={"1"} text={"marked"}/>, " change in her study habit."],
A: "fill",
B: "real",
C: "significant",
D: "complete",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question40",
question: ["40. He was ", <UnderlineText key={"1"} text={"directed"}/>, " to write the letter."],
A: "advised",
B: "forced",
C: "persuaded",
D: "instructed",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
section: "V",
instruction: "From the words or group of words lettered A to D, choose the word or group of words that best completes each of the following sentences.",
id: "question41",
question: "41. Every one of the students _________________ to be excited about the excursion.",
A: "seems",
B: "is seeming",
C: "seem",
D: "was seeming",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question42",
question: "42. We should assist the poor, _________________ ?",
A: "shall we",
B: "shouldn’t we",
C: "isn’t it",
D: "we shouldn’t",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question43",
question: "43. Either he or you _________________ to clean up the mess.",
A: "has",
B: "was",
C: "must",
D: "have",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question44",
question: "44. If Musa had woken up earlier, he _________________ breakfast.",
A: "shall have missed",
B: "ought not to miss",
C: "would not have missed",
D: "may have missed",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question45",
question: "45. He would rather appeal the decision _________________ defeat.",
A: "instead of accepting",
B: "than accepting",
C: "than accept",
D: "than accepts",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question46",
question: "46. The student complained that he _________________ the teacher.",
A: "could not hear",
B: "was not hearing",
C: "does not hear",
D: "is not hearing",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question47",
question: "47. My brother _________________ in Lagos for the past ten years.",
A: "is living",
B: "has been living",
C: "will have lived",
D: "lived",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question48",
question: "48. I am totally disappointed _________________ such poor grades.",
A: "with",
B: "from",
C: "for",
D: "on",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question49",
question: "49. He is a doctor but he dabbles _________________ politics now and then.",
A: "on",
B: "through",
C: "in",
D: "into",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question50",
question: "50. _________________  arrived before the manager.",
A: "Neither me nor him",
B: "Neither me nor he",
C: "Either I nor him",
D: "Neither he nor I",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question51",
question: "51. The evening was rounded _________________ with a dance.",
A: "up",
B: "off",
C: "out",
D: "down",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question52",
question: "52. I _________________ have done the dishes but I haven’t had the time.",
A: "should",
B: "will",
C: "might",
D: "shall",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question53",
question: "53. I have heard all _________________ you said.",
A: "what",
B: "that",
C: "which",
D: "whatever",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question54",
question: "54. Life in the city is _________________ challenging for the lazy.",
A: "too much",
B: "so much",
C: "much too",
D: "very much",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question55",
question: "55. It is always _________________ that get the blame.",
A: "me",
B: "mine",
C: "myself", 
D: "I",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
}, 

{
id: "question56",
question: "56. He spends a _________________ deal of his time studying.",
A: "large",
B: "huge",
C: "big",
D: "great",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question57",
question: "57. I guess he holds_________________ sensitive position in the company.",
A: "some kind of",
B: "many kind of",
C: "some kind",
D: "many kind",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question58",
question: "58. He always gives _________________ for coming late to school.",
A: "some excuse or another",
B: "one excuse or the other",
C: "one excuse or another",
D: "some excuse or the other.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question59",
question: "59. _________________  you turn down the volume of the radio? I am trying to read!",
A: "May",
B: "Should",
C: "Would",
D: "Will",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question60",
question: "60. I know it’s a secret, so I _________________ tell anyone.",
A: "couldn't",
B: "mightn't",
C: "needn't",
D: "shan't",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question61",
question: "61. At the last minute, Amidu backed _________________ of the plan.",
A: "out",
B: "off",
C: "up",
D: "down",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question62",
question: "62. He _________________ be very handsome but I don’t like him.",
A: "shall",
B: "will",
C: "can",
D: "might",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question63",
question: "63. During her early days in school, she _________________  study for hours.",
A: "would",
B: "may",
C: "shall",
D: "can",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question64",
question: "64. He _________________ this morning in a dazzling white shirt.",
A: "turned out",
B: "turned in",
C: "turned by",
D: "turned off",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question65",
question: "65. The police have _________________ a warning to all residents of the area.",
A: "put on",
B: "put in",
C: "put out",
D: "put off",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question66",
question: "66. My parents taught me a lot of lessons, most of _________________ are difficult to forget.",
A: "whom",
B: "who",
C: "which",
D: "what",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question67",
question: "67. Sani _________________ on a banana peel and fell down.",
A: "slid",
B: "slide",
C: "had slid",
D: "was sliding",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question68",
question: "68. I look forward to _________________ from you.",
A: "hear",
B: "to be hearing",
C: "hearing",
D: "have heard",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question69",
question: "69. I have made remarkable progress _________________ learning French.",
A: "in",
B: "at",
C: "by",
D: "for",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question70",
question: "70. The beans have not been properly _________________ .",
A: "grind",
B: "grinding",
C: "ground",
D: "grounded",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
section: "VI",
instruction: "In the following passage the numbered gaps indicate missing words. Against each number in the list below the passage, four options are given in columns lettered A to D. Choose the word that is the most suitable to fill the numbered gaps in the passage.",
passage: "An entrepreneur is a person who organises and manages any business enterprise, or one who combines the other factors of —71— to start a business and make a profit. He possesses considerable initiative and is willing to take —72—. An entrepreneur can be a farmer, a dressmaker, a factory owner, a wholesaler or a — 73—. More often than not, it is best for an entrepreneur to start a business from scratch rather than —74— in or buy an existing business. One advantage is that he would be independent and not become a —75— or get to inherit some bad debt. The —76— of a good entrepreneur must include hard work, innovation and creativity. He must be well informed and confident to make worthwhile decisions. As it takes a great deal of energy, time and money to operate one’s own business, entrepreneurs must seek to possess good managerial —77— in order to manage their business successfully. But how useful is the entrepreneur to the society? He is an innovator who develops new —78— and services to make life easier and more comfortable. He plans, organises, directs and —79— his business activities effectively thus minimising wastage of limited —80— and enhancing",
id: "question71",
question: "71. *********************",
A: "production",
B: "provision",
C: "construction",
D: "creation",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question72",
question: "72. *********************",
A: "debts",
B: "risks",
C: "pitfalls",
D: "problems",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question73",
question: "73. *********************",
A: "retailer",
B: "peddler",
C: "hawker",
D: "trader",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question74",
question: "74. *********************",
A: "plunge",
B: "break",
C: "invest",
D: "delve",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question75",
question: "75. *********************",
A: "colleague",
B: "partner",
C: "fellow",
D: "comrade",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question76",
question: "76. *********************",
A: "tendencies",
B: "properties",
C: "features",
D: "attributes",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question77",
question: "77. *********************",
A: "knack",
B: "talents",
C: "skills",
D: "foresight",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question78",
question: "78. *********************",
A: "products",
B: "yields",
C: "outputs",
D: "materials",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question79",
question: "79. *********************",
A: "bridles",
B: "checks",
C: "restrains",
D: "controls",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question80",
question: "80. *********************",
A: "assets",
B: "resources",
C: "stock",
D: "wealth",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},


]