import { UnderlineText, SquareRoot, superscript, subscript, BoldText, ItalicText, Fraction, ShortFraction, LongFraction, MixedFraction, Isotopes } from "@/mathnotation"

export const ENGLISHLANGUAGEA2017 = [

{
instruction: "In each of the following sentences, there is a word underlined and one gap. From the list of words lettered A to D choose the word that is most nearly opposite in meaning to the underlined word and that will at the same time correctly fill the gap in the sentence.",
id: "question1",
question: ["1. Honest labour can lift one from circumstances of ", <UnderlineText key={"1"} text={"poverty"}/>, " to _________________ "],
A: "happiness",
B: "generosity",
C: "development",
D: "affluence",
answer: "D. affluence",
correctLetter: "D",
correctOption: 4,
},

{
id: "question2",
question: ["2.  ", <UnderlineText key={"1"} text={"Trained"}/>, " physicians are more careful than  _________________ doctors when treating patients"],
A: "careless",
B: "quack",
C: "reckless",
D: "indifferent",
answer: "B. quack",
correctLetter: "B",
correctOption: 2,
},

{
id: "question3",
question: ["3. The leader ", <UnderlineText key={"1"} text={"encouraged"}/>, " all present not to be _________________ by recent happenings"],
A: "controlled",
B: "disheartened",
C: "cautioned",
D: "surprised",
answer: "B. disheartened",
correctLetter: "B",
correctOption: 2,
},

{
id: "question4",
question: ["4. His knowledge in the sciences is only ", <UnderlineText key={"1"} text={"superficial"}/>, " and not _________________…"],
A: "profound",
B: "instructive",
C: "complex",
D: "strong",
answer: "A. profound",
correctLetter: "A",
correctOption: 1,
},

{
id: "question5",
question: ["5. Electricity supply is only ", <UnderlineText key={"1"} text={"erratic"}/>, " in the city but _________________ in the villages."],
A: "frequent",
B: "stable",
C: "normal",
D: "available",
answer: "B. stable",
correctLetter: "B",
correctOption: 2,
},

{
id: "question6",
question: ["6. People who talk about others can only do ", <UnderlineText key={"1"} text={"temporary,"}/>, "  not _________________ damage to them."],
A: "heavy",
B: "serious",
C: "lasting",
D: "considerable",
answer: "C. lasting",
correctLetter: "C",
correctOption: 3,
},

{
id: "question7",
question: ["7. It is difficult to afford ", <UnderlineText key={"1"} text={"sumptuous"}/>, " meals nowadays, one has to make do with _________________."],
A: "frugal",
B: "unbalanced",
C: "unpalatable",
D: "available",
answer: "C. unpalatable",
correctLetter: "C",
correctOption: 3,
},

{
id: "question8",
question: ["8. The advantages of reconciliation for ", <UnderlineText key={"1"} text={"outweigh"}/>, " living in _________________ "],
A: "disharmony",
B: "opposition",
C: "indifference",
D: "violence",
answer: "A. disharmony",
correctLetter: "A",
correctOption: 1,
},

{
id: "question9",
question: ["9. Academic performance, which was at its lowest ", <UnderlineText key={"1"} text={"ebb,"}/>, " is now at its _________________ "],
A: "climax",
B: "tip",
C: "peak",
D: "maximum",
answer: "C. peak",
correctLetter: "C",
correctOption: 3,
},

{
id: "question10",
question: ["10. It is advisable to avoid ", <UnderlineText key={"1"} text={"apathy"}/>, " and embrace _________________ "],
A: "bravery",
B: "leniency",
C: "satisfaction",
D: "enthusiasm",
answer: "D. enthusiasm",
correctLetter: "D",
correctOption: 4,
},

{
section: "II",
instruction: "From the list of words lettered A to D, choose the one that best completes each of the following sentences",
id: "question11",
question: "11. Some articles of noted value are always in… _________________ demand",
A: "great",
B: "pressing",
C: "urgent",
D: "rising",
answer: "A. great",
correctLetter: "A",
correctOption: 1,
},

{
id: "question12",
question: "12. The politicians… _________________ considerable light on the subject.",
A: "conveys",
B: "provides",
C: "reveals",
D: "sheds",
answer: "D. sheds",
correctLetter: "D",
correctOption: 4,
},

{
id: "question13",
question: "13. Positive results are achieved when matters are put in the… _________________ perspective",
A: "concise",
B: "right",
C: "sound",
D: "direct",
answer: "B. right",
correctLetter: "B",
correctOption: 2,
},

{
id: "question14",
question: "14. The board was entrusted with the responsibility to… _________________ the affairs of the company.",
A: "drive",
B: "navigate",
C: "steer",
D: "guard",
answer: "C. steer",
correctLetter: "C",
correctOption: 3,
},

{
id: "question15",
question: "15. Both countries believe that economic co-operation will be to their _________________ ",
A: "unilateral",
B: "crucial",
C: "mutual",
D: "substantial",
answer: "C. mutual",
correctLetter: "C",
correctOption: 3,
},

{
id: "question16",
question: "16. Impressive achievements were made during the chairman’s  _________________ of office.",
A: "regime",
B: "tenure",
C: "occupancy",
D: "reign",
answer: "B. tenure",
correctLetter: "B",
correctOption: 2,
},

{
id: "question17",
question: "17. For some time now the company has been _________________ the verge of collapse.",
A: "in",
B: "on",
C: "around",
D: "near",
answer: "B. on",
correctLetter: "B",
correctOption: 2,
},

{
id: "question18",
question: "18. As Maya gained experience in life, she learnt not to act… _________________ reason.",
A: "beside",
B: "across",
C: "against",
D: "outside",
answer: "C. against",
correctLetter: "C",
correctOption: 3,
},

{
id: "question19",
question: "19. Understanding one another makes it far… _________________ for tolerance to flourish",
A: "easier",
B: "easy",
C: "easiest",
D: "much easy",
answer: "A. easier",
correctLetter: "A",
correctOption: 1,
},

{
id: "question20",
question: "20. In times of unrest, the distribution system _________________ to a halt",
A: "is ground",
B: "is grinding",
C: "grinds",
D: "grounded",
answer: "C. grinds",
correctLetter: "C",
correctOption: 3,
},

{
section: "III",
instruction: "Choose from the alternatives lettered A to D the one which is nearest in meaning to the underlined word or expression in each sentence",
id: "question21",
question: ["21. The ", <UnderlineText key={"1"} text={"velocity"}/>, " of light could not be determined until quite recently."],
A: "colour",
B: "speed",
C: "power",
D: "movement",
answer: "B. speed",
correctLetter: "B",
correctOption: 2,
},

{
id: "question22",
question: ["22. All these ", <UnderlineText key={"1"} text={"prospective"}/>, " investors attended the meeting"],
A: "rich",
B: "enterprising",
C: "selected",
D: "potential",
answer: "D. potential",
correctLetter: "D",
correctOption: 4,
},

{
id: "question23",
question: ["23. Only humans have the ", <UnderlineText key={"1"} text={"innate"}/>, " ability to cook their food before eating"],
A: "intimate",
B: "real",
C: "substantial",
D: "inborn",
answer: "D. inborn",
correctLetter: "D",
correctOption: 4,
},

{
id: "question24",
question: ["24. Whenever ", <UnderlineText key={"1"} text={"avarice"}/>, " rears its ugly head, it should be avoided."],
A: "antagonism",
B: "greed",
C: "selfishness",
D: "obsession",
answer: "B. greed",
correctLetter: "B",
correctOption: 2,
},

{
id: "question25",
question: ["25. After days of heavy rains, the islanders feared a possible ", <UnderlineText key={"1"} text={"inundation"}/>, ""],
A: "submerging",
B: "greed",
C: "selfish",
D: "obsession",
answer: "C. selfish",
correctLetter: "C",
correctOption: 3,
},

{
id: "question26",
question: ["26. Mary succeeded through ", <UnderlineText key={"1"} text={"perseverance"}/>, ""],
A: "persistence",
B: "knowledge",
C: "accomplishment",
D: "inspiration",
answer: "A. persistence",
correctLetter: "A",
correctOption: 1,
},

{
id: "question27",
question: ["27. Confidence tricksters can dupe only ", <UnderlineText key={"1"} text={"gullible"}/>, " people"],
A: "careless",
B: "naïve",
C: "greedy",
D: "humble",
answer: "B. naive",
correctLetter: "B",
correctOption: 2,
},

{
id: "question28",
question: ["28. The weather is ", <UnderlineText key={"1"} text={"serene"}/>, " today"],
A: "friendly",
B: "intense",
C: "great",
D: "calm",
answer: "D. calm",
correctLetter: "D",
correctOption: 4,
},

{
id: "question29",
question: ["29. A swarm of locusts caused widespread ", <UnderlineText key={"1"} text={"damage"}/>, " to the crops"],
A: "deterioration",
B: "destruction",
C: "wreckage",
D: "spoilage",
answer: "B. destruction",
correctLetter: "B",
correctOption: 2,
},

{
id: "question30",
question: ["30. Many people are unable to cope with ", <UnderlineText key={"1"} text={"escalating"}/>, " medical expenses"],
A: "ascending",
B: "rising",
C: "heightening",
D: "expanding",
answer: "B. rising",
correctLetter: "B",
correctOption: 2,
},

{
section: "IV",
instruction: "After each of the following sentences, a list of possible interpretations of all or part of the sentence is given. Choose the interpretation you consider most appropriate for each sentence",
id: "question31",
question: "31. The job seekers were told to keep their fingers crossed. This means the job seekers were to",
A: "revise their notes thoroughly",
B: "crosscheck their documents",
C: "receive further instruction",
D: "hope for the best",
answer: "D. hope for the best",
correctLetter: "D",
correctOption: 4,
},

{
id: "question32",
question: "32. In spite of severe criticism, he stood his ground. This means that he",
A: "remained on the grounds",
B: "reasoned sensibly",
C: "made remarkable progress",
D: "remained firm",
answer: "D. remained firm",
correctLetter: "D",
correctOption: 4,
},

{
id: "question33",
question: "33. When I appeared before the interview panel, I had my heart in my mouth. This means that I",
A: "was more than ready",
B: "was very anxious",
C: "lost my voice completely",
D: "felt quite indifferent",
answer: "B. was very anxious",
correctLetter: "B",
correctOption: 2,
},

{
id: "question34",
question: "34. Policies are formulated by those at the helm of affairs. This means that policies are made by those",
A: "with the know-how,",
B: "in authority",
C: "in favour of affairs only",
D: "who are present at the time",
answer: "B. in authority",
correctLetter: "B",
correctOption: 2,
},

{
id: "question35",
question: "35. They were asked to obey the instruction to the letter, This means that they were to obey the instruction",
A: "according to the letters",
B: "as and when requested,",
C: "in every detail,",
D: "only in part,",
answer: "C. in every detail,",
correctLetter: "C",
correctOption: 3,
},

{
id: "question36",
question: "36. The contestants spent precious time splitting hairs over matters, This means that the contestants",
A: "were arguing over unimportant issues",
B: "tired to dye their hair in disguise",
C: "caused serious alarm about events",
D: "preferred only superior products",
answer: "A. were arguing over unimportant issues",
correctLetter: "A",
correctOption: 1,
},

{
id: "question37",
question: "37. The monetary reward came to him as a windfall. This means that reward was",
A: "an added advantage",
B: "adequate compensation",
C: "well earned",
D: "an unexpected fortune",
answer: "D. an unexpected fortune",
correctLetter: "D",
correctOption: 4,
},

{
id: "question38",
question: "38. The smugglers hid themselves until the coast was clear. This means that the smugglers hid",
A: "for the time being",
B: "until the danger was over",
C: "until investigation was over",
D: "to seek protection at the coast",
answer: "B. until the danger was over",
correctLetter: "B",
correctOption: 2,
},

{
id: "question39",
question: "39. The law-breakers will be made to face the music. This means that they will be",
A: "brought before the law",
B: "deprived of all music",
C: "reconsidered on appeal",
D: "arrested and relocated",
answer: "A. brought before the law",
correctLetter: "A",
correctOption: 1,
},

{
id: "question40",
question: "40. Although prudent measures were put in place to salvage the economy, it still remained in the doldrums. This means that the economy",
A: "lacked clear direction",
B: "performed beyond expectation",
C: "depended on the importation of drums",
D: "lacked any improvement",
answer: "D. lacked any improvement",
correctLetter: "D",
correctOption: 4,
},

{
section: "VI",
instruction: "In the following passage, the numbered gaps indicate missing words. Against each number in the list below the passage, four choices are offered in columns lettered A and B. For each numbered gap, choose from the options provided for that number, the word that is most suitable to fill the gap.",
passage: "The courtroom was hushed but alive with suppressed excitement. The widely publicised trial of the notorious criminal was for that day. \nAt a signal from the courtroom –41–, the audience stood up respectfully as the –42—judge entered. Soon afterwards the –43—also filed in. The –44—and his team, as well as the defence –45—also took their positions; the legal battle commenced. \nPeople from all walks of life had assembled there just to listen to the –46–. The prosecution read the charges –47—against the accused. The defence vehemently objected to all of them. The judge –48—the objections as the evidence before the court was clear and incontrovertible. Eventually, a –49—was given; a –50—sentence was slapped on the accused. The audience did not express any pity for him; everyone praised the court for allowing the law take its course.",
id: "question41",
question: "41. *********************",
A: "Attendant",
B: "Clerk",
C: "Official",
D: "Interpreter",
answer: "B. Clerk",
correctLetter: "B",
correctOption: 2,
},

{
id: "question42",
question: "42. *********************",
A: "Presiding",
B: "Leading",
C: "Additional",
D: "Ruling",
answer: "A. Presiding",
correctLetter: "A",
correctOption: 1,
},

{
id: "question43",
question: "43. *********************",
A: "Staff",
B: "Panel",
C: "Jury",
D: "Bench",
answer: "C. Jury",
correctLetter: "C",
correctOption: 3,
},

{
id: "question44",
question: "44. *********************",
A: "Presenter",
B: "Complainant",
C: "Recorded",
D: "Prosecutor",
answer: "B. Complainant",
correctLetter: "B",
correctOption: 2,
},

{
id: "question45",
question: "45. *********************",
A: "Counsel",
B: "Counsellor",
C: "Registrar",
D: "Administrator",
answer: "A. Counsel",
correctLetter: "A",
correctOption: 1,
},

{
id: "question46",
question: "46. *********************",
A: "Procedures",
B: "Presentations",
C: "Processes",
D: "Proceedings",
answer: "D. Proceedings",
correctLetter: "D",
correctOption: 4,
},

{
id: "question47",
question: "47. *********************",
A: "Levelled",
B: "Stated",
C: "Invoked",
D: "Pronounced",
answer: "A. Levelled",
correctLetter: "A",
correctOption: 1,
},

{
id: "question48",
question: "48. *********************",
A: "Overrode",
B: "Overran",
C: "Overturned",
D: "Overruled",
answer: "D. Overruled",
correctLetter: "D",
correctOption: 4,
},

{
id: "question49",
question: "49. *********************",
A: "Decision",
B: "Verdict",
C: "Summary",
D: "Conviction",
answer: "B. Verdict",
correctLetter: "B",
correctOption: 2,
},

{
id: "question50",
question: "50. *********************",
A: "Weighty",
B: "Prolonged",
C: "Painful",
D: "Heavy",
answer: "D. Heavy",
correctLetter: "D",
correctOption: 4,
},


]