import { UnderlineText, SquareRoot, superscript, subscript, BoldText, ItalicText, Fraction, ShortFraction, LongFraction, MixedFraction, Isotopes } from "@/mathnotation"

export const ENGLISHLANGUAGEA2002 = [

{
section: "1",
sectiontitle: "In each of the following sentence, there is one word or group of words underlined word and one gap. From the list of words or group of words lettered A to D, choose the one that is most noarly opposito in meaning to the underlined word or group of words and that will, at the hame time, correctly fill the gap in the sentence.",
id: "question1",
question: ["1. The workers expected management to be, ____________ rather than  ", <UnderlineText key={"2"} text={"indifferent"}/>, " to their welfare."],
A: "different from",
B: "interested in",
C: "opposed to",
D: "careful of",
answer: "B. interested in",
correctLetter: "B",
correctOption: 2,
},

{
id: "question2",
question: ["2. Words spoken in the heat of an argument could  ", <UnderlineText key={"2"} text={"offend"}/>, " rather than _____________ ..."],
A: "pacify",
B: "amuse",
C: "inspire",
D: "irritate",
answer: "A. pacify",
correctLetter: "A",
correctOption: 1,
},

{
id: "question3",
question: ["3. Although they have declared the student a  ", <UnderlineText key={"2"} text={"suspect,"}/>, " he may turn out to be _____________ "],
A: "culpable",
B: "innocent",
C: "safe",
D: "ignorant",
answer: "B. innocent",
correctLetter: "B",
correctOption: 2,
},

{
id: "question4",
question: ["4. Some  ", <UnderlineText key={"2"} text={"outspoken"}/>, " social critics live a. ____________ family life"],
A: "reserved",
B: "happy",
C: "boisterous",
D: "still",
answer: "A. reserved",
correctLetter: "A",
correctOption: 1,
},

{
id: "question5",
question: ["5. While the manager was  ", <UnderlineText key={"2"} text={"prudent"}/>, " in his expenditure, his deputy was _____________ "],
A: "miserly",
B: "careful1",
C: "thoughtful",
D: "extravagant.",
answer: "D. extravagant",
correctLetter: "D",
correctOption: 4,
},

{
id: "question6",
question: ["6. The cultured and the. ____________ are known by their conduct."],
A: "barbaric",
B: "ignorant",
C: "clean",
D: "lazy.",
answer: "A. barbaric",
correctLetter: "A",
correctOption: 1,
},

{
id: "question7",
question: ["7. Many Africans now live in abject  ", <UnderlineText key={"2"} text={"poverty"}/>, " instead of enjoying the. ____________ of the countries."],
A: "comfort",
B: "greatness",
C: "possessions",
D: "affluence",
answer: "D. affluence",
correctLetter: "D",
correctOption: 4,
},

{
id: "question8",
question: ["8. Tunde  ", <UnderlineText key={"2"} text={"seldom"}/>, " asks questions in class and was. ____________ very careful when he did."],
A: "hardly",
B: "sometimes",
C: "often",
D: "never.",
answer: "C. often",
correctLetter: "C",
correctOption: 3,
},

{
section: "2",
sectiontitle: "From the words lettered A to D, choose the word that beht completeh each of the following sentences.",
id: "question9",
question: "9. Tests revealed that the winning athlete had taken performance-ensancing _____________ ",
A: "drugs",
B: "tablets",
C: "vitamins",
D: "capsules",
answer: "A. drugs",
correctLetter: "A",
correctOption: 1,
},

{
id: "question10",
question: "10. The lawyer’s client was ____________ under oath in the law count.",
A: "investigated",
B: "interrogated",
C: "cross-fired",
D: "cross-examined",
answer: "D. cross-examined",
correctLetter: "D",
correctOption: 4,
},

{
id: "question11",
question: "11. The man has a large ____________ of cattle.",
A: "herd",
B: "flock",
C: "multitude",
D: "swine.",
answer: "A. herd",
correctLetter: "A",
correctOption: 1,
},

{
id: "question12",
question: "12. The relationship between the couple is ____________ for lack of communication.",
A: "tense",
B: "strained",
C: "relaxed",
D: "uneasy.",
answer: "B. strained",
correctLetter: "B",
correctOption: 2,
},

{
id: "question13",
question: "13. Many players have complained about biased ____________ by referees.",
A: "officiating",
B: "control",
C: "direction",
D: "handling",
answer: "A. officiating",
correctLetter: "A",
correctOption: 1,
},

{
id: "question14",
question: "14. Government officials have to swear to ____________ of secrecy.",
A: "an oath",
B: "a vow",
C: "a pledge",
D: "an act",
answer: "A. an oath",
correctLetter: "A",
correctOption: 1,
},

{
id: "question15",
question: "15. The students ____________ the planned meeting with the new principal.",
A: "refused",
B: "neglected",
C: "boycotted",
D: "rejected",
answer: "C. boycotted",
correctLetter: "C",
correctOption: 3,
},

{
id: "question16",
question: "16. She won by ____________ because her opponent refused to play.",
A: "defeat",
B: "default",
C: "defiance",
D: "defence.",
answer: "B. default",
correctLetter: "B",
correctOption: 2,
},

{
id: "question17",
question: "17. Some candidates have developed the ____________ for cheating in examinations.",
A: "instinct",
B: "addiction",
C: "knack",
D: "habit",
answer: "C. knack",
correctLetter: "C",
correctOption: 3,
},

{
id: "question18",
question: "18. The secretary was ____________ from her job for absenteeism.",
A: "evicted",
B: "dismissed",
C: "rejected",
D: "eliminated",
answer: "B. dismissed",
correctLetter: "B",
correctOption: 2,
},

{
section: "3",
sectiontitle: "After each of the following sentences, a list of possible interpretations is given. Choose the interpretation that you consider most appropriate for each sentence.",
id: "question19",
question: "19. Peter was on tenterhooks until the examination results were announced. This means that Peter was ______________",
A: "unsappy about the examination.",
B: "suspended from school.",
C: "anxiously waiting for the results",
D: "detained by the police.",
answer: "C. anxiously waiting for the results",
correctLetter: "C",
correctOption: 3,
},

{
id: "question20",
question: "20. The military leader blazed the trial by handing over power to civilians. This means that the leader ______________",
A: "resigned from the army.",
B: "supported civilian ideals",
C: "was against the army",
D: "set an example",
answer: "D. set an example",
correctLetter: "D",
correctOption: 4,
},

{
id: "question21",
question: "21. Life is all about 'give and take'. This means that  _____________ ",
A: "people should be willing to compromise.",
B: "life gives and takes",
C: "life is about gifts",
D: "any gift should be accepted",
answer: "A. people should be willing to compromise",
correctLetter: "A",
correctOption: 1,
},

{
id: "question22",
question: "22. Jumai's life was in danger but now she had turned the corner. This means that Jumai _____________ ",
A: "has given up hope of recovery.",
B: "has worsened her situation.",
C: "is recovering",
D: "has died.",
answer: "C. is recovering",
correctLetter: "C",
correctOption: 3,
},

{
id: "question23",
question: "23. It is unwise for politicians to make off hand statements to journalists. This means that politicians  _____________  ",
A: "should insist on their interviews being recorded",
B: "would be wise not to speak to journalists",
C: "should not make any statement to journalists",
D: "should be sure of whatever they say.",
answer: "D. should be sure of whatever they say",
correctLetter: "D",
correctOption: 4,
},

{
id: "question24",
question: "24. The dentist told his patient that the toothache would pass of when he took Some aspirins. This means that",
A: "the tooth would automatically drop off.",
B: "the pains would subside.",
C: "the pains would spread to other teeth.",
D: "the pains would worsen.",
answer: "B. the pains would subside",
correctLetter: "B",
correctOption: 2,
},

{
id: "question25",
question: "25. The students made such a noise in thee class that the teacher read them the Riot Act. This means that the teacher  _____________ .",
A: "punished all the students.",
B: "instigated the students to riot.",
C: "warned the students to stop the noise or get punished.",
D: "read the school's rules and regulations to the students.",
answer: "C. warned the students to stop the noise or get punished",
correctLetter: "C",
correctOption: 3,
},

{
id: "question26",
question: "26. When I went on leave I asked Mr. Bamson to hold the forte. This means that I asked him to _____________  ",
A: "defend me.",
B: "act in my absence.",
C: "protect my position.",
D: "be strong in my absence.",
answer: "B. act in my absence",
correctLetter: "B",
correctOption: 2,
},

{
id: "question27",
question: "27. The senator's house is the last word in comfort. This means that the senator _____________ ",
A: "has the most comfortable house.",
B: "speaks about the comfort of his house.",
C: "owns the last house on Comfort Street.",
D: "has a house that is not comfortable.",
answer: "D. has a house that is not comfortable",
correctLetter: "D",
correctOption: 4,
},

{
id: "question28",
question: "28. I was given a standing ovation for my outstanding performance. This means that  _____________ ",
A: "everyone stood up to clap for me.",
B: "everyone stood to catch a glimpse of me.",
C: "everyone congratulated me.",
D: "I was asked to stand up.",
answer: "A. everyone stood up to clap for me",
correctLetter: "A",
correctOption: 1,
},

{
section: "4",
sectiontitle: "From the words lettered A. to D below each of the following sentences, choose the word that is nearost in moaning to the underlined word ah it is uhed in the sentence.",
id: "question29",
question: ["29. His father's death  ", <UnderlineText key={"2"} text={"derailed"}/>, " his plans to enter the university"],
A: "discouraged",
B: "failed",
C: "moved",
D: "ruined",
answer: "D. ruined",
correctLetter: "D",
correctOption: 4,
},

{
id: "question30",
question: ["30. Adamu  ", <UnderlineText key={"2"} text={"inadvertently"}/>, " shot his friend dead."],
A: "deliberately",
B: "spontaneously",
C: "accidentally",
D: "inappropriately",
answer: "C. accidentally",
correctLetter: "C",
correctOption: 3,
},

{
id: "question31",
question: ["31. The student made  ", <UnderlineText key={"2"} text={"scathing"}/>, " remarks about the vice chancellor."],
A: "critical",
B: "positive",
C: "mild",
D: "damaging",
answer: "D. damaging",
correctLetter: "D",
correctOption: 4,
},

{
id: "question32",
question: ["32. Several cabinet ministers joined the president's  ", <UnderlineText key={"2"} text={"retinue"}/>, " for the summit conference."],
A: "entourage",
B: "vehicle",
C: "followers",
D: "enemies.",
answer: "A. entourage",
correctLetter: "A",
correctOption: 1,
},

{
id: "question33",
question: ["33. The manager refused his deputy's request in  ", <UnderlineText key={"2"} text={"reprisal"}/>, " for his disloyalty."],
A: "compensation",
B: "annoyance",
C: "retaliation",
D: "exchange.",
answer: "C. retaliation",
correctLetter: "C",
correctOption: 3,
},

{
id: "question34",
question: ["34. She  ", <UnderlineText key={"2"} text={"spurned"}/>, " the advances of her boss."],
A: "accommodated",
B: "accepted",
C: "rejected",
D: "discouraged",
answer: "C. rejected",
correctLetter: "C",
correctOption: 3,
},

{
id: "question35",
question: ["35. Whatever he says is  ", <UnderlineText key={"2"} text={"irrevocable"}/>, ""],
A: "final.",
B: "false",
C: "debatable",
D: "unclear.",
answer: "A. final",
correctLetter: "A",
correctOption: 1,
},

{
id: "question36",
question: ["36. Lunatics have some  ", <UnderlineText key={"2"} text={"lucid"}/>, " moments."],
A: "troubled",
B: "quiet",
C: "noisy",
D: "sane",
answer: "B. quiet",
correctLetter: "B",
correctOption: 2,
},

{
id: "question37",
question: ["37. Don't expect anything but  ", <UnderlineText key={"2"} text={"hypocrisy"}/>, " from politicians."],
A: "promises",
B: "manifestoes",
C: "insincerity",
D: "dishonesty",
answer: "C. insincerity",
correctLetter: "C",
correctOption: 3,
},

{
section: "5",
sectiontitle: "Form the words or group of words lettered A to D, choose the word or group of words that bost complotos each of the following sentences:",
id: "question38",
question: "38. The secretary needs to run ____________ two hundred copies of the previous minutes for the next meeting.",
A: "off",
B: "on.",
C: "out",
D: "over.",
answer: "A. off",
correctLetter: "A",
correctOption: 1,
},

{
id: "question39",
question: "39. Let us keep ____________ the plans we made earlier.",
A: "away",
B: "to",
C: "off",
D: "on",
answer: "B. to",
correctLetter: "B",
correctOption: 2,
},

{
id: "question40",
question: "40. To be alive after such a serious accident ____________ a celebration.",
A: "is called for",
B: "calls for",
C: "has been called for",
D: "call for.",
answer: "B. calls for",
correctLetter: "B",
correctOption: 2,
},

{
id: "question41",
question: "41. She does not remember ever ____________ a tiger",
A: "to see",
B: "to have seen",
C: "seeing",
D: "having to see",
answer: "C. seeing",
correctLetter: "C",
correctOption: 3,
},

{
id: "question42",
question: "42. The Commissioner for Education with his secretary ____________ expected yesterday.",
A: "are",
B: "was",
C: "were",
D: "is.",
answer: "D. is",
correctLetter: "D",
correctOption: 4,
},

{
id: "question43",
question: "43. After rigorous interrogation, the thief had no alternative. ____________ to confess the truth.",
A: "except",
B: "unless",
C: "but",
D: "rather.",
answer: "C. but",
correctLetter: "C",
correctOption: 3,
},

{
id: "question44",
question: "44. The director is open ____________ criticism.",
A: "for",
B: "to",
C: "on",
D: "about",
answer: "B. to",
correctLetter: "B",
correctOption: 2,
},

{
id: "question45",
question: "45. Tunji divided the money between David and _____________ ",
A: "he",
B: "him",
C: "himself",
D: "themselves.",
answer: "C. himself",
correctLetter: "C",
correctOption: 3,
},

{
id: "question46",
question: "46. The jury gave. ____________ verdict.",
A: "it's",
B: "its",
C: "his",
D: "her",
answer: "B. its",
correctLetter: "B",
correctOption: 2,
},

{
id: "question47",
question: "47. No ____________ person will do that.",
A: "matured",
B: "maturing",
C: "mature",
D: "matures",
answer: "C. mature",
correctLetter: "C",
correctOption: 3,
},

{
id: "question48",
question: "48. She stabbed her friend ____________ the back.",
A: "on",
B: "at",
C: "upon",
D: "in",
answer: "B. at",
correctLetter: "B",
correctOption: 2,
},

{
id: "question49",
question: "49. I am not accustomed ____________ on an empty stomach.",
A: "to sleep",
B: "to have slept",
C: "for sleeping",
D: "to sleeping",
answer: "D. to sleeping",
correctLetter: "D",
correctOption: 4,
},

{
id: "question50",
question: "50. Take your share and give them _____________ ",
A: "their",
B: "there",
C: "there's",
D: "theirs",
answer: "D. theirs",
correctLetter: "D",
correctOption: 4,
},

{
id: "question51",
question: "51. My uncle was not sure ____________ the strange guests were.",
A: "which",
B: "who",
C: "whom",
D: "what",
answer: "B. who",
correctLetter: "B",
correctOption: 2,
},

{
id: "question52",
question: "52. The Principal has already summoned all the ____________ on the matter.",
A: "heads of departments",
B: "head of department",
C: "heads of department",
D: "head of departments",
answer: "C. heads of department",
correctLetter: "C",
correctOption: 3,
},

{
id: "question53",
question: "53. But for the timely intervention of the police, the kidnapper ____________ by the angry mob.",
A: "will be lynched",
B: "would have been lynched",
C: "would be lynched",
D: "will have been lynched.",
answer: "B. would have been lynched",
correctLetter: "B",
correctOption: 2,
},

{
id: "question54",
question: "54. _____________ she was tired when we arrived, Mummy prepared delicious dinner for us.",
A: "Despite",
B: "If",
C: "Since",
D: "Although.",
answer: "D. Although",
correctLetter: "D",
correctOption: 4,
},

{
id: "question55",
question: "55. __________ Science and Technology many African countries have not made significant progress since their independence.",
A: "With regards to",
B: "In respect to",
C: "As far as",
D: "With regard to",
answer: "D. With regard to",
correctLetter: "D",
correctOption: 4,
},

{
id: "question56",
question: "56. If I. ____________ your father, I would call thee police",
A: "have been",
B: "am",
C: "will be",
D: "were",
answer: "D. were",
correctLetter: "D",
correctOption: 4,
},

{
id: "question57",
question: "57. I hate _____________ waiting.",
A: "to be keeping",
B: "having been kept",
C: "being kept",
D: "to have been kept.",
answer: "C. being kept",
correctLetter: "C",
correctOption: 3,
},

{
id: "question58",
question: "58. You had better ____________ the examination.",
A: "written",
B: "write",
C: "wrote",
D: "be writing",
answer: "B. write",
correctLetter: "B",
correctOption: 2,
},

{
id: "question59",
question: "59. The policeman tried to cash in. ____________ the driver's ignorance.",
A: "under",
B: "against",
C: "on",
D: "with",
answer: "C. on",
correctLetter: "C",
correctOption: 3,
},

{
id: "question60",
question: "60. Yesterday, I ____________ on the beach for half an hour.",
A: "lain",
B: "lay",
C: "lie",
D: "lied",
answer: "B. lay",
correctLetter: "B",
correctOption: 2,
},

{
id: "question61",
question: "61. We were told to mind our business during the examination and not _____________ ",
A: "somebody's else",
B: "somebody else's",
C: "somebody's else's",
D: "somebody else",
answer: "B. somebody else's",
correctLetter: "B",
correctOption: 2,
},

{
id: "question62",
question: "62. Whenever you travel buy me ____________ please",
A: "a trouser",
B: "one trouser",
C: "a pair of trousers",
D: "trouser",
answer: "C. a pair of trousers",
correctLetter: "C",
correctOption: 3,
},

{
id: "question63",
question: "63. The Housemaster asked Ekene whether he had ever ____________ the marathon.",
A: "run",
B: "ran",
C: "running",
D: "runs",
answer: "A. run",
correctLetter: "A",
correctOption: 1,
},

{
id: "question64",
question: "64. The maid denied ________________ her mistress' money.",
A: "to stealing",
B: "stolen",
C: "to have stolen",
D: "stealing",
answer: "D. stealing",
correctLetter: "D",
correctOption: 4,
},

{
id: "question65",
question: "65. One of the victims ____________ rushed to the nearest hospital.",
A: "was",
B: "have been",
C: "were",
D: "were being",
answer: "A. was",
correctLetter: "A",
correctOption: 1,
},

{
id: "question66",
question: "66. Bachelors find it convenient to buy ____________ pepper.",
A: "grind",
B: "grinding",
C: "ground",
D: "grounded",
answer: "C. ground",
correctLetter: "C",
correctOption: 3,
},

{
id: "question67",
question: "67. I heard the news ____________ the radio.",
A: "from",
B: "by",
C: "on",
D: "through",
answer: "C. on",
correctLetter: "C",
correctOption: 3,
},

{
id: "question68",
question: "68. The invigilator had hardly turned her back ____________ the candidate was caught cheating.",
A: "than",
B: "when",
C: "hence",
D: "that",
answer: "B. when",
correctLetter: "B",
correctOption: 2,
},

{
id: "question69",
question: "69. Of the three girls, Yetunde is the _____________  ",
A: "tallest",
B: "taller",
C: "most tall",
D: "tall",
answer: "A. tallest",
correctLetter: "A",
correctOption: 1,
},

{
id: "question70",
question: "70. It was Peter that I saw, ____________ ?",
A: "wasn't it",
B: "didn't I",
C: "isn't it",
D: "wasn't he",
answer: "D. wasn't he",
correctLetter: "D",
correctOption: 4,
},

{
id: "question71",
question: "71. They finally broke ____________ after years of being together.",
A: "up",
B: "away",
C: "out",
D: "in",
answer: "A. up",
correctLetter: "A",
correctOption: 1,
},

{
id: "question72",
question: "72. When I was in school, boarders ____________ very early every morning.",
A: "are rising",
B: "have risen",
C: "had to rise",
D: "have to rise",
answer: "C. had to rise",
correctLetter: "C",
correctOption: 3,
},

{
id: "question73",
question: "73. ________________ of the two girls sang sweetly.",
A: "Every one",
B: "Each",
C: "Some",
D: "All.",
answer: "B. Each",
correctLetter: "B",
correctOption: 2,
},

{
section: "6",
sectiontitle: "In the following passages, the numbered gaps indicate missing words. Against each number in the list below each passage, four options are offered in column lettered A to D. Choose the word that is the most suitable to fill the numbered gap in the passages",
passage: "Last month our school marked her diamond jubilee with a double celebration: an inter house sports competition in the morning and a football match later in the afternoon. The former was very exciting as many -74- were broken and several new ones were set. The most exciting were the -75- events, especially the 100 metres -76-, the 200 metres hurdles and the -77- races. The -78- did not seem particularly interested in the -79- events. Expectedly, the football match drew a very large crowd because of the reputation of the two contesting teams. The -80- was taken by the State Administrator who was the special -81-. Our team played excellent soccer: the -82- were accurate and our players displayed such -83- that the spectators were not surprised when, by the end of the - 84- they had scored three goals to nil. In the second half, one of our players was shown a -85- for a rough -86-. Although our opponents were awarded a -87- our -88- was so smart the he did not concede a goal.",
id: "question74",
question: "74. *********************",
A: "records",
B: "trophies",
C: "titles",
D: "events",
answer: "A. records",
correctLetter: "A",
correctOption: 1,
},

{
id: "question75",
question: "75. *********************",
A: "path",
B: "track",
C: "road",
D: "race.",
answer: "B. track",
correctLetter: "B",
correctOption: 2,
},

{
id: "question76",
question: "76. *********************",
A: "run",
B: "lap",
C: "dash",
D: "finish",
answer: "B. lap",
correctLetter: "B",
correctOption: 2,
},

{
id: "question77",
question: "77. *********************",
A: "fast",
B: "single",
C: "group",
D: "relay",
answer: "D. relay",
correctLetter: "D",
correctOption: 4,
},

{
id: "question78",
question: "78. *********************",
A: "audience",
B: "congregation",
C: "spectators",
D: "mob",
answer: "C. spectators",
correctLetter: "C",
correctOption: 3,
},

{
id: "question79",
question: "79. *********************",
A: "athletic",
B: "field",
C: "sport",
D: "house",
answer: "B. field",
correctLetter: "B",
correctOption: 2,
},

{
id: "question80",
question: "80. *********************",
A: "kick-off",
B: "short",
C: "kick out",
D: "pass",
answer: "A. kick-off",
correctLetter: "A",
correctOption: 1,
},

{
id: "question81",
question: "81. *********************",
A: "chief of ceremonies",
B: "guest of honour",
C: "master of ceremonies",
D: "guard of honour",
answer: "B. guest of honour",
correctLetter: "B",
correctOption: 2,
},

{
id: "question82",
question: "82. *********************",
A: "shootings",
B: "moves",
C: "passes",
D: "dribbling",
answer: "C. passes",
correctLetter: "C",
correctOption: 3,
},

{
id: "question83",
question: "83. *********************",
A: "combination",
B: "understanding",
C: "co-operation",
D: "team work",
answer: "D. team work",
correctLetter: "D",
correctOption: 4,
},

{
id: "question84",
question: "84. *********************",
A: "break",
B: "half- way",
C: "interval",
D: "first-half",
answer: "D. first-half",
correctLetter: "D",
correctOption: 4,
},

{
id: "question85",
question: "85. *********************",
A: "blue card",
B: "white card",
C: "red card",
D: "green card",
answer: "C. red card",
correctLetter: "C",
correctOption: 3,
},

{
id: "question86",
question: "86. *********************",
A: "dribbling",
B: "passing",
C: "rushing",
D: "tackle",
answer: "D. tackle",
correctLetter: "D",
correctOption: 4,
},

{
id: "question87",
question: "87. *********************",
A: "penalty-kick",
B: "throw -in",
C: "back-pass",
D: "corner-kick",
answer: "A. penalty-kick",
correctLetter: "A",
correctOption: 1,
},

{
id: "question88",
question: "88. *********************",
A: "mid-fielder",
B: "goal-keeper",
C: "defender",
D: "striker",
answer: "B. goal-keeper",
correctLetter: "B",
correctOption: 2,
},

{
passage: "The airport had a big tarmac and a wide -89-. Departure time for our flight was announced and all the passengers -90- to -91- the plane. Soon the aircraft began to -92- for -93- and in a few moments, we were -94- in no time, we were lost in the -95-. A beautiful young -96- was meanwhile standing in the -97-, close the cockpit, demonstrating security -98- in the event of an emergency. All along, the engines of the plane -99- and provided a background of sinister -100-.",
id: "question89",
question: "89. *********************",
A: "air- strip",
B: "runway",
C: "stretch",
D: "expressway",
answer: "B. runway",
correctLetter: "B",
correctOption: 2,
},

{
id: "question90",
question: "90. *********************",
A: "stretched out",
B: "fell out",
C: "queued up",
D: "moved up",
answer: "C. queued up",
correctLetter: "C",
correctOption: 3,
},

{
id: "question91",
question: "91. *********************",
A: "ascend",
B: "climb",
C: "board",
D: "embark",
answer: "C. board",
correctLetter: "C",
correctOption: 3,
},

{
id: "question92",
question: "92. *********************",
A: "race",
B: "speed",
C: "fly",
D: "taxi",
answer: "D. taxi",
correctLetter: "D",
correctOption: 4,
},

{
id: "question93",
question: "93. *********************",
A: "take-off",
B: "take-up",
C: "departure",
D: "flight",
answer: "A. take-off",
correctLetter: "A",
correctOption: 1,
},

{
id: "question94",
question: "94. *********************",
A: "floating",
B: "coasting",
C: "air - borne",
D: "air - lifted",
answer: "C. air - borne",
correctLetter: "C",
correctOption: 3,
},

{
id: "question95",
question: "95. *********************",
A: "atmosphere",
B: "clouds",
C: "skies",
D: "heavens.",
answer: "B. clouds",
correctLetter: "B",
correctOption: 2,
},

{
id: "question96",
question: "96. *********************",
A: "lady",
B: "waitress",
C: "maid",
D: "air-hostess",
answer: "D. air-hostess",
correctLetter: "D",
correctOption: 4,
},

{
id: "question97",
question: "97. *********************",
A: "aisle",
B: "corridor",
C: "strait",
D: "passage",
answer: "A. aisle",
correctLetter: "A",
correctOption: 1,
},

{
id: "question98",
question: "98. *********************",
A: "methods",
B: "programmes",
C: "measures",
D: "plans",
answer: "C. measures",
correctLetter: "C",
correctOption: 3,
},

{
id: "question99",
question: "99. *********************",
A: "burred",
B: "clattered",
C: "creaked",
D: "hummed",
answer: "D. hummed",
correctLetter: "D",
correctOption: 4,
},

{
id: "question100",
question: "100. *********************",
A: "sound",
B: "droning",
C: "cacophony",
D: "disturbance",
answer: "C. cacophony",
correctLetter: "C",
correctOption: 3,
},



]