export const SOCIALSTUDIESA2004 = [

{
id: "question1",
question: "1. The main aim of cross-cousin marriage among some ethnic groups in Ghana is to",
A: "Ensure stability of marriage",
B: "Promote exogamy",
C: "Prevent endogamy",
D: "Protect family property",
answer: "D. protect family property",
correctLetter: "D",
correctOption: 4,
},

{
id: "question2",
question: "2. An advantage of a duolocal residence of marriage is that the woman receives",
A: "Spiritual protection from ancestors",
B: "Financial support from her parents",
C: "Adequate post-natal care from her parents",
D: "Vocational training from her father",
answer: "B. financial support from her parents",
correctLetter: "B",
correctOption: 2,
},

{
id: "question3",
question: "3. If a man decides to break a marriage which is under the ordinance, the court will force him to",
A: "Pay bride wealth to the woman’s family",
B: "Pay alimony to the divorced woman",
C: "Give all his assets to the divorced woman",
D: "Will his assets to the children",
answer: "B. pay alimony to the divorced woman",
correctLetter: "B",
correctOption: 2,
},

{
id: "question4",
question: "4. One of the psychological effects of divorce on women is",
A: "Premature menopause",
B: "Denial of sexual intercourse",
C: "Emotional stress",
D: "Financial difficulties",
answer: "C. emotional stress",
correctLetter: "C",
correctOption: 3,
},

{
id: "question5",
question: "5. An effective way of dealing with drug addicts in schools is",
A: "Dismissal",
B: "Lashing",
C: "Counselling",
D: "Suspension",
answer: "C. counselling",
correctLetter: "C",
correctOption: 3,
},

{
id: "question6",
question: "6. Which of the following is considered a good quality of a person?",
A: "Being strict always in the upbringing of the child",
B: "Adapting to different situations when dealing with the child",
C: "Always praising and defending the child",
D: "Encouraging the child to be self-centred",
answer: "B. Adapting to different situations when dealing with the child",
correctLetter: "B",
correctOption: 2,
},

{
id: "question7",
question: "7. The percentage of the dependency group is",
A: "58.0 per cent",
B: "53.4 per cent",
C: "42.0 per cent",
D: "4.6 per cent",
answer: "A. 58",
correctLetter: "A",
correctOption: 1,
},

{
id: "question8",
question: "8. What percentage of the population constitutes the working force?",
A: "95.4 per cent",
B: "53.0 per cent",
C: "46.6 percent",
D: "42.0 percent",
answer: "D. 42",
correctLetter: "D",
correctOption: 4,
},

{
id: "question9",
question: "9. The population statistics represent",
A: "High dependency ratio",
B: "Low dependency ratio",
C: "Low fertility rate",
D: "High mortality rate",
answer: "A. high dependency ratio",
correctLetter: "A",
correctOption: 1,
},

{
id: "question10",
question: "10. The imposition of a curfew limits the individual’s right of",
A: "Worship",
B: "Association",
C: "Movement",
D: "Ownership",
answer: "C. movement",
correctLetter: "C",
correctOption: 3,
},

{
id: "question11",
question: "11. The Commission on Human Rights and Administrative Justice (CHRAJ) in Ghana seeks to promote",
A: "Formation of civil groups",
B: "Rule of law",
C: "Political tolerance",
D: "Self independence",
answer: "B. rule of law",
correctLetter: "B",
correctOption: 2,
},

{
id: "question12",
question: "12. Which of the following rights exist independently of the laws of the state? *",
A: "Civil rights",
B: "Natural rights",
C: "Political rights",
D: "Economic rights",
answer: "B. Natural rights",
correctLetter: "B",
correctOption: 2,
},

{
id: "question13",
question: "13. Low productivity in the agricultural sector in Ghana can be attributed to",
A: "Unwillingness of the youth to go into farming",
B: "Superstitious beliefs among farmers",
C: "Introduction of plantation farming",
D: "Willingness of farmers to accept new techniques of farming",
answer: "A. unwillingness of the youth to go into farming",
correctLetter: "A",
correctOption: 1,
},

{
id: "question14",
question: "14. Which of the following is a civic responsibility?",
A: "Playing in the national football team",
B: "Taking part in a civil unrest",
C: "Protecting the assets of the state",
D: "Winning a national award",
answer: "C. Protecting the assets of the state",
correctLetter: "C",
correctOption: 3,
},

{
id: "question15",
question: "15. Knowledge of oneself enables the individual to",
A: "Acquire quality education",
B: "Conform to traditional beliefs",
C: "Secure better employment",
D: "Take right decisions",
answer: "D. take right decisions",
correctLetter: "D",
correctOption: 4,
},

{
id: "question16",
question: "16. The basic force of motivating the individual is",
A: "Self-determination",
B: "Self-centredness",
C: "Self-abasement",
D: "Self-complacency",
answer: "A. self-determination",
correctLetter: "A",
correctOption: 1,
},

{
id: "question17",
question: "17. Social norms and values are mainly acquired in the traditional society through",
A: "Formal education",
B: "informal education",
C: "non formal education",
D: "religious education",
answer: "B. informal education",
correctLetter: "B",
correctOption: 2,
},

{
id: "question18",
question: "18. Storytelling, as a socialization process, enables a child to",
A: "Become a historian in future",
B: "be a poet and an orator",
C: "Develop keen interest in entertainment",
D: "acquire desirable habits and values of society",
answer: "D. acquire desirable habits and values of society",
correctLetter: "D",
correctOption: 4,
},

{
id: "question19",
question: "19. Which of the following social control mechanisms in educational institutions undermines the rights of the child?",
A: "Internal suspension",
B: "Indefinite suspension",
C: "Corporal punishment",
D: "Outright dismissal",
answer: "C. Corporal punishment",
correctLetter: "C",
correctOption: 3,
},

{
id: "question41",
question: "41. Which of the following contributes to the low standard of living in Ghana?",
A: "Inadequate rainfall",
B: "Unstable governance",
C: "High dependency ratio",
D: "High literacy rate",
answer: "C. High dependency ratio",
correctLetter: "C",
correctOption: 3,
},

{
id: "question42",
question: "42. Sustainable development in a country thrives in an environment of",
A: "Political stability",
B: "Adequate natural resources",
C: "Potential capital resources",
D: "Abundant manpower",
answer: "A. political stability",
correctLetter: "A",
correctOption: 1,
},

{
id: "question20",
question: "20. The Dipo puberty rites among the Krobo need to be preserved because it is a mechanism for",
A: "Preventing adultery lo",
B: "Decreasing population growth rate",
C: "Increasing fertility rate",
D: "Maintaining adolescence chastity",
answer: "D. maintaining adolescence chastity",
correctLetter: "D",
correctOption: 4,
},

{
id: "question43",
question: "43. One basic way of improving the standard of living in Ghana is to",
A: "Increase the tax rate",
B: "Make education accessible to all",
C: "Provide free common needs to all",
D: "Encourage more foreign investment",
answer: "B. make education accessible to all",
correctLetter: "B",
correctOption: 2,
},

{
id: "question44",
question: "44. Labour disputes are best settled through",
A: "Confrontation",
B: "Resolution",
C: "Arbitration",
D: "Agitation",
answer: "C. arbitration",
correctLetter: "C",
correctOption: 3,
},

{
id: "question21",
question: "21. The cultural heritage of a people forms the basis of their",
A: "Statehood",
B: "Enlightenment",
C: "Sovereignty",
D: "Civilization",
answer: "D. civilization",
correctLetter: "D",
correctOption: 4,
},

{
id: "question45",
question: "45. The value of Ghana’s currency can be appreciated through",
A: "Generation of local funds",
B: "Attraction of foreign investors",
C: "Importation of foreign goods",
D: "Increased exports",
answer: "D. increased exports",
correctLetter: "D",
correctOption: 4,
},

{
id: "question46",
question: "46. Which of the following business units has shareholders with limited liability?",
A: "Sole proprietorship",
B: "State enterprise",
C: "Partnership",
D: "Private joint stock company",
answer: "C. Partnership",
correctLetter: "C",
correctOption: 3,
},

{
id: "question22",
question: "22. Which of the following contributes to chieftaincy disputes in Ghana?  \nI.	Sale of stool lands  \nII.	Succession conflict  \nIII.	Quest for power  \nIV.	Refusal to perform naming ceremonies  \nV.	Curses from the ancestors",
A: "I, II and IV only",
B: "I, III and III only",
C: "III, IV and V only",
D: "I, III and IV only",
answer: "B. I, II and III only",
correctLetter: "B",
correctOption: 2,
},

{
id: "question47",
question: "47. Entrepreneurs engage in productive activities in order to",
A: "Earn salaries",
B: "Develop their talents",
C: "Make profits",
D: "Gain experience",
answer: "C. make profits",
correctLetter: "C",
correctOption: 3,
},

{
id: "question48",
question: "48. While it is easy to establish the sole proprietorships business, it is difficult to",
A: "Plough back profit",
B: "Register the business",
C: "Raise adequate capital for its operation",
D: "Keep a current account in a bank",
answer: "C. raise adequate capital for its operation",
correctLetter: "C",
correctOption: 3,
},

{
id: "question23",
question: "23. During traditional festivals, chiefs use the sword mainly for",
A: "Dancing",
B: "Oath swearing",
C: "Ritual purpose",
D: "Incantation",
answer: "B. oath swearing",
correctLetter: "B",
correctOption: 2,
},

{
id: "question49",
question: "49. Greater profits are made in a business organization through",
A: "The availability of computers",
B: "A stable labour environment",
C: "The reliance on forced labour",
D: "A communication network",
answer: "B. a stable labour environment",
correctLetter: "B",
correctOption: 2,
},

{
id: "question50",
question: "50. The best method of preventing bush fire in Ghana is to",
A: "Farm near water bodies",
B: "Plant more trees",
C: "Stop hunting with fire during the dry season",
D: "Train more fire and forest guards",
answer: "C. stop hunting with fire during the dry season",
correctLetter: "C",
correctOption: 3,
},

{
id: "question24",
question: "24. Taboos in the traditional society are means of",
A: "Serving the gods",
B: "Social control",
C: "Honouring the ancestors",
D: "Promoting religion",
answer: "B. social control",
correctLetter: "B",
correctOption: 2,
},

{
id: "question25",
question: "25. One positive effect of cultural integration is",
A: "Increase in traditional religion",
B: "Promotion of stable society",
C: "Creation of markets for artefacts",
D: "Abolition of polygamous marriage",
answer: "B. promotion of stable society",
correctLetter: "B",
correctOption: 2,
},

{
id: "question26",
question: "26. Among the Akans, the responsibility to nominate and install a chief lies in the hands of the",
A: "Head of the royal family and the traditional priest",
B: "Traditional priest and the queen mother",
C: "Queen mother and the kingmakers",
D: "Head of the royal family and the Asafo company",
answer: "C. queen mother and the kingmakers",
correctLetter: "C",
correctOption: 3,
},

{
id: "question27",
question: "27. The main symbol of authority of a Ghanaian chief is the",
A: "State sword",
B: "Stool or a skin",
C: "Palanquin or a horse",
D: "Linguist staff",
answer: "A. state sword",
correctLetter: "A",
correctOption: 1,
},

{
id: "question28",
question: "28. Which of the following national symbols is used to signify State Mourning?",
A: "The State Sword",
B: "The National Flag",
C: "The Coast-of-Arms",
D: "The National Anthem",
answer: "B. The National Flag",
correctLetter: "B",
correctOption: 2,
},

{
id: "question29",
question: "29. The concept of national identity promotes",
A: "National integration",
B: "National diversity",
C: "Ethnic diversity",
D: "Ethnic unity",
answer: "A. national integration",
correctLetter: "A",
correctOption: 1,
},

{
id: "question30",
question: "30. The principal stakeholders of a constitution of a democratic state are the",
A: "Members of the executive",
B: "Members of parliament",
C: "Security agencies",
D: "People of the country",
answer: "D. people of the country",
correctLetter: "D",
correctOption: 4,
},

{
id: "question31",
question: "31. A constitution is very important because it  \nI.	Limits the arbitrary actions of government  \nII.	Guarantees the rights of the government to rule.  \nIII.	Limits the powers of the elite  \nIV.	Portrays the cultural heritage of the people",
A: "I and II only",
B: "II and III only",
C: "III and IV only",
D: "I and IV only",
answer: "A. I and II only",
correctLetter: "A",
correctOption: 1,
},

{
id: "question32",
question: "32. One disadvantage of a democratic type of leadership is that",
A: "In times of crises decision making is unduly delayed",
B: "Certain powerful persons easily dominate the scene",
C: "The goals of the group are not achieved",
D: "followers get discouraged because their initiatives are killed",
answer: "A. in times of crises decision making is unduly delayed",
correctLetter: "A",
correctOption: 1,
},

{
id: "question33",
question: "33. The main objective of the rule of law is to",
A: "Give more powers to the judiciary",
B: "Give absolute powers to the executive",
C: "Promote the freedom of speech and expression",
D: "Prevent arbitrary and tyrannical rule",
answer: "D. prevent arbitrary and tyrannical rule",
correctLetter: "D",
correctOption: 4,
},

{
id: "question34",
question: "34. The District Assembly concept in Ghana is based on the practice of",
A: "Localization",
B: "Decentralization",
C: "Politicization",
D: "Capitalization",
answer: "B. decentralization",
correctLetter: "B",
correctOption: 2,
},

{
id: "question35",
question: "35. One main reason for the limited trading activity among West African states is the",
A: "Institution of tight border controls",
B: "Introduction of party politics",
C: "Attachment to former colonial masters",
D: "Predominance of weak currencies",
answer: "A. institution of tight border controls",
correctLetter: "A",
correctOption: 1,
},

{
id: "question36",
question: "36. A major effect of conflicts in the world today is that",
A: "Development projects are limited",
B: "Many people suffer from starvation",
C: "Peace keepers get more pay",
D: "Firearms are produced",
answer: "B. many people suffer from starvation",
correctLetter: "B",
correctOption: 2,
},

{
id: "question37",
question: "37. Ghana has contributed significantly to the United Nations Organization (UNO) through",
A: "Paying salaries of UNO workers",
B: "Prosecuting war criminals",
C: "Undertaking peace-keeping operations",
D: "Supplying cocoa to the world market",
answer: "C. undertaking peace-keeping operations",
correctLetter: "C",
correctOption: 3,
},

{
id: "question38",
question: "38. The depletion of the ozone layer has been traced to",
A: "Excessive increase in plant diseases",
B: "Low temperatures of plant disease",
C: "Creation of forest reserves",
D: "Emitting of chlorofluorocarbons into the atmosphere",
answer: "D. emitting of chlorofluorocarbons into the atmosphere",
correctLetter: "D",
correctOption: 4,
},

{
id: "question39",
question: "39. The physical environment in Ghana is deteriorating rapidly because",
A: "There is increased pressure on its natural resources",
B: "More complex tools and machines are used in farming",
C: "The world’s climate is changing very fast",
D: "There is flooding after every rain in the cities",
answer: "A. there is increased pressure on its natural resources",
correctLetter: "A",
correctOption: 1,
},

{
id: "question40",
question: "40. Game reserves in the country",
A: "Promote sporting activities",
B: "Preserve endangered animal species",
C: "Add aesthetic value to the environment",
D: "Create employment for urban dwellers",
answer: "B. preserve endangered animal species",
correctLetter: "B",
correctOption: 2,
},



]