export const SOCIALSTUDIESA2023 = [

{
id: "question1",
question: "1. One primary objective of the New Partnership for Africa's Development is to",
A: "create structures to monitor progress of development in Africa.",
B: "create peer review mechanism among African nations.",
C: "sign an agreement with African nations.",
D: "eradicate poverty through accelerated growth and development in Africa.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question2",
question: "2. A constitutional rule ensures that the",
A: "citizens can act in any manner.",
B: "executive acts within the law.",
C: "legislature is above the other organs of government.",
D: "judiciary cannot be checked.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question3",
question: "3. The symbol that best helps to foster allegiance to the state of Ghana is",
A: "Gye Nyaine.",
B: "Sankofa.",
C: "The Independent Ark.",
D: "The National Flag.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question4",
question: "4. When there is conflict between personal and national interest in the exercise of rights and responsibilities, the individual must place",
A: "social interest first.",
B: "personal interest first.",
C: "political party interest first.",
D: "ethnic interest first.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question5",
question: "5. The constitution is important in nation building effort because it",
A: "allocates powers to the organs of government.",
B: "prevents criticism of the government.",
C: "is approved by parliament.",
D: "can be written or unwritten.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question6",
question: "6. The best way of resolving parent-child conflict is",
A: "being consistent in dealing with children.",
B: "avoiding over-protection of children.",
C: "adhering to the rules of the home.",
D: "keeping children away from misbehaviour.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question7",
question: "7. To ensuTe stability in marriage, couples must",
A: "pamper their children.",
B: "encourage consensus building.",
C: "resort to divorce.",
D: "have more children.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question8",
question: "8. Which of the following options is not an agency of socialization ?",
A: "Family.",
B: "Mosque.",
C: "Youth clubs.",
D: "Peers.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question9",
question: "9. To make education play its proper role in changing society, the following measures must be taken except",
A: "improving technical and vocational education.",
B: "placing emphasis on literacy education.",
C: "providing infrastructural facilities in Ghana.",
D: "making the content of education institutions reflect the needs of society.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question10",
question: "10. Irresponsible parenting results in",
A: "large family size.",
B: "child abuse.",
C: "poverty.",
D: "peer pressure.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question11",
question: "11. Democratic governance can best be sustained in Ghana through the",
A: "expansion of compulsory basic education programme.",
B: "intensification of national service programme for the youth.",
C: "enhancement of periodic free and fair eSection.",
D: "institution of entrepreneurial training programmes for the unemployed.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question12",
question: "12. Which of the following elements of our culture is common to all the ethnic groups in Ghana?",
A: "The language we speak",
B: "Music and dance",
C: "The institution of chieftaincy",
D: "Names given to people",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question13",
question: "13. Improvement in the manufacturing of medicine has led to the",
A: "reduction in mortality rate.",
B: "development of the varieties of herbs",
C: "increase in contagious diseases.",
D: "advent of high medical bills.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question14",
question: "14. Which of the following is not a reason for people's right to be curtailed?",
A: "When the decisions and policies of the government are opposed.",
B: "When a state of emergency is declared.",
C: "When there is an outbreak of war.",
D: "When there is an epidemic of a contagious disease.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question15",
question: "15. The conscious effort to create an atmosphere of harmonious living in a society is known as",
A: "peace building.",
B: "conflict management.",
C: "peace keeping.",
D: "conflict resolution.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question16",
question: "16. A leadership style which does not promote personal initiative among followed‘s is",
A: "Delegative.",
B: "Democratic.",
C: "Autocratic.",
D: "Laissez-faire.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question17",
question: "17. When deviant behaviour is not punished, it has the tendency of encouraging",
A: "tolerance of law breakers.",
B: "recruitment into the security services.",
C: "apathy among law-abiding citizens.",
D: "respect for human rights.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question18",
question: "18. One of the inip!ic ions of neglecting one's family is",
A: "loss of‘oiie s identity.",
B: "high cost of living for the individual.",
C: "inability to achieve self-actualization.",
D: "inadequate care for dependents.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question19",
question: "19. The best way to create sustainable financial security for the future is by",
A: "receiving and keeping money on behalf of others.",
B: "investing money into a productive venture.",
C: "joining pressure groups to draw resources together.",
D: "improving standard of living through hard work.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question20",
question: "20. In arriving at a decision to bring development to a community, the first thing to consider is",
A: "availability of resources.",
B: "needs of the community.",
C: "interest of the leaders.",
D: "support of the community.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question21",
question: "21. The desire of an adolescent to assume false identity could influence the person to",
A: "act irresponsibly.",
B: "stay focused.",
C: "act responsibly.",
D: "act reasonably.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question22",
question: "22. The ultimate aim of socio-economic development is to",
A: "improve the standard of living of the people.",
B: "enhance the cost of living.",
C: "create more job opportunities.",
D: "establish more industries.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question23",
question: "23. When the larger percentage of the country's population is under the age of fifteen, it implies",
A: "a higher dependency burden in future.",
B: "an increase in the labour force.",
C: "a lot of people are in the working class.",
D: "a decrease in the labour force.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question24",
question: "24. Social development in Ghana is usually measured by the",
A: "quality of life of the people.",
B: "population increase in the country.",
C: "employment in the security services.",
D: "economic growth of the country.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question25",
question: "25. A leadership style that allows for free expression of views to arrive at a decision through consensus is",
A: "Paternalistic.",
B: "Democratic.",
C: "Laissez-faire.",
D: "Autocratic.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question26",
question: "26. When an individual develops to the. highest potential, one is said to have achieved",
A: "self-actualization.",
B: "self-determination",
C: "self-confidence.",
D: "self-identity.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question27",
question: "27. One of the benefits of sex education is",
A: "treatment of sexually transmitted diseases.",
B: "promotion of social relationship.",
C: "promotion of good gender relationship.",
D: "termination of unwanted pregnancies.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question28",
question: "28. Which of the following condition does not constitute a challenge in marriage?",
A: "Spousal abuse",
B: "Interference by in-laws",
C: "Sexual compatibility",
D: "Separation of couple",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question29",
question: "29. A social implication of Ghana's youthful population structure is the",
A: "high dependency burden.",
B: "need for more schools.",
C: "low savings from earnings.",
D: "low capital accumulation.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question30",
question: "30. The reason for which governments give support to small-scale enterprises is to",
A: "encourage entrepreneurship.",
B: "create access to markets.",
C: "encourage savings.",
D: "gain popularity",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question31",
question: "31. Positive change in attitude at the workplace ultimately",
A: "improves living standards.",
B: "promotes peaceful co-existence.",
C: "improves upon job creation.",
D: "promotes social initiatives.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question32",
question: "32. Extended family support is best realized during",
A: "funerals.",
B: "festivals.",
C: "marriage ceremonies.",
D: "outdooring ceremonies.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question33",
question: "33. Farming activities in Ghana are largely influenced by",
A: "tree felling.",
B: "vegetation growth.",
C: "shifting cultivation.",
D: "seasonal changes.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question34",
question: "34. The ability to think, create, control the environment and solve problems refers to one's",
A: "capabilities.",
B: "determination.",
C: "development.",
D: "achievement.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question35",
question: "35. The term chastity refers to",
A: "having sexual intercourse once a while.",
B: "abstaining from sexuaJ intercourse.",
C: "refraining from immoral activities.",
D: "abstaining from sexually related activities until marriage.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question36",
question: "36. Ghana's independence is not absolute because of her over dependence on",
A: "The Commonwealth.",
B: "foreign financial aid.",
C: "educational facilities.",
D: "The United Nations Organization.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question37",
question: "37. To avoid incurring unmanageable debts, the individual must",
A: "use loans productively.",
B: "contract only sofi loans.",
C: "take unnecessary loans.",
D: "borrow from friends only.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question38",
question: "38. To meet the energy demands of households, more emphasis should be laid on the use of",
A: "kerosene.",
B: "diesel.",
C: "firewood.",
D: "Liquefied Petroleum Gas.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question39",
question: "39. Any alteration in the structure of society's social organizations, institutions and behavioural patterns is known as",
A: "physical change.",
B: "educational change.",
C: "cultural change.",
D: "social change.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question40",
question: "40. For education to play its transformation role in society, it should be structured to",
A: "produce personnel for clerical jobs.",
B: "meet the needs of the society.",
C: "enable people to acquire book knowledge.",
D: "promote the extended family system.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question41",
question: "41. A condition which does not help in resolving conflict in our communities is",
A: "tolerating one another's views.",
B: "respecting one another's views.",
C: "socializing with one another.",
D: "insisting on an individual's views.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question42",
question: "42. In the globalization process, businesses cooperate through",
A: "networks.",
B: "computers.",
C: "banks.",
D: "education.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question43",
question: "43. An individual can contribute to community development in Ghana by",
A: "developing the get-rich-quick attitude.",
B: "pi oinoting high population growth.",
C: "exhibiting a positive attitude to work.",
D: "promoting sentiments of individualism.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question44",
question: "44. Ghana can make great strides in her development agenda through the application of",
A: "science and technology.",
B: "traditional education.",
C: "cultural practices.",
D: "indigenous technology.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question45",
question: "45. Countries which are poorly endowed with natural resources are able to build strong economies through",
A: "skilled labour force.",
B: "foreign loans.",
C: "foreign exports.",
D: "general education.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question46",
question: "46. One of the surest ways by which a state can develop is when",
A: "the state allows religious sects to operate freely.",
B: "citizens do not sit on the fence.",
C: "when the military intervenes at will.",
D: "leaders operate without the input of the public.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question47",
question: "47. The process of ensuring that development projects keep operating effectively is termed",
A: "resource development.",
B: "political stability.",
C: "maintenance culture.",
D: "sustainable development.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question48",
question: "48. An individual can best ensure sustainability of life in the future by",
A: "adopting precautionary measures at work place.",
B: "living a religious life.",
C: "joining prestigious social clubs.",
D: "maintaining financial plan.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question49",
question: "49. Which of the following statements is true about the concept of resources?",
A: "Availability of efficient human resources does not matter in economic productivity.",
B: "Human resource is indispensable in the production of goods and services.",
C: "Human resources interact with capital resources to produce natural resources.",
D: "The exploitation and utilization of natural resources depends solely on capital resources.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question50",
question: "50. A major factor that hinders sustainable development in Ghana is",
A: "apathy towards protecting government property.",
B: "using good quality materials for execution of projects.",
C: "establishment of single sex schools.",
D: "developing positive attitude to work.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},


]