export const SOCIALSTUDIESA2019 = [

{
id: "question1",
question: "1. Which of the following, options describes the totality of an individual's being?",
A: "Behaviour",
B: "Character",
C: "Self",
D: "Temperament",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question2",
question: "2. According to Abraham Maslow's Hierarchy of Needs theory, air, thirst and hunger are described as",
A: "physiological.",
B: "safety.",
C: "self-actualization.",
D: "self-esteem.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question3",
question: "3. The innate tendency that compels an individual to develop his or her capability is",
A: "enabling environment.",
B: "formal education.",
C: "professional training.",
D: "self-determination.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question4",
question: "4. A virtue which is still highly cherished in Ghana before marriage is",
A: "almsgiving.",
B: "chastity.",
C: "fasting.",
D: "prayer.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question5",
question: "5. Which of the following factoi's is not a characteristic of an adolescent?",
A: "Association with i\ eir mates",
B: "Confiding in their parents",
C: "Forming strong boy-girl relationships",
D: "St izin to gain popularity",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question6",
question: "6. Ghanaians can be unitetl flu otiglJ II c foIlo›viIJg cuItnral yi acticcs except",
A: "marriage rites.",
B: "nam ing ceremonies.",
C: "puberty riies.",
D: "lribtil marks.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question7",
question: "7. IU the GhaMaian society, the fundamental aim of naming n child is to",
A: "givc time bahy an idci lily.",
B: "introduce the bahy to walcr end wine.",
C: "link the haby to the ancestors.",
D: "present assorted gifts to the baby.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question7",
question: "7. Whicich of the following shared tmditional Glianaian values has been undermined by the activities of fraudsters?",
A: "Hospitnlity",
B: "Humility",
C: "Loyalty to aut1ioi'ity",
D: "Respect for elders",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question9",
question: "9. Which of the following statements is not true about the purpose of marriage in the Ghanaian society?",
A: "A means for the couple to provide support for each other",
B: "Avenue for companionship among couples",
C: "Provision of legitimacy to have sexual relations with anybody",
D: "Provision of legitimate avenue for procreation",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question10",
question: "10. Which of the following activities is the Rrel stage in the performance of customary marriage rite in Ghana?",
A: "Having a marriage feast",
B: "€ioing for knocking",
C: "Payment of bride wealth",
D: "Presentation of drinks",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question11",
question: "11. The practice whereby people marry outside their clan is referred to as",
A: "endogainy.",
B: "exogamy.",
C: "homogamy.",
D: "polygamy.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question12",
question: "12. The basic purpose of marriage in Ghana is",
A: "companionship.",
B: "procreation.",
C: "provision of shelter.",
D: "sexual gratification.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question13",
question: "13. One obligation oFthc inclividiial in tlic family is",
A: "bonowing moncy to iindcnake community projects.",
B: "keeping c i.stody uf I.innily pi opeily.",
C: "organizing|›artics iii llic rtciglihourhood.",
D: "settling disputes in tI›c comm nzily.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question14",
question: "14. The role of the family which ensures that the cl il‹l 'ai‹» x t‹› l›cc‹›mc a responsible and acceptable member of the society is llie provision of",
A: "accommodation.",
B: "cI›aractcr training.",
C: "physic:iI needs.",
D: "xcctii“ily.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question15",
question: "15. i",
A: "hlamiMș cl\ildiciz c‹›i1Iiiicinusly.",
B: "in pi‹›|›ci I‹tmily ›l:ii\itiMș.",
C: "lack of:il1cctiuM fui «liiltlrcil.",
D: "moral dcgcneiaticn ofcliildrCil.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question16",
question: "16. lieu cliildicn hccomc deliiiqticNt the best thing parents should do is to",
A: "disciplinary treasures.",
B: "rlci x’ ihcin their hasic needs.",
C: "hand them over to juvenile courts.",
D: "take them through counselling.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question17",
question: "17. ’the type of socialization which the school provides to students is described as",
A: "anticipatory.",
B: "primary.",
C: "re-socialization.",
D: "secondary.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question18",
question: "18. One activity that can bring harmony between personal and group interests is",
A: "paying television licence fee in an area of poor television reception.",
B: "paying utility bills in an area where services are not provided.",
C: "protecting community property where one finds himself or herself.",
D: "swearing of oath of office against a person's conscience.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question19",
question: "19. Which of the following features is not part o£tlie physical environment?",
A: "Climate",
B: "Ocean",
C: "Population",
D: "Vegetation",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question20",
question: "20. One way of conserving wild-life is",
A: "creation of national parks.",
B: "establishment of state fanqs.",
C: "importation of mole meat.",
D: "production ofn›orc fisl›.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question21",
question: "21. A key function of Connal cd‹icatinn is",
A: "piovision ofmoial ti ainiii_.",
B: "provision of life ski11s.",
C: "tranmission of book kno s’lcd¿zc.",
D: "transmission of religious chili lie.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question22",
question: "22. Uitc problcm that threatens Ghana as :m ii›‹Icj›cn‹lvnl cntintiy is",
A: "l›cavy dependence on export ul'j›riiit.in c‹›mInnditics.",
B: "inability to adopt a national lang i.igc.",
C: "luigc-scale urban-rural migration.",
D: "uitlfi ’ourable weather condition.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question23",
question: "23. Pulil ical independence ofa country refers to",
A: "I fnr citizens.",
B: "sell- ovci”m»ci t.",
C: "scl-reliance.",
D: "snci.aljiislicc.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question24",
question: "24. lie rn‹isl effective iiieaiis of resolving conflict in llie €iltaiiaiaii sopiety is through",
A: "**********",
B: "**********",
C: "**********",
D: "**********",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question25",
question: "25. The essence of reconciliation is to",
A: "compensate and pay innocent people.",
B: "insist on the guilty party to apologize.",
C: "let go of anser and repair injury.",
D: "acknoi 'ledge guilt voluntarily.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question26",
question: "26. One anribute of a good leader is",
A: "effective organization of followers.",
B: "insisting on followers to abide by decision.",
C: "reliance on followers for direction.",
D: "self-centredncss iii decision-making.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question27",
question: "27. Based on the principle of separation of powers, the legislature is responsible for",
A: "appointing members of the executive.",
B: "implementing the laws of the state.",
C: "interpreting the laws of the state.",
D: "making laws for the state.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question28",
question: "28. An esset tial feature of democratic governance is",
A: "periodic elections.",
B: "pi”ess censorship.",
C: "rule by decree.",
D: "‘	selection of candidates.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question29",
question: "29. The main condition for constitutional democracy in Ghana is",
A: "encouragement t›f ethnicity.",
B: "frequent demonstrations.",
C: "parliamentary boycotts.",
D: "poI itical tolei-ance.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question30",
question: "30. The right of an indi vidual to participate in governance is",
A: "an econoni ic right.",
B: "a legal right.",
C: "a political right.",
D: "a social right.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question31",
question: "31. A n objective of the New Parinrrsliip foi A fi ica's Development (NEPAD) is to",
A: "eradicate abject povcrty.",
B: "eradicate otitino‹lc‹l cusioiiis.",
C: "form a cons\Iltul ix'c  o ci n nlent.",
D: "scck a rc Lai:iti‹›ii linm colonial masters.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question32",
question: "32. One sub-rcgion:i I intern.‹tional body Ghana belongs to is tl c",
A: "Conlmon wealth of Nations.",
B: "Ecciion ic Community of Wcst A liicnn Stnics.",
C: "Now-Aligned nzoven›ent.",
D: ".",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question34",
question: "34. VhicIi office Follo»'ing »’ays is lent essential for prep2ring II e youtl  for ",
A: "Exposure to appropriate role models",
B: "Fonnation of pressure groups",
C: "Pro›’ision of education and twining",
D: "Pro •ision or¿‹iidance and counselling",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question35",
question: "35. The government has contributed to the promotion of science and technology in the coiintry through",
A: "encouragement or air travels.",
B: "encouragement of consumption of cocoa products.",
C: "establishment of research centres.",
D: "importation of foreign goods and services.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question36",
question: "36. Scientific know1ed¡;e has contributed a great deal in eradicating",
A: "crime in the society.	,",
B: "food security in the country.",
C: "3ender inequality in the country.",
D: "supemition in the country.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question37",
question: "37. Apart from natural resources, all other iiialei ials used for production may be referred to as",
A: "capital resources.",
B: "human resoui ce.",
C: "non-renewable resources.",
D: "renewable resources.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question38",
question: "38. Ne  least relevant factor in decision-making at community level is",
A: "identification of needs.",
B: "mobilization of hinds.",
C: "political inclination oftl e people.",
D: "sensitization ofd e people.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question39",
question: "39. l1icl1 office following situations cannot be considered an aspect of conHJ1\lnity development?",
A: "Fnco‹iraging rural people to migrate to lii han areas",
B: "helping mral people to identify their needs and problems",
C: "Motix•ating rural people to use their initiative and volutitaig' effoi1",
D: "Stimulating rural people to take active part in community alTairs",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question40",
question: "40. One inajc›r nh.sl‹iclc to the iiziprovement of standard of living in Ghana is",
A: "gn‹›d Ir:ti›sporlation and communication.",
B: "high tnsi ‹›l“liviitg.",
C: "i›iipi‹›vvJ ‹ ‹i.iJity l›calt)› delivery.",
D: "qtialii}’ai›J iicccssihlc education.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question41",
question: "41. To cnsiirc s‹›st:lin:ihlc ‹l«›•cluj›mcitt, Glinnaians iJecd to cultivate the habit of",
A: "buying cxycMsivc t‹›ols loi ;›rojccts.",
B: "imposing tools from abroad.",
C: "servicing and repairing} loom.",
D: "using indigenous lool.s for projects.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question42",
question: "42. **********",
A: "**********",
B: "**********",
C: "**********",
D: "**********",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question43",
question: "43. The first condition in",
A: "building good schools.",
B: "onc*s desire and set r-dctcn›iin‹itioi .",
C: "tlle discovcry of one’s |›otc°nticl.",
D: "the encouragement from onc's parents.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question44",
question: "44. Empo›x•ering fetzzalcs tlit uugl Connal education is a means of Jisco\iiagills",
A: "high dcatli mle.",
B: "high birth rate.",
C: "increasing child i»orhidiiy.",
D: "increasing female po}›ulation.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question45",
question: "45. The hills rate of population growth ii Ghana can hcst he rcduccd through",
A: "ci catioi of many jobs.",
B: "increasing the inai”riagc age.",
C: "practicing family planning.",
D: "reduction of income inequalities.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question46",
question: "46. The M iltcni i mz DcvcIopi»cMt Goal Ghana has been able to achieve relates to",
A: "child mcd inatci iial i›ioi1ality.",
B: "increased tax collection t›roccdui cs.",
C: "ptovisioiJ oftcrtiary education.",
D: "small scale industries.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question47",
question: "47. One consequence of inappropriate behaviour at work places in Ghana is",
A: "a reduction in salai ies.",
B: "a reduction in sanctions.",
C: "inability of businesses to meet targets.",
D: "inability of rrianagers to discuss issues.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question48",
question: "48. Most businesses in Ghana fail to survive heca\ise the owners do not",
A: "conduct considerable investigations.",
B: "consult religious lcadei's for prayers.",
C: "maintain high quality products.",
D: "travel abroad for cxpericnces.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question49",
question: "49. kisk taking enables the ent‹epreneui to take bold decisions in the midst of",
A: "business uncertainties.",
B: "labour unrest.",
C: "tax obligation.",
D: "scarce i esources.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question50",
question: "50. To start a business, the first step the entret›rcneur must take is to",
A: "advertise tlJe product.",
B: "conceptualize the idea.",
C: "conduct a marl‹et survcy.",
D: "secure funr!s.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},



]