export const SOCIALSTUDIESB2003 = [

{
id: "question1",
question: "1. Discuss five Advantages Associated with Adolescent Chastity",
options: "\
1. Safe from Sexually Transmitted diseases (STD’s): When adolescent lives a chase life she helps to eliminate such reproductive health risks as sexually transmitted diseases (STD’s) like syphilis, gonorrhea and the deadly HIV/AIDS     These diseases are mainly contracted through sexual intercourse with an infected person or persons. Hence being chaste as an adolescent till marriage, helps one to protect one’s life from sexually transmitted diseases and the continuity of life securely without fears of contracting incurable diseases like HIV/AIDS.\n\n\
2. Prevention of unwanted pregnancy: An adolescent who lives a chaste life till marriage can prevent herself from unwanted pregnancy, which often leads to unsafe abortion and its complications. An adolescent who indulges in sex and becomes pregnant will attempt to abort the pregnancy by putting all sort of things in her uterus (e.g. drugs from chemical shops or poisonous herbs) to get rid of it. Abortion can lead to complications such as emotional stress, infections, perforated uterus, injuries to vital organs or irreparable damage to internal organs or blocked tubes, or sterility or infertility, removal of the womb, or worse, “death is the ultimate complication”.\n\n\
3. Prevention of Early Pregnancy: Adolescent chastity helps to prevent early pregnancy and child bearing. The teenager who does not lead a chaste life and becomes pregnant may face prolonged and difficult labour which may require caesarean section, lead to loss of blood etc. She may also be prone to medical conditions such as high levels of anemia, swollen feet, bleeding, cervical trauma, poor nutrition etc. There is also the danger of a young girl giving birth to premature or mentally regarded baby, not to mention complicated pregnancies. The death of a teenage mother or the baby may occur more frequently than with matured woman.\n\n\
4. Ability to enjoy education and higher earnings: Adolescent chastity enables adolescents to aspire to achieve their aim in life. When an adolescent lives a chaste life she can achieve her ambition and goals in life and will be able to secure a good job with a high remuneration. Adolescents who become parents early in life especially girls may not be able to complete their education and may therefore become a drop out.\n\n\
5. Chastity before marriage is still a highly cherished virtue in Ghana: It confers honour and prestige on the bride, family and the community. Adolescents who are chaste serve as a role model to younger girls in the community and her husband will respect and be proud of her as having lead a good life before marriage.\n\n\
6. Adolescent chastity ensures trust in marriage: An adolescent who is chaste will be a trustworthy woman or wife for her husband. She will earn the trust and respect of her husband since the husband can leave her behind and travel for weeks without thinking that she will indulge in any extramarital affair."
},


{
id: "question2",
question: "2. Examine the factors that have affected the traditional roles of Ghanaian women.",
options: "\
1. Social Change: One of the factors that has affected the traditional role of Ghanaian women is that women now perform some of the duties and roles of men. Women traditionally stay at home and take care of the children while the men work to feed and maintain the household. However, women now work as salary earners or perform other economic activities which take them away from the home to enable them provide food, clothing and shelter for the family.\n\n\
2. Economic conditions: The cost of living in the country has become so high that women are forced to compete with men in the new economic world. The high prices of goods and services in the: country have forced women to work in order to support their husbands in catering for their children. Thus the father is unable to play his role effectively in providing the needs of the family. The household expenses are therefore shared between the husband and wife in order to provide a comfortable life for their children and build a better future for the family\n\n\
3. Individualism: The traditional Ghanaian women like all people are now concerned with self fulfillment and personal desires which have become more important than their traditional obligations. In Ghana many women aspire to high positions of excellence and the quest for luxury items have made women to think of themselves more than their immediate family.\n\n\
4. Fashion / Scientific and Synthetic foods: Women these days spend greater part of the day at their various work places hence little time is given to the husband and the children. The avnilability of varieties of baby foods instead of breast feeding infants enable many women to work for long hours at their work places. Working women also engage the services of maids and baby-sitters since llicy. cannot combine the demands of their work with their house duties. Women these days also do not wear the traditional “Kaba and Cloth” but rather wear foreign clothing e.g. trousers and shirt, Many women also bleach their bodies or tone the colour of their faces to symbolize that they are modern.\n\n\
5. Broken Homes, Divorce etc: Another factor affecting the traditional roles of Ghanaian women is broken homes, divorce etc. When marriage breaks down it leads to single parenthood forcing women to combine the roles of father and mother. In such a situation if the woman is unable to provide the needs of the children and also give them counselling they can easily fall into bad company and become wayward.\n\n\
6. Urbanization, Rural-urban migration etc.: Lack of stable jobs in the rural areas has forced many men to leave their wives and children in the rural areas for the urban centres in search of jobs. Where the men leave home to the big towns they leave the women behind to perform the roles that men should perform. Women then have to farm or do petty trading to provide food and other things for the family.\n\n\
7. Legal systems, laws protecting women, gender balance etc.: The traditional Ghanaian women now know their rights since many of them can read and write and contribute to public lectures and issues affecting women. Men who molest their wives by using them as punching bags have no respect for them. But thanks to Women and Juvenile Unit of the Ghana Police Service, women now know their rights and report cases of violence and assault to the police. As a result men have been are -jailed for assaulting their wives. Ghanaian women are now involved in decision making as they are now ministers of state, regional ministers, parliamentarians, directors of public and private businesses.\n\n\
8. Western culture and Christian education: Western culture and Christian education have enhanced the importance of women in the family, particularly the educated ones. Educated Ghanaian women now play vital roles in the development of the country. Many women are now headmistresses of schools, doctors, nurses, accountants, businessmen, lecturers at the university, high court judges etc. because of their academic achievement at school and collapse."
},


{
id: "question3",
question: "3. Discuss the factors that hinder the full realization of the educational rights of the Ghanaian child.",
definition: "The following factors hinder the full realization of the educational rights of the Ghanaian child:",
options: "\
1. There is inadequate qualified teachers for the schools to handle the syllabuses especially those in the rural areas. Many teachers after undertaking higher courses at the university do not return to the classroom again. Others leave the classroom for other jobs which offer them better conditions of service. Also there is limited supply of teachers with vocational and technical skills to teach these subjects in the Junior Secondary School level. This is because there are few technical and vocational collages to train teachers to teach these subjects in the Junior Secondary Schools.\n\n\
2. A large proportion of the people of Ghana cannot afford the high cost of education even at the basic level where the fees involved are not so high. The high cost of living and the low income earned from agricultural output makes it very difficult for many parents especially in the rural areas to buy the needed textbooks for their children. Some parents cannot even provide their children’s uniform and also pay their school fees.\n\n\
3. Another factor is inadequate infrastructure and materials. Many schools especially those in the rural areas lack school buildings, workshops for any serious academic work. Also teaching materials like textbooks, science equipment etc are inadequate making teaching and learning difficult. Some schools don’t have adequate furniture in the classroom and in some areas pupils have to sit on stools to write.\n\n\
4. There are uneven number of schools at various levels. The number of schools at the higher levels of the school system is inadequate to absorb the graduates from the low levels. This is because the numbers of primary schools out-number that of both junior secondary and senior secondary levels. Many good students therefore cannot avail themselves of secondary school education because of few secondary schools.\n\n\
5. The school curriculum is overloaded. The syllabus for a subject under the system is overloaded and in addition a student is required to offer many subjects within a short period especially at the J.S.S. and S.S.S. levels. The number of subjects for the Primary level was changed to comprise nine subjects while the number of subjects at the J.S.S level was changed from 12 subjects to 10 subjects. Students’ poor performance at both the Basic Education Certificate Examination (B.E.C.E) and the Senior Secondary School Certificate Examination (S.S.S.C.E.) was due the fact that students have to cope with too-many subjects within a very short period.\n\n\
6. The high turnover of students from the J.S.S .level who cannot be absorbed into the S.S.S. level had to join the labour market with no marketable skill. The lack of job opportunities in the system has rendered even the few J.S.S, and S.S.S. graduates who are able to go through the educational system unemployed. This creates the erroneous impression that after all, education has no value.\n\n\
7. The admission requirements for students entering especially the higher institutions like universities and the polytechnics are very high and as such many students with good grades are prevented from enjoying their full educational rights.\n\n\
8. Cultural practices such as infant betrothal, trokosi, early marriage, eloperent etc prevent girls from enjoying their educational rights. In certain traditional areas girls are given out into marriage at an early age which denies the girl her educational rights In some communities young virgins are pledged to the shrine for life to atone for the sins of other family. This cultural practice suppresses the growth and realization of these young girl’s educational rights. hungry child cannot learn well in class and perform well in his /her exams.\n\n\
9. Another implication of the theory is that it urges the individual to forge ahead to achieve self- esteem. One needs to be respected for one’s social status, personality and competence for doing something. One’s self-esteem can also be boosted if one is recognised for his/her efforts in achieving a particular feat in the society,\n\n\
10. Maslow’s theory of needs encourages people who are self-actualized to help others also achieve some higher needs. A self-actualized person assists people in times of need and encourages people to aspire higher. Such a person does things not for himself but for the whole community.\n\n\
11. The theory serves as a reminder to the individual to strive to achieve the ultimate which is self- actualization. A student who wants to be a medical doctor will learn hard to realize his objective in life. He will also make maximum use of his time and learn hard to realize his potentialities for the achievement of his personal goals and ambitions."
},


{
id: "question5",
question: "5. Discuss the measures that can be adopted to reduce the high cost of funerals in Ghana.",
options: "\
1. Elaborate wake-keepings should be discouraged: During wake-keeping, the bereaved family will hire canopies, chairs, sound systems, choral groups, serve toffees, biscuits, chewing gums, coffee etc. to keep mourners awake throughout the night. These are expenses which should be discouraged as they add to the expenses of the bereaved family. These days some churches, for example, the Methodist Church, have banned wake-keeping for their church members since they consider it as waste of financial resources. If wake-keeping is discouraged families can also minimize funeral expenditure on food, hiring of band and spinners to entertain mourners during funeral celebrations. Music can be provided by local choral groups or the church choirs or any singing group in the church to reduce funeral expenditure.\n\n\
2. Discouraging the practice of buying special cloth: The purchase and use of special cloth for funerals – where family members purchase a particular or special type of cloth to be worn by all should be discouraged as it is unnecessary. Families overburden themselves by buying two new funeral cloths (one for funeral service and the other for thanksgiving service) and also print photographs of the dead person on T shirts, which are worn by family members during the funeral celebration. Funeral expenditure can be reduced if family members use any decent funeral cloth during the funeral celebration. Printing of T- shirts and photographs of the dead should be stopped since the funeral cloth alone is enough for the funeral celebration.\n\n\
3. There should be shorter periods for preservation of the corpse: Many families these days preserve the corpse in the mortuary for a long period of time so that they can have enough time to renovate the family house before the funeral takes place which shows the state of wealth of the family. It has also become a practice these days to wait for relations from abroad to come down before the corpse is removed from the mortuary. This also contributes to the long period the corpse is preserved at the mortuary, which means that the family will have to pay more money to the hospital where the corpse is kept. It should be explained that once the person is dead expenses made on his funeral should be done with circumspection since such expenses make relatives poorer. Families should therefore stop the habit of preserving the corpse in the mortuary for a long period to save the family from paying high mortuary bills. Such money can be used to improve the conditions of the poorer members of the family."
},


{
id: "question6",
question: "6. Discuss the significance of naming ceremony in the Ghanaian traditional society",
options: "\
1. Naming ceremony gives a sense of identify to the child. It is an occasion when a newly born baby is officially given a name, a rite of passage practised by all the various ethnic groups in Ghana. The child therefore becomes identified with the clan when he grows up. This rite of passage therefore needs to be continued for its great importance to the child and society as a whole.\n\n\
2. Naming ceremony marks a separation and transition of the child from the spirit world into the physical world and his acceptance by the living community. The baby is welcomed into the family, community and the society. If the rite is not performed it is believed that the spirit of the child “kra” (soul) would be aggrieved and return to its ghost mother.\n\n\
3. Naming ceremony humanizes and socializes the child; it makes the child a member of the family and society at large. It individualizes and incorporates the child into the society. A child is known by his name and therefore such a child is able to mix freely with his/her friends when he/she grows up.\n\n\
4. When a child is given a name his/her life is entrusted into the hands and care of God, the divinities and ancestors. Blessings and protection are solicited from the spiritual world for the child into the society. It is also a period for the couples to give thanks to God for protecting the mother during the period of pregnancy till the day of delivery. In the traditional set up libation is poured and prayers are offered to the ancestral gods for safe arrival of the newly born baby.\n\n\
5. Naming ceremony inculcates into the child a sense of moral values such as honesty, truthfulness, open-mindedness, industry and hard work. For example, among the Akans, during naming ceremony an elderly person puts the child on his laps and dips his hand into water and allows the water to drop on the child’s tongue. He says these words; “Kweku Mensah, if you see water, it is water” This is done three times. He does the same with wine. This water and wine ritual teaches the child a good moral lesson. This practice inculcates into the child values-like truthfulness, loyalty, honesty, fairness and justice.\n\n\
6. Naming Ceremony introduces the child into the rich cultural heritage of the Ghanaian society. It is a rich cultural heritage which every Ghanaian society cherishes and is performed in every household to welcome a newly born baby. It helps to bring about a continuity of the family or lineage name so that it does not become extinct. The child as he grows up takes part in every naming ceremony and therefore when he becomes of age he will also perform this cultural practice.\n\n\
7. Naming Ceremony offers an opportunity for the husband to honour the wife while the woman also gets the chance to prove her fertility. It also serves as a venue for the mother to exhibit her pride as a mother which is an indication of her fertility and a realization of her creative potential and essence of her existence as a woman. It is also a period for the father to declare his paternity and his assurance to be responsible for the child and the mother.\n\n\
8. Naming ceremony serves as a reunion of family members and friends. Families of both the father and mother renew their blessings to the marriage they had consented to. Families, friends and well wishers come together to celebrate the occasion. This brings about peace and social integration which in the long run benefits the society.\n\n\
9. Naming ceremony provides economic support for the mother. After the naming ceremony members offer gifts for the newly born baby. The father may present money which the mother can use to buy some of the needs of the child. Gifts are presented by family members and well wishes to the child. It may be money, dress, powder, pomade etc."
},


{
id: "question7",
question: "7. Examine the role those traditional rulers play in uniting the people of Ghana",
options: "\
1. Traditional rulers unite the people of Ghana by acting as arbitrators ,that is settling disputes. When there is dispute between two people or matters relating to land disputes between two famil1es the chief will summon his council of elders and settle the case so that there will be peace between the families .lf there are disturbances between family heads which will create confusion in the town It is the duty of the chief acting on the advice of his council of elders to settle the amicable settlement of the case. In judging cases, traditional rulers try to be impartial so that peace will prevail between’ the members of the family. As the head of the traditional court, the chief has the final say in the decision making process that is aimed at bringing about peace to the community.\n\n\
2. The National house of Chiefs hears appeals from the Regional Houses of Chiefs on chieftancy disputes They also advise agents of the central government on customary law and matters affecting chieftaincy.\n\n\
3. In the absence of party government, the chief helps his people in national affairs, for example, the chief acts as an adviser for the people and the government. When the government introduces new policies it is the role of the traditional ruler to explain them to his people. They also communicate to the Central Government the problems affecting the traditional area in terms of infrastructure. The government normally seeks the advice of the traditional rulers before certain projects are undertaken in their traditional area.\n\n\
4. A good and progressive ruler mobilizes his people to undertake self-help and community development projects. As a social, religious and political leader of his people the chief commands the respect of the people and can mobilize them to build community centres, clinics, K VIP, clean the town and weed the bushes around the town or village. This will reduce the spread of mosquitoes and promote good health for the people.\n\n\
5. Traditonal Chiefs are appointed to serve at the national level. The Central Government upon the advice of the Council of State may appoint educated and prominent traditional chiefs to serve the nation on Public Boards and Corporations as Chairmen or members. Some chiefs serve on the country’s Council of State and therefore advise the President on some major decisions affecting the country especially on chieftaincy.\n\n\
6. Traditional rulers serve or act as members of committee of enquiry in cases relating to chieftaincy. There are traditional chiefs who are renowned lawyers or have been chiefs for many years and because of their rich ideas in chieftaincy matters they may be called upon by the government to handle chieftaincy matters to bring peace and stability in the country.\n\n\
7. Traditional rulers ensure the preservation of the cultural heritage of the community: Festivals, drumming and dancing, chieftaincy, singing etc are elements of cultural practices that bind the people together. During festivals, the chief symbolizes the culture and traditions of his people. The chief is a liaison between the living and the dead. As such he pours libation to the gods and the spirits of the dead for their blessings, guidance and protection and also offers sacrifices as a thank-offering to the traditional deities and ancestral spirits.\n\n\
8. The traditional ruler is the custodian of ancestral lands and stools. Earth is regarded as a sacred deity which includes mountains, hills, caves, rivers, lagoons etc. They are regarded as natural sacred places where ancestral spirits and gods inhabit. Some trees, grooves are also regarded as sacred. This explains why the chief has to pour libation to these deities and offer them food and drinks. It is the belief of the Akan that the spirits of the dead are embodied in some blackened stools specially made for them. These stools are thus considered as shrines or places where they dwell. It is the duty of the chief to enter the stool room to offer sacrifices, prayers and libation to the ancestors on specific days like on Adae and Ahoba.\n\n\
9. Traditional rulers play political role in their communities. Ile leads his people in times of war to defend themselves. The Asafo Companies are the traditional soldiers in our communities who defend the towns and villages from external attacks. The chief leads the Asafo Companies in times of war. When a chief is enstooled, he swears to defend his peoole without fail and by leading his people to go to war he is fulfilling his oath to the people."
},


{
id: "question8",
question: "8. Discuss the measures that can be taken by the government of Ghana to minimize her over-dependence on other nations",
definition: "The following are measures that can be taken by the government of Ghana to minimize her over- dependence on other nations:",
options: "\
1. Ghana should terminate co-operation with any international organization which is not beneficial to the nation. The Government of Ghana should review all her trade agreement with her trading partners to make sure that they favour real growth in the nation. Imports brought into the country must meet international standards and goods found to be of poor quality should be returned to the importing country,\n\n\
2. The government has to encourage the people to patronize locally produced goods. This will encourage the local industries to expand production and employ more workers to increase output to meet the increase in demand for local goods. The local industries should be given incentives to produce high quality goods that can compete favourably with foreign imported goods.\n\n\
3. The country’s natural resources should be developed with emphasis on local investments and industries, The government should give incentives to local investors to take soft loans from the banks to expand their industries and exploit the natural resources as sources of raw materials to feed the industries. This will increase output for the local market and export to earn foreign exchange for the country.\n\n\
4. The government should develop the country’s human resources by emphasing on the technical and science education. This means that the government must establish more technical and science institutions to train high and middle level manpower of the country. The human resources in the form of architects, managers, engineers, doctors, lecturers’ accountants, technicians, economists, surveyors, etc are needed to man the various sectors of the economy. The training of more personnel as middle and high level manpower of the country will reduce the country’s reliance on foreign experts for advice or to man strategic sectors of the economy.\n\n\
5. Ghanaians must endeavour to understudy foreign experts who provide aid. Foreign experts recruited to assist in the development projects of the country work with Ghanaian technicians and engineers and by so doing pass on their skills and knowledge to them so that when they leave they can manage the projects.\n\n\
6. The government should introduce policies to reduce brain drain of the country’s high level and middle personnel. The government should improve the salaries and other conditions of service of workers. Workers must be given loans to purchase or build houses, buy cars, enjoy subsidized meals at their work places etc. Workers must also be given a good pension which will ensure their security after retirement from active service. The workers should be provided with the necessary tools and equipment and materials that they need at their work places to make them enjoy the work they do.\n\n\
7. The financial assistance for projects must be known in both recipient and donor countries to ensure accountability and effective use of the said resources.\n\n\
8. The government must ensure that projects that are undertaken in the country are seen as our own monitored and supervised by Ghanaians. The situation where roads and buildings constructed with foreign assistance and certified as being completed but in no time show signs of deterioration should be checked and the officials concerned sanctioned for incompetence.\n\n\
9. There is the need for a long term plan to restructure the economy in order to reduce the country’s over-dependence on other nations. The country’s agricultural and industrial sectors need total restructuring to enable them perform better. As an agricultural country we need to have an industrial sector which can process our raw materials for export instead of exporting the raw materials in their raw form which fetch only little foreign exchange. The government can also encourage the private sector by creating an enabling environment which will encourage many local entrepreneurs to produce goods for local use and export to earn foreign exchange for the country."
},


{
id: "question9",
question: "9. Discuss four causes of flooding in the urban centres in Ghana and suggest ways of controlling this environmental problem",
definition: "The following are the causes of flooding in the urban centres in Ghana:",
options: "\
1. Poor planning of towns and cities: In the urban centres in Ghana, cities grow anyhow into giant sprawls with no order in them. Shanty towns soon develop into cities with no proper planning. Rivers and waterways have their flood plain and catchment areas. When people put up structures in a haphazard manner (i.e.near waterways or water-courses and in flood plain area) and it rains heavily the rain water cannot flow freely and this can cause severe flooding in the surrounding areas.\n\n\
2. Poor architecture: Flooding in urban centres in Ghana may be caused by poor architecture resulting from ignorance on the effects of improper siting of buildings. When buildings are poorly designed and constructed without due regards to whether the area is low lying or near an area prone to flooding then when it rains rain water will not flow freely but will find its way into the homes of people.\n\n\
3. Poor drainage systems in the towns and cities: In the urban centers gutters constructed to carry rain water are very small in size and in many areas, there are no pipes or channels that carry away dirty water or other liquid waste from people’s homes into gutters. As a result, the waste liquid from people’s homes flow direct into the streets creating artificial gutters to carry the wastes. When it rains these gutters overflow their banks thereby causing flooding,\n\n\
4. Silting and choking of drains: The dumping of garbage and solid waste into gutters and waterways choke them causing the gutters to over-flow their banks when it rains. People also intentionally throw their refuse and other wastes into gutters and on the streets when it rains and these waste choke gutters and prevent the easy flow of the rain water thereby causing flooding.\n\n\
5. Improper disposal of refuse: Urban centres in Ghana experience improper disposal of refuse leading to poor sanitation. The concentration of people in the urban centres has led to the development of shanty towns with its attendant problem of indiscriminate dumping of refuse thereby creating sanitation problem. Also in urban centres refuse is dumped near water courses or settlement areas thereby causing serious sanitation problems. When it rains the refuse is carried along making it difficult for the rain water to flow freely thereby causing flooding.\n\n\
6. Low lying level of the coastal lands: The topography of the coastal areas is such that it is low lying and prone to flooding when it rains. Therefore if one is not guided by the officials of town planning and cities with regards to the siting of buildings, one is likely to build in flood plain area.\n\n\
7. Non enforcement or improper enforcement of laws on building construction and sanitation: The Town and Country Planning Department is government organization which has the responsibility of planning towns and cities and also enforcing laws on building construction and sanitation. But in the urban centres, the officials of this Department do not enforce the laws on construction of buildings. Some of these officials are interested in taking bribes from people submitting their building plans for approval and permit to construct such buildings. People therefore take advantage of the bribes they pay and construct buildings in wetland areas which create serious flooding problems.\n\nSolutions\n\n\
1. The Town and Country Planning Department has to ensure proper planning of towns and cities. The District and Regional Offices have to see to it that an area that has been reserved for a specific activity is not used for something else. The Department also has to ensure that towns and cities are properly planned in such a way that people do not build in wetland areas which are prone to flooding. cantt andr\n\n\
2. Drainage systems must be appropriately located and properly constructed. Gutters constructed must be of reasonable size to accommodate the volume of water when it rains. Big drains must be constructed especially where we have lagoons or streams so that when it rains they can contain the volume of water flowing through them.\n\n\
3. There should be education on the proper disposal of refuse to control flooding in the urban centres. The dumping of refuse into gutters should also be discouraged. This can be done when laws are put in place and offenders arrested and prosecuted. People should be educated on the proper disposal of refuse to prevent choked gutters from overflowing to cause flooding. Better places should be designed for the dumping of refuse to discourage people from throwing waste materials into gutters.\n\n\
4. The Municipal and District Assemblies should ensure regular and effective cleaning and desilting of drains. This will ensure the free flow of rain water when it rains and also control flooding.\n\n\
5. The Town and Country Planning Department should ensure proper architectural work and education on the effects of proper siting of buildings. Public education should be mounted in every part of the country to sensitize the people on the need to have their building plans approved and ensure that they construct their buildings according to the approved design.\n\n\
6. The government has to enforce laws on building construction and sanitation. The Municipal and District Assemblies should ensure that people who construct buildings in unauthorized areas are prosecuted to serve as an example to people. Buildings constructed on the path of water ways or kiosks erected on gutters should be demolished since they tend to prevent the free flow of rain water and cause flooding. The government should also prosecute people who do not keep their surroundings clean or observe proper environmental sanitation. The Assemblies can also solve environmental sanitation by providing enough litter boxes or containers at public places so that pedestrians, traders and hawkers can use them in disposing their waste materials."
},


{
id: "question10",
question: "10. Account for the high rate of unemployment among the youth of Ghana.",
options: "\
1. Educational system: - The educational system of the country is such that it places more emphasis on clerical subjects like English and arithmetic which fit the youth into white collar jobs to the neglect of technical and vocational education. Technical and vocational training enable students acquire practical training in sewing, basketry, carpentry, masonry, agriculture which enables them to start their own businesses. Thus, many school leavers are unemployable because they lack technical and vocational skills.\n\n\
2. Job discrimination by the youth; Many youth in the rural areas who do not want to undertake to farming may leave for the urban centres for non-existent jobs like security, messenger, housemaids or boys, errand boys etc. to farming, kente weaving, basketry, etc .they become unemployed. Some youth may also discriminate in the choice of jobs .Some youth may prefer working in a Hotel to working as a messenger but this desire may not materialize because of his level of education.\n\n\
3. Negative work culture:-Negative work attitude of the youth like laziness, sleeping at work place, absenteeism, loitering, lateness to work may lead to low productivity. This situation may eventually cause the collapse of the business and lead to the unemployment of the youth.\n\n\
4. Reduction in the duration of school years: There is high turnover of students from the Junior Secondary Schools, Senior Secondary Schools Polytechnics and the Universities, as a result of the shorter academic years students use fewer years to complete their course of study. In the old educational system students spend 17 years to complete secondary school education but with the present educational system students take 12 years to complete the secondary education. As a result the excess of students who cannot enter the Senior Secondary School (SSS) from the Junior Secondary Schools and the S.S.S. who cannot gain admission into the tertiary institutions also become unemployed. There is high graduate unemployment because of the high turnover of students from the country’s universities who cannot be absorbed into the few job opportunities available.\n\n\
5. Corruption and Nepotism: Corruption and nepotism deny some of the youth employment. This is because if the youth has to pay a bribe before he is employed and can not afford the amount involved this may make him loose the job. Where one does not have a relative in high places to assist one get a job one cannot be employed in a job he has applied. So the situation where certain tribes or class of people who occupy certain positions of influence favour their own tribesmen or relatives in job placement may result in putting square pegs into round holes.\n\n\
6. Retrenchment of Workers: The Government’s Structural Adjustment Programme has led to the retrenchment of many workers. Many corporations which have not been performing well have been divested and the workers retrenched. Many of such businesses have found it difficulty to adjust themselves to the new economic trend and because of the huge losses they incur in production they have to laid off their workers.\n\n\
7. Unjust Economic Order: The unjust world economic order has lead to the inability of the government to create employment opportunities for the people. The government’s policy of trade liberalisation has led to the inflow of the foreign goods thereby discouraging similar goods produced in the country. The local market is therefore flooded with foreign cheap and low cost goods which outcompete the locally produced goods making producers to reduce the number of workers employed so as to sustain the business.\n\n\
8. Slow Growth of the Economy: Another factor accounting for the high rate of unemployment among the youth is the slow agricultural and industrial growth. The country’s agricultural seotor has been experiencing sluggish growth because of low output to poor rainfall and falling world prices of agricultural commodities. As a result, local industries, which depend on agriculture for their raw materials do not have adequate raw materials to feed the factories. High maintenance cost of the industrial machines and the use of outmoded machines coupled with inadequate raw materials have combined to reduce the number of workers employed in industries and factories to produce goods for the local market and export"
}

]