export const SOCIALSTUDIESB2000 = [




{
id: "question1",
question: "1. Explain any four challenges that confront couples in marriage,",
definition: "Many factors contribute to marriage failure or breakdown in this country. The factors include:",
options: "\
1. Financial problems: The unbearable economic conditions and the high cost of living that make it difficult for couples to honour their financial obligations affect the stability of marriages. Lack of money to provide the basic necessities of life like food, clothing, health care and shelter for the family can easily disturb the stability of a good marriage.\n\n\
2. Childlessness /Infertility: The inability of couples to procreate on the accounts of barrenness or impotency may threaten the stability of marriages in Ghana. Childlessness is regarded as a shame and a curse in our traditional system. It brings about frustration and bitterness and this can lead to divorce. Inability to have children can easily disturb the stability of a marriage as the in-laws may put pressure on either the man or woman to look for another partner who can bear children.\n\n\
3. Verbal or physical abuse from any of the couple: Some men are in the habit of beating or physically abusing their wives sometimes to the extent of maiming them or causing serious bodily harm to them. Where such behaviour becomes a common feature of marriage then the woman who is always vulnerable may seek for divorce to avert any bodily harm to her.\n\n\
4. Unfaithfulness of the couple/ adultery: One of the primary rights that the couples enjoy in marriage is the exclusive right of sexual access to each other. Sexual unfaithfulness on the part of the man or woman can lead to problems and divorce. A successful marriage can easily break if the man or the woman has extra marital affairs or flirts with other women or men outside the marital home.\n\n\
5. Disagreement on family size and sex preference of children: When couples do not agree on the number of children or size of the family they would want to have this can bring about misunderstanding between the couples and may easily break the marriage. The desire on the part of one of the couples for either a boy or girl can also bring about misunderstanding between married couples.\n\n\
6. Sexual incompatibility on the part of couple the: Sexual satisfaction plays a very important role in the stability of a marriage. If a man cannot satisfy his wife sexually this may result in either partner indulging in extra-marital sex. This can undermine the bond of marriage existing between them.\n\n\
7. Lack of effective communication between married couples can easily lead to conflict. Married couples who cannot communicate freely and solve their problems together and have to resort to quarrels or an outside assistance in solving their problems are likely to have problems in their marriage.\n\n\
8. Variation/ differences in religious inclination of the couples: If couples belong to different religions and do not get on well because of differences in certain doctrines of a partner’s church. As a result, the couples may disagree on many issues or things relating to life. Again where the woman persistently refuses to join the man’s church then this problem is likely to disturb the stability of the marriage\n\n\
9. Interference by in-laws: Unnecessary interference from the family members and friends of the couples on account of excessive financial demands, frequent unannounced visits etc. may affect the stability of marriages in Ghana. Family members, in-laws and friends, may interfere in the marriage affairs of couples in issues like decision making, use of family resources e.g. income and also when to have the first child. There are situations when in-laws visit their children and in the process interfere in the household duties of the family, which create problems for the couples. Lack of respect and acceptance of in-laws, poor relations with in-laws and unnecessary interference from in-laws in the marriage affairs of the couples tend to create unhealthy relationships.\n\n\
10. Prolonged sickness on the part of either of the couples.\n\n\
11. Alcoholism/drunkenness on the part of one of the couples\n\n\
12. Presence of step children in the marriage."
},


{
id: "question2",
question: "2. In what ways does early pregnancy and childbirth affect the young mother?",
definition: "The effects of adolescent pregnancy can be devastating. The following are some of the ways early pregnancy and childbirth affect the young mother.",
options: "\
1. Emotionally, a teenager may not be ready to give birth to a child. The boy equally may not have money. Most of the time, the parents of the boy and the girl are forced to assume the responsibility of looking after the baby. This may be difficult for them. When a ‘child’ gives birth to a child, the economic hardships, which she faces, result in poor health for both mother and child. This poor health stems from malnutrition, hunger, lack of health care because there is no money to pay for hospital bills and drugs. Inadequate clothing for the baby and the teenage mother can affect their health. Frequent insults from parents may result in the pregnant teenager losing appetite and becoming malnourished and have anaemia. This may affect the growth of the foetus.\n\n\
2. Complications of Pregnancy and labour may develop. Prolonged and difficult labour may require caesarean section due to the small pelvis of the teenage mother (that is, the teenage mother would have to be operated upon to assist delivery) and this may lead to the death of the mother and baby.\n\n\
3. The teenage mother may be prone to medical conditions such as high levels of anaemia, oedema (swollen feet), bleeding, cervical trauma, poor nutrition etc. These conditions may affect her health and the foetus.\n\n\
4. The teenager who gives birth to a baby automatically would have her education terminated prematurely, it is not always possible for the teenage mother back to school. This means an end of formal education or training and an end to all her future plans and career. As she is not trained for any job she may depend on her parents for support. As the teenage-mother may not have the means to take care of her child she may abandon or neglect the child. Teenage mothers usually have little love for their children because they are not matured.\n\n\
5. The teenage mother may become a social outcast because the community may reject her. The teenage mother may loose the respect of her friends and family members, and her family could be disgraced in the society. The teenager is not able to go out to meet her peer group because she has to take care of her baby. She may become mentally disturbed because of insults from parents.\n\n\
6. Physically, a young girl’s body may not be matured enough to bear a baby easily. There is the danger of a young girl giving birth to premature or mentally retarded baby, not to mention complicated pregnancies. The death of a teenage mother or the baby may occur more frequently than with matured woman. This is so especially if the girl did not seek any ante-natal care.\n\n\
6. A teenager who gets pregnant generally does not have money to support a pregnancy because she earns no money. She will have money problems and be poor. This poverty may lead to emotional disturbances, which may force her to leave home and find somewhere to live, which can be a difficult experience. Poverty may also lead to diseases e.g. malnutrition of both mother and child Unmarried and unemployed teenage mother depends on his parents who are already overburdened with their own problems. The teenage mother may out of poverty take to prostitution due to financial problems.\n\n\
8. If the pregnancy leads to marriage, such a marriage might end in a lot of unhappiness because both the boy and the girl are not ready emotionally for marriage. A young teenage mother could be discouraged in life or the neglect by her parents may lead to waywardness.\n\n\
9. Teenage mothers lack the experience and training in bringing up children. Because they lack the art of motherhood, their children, if not properly brought up, cannot be trained to become responsible citizens in the community. Such children may be neglected and unloved cr uncared for and may become social misfits, that is, armed robbers, drug addicts and pushers.\n\n\
10. Teenagers who indulge in unprotected sex are likely to be infected with sexually transmitted diseases (STDs) like gonorrhoea, syphilis and AIDS\n\n\
11. Children from poor teenage mothers could suffer from poor health. This is because a teenage mother may not have enough money to buy food or attend post-natal clinic. As a result she may not have enough breast milk to feed the child. This may result in the child being malnourished and exposed to the six killer diseases of infants.\n\n\
12. The teenager may try to abort the pregnancy in a criminal way by using herbs or drugs or by going to a quack doctor. She may end up bleeding profusely which may result in her death. She may also have infection of the tubes, which may lead to sterility. The uterus may be perforated as a result of the quack doctor trying to use some instruments to abort the pregnancy. The result is that the teenager may easily die or become sterile.\n\n\
13. The teenager’s future marital status may be disturbed, as she would not have a husband to take care of her and the baby. As she has no skill because she could not complete her education she may end up becoming a prostitute due to financial problems. Children are a great responsibility."
},


{
id: "question3",
question: "3. How does the individual develop self-confidence?",
definition: "Every individual is born with some innate potentials which when the necessary environment is created can make the individual seize the opportunity to exploit his/her potentials for self-actualization and hence self-confidence. There are several ways by which the individual can build self-confidence.",
options: "\
1. Role Taking: Through the process of role taking the individual learns to know himself by creating an image of himself and by identifying somebody as a role model. During child play one often sees children playing the role of a father, mother, doctor, teacher, soldier, etc. Through this process the child learns to wield power and exert authority over those he/she finds as subordinates. Some of these children out of these primary leadership roles emerge to become renowned leaders in their future social life. The individual, therefore, by identifying himself or herself with inspiring and prominent people in the society tries to take over certain characteristics or traits of these role models; which invariably help to boost his/her ego and confidence in life.\n\n\
2. Taking on an identity: Family names help an individual to be identified with responsible and great personalities in the family. Names, therefore, give a sense of identity to an individual. If one is named after a respected and responsible family member whether dead or alive one tries as much as possible to follow the foot steps of the person so that one does not bring disgrace to that family member. Names therefore help one to be identified with great people in life. The individual therefore needs to take on an identity which will help to develop his personality and confidence and make him capable to live to the expectation of his idol or mentor\n\n\
3. Self-awareness and knowledge of capabilities: The individual must be aware of himself and also know his capabilities. The capabilities of man include the ability to think, remember, create, invent, control the environment and solve problems. Individuals can develop their own capabilities if they are prepared to take risks and venture into new areas. This means that individuals must build self- determination and self confidence so that they can put their talents into use.\n\n\
4. Provision of Conducive Home Environment: Parents, siblings, guardians and family members have an important role in providing an enabling environment at home which will be conducive enough to develop the individual’s self-confidence. The love and encouragement that parents, siblings, family members give to the individual will enhance his image and strengthen his potential and equip him with the tools necessary for his future life. Parents must also provide the needs of children and ensure that their rights are protected. This will make the child have confidence in himself and his immediate relatives.\n\n\
5. Availability of Enabling Environment: The state and other agencies should provide an enabling environment to develop the self-confidence in the individual. Agencies like the School, mass media, religious groups, youth associations like Boys Scouts, Girls’ Guide etc. can be very crucial in shaping the character and values of the individual. The individual can take up leadership role in some of these organisations which invariably will help to boost his/her morale and self-confidence.\n\n\
6. Education and Training: Education and training helps in discovering and developing a person’s potentials. Education trains the mind and equips the individual with the needed skills required to develop these potentials. For example, through education a student can assist his/her mother to keep proper accounting record for his/her mother’s business. Apart from classroom education, training and apprenticeship help the individual to develop his identified potentialities. Also training and re-training of the individual helps to sharpen his skills and make him self-confident in his chosen profession.\n\n\
7. Self-determination: The individual can develop self-confidence by having a sense of vision to identify his hidden talents and other human qualities. Sense of vision also means goal setting. Once the individual has recognized his set goals in life it becomes necessary for him to make a systematic planning or work hard to achieve these goals that he has set for himself in life. In his effort to achieve these set goals the individual must know that there will be obstacles in his way. By developing positive self-confidence the individual can overcome these obstacles and achieve his set goals in life. For example, a student who is determined to be a medical doctor in future will have to learn very hard to achieve his future aim"
},


{
id: "question4",
question: "4. Discuss any four ways by which productivity in Ghana can be increased.",
options: "\
1. Education and training to improve the quality of the human resource: Productivity can be increased by improving the quality of the labour force through education and training. The kind of education and training given to labour will determine its productivity. Schools often provide basic education and lead to increased literacy. Literacy makes mass communication easier and opens the way for people to learn for themselves and obtain new ideas and information. For example a literate farmer who can read and follow instruction in the application of say, fertilizer and adopt modern methods of farming will be able to increase his level of output as against an illiterate farmer who connoted. Training facilities provided by Universities, Polytechnics, Technical schools, Institutes, Commercial and Vocational schools help to improve the skills of workers. Education is necessary to equip workers with appropriate skills as well as adopting new machines and technology. A clerk who has been trained to use a word processor can perform better than an ordinary typist. Training within industry enables workers to handle particular machine properly and for work to be done correctly. In addition seminars should be organized periodically for all level of manpower to improve their skills. The activities of Management Development and Public Administration as well as Ghanaian Enterprises Development Commission need to be expanded to cater for the shortcoming in the country’s manpower training programmers.\n\n\
2. Improved remuneration and conditions of work: High wages and salaries may result in a high standard of efficiency and this has often led employers to offer higher than the standard rates of pay to their employees. Efficiency will be increased if high wages increase the physical welfare of the workers. Higher wages normally induce workers to put in more effort thus increasing productivity while low wages make workers less efficient. The conditions under which work is done can affect workers output or efficiency. To increase workers’ efficiency, adequate ventilation, lighting and sanitation are important. Over crowding must be avoided since this affects efficiency and health. The health of the worker is very important since a worker with a weak health cannot be very productive. Improved health facilities are necessary to increase workers efficiency. The provision of better health services is necessary, because a healthy worker would be able to work well whereas a sick worker is likely to fall sick. Employers must cater for the health needs of workers. The worker’s efficiency can be raised if relevant and appropriate incentives like bonuses, housing schemes, rent and transport allowances, canteen facilities are provided for him. For example, a poorly housed worker can hardly give off his best in his job. Transport to and from work and recreational facilities all induce workers to work hard.\n\n\
3. Co-operating Factors/Quantity and Quality of other inputs: The quality of the factors (land and capital) with which labour has to work with is an important determinant of labour’s productivity. The greater quantity and quality of the capital employed the greater will be the productivity of labour. The right type of tools, machinery, and equipment should be provided in all factories and in sufficient quantities to increase labour power of productivity. Also the fertility of the land, type of machines and equipment used in production are factors, which affect the productivity of labour,\n\n\
4. Worker/Management relations: The workers’ efficiency (or productivity) can be raised if they are motivated by their management to boost their morale. Management must promote good management- worker relationship. This means that the management must have a cordial relationship with their workers. Management must be approachable, friendly and sympathetic towards their workers so that they can discuss their problems with them. Management must also identify the needs of their workers and satisfy them to reduce apathy and increase their productivity. The exercise of effective management control is, therefore, needed in all establishments to increase output.\n\n\
5. Development of positive work attitudes :Improvement in attitude to work is very essential. Many workers have the wrong attitude to work because they have the impression that additional output or profit only benefits the ‘Government’ and not the workers themselves. Laziness, lateness, absenteeism, embezzlement, falsification of accounts, drunkenness and working lottery during working hours are some of the poor work ethics exhibited at work places by Ghanaian workers. To raise productivity workers should be educated to show a change in these negative attitudes to work and inculcate new and positive attitude towards work to enhance productivity.\n\n\
6. Better management practices: There is the need to ensure sound and efficient management practices at the various work places to increase productivity. Managers of business must be trained and have regular re-training and must also attend workshops, seminars, management courses to update their managerial practices. If a business is managed by a well-trained personnel they will be able to supervise their subordinates to exact maximum productivity from them.\n\n\
7. Involvement of workers in decision-making: Decisions taken by employers or management should not be imposed on workers. They should be part of the decision making process of the organisation since their well-being and future are tied to the survival of the organisation. When workers are allowed in determining the working process of the organisation, they become committed to the work they are assigned to do. This is because the success or failure of the business will rest on them and to avoid this they will work harder. Worker participation in decision-making motivates them to put in their best in the job that they are doing.\n\n\
8. Political stability :Political instability in the form of coups disturbs the orderly process of government and affects economic stability of the country. Smooth change in government, absence of coups, ethnic conflicts or civil wars ensures congenial atmosphere for workers to increase output without the fear of war looming over them. Under this condition worker productivity can be increased, as management will be prepared to invest more capital into the business since their investment will be protected.\n\n\
9. Conducting research: There is the need to conduct research to improve the methods of production, which will lead to quality goods produced. This will enhance the efficiency of the worker and enable goods to be produced on a large scale. It is therefore necessary for a business enterprise to adopt modern research methods in the production of goods and also make use of modern technology to increase labor productivity."
},


{
id: "question5",
question: "5. How can the Ghana Police Service be made much more effective in the maintenance of law and order? 6.In what ways can the youth be equipped to contribute effectively to national development?",
definition: "The Ghana Police Service can be made much more effective in the maintenance of law and order by using the following measures:",
options: "\
1. The police must be provided with adequate financial resources for the development of barracks, training institutions, recruitment, welfare facilities, etc. If the police are provided with more and well equipped training institutions with modern facilities they will be able to produce efficient officers.\n\n\
2. The police must be provided with formal and in-service training. For the police to perform better on their job, there is the need to ensure that those employed have formal education, which will form the basis for formal training to take place. Formal training and in-service training will equip the police personnel with modern ideas and skills in the performance of their day-to-day activities. In-service training, for example, can equip the police personnel with new skills, which will enhance their performance and make them comparable to their counterparts in the advanced countries.\n\n\
3. The police must be trained to use modern technology for effective crime detection and crowd control detectors, cameras, communication gadgets, etc. The use of modern technology by the police in their day to day activities will enable them to be more effective in their duties. This will enable the public to have confidence in the police. The police stations must be equipped with good telephone systems so that the public can easily reach them with adequate information on the activities of criminals.\n\n\
4. The government must improve the rather poor transportation situation in the police service to enable the men to be mobile. If the police are provided with vehicles they will enable the men to respond to any call from the public about cases of burglary or crime without delay. Vehicles provided should be regularly maintained and provided with fuel -petrol and diesel enable the police service perform their patrol work better. For effective administrative work every police station should have a vehicle(s) to facilitate their work.\n\n\
5. The police administration must improve the poor perception/image of the Police by the public to enhance public police co-operation. The police must lift up their rather poor image by ensuring that all corrupt, lazy, inefficient personnel are weeded out from the service to improve the image of the police. Corrupt and unscrupulous Police personnel must be seriously disciplined to serve as an example to their fellow officers or men. The police must have positive attitudes to work so that the public will ready to volunteer information to them about the activities of criminals in the community.\n\n\
6. The Police must be provided with adequate remuneration and improved conditions of work to enhance morale. Salaries for the Police must be very attractive so that they are not easily corrupted into taking bribes. They must be provided with subsidized accommodation and canteen services, risk allowance, hospital allowance to boost their morale.\n\n\
7. For effective coverage/policing, recruitment must take account of the population of the country. There is the need for the Police administration to recruit and deploy adequate police personnel to cover the whole country for effective coverage. If the number of Policemen is increased it will enable them to have regular street patrols day and night and check criminals and arrest them and also protect lives and property."
},


{
id: "question6",
question: "6. In what ways can the youth be equipped to contribute effectively to national development?",
definition: "These are many ways by which the youth can be equipped to contribute effectively to national development",
options: "\
1. Giving them opportunities/facilities for basic education and training: The youth can be equipped to contribute to national development by educating and training them to upgrade their knowledge. Through education, knowledge is imparted to the youth. Education also brings out the talent in the youth and helps them to know their strengths and weaknesses. Through school debates, quizzes, symposia and other club programmes the youth will be exposed to ex pressing himself/herself in public and also learn to be self confident when speaking to a large crowd. Facilities like learning materials, equipment and workshops should be provided by the government to facilitate training of the youth. When these facilities for basic education and training are put in place the youth will be equipped with the necessary skills for national development.\n\n\
2. Provision of Avenues/Opportunities to put their skills and talents to use: The government should provide avenues or opportunities that will enable the youth to take part in environmental projects like tree planting. The youth can also teach the local people the dangers of bush fires, deforestation, etc and measures that can be taken to control these environmental problems. The youth should also take part in projects planned by the Government in the country like immunization, population census, AIDS campaign, registration of voters etc. These activities enable the youth to put their skills and talents to use and also know the task ahead of them as future leaders of the state. By taking part in national and local programmes, the youth learns to be patriotic and loyal to the state. At workshops, the youth can be encouraged to improve upon the sanitation in their areas by desilting gutters, clearing bushes etc.\n\n\
3. Providing adequate Guidance and Counselling Programmes: The youth as the nation’s future leaders must be guided and advised on how to help in national development. Most youth misuse their huran resources on useless ventures as a result they need to be guided so that they can learn skills that can prepare them for national development. The youth should also be counselled by the adult to know their role or what they can contribute to the development of the nation. Guidance and Counselling therefore helps the youth to bring out their hidden talents or visions in life which can prepare them to contribute their quota to nation’s development. The youth should be guided by the adult to develop appropriate lifestyle and desist from social vices like drunkenness, armed robbery, rape, etc.\n\n\
4. Role models: The youth should be exposed to appropriate role models, that is, people with outstanding qualities or big minds and have status in the society. If the youth are exposed to these role models they will be able to learn certain values and norms from them which will help to fashion their lives. As the youth aspire to be like their role models, they try to direct their energies to profitable ventures that would push them to positions attained by these role models. Good role model becomes an assert to the youth and even brings out the best talent for national development.\n\n\
5. Formations of various Organisations and Movement: In preparing the youth for national development there is the need for the formation of various organisations and movements where the energies of the youth can be effectively harnessed. Youth organisations and movements like the Boys Scout, Girls Guide, CTO, YWCA, YMCA enable the youth to come together to share ideas and learn skills for national development. The youth can also form environmental protection clubs such as Green Earth Organisation so that they can direct their energies to assist the local people to know the importance of protecting the environment against the various causes of environmental degradation, e.g. deforestation, pollution etc. The youth can also join progressive clubs such as ‘Young and Wise’ and invite resource persons from PPAG to give a talk on abstinence, teenage pregnancy, HIV/AIDS, abortion etc. The youth can then go to community to impact the knowledge acquired to other people.\n\n\
6. Setting up institutions for leadership training: The government can set up institutions to develop the leadership qualities in the youth. Here the youth should be made to take responsible positions in training or youth camps, which can help them to acquire leadership qualities and also equip them with the necessary skills that will be needed for future leadership position. The establishment of youth training camps like that of Afienya in the Greater Accra Region contributes a lot in unearthing the leadership qualities in the youth. It was established to equip the youth with unemployable skills like tie- dye, screen- printing, sewing, leather-works, knitting, hat making. It has class rooms, workshops, assembly Hall, computer training center and other facilities.\n\n\
7. Providing a Policy Framework for youth development: The government should draw up an achievable policy framework for youth development. This can be done by introducing the youth to various social programmes set out for national development. The government’s policy framework should also address the manpower needs of the country by encouraging the development and promotion of youth organisations in the regional and district capitals. Such youth organisations should be provided with the necessary logistics like personnel, equipment and materials for their growth."
},


{
id: "question7",
question: "7. Examine some aspects of traditional government which you consider democratic.",
definition: "The following are some aspects of traditional government which I consider democratic:",
options: "\
1. Popular participation in decision making: In modern representative system where one person represents thousands of people in parliament, which does not make for good democracy. In the traditional set up, beyond the council of elders popular participation in decision making occurs at some levels. Popular participation in decision making can be brought very close to the people if for each electoral area or village by beating the gong-gong for people to meet and deliberate over issues affecting them. When consensus has been reached, the representatives will in turn send the outcome of the deliberations to the council of elders or the parliament. Thus the people would be truly represented and their views would be heard by all.\n\n\
2. Role of council of elders: In the traditional system, consensus building is upheld for good governance. Thus the chief has council of elders through whom he ruled. The council of elders is composed of the various sub-chiefs and elders of the lineage or “Ebusuapanyin.” The traditional ruler is assisted by a council of elders who advise and help in making laws. Laws are therefore strictly obeyed through the institution of taboos. The chief is, therefore, not a dictator. However, he is the spiritual leader of the society and therefore ensures that libation is poured for the up keep and well being of the society. He also invokes the ancestral spirit and asks for help and support. This position of the chief makes him to be held in high esteem, revered and respected by the council of elders and among the people.\n\n\
3. Removal of a ruler: A ruler who falls out of favour may be removed. But he is given the opportunity to respond to charges preferred against him. Since there are laid down rules for changing the government in the traditional set up no single person can stage ‘Coup d’état’ to overthrow a traditional government. Before there is any change of government the council of elders in collaboration with the elders of the royal family and the general public have to come lo compromise and destoolment charges are heard and debated on by the council of elders before changing the administration headed by the chief. Clearly consensus building has been the basis for traditional government for it incorporates democratic systems, respect for authority and transparency in the governance of the society which can be applied in the modern system of democracy.\n\n\
4. Swearing an oath of office: In the traditional government, the chief ascends the throne in accordance with customs of the community. He takes an oath of office and consents to govern in the interest of the people. He also makes pledges of allegiance or loyalty to the people. The chief is therefore expected to rule within the limits of the customs and traditions of the area. In adjudicating cases, the ruler is expected to be impartial. The chief is, therefore, regarded as the soul or father of the people and must at all times bring the various families or ‘abusua’ together to assist the council of elders to govern the community to the satisfaction of the people.\n\n\
5. Selection of a chief: Even though the ruler is selected from an inclusive group by a small group of kingmakers, the public may be given the opportunity to express approval or disapproval of the choice. In traditional set up, the ruler is not imposed on the people because he is selected by kingmakers and he must be a person of good character and having the characteristics of a chief. If the public disapproves of the choice made the king makers will have to accept the popular decision of the people.\n\n\
6. Freedom of speech: The traditional system of government provides for some freedom of speech, right to life, right to ownership of property, fundamental human rights etc. The traditional system of government has no organised opposition. For example, decisions-making comes not directly from the chief but in consultation with the council of elders composed of the sub-chiefs, lineage heads and other elders of the chiefdom, who deliberate freely on issues so that whatever decision that comes out is from the cross section of the community. Above all, before the implementation of decisions the gong-gong is beaten and the public meet to share their views on them during, which all adult male and women can participate. –"
},


{
id: "question8",
question: "8. In what ways has Ghana benefited from her membership of the Commonwealth?",
definition: "The Commonwealth member states derive several benefits from the association. The following are some of the benefits Commonwealth member states enjoy.",
options: "\
1. Promotion of Trade: Commonwealth countries are members of a family, they give preferential tariffs to one another in their trading relations. In other words, taxes imposed on goods traded between member states and those that are not members of the association differ.\n\n\
2. Common Policy: Member countries are provided with the opportunity to share experience and discuss matters of common interest and to adopt a common policy in such matters. Very often member countries agree on one plan of action in world affairs. In times of war Commonwealth countries generally help one another. In the two world wars they fought on one side. They also play a very important role in disarmament, racial discrimination and environmental degradation. For stability of the organization member countries meet annually and freely to discuss matters that are of common concern to them.\n\n\
3. Education and Training: Member countries co-operate in the field of education and training. Some developed countries of the Commonwealth e.g. Canada, and Britain offer scholarships and fellowships to students from other member countries to study in institutions of awarding countries. They also supply equipment, books, journals and fund research for development in the member countries.\n\n\
4. Participation in sporting activities: In the field of sports, Commonwealth games are organized among member countries once every four years, rotating among member countries. Sports help to foster unity through boxing, athletics, cycling, hockey, swimming, etc. which promote understanding, unity and peace.\n\n\
5. Technical Assistance: Technical assistance is provided by many of the specialized agencies of the Commonwealth to member countries on a wide range of subjects including oil exploration, agriculture, forestry, fisheries and water resource development. The developed nations in the Commonwealth help the developing nations in globalization in terms of information technology. They make available the services of experts and consultants, financing of technical training programmes.\n\n\
6. Promotion of Democracy: Member countries help in democratic governance and also co-operate in activities to support democratic governance in terms of drafting of legislation, review of electoral procedures and monitoring the conduct of elections, sponsoring observer teams. For example in recent past the Commonwealth has observed democratic elections in Korea, Caribbean and Ghana just to mention a few.\n\n\
7. Financial Aid: Smaller countries of the Commonwealth like the Gambia for example feels secured for belonging to a world-wide organization which has a large membership but without any binding obligations on members. Member countries enjoy financial security because they are able to obtain grants and loans from the United Kingdom to promote development in the areas of mining, agriculture, sanitation, education, health etc.\n\n\
8. Avenue of exchange of ideas :Ghana has used the commonwealth as a forum for the exchange of ideas on inter-national issues and the solution of common problems. For instance, at the 1995 Commonwealth Leaders Conference held in Auckland, New Zealand, Ghana was among the countries, which discussed at length, a variety of issues including bad governance and the abuse of human rights, especially in African countries and its effects on regional peace and society.\n\n\
9. Cultural exchanges: Ghana’s cultural troupes have been visiting Commonwealth member countries including Britain to portray rich cultural heritage of the country. Other Commonwealth countries like Nigeria and South Africa have also visited Ghana to display the culture of their people."
},


{
id: "question9",
question: "9. Discuss FOUR effects of Mining activities on the physical environment in Ghana.",
options: "\
1. Emission of dangerous gases: The extraction of minerals from the earth crust brings about the emission of dangerous gases like arsenic oxide, sulphur dioxide etc which pollute the air and cause acid rain. Some gases like carbon monoxide, sulphur dioxide etc, which are released into the atmosphere are poisonous to human beings. For example, sulphur dioxide dissolves in water to form acids that corrode materials and irritate the human body.\n\n\
2. Discharge of dust into the atmosphere: The dust particles and smoke released into the atmosphere as a result of mining activities can cause respiratory disorders and lung diseases for people. Dust and smoke can cut down the amount of sunlight reaching plants for photosynthesis thereby leading to reduction of crop yields and retardation of plant growth.\n\n\
3. Land Degradation: Extraction of mineral ores is done by deep shaft mining, surface mining or open cast mining. The use of heavy machines like bulldozers to dig out minerals from the earth crust degrade the land through the creation of pits, sagging of the land etc leading to the flooding when it rains and soil erosion. In Prestia and Bogoso area, Billington Bogoso and Sankofa Goldfields have cleared a large area of forestland in order to get gold. Removal of topsoil to expose the ore is one of the greatest problems created by the mining companies in their areas of operation. These operations have resulted in the destruction of vast tracts of farmland and forest. When these mines have been exploited they are abandoned and nothing is done to re-integrate the land. The unscientific mining methods adopted by traditional mining (galamsey) in mining areas have made large-tracts of arable land unsuitable for farming. Thus the abandoned mining areas have become breeding grounds for mosquitoes as water collects in the gullies created. Also mineral exploitation pollutes the area around with dust produced from bauxite and manganese mines.\n\n\
4. Destruction of Vegetation: Mining activities lead to the destruction of vegetation, farmlands, forests, riverbeds. etc. Excessive mineral exploration destroys the country’s farmlands and forests which can cause low agricultural yield as the soil nutrient is destroyed. The decline in soil fertility leads to loss of soil moisture which results in the poor yield from the land or the affected land cannot be used for agricultural production. In some areas, the roots of some trees are damaged in attempt to acquire minerals. This causes trees to be uprooted easily during rainstorms. The operation of small scale miners causes the removal of top soil which happens to be rich in soil nutrients, Alluvial gold and diamond mining take place in some rivers and this affect the riverbed. Surface mining popularly called “galamsay’ has the effect of destroying the vegetation since the top soil is removed to extract the gold. Pollution of Water Bodies: Water sources in mining communities get contaminated as a result of mining activities like dredging. Some of the particles discharged from the mining industries are mine tailing and other effluents. Others are chemicals like Sulphur compounds, sulphur acids etc. The large volume of waste water, which is muddy, released during the ore washing process of the extraction of manganese and diamond cause water pollution. Some rivers, which are affected, include Rivers Ankobra, Birim, offin, Pra and their tributaries.\n\n\
5. Destruction of Physical Structure: Mining activities near towns have a damaging effect on the physical environment. Through the use of heavy machines like bulldozers and dynamite to blast rocks containing minerals, the physical structures like buildings, roads and other facilities develop serious cracks and also weaken the foundation of these structures and with time cause their eventual collapse.\n\n\
6. Noise Pollution: Noise and vibration that mineral exploration produces have serious effect on the environment. These noises and vibrations are the result of blasting, processing plants, such as air compressors and the grinding mills. These intensive noise could cause auditory problem (i.e. lasting or temporary hearing loss), cardiovascular problems etc.\n\n\
7. Development of Slums and Shanty Settlements: Mining areas attract a lot of people who come to seek employment in the mines. This leads to population concentration in the mining centres and put pressure on the available facilities like housing, water, electricity, schools etc. The effect is the development of slums and shanty settlements in the mining areas."
},


{
id: "question10",
question: "10. Why is Ghana unable to achieve self- sufficiency in food production",
definition: "Ghana is unable to achieve self- sufficiency in food production due to the following reasons:",
options: "\
1. Inadequate capital for farmers to invest in crop production, livestock, fish: Farmers receive low level of farm incomes from their produce and this leads to inadequate investment in large scale and efficient farming. The low level of farm incomes makes it difficult for farmers to get sufficient money to hire labour, up-to-date agricultural equipment like farm tractors, seeds, fertilizers, insecticides etc. Farmers find it difficult raising loans from the banks because they do not have the collateral security like insurance policy or title deed to property (like land, equipment or building) often demanded by financial institutions (i.e. Banks) as security against loans. Also many farmers farm on land owned by the family and therefore cannot use it to secure loan from the bank to buy improved seeds, fertilizer, pesticides etc. to increase output, Lack of sufficient capital also prevents cattle rearers from confining animals or providing shelter, purchasing of food, providing input or constructing stalls and purchasing of chemicals.\n\n\
2. Inadequate Infrastructure : Lack of transport facilities is a problem to increased agricultural production. There are few accessible roads and where roads exist they are in most cases impassable in the rainy season or contain large pot holes which retard the smooth movement of vehicles. The resultant effect of this poor transport facilities is that a considerable amount of farm produce get rotten on the farms since farmers cannot transport their farm products to the marketing centres in the cities. As a result, farmers are forced to sell their farm produce at a ridiculously low price to middlemen who in turn sell them at prohibitive prices. In Sept. 6, 1994, Daily Graphic reported that food prices at Bolgatanga have shot up following the flooding of about 1 km. of the main Bolgatanga-Tamale road around Pwalugu thus making the road unmotorable.\n\n\
3. Lack of storage facilities : Lack of knowledge of proper storage methods or processing of produce usually results in insect infestation or spoilage. If farmers do not know how to store their produce, they will be forced to sell at cheap prices to consumers at harvest. Consequently, they will lose income and this will reduce their working capital and profit. Farmers also cannot afford to build storage tanks or silos to preserve their agricultural produce to reduce post-harvest losses. Because farmers cannot store and preserve their farm products for long, they usually grow food only for the needs of their family and what they can sell quickly in the local market. This is why food tends to be plentiful and cheap during the harvesting season but scarce and expensive latter in the year. The storage losses of all food crops produced in the country are estimated to be between 15 and 30% (Ministry of Food and Agric 1990). The development of a number of storage facilities for grain storage (70,000 mt capacity) are few and not within easy reach of farmers in the rural areas who would want to use them. A reduction of about 30 to 50% of the level of losses could significantly reduce the country’s dependence on food imports needed annually to meet consumption demand\n\n\
4. Inadequate marketing facilities: Inadequate marketing facilities especially poor roads inhibit movement of farm product to the marketing centres. As a result most farmers are therefore at the mercy of traders who offer them very low prices; and if such prices are refused the produce will be left to rot. The result is that the farmer gets very little money for his produce. There is no central selling organisation for farm products particularly foodstuffs and there is no guaranteed market price for then. The Ghana Food Distribution Corporation (GFDC) and the State Fishing Corporation (SFC) are ineffective in assisting the farmers and fishermen to preserve their farm produce and fish when there is bumper harvest and offer guaranteed prices for foodstuffs and fish. This explains why food-stuffs are plentiful in the rural areas and scarce in the urban centres. Poor marketing arrangements, transportation and storage discourage farmers and fishermen to increase output per head.\n\n\
5. Price Instability/Poor agricultural pricing policy: Prices of agricultural products vis-à-vis those of manufactured products are usually low. People with high entrepreneurial ability are therefore not attracted. Furthermore, because of the general seasonal nature of agricultural products, their prices are very unstable. Farmers, therefore, cannot forecast their incomes for any given period. This has proved a strong disincentive to farmers who want to apply for loans since they cannot compute their earnings. The prices of foodstuffs are quite unstable because of low labour productivity with resultant low incomes for farmers due to post harvest losses and poor storage facilities.guml.in\n\n\
6. Rudimentary technology and conservatism: Most farmers in Ghana are illiterate, very conservative and continue to use cutlasses, hoes; sticks etc. in farming. They therefore find it difficult to understand the use of modern implements like’ tractors, combine harvesters, planters, ploughs etc. and new methods of farming introduced by the extension officers. Many of the researches carried out are not adopted by the farmers, and even the simple application of fertilizer cannot be undertaken by most of the farmers. The indiscriminate use of agro-chemicals by farmers who cannot follow the instruction for their use is a consequence of low agricultural productivity in Ghana. The reliance on traditional methods of farming like bush following, bush burning and shifting cultivation by farmers in Ghana impoverish the soil and reduce farm productivity and the area planted.\n\n\
7. Inadequate research and extension officers.: Ghana is not self-sufficient in food supply because of non- application of research findings. This may be due to poor communication between research findings, adherence to age-old conservative farming ideas due to superstition and high cost of applying research findings. In Ghana there is a wide gap between farmers and agricultural research workers which is a major weakness in food supply. The ratio of extension officers to farmers needs to be increased from the present ratio of 1:2000 to about 1:50. New ideas that should come from research and extension officers are not forthcoming hence low productivity in foodstuff production.\n\n\
8. Urban migration: The low agricultural production can be attributed to the rural-urban income differential, which has tended to draw many young people from the food growing areas to the urban centres. The effects of this rural-urban drift are two. In the first place, the farming population left in the rural areas to feed the nation is made up of aged and weak people and therefore are not able to produce enough. Secondly, the rural-urban drift had created an acute shortage of farm labour in the farming areas. Labour costs are, therefore very high. As a result very few farm labour can be employed and their output per head would -be very low.\n\n\
9. Land Tenure System: Land tenure system inhibits very much any attempt to operate large plantation farms. In the traditional set-up, the traditional rulers or family heads are the trustees of the lands within their area of control. This system of ownership makes it difficult for an enterprising farmer to acquire large tracts of land for commercial farming since farm lands may be family owned. Enterprising farmers in the family are only allotted fragmented bits – very unsuitable for any commercial farming. Due to these problems, enterprising family members have found it difficult to use family farm lands as security for loans from the banks. Sometimes, land boundaries have not been well demarcated between families and litigations over who owns what have very much been time and money consuming. The land tenure system and land fragmentation in Ghana lead to small acreage farmed and farming on subsistence basis resulting in low output per head.\n\n\
10. Diseases and Insect Pests: Diseases and insects are threats to farmers in Ghana, and a disincentive to large-scale agricultural production. Many of the farm products like cocoa are at the mercy of diseases like swollen shoots and black pod diseases while grasshoppers also destroy large areas of cassava and vegetable farms. Cattle and cows suffer from tsetsefly while fowls suffer from fowl pox. The cultivation of tomatoes at the VA Irrigation Project near Bolgatanga was banned for at least three years following a high infestation of the area by nematode, a tomato disease (Daily Graphic, Dec. 7 1983). There is lack of effective methods of pest control and this explains why there is low level of labour productivity in agriculture in the country.\n\n\
11. Inadequate supply of agriculture inputs/High cost of inputs: The supply of agricultural inputs like tractors, fertilizers, insecticides, pesticides and so on is inadequate to meet the needs of all farmers. The high prices at which these agricultural inputs are sold make it difficult for farmers to buy them to increase their output. Late arrival of farm inputs to farming communities also contribute to the low productivity of the farmer. Cuts on subsides of agricultural inputs have had negative consequences culminating in the reduction of the rate of adoption of innovations that will lead to increase production. Extension officers in agriculture complain about the inability of farmers to purchase basic agricultural inputs like fertilizers, insecticides etc. The soaring prices of agricultural inputs resulting from the cuts on subsides have made it difficult for the farmer to undertake routine spraying and other cultural practices.\n\n\
12. The Weather/Natural hazards: There is widespread crop failures due to adverse weather conditions; the frequent droughts and inadequate and irregular rainfall on a prolonged scale have badly affected agricultural productivity. The rainfall in Ghana is quite unreliable with respect to the onset, duration, intensity, amount etc. The rainfall pattern is partly the cause of the considerable seasonal fluctuations in crop output as reflected in the low yield per hectare.\n\n\
13. Reliance of food imports In Ghana various kinds food items are imported into the country, particularly rice, the result is lack of interest by government and non-governmental institutions in the development of agriculture. The government imports $120 million worth of rice annually. This negates the attainment of food sufficiency which constitutes a vital step in the development of food production in Ghana"
}

]