export const SOCIALSTUDIESB2009 = [


{
id: "question1a",
question: "1a. Explain the term national building.",
options: "\
1. Nation building is the sustained efforts to maintain the unity and harmonious living and to improve the quality of life in the country – Ghana.\n\n\
2. It implies integrating multi-ethnic, multi-lingual and multi-cultural groups into one nation for social and economic development\n\n\
3. It entails living in peace and harmony to ensure sustainable development and economic growth."
},


{
id: "question1b",
question: "1b. Outline four ways in which individual can help promote nation building. [16 marks]",
definition: "The following are some of the ways in which an individual can help promote nation building:",
options: "\
1. Fulfilment of obligation: The individual must be law abiding by paying his/her taxes and must also ensure good inter-personal relation with people whom he/she interacts. Taxes and levies that individuals pay as members in the community are used by District/Metropolitan Assemblies to finance development projects like constructing schools, feeder roads, markets, clinics, hospitals etc. for the people. It is therefore obligatory for the individual in the community to pay his/her levies and taxes. The individual can send it count if he fails to honour this national duty. Individuals must also obey rules to ensure peace and harmony in community: The individual is expected to abide by the rules and regulations in the community. This will promote peaceful co-existence and harmony in the community. The individual must respect the views of other people and must not react irrationally since such behaviour can lead to conflict and disturb the peace of the community.\n\n\
2. The individual must adopt positive attitude towards national development: The individual must lead an exemplary life in the community for the youth to follow. He must be courteous to the elderly and assist them where necessary. The individual must be loyal and law abiding and eschew self-interest. An individual who is loyal will stand up against acts, which will disturb the stability of the community.\n\n\
3. The individual must eschew all forms of ethnicity, ethnocentrism and nepotism. Ethnicity is the cause of civil strife among some of our ethnic groups whiles ethnocentrism obstructs the peaceful atmosphere, unity and the spirit of national integration needed for nation building. Nepotism, on the other hand, breeds favouritism in the public service and in the allocation of resources and development projects. It is the duty of the individual to promote national traits like Independence Day, Republic Day, and National Cultural Festivals etc which they have the potential of binding the people together and put less emphasis on ethnic traits which can divide us.\n\n\
4. Loyalty to the state: The individual must be loyal to the state and protect the constitution of which he is a stakeholder. This means that the individual must not involve himself/herself in treason which will undermine the stability of the nation. The individual must not conspire with people with questionable characters to overthrow the government through military coup. This can disrupt the sustainable development of the country and also affect the constitution of the country.\n\n\
5. The individual must participate in decision making at the community level and national level. The individual must involve. /Herself in communal labour: Here the individual is obliged to take part in communal labour activities in the community in which he/she resides. He can help in clearing chocked gutters and weedy areas etc. This will promote healthy and clean environment devoid of mosquitoes. For communal labour if the individual does not attend, he can be sanctioned. The individual can also express his support for his community by engaging in community initiated projects like the establishment of community library, clinic, Football Park, school, etc. Here the individual takes part in the self-help project because he is patriotic and therefore receives no money in return. 6. Prevention of crime: It is the role of the individual to help the police/law enforcing agencies to combat crime. Here the individual can provide information which can lead to the arrest of a criminal in the community. The individual can with the community support form a vigilante group to support the effort of the police in his/her locality to combat crime.\n\n\
7. Protection of State Property: Every state property is built with public funds or taxes that we pay to the sate. It is important these properties are handled responsibly and with care. If this is not done, the government will have to spend scarce resources in replacing damaged state property"
},


{
id: "question2a",
question: "2a. What is rule of law? [4 marks]",
definition: "The rule of law essentially is the principle that in all things it is the law that rules. It implies all members of the executive branch of the government including the president, all public officials, members of parliament, judges and all citizens are subject to the law and must obey the laws of the state. It requires that no other means such as force or violence must be used to manage the affairs.",
},


{
id: "question2b",
question: "2b. Highlight four conditions that must prevail to ensure the operation of rule of law. [16 marks]",
definition: "The conditions that must prevail to ensure the operation of rule of law may be stated as follows:",
options: "\
1. There should be a written constitution: To ensure the operation of the rule of law there should be in existence a written constitution, which spells out all the rights enjoyed by the individual in the country. The fundamental human rights must be entrenched in a written constitution to make it difficult for the government to tamper with. This will ensure that all people are treated with the same law of the land.\n\n\
2. Good governance: The constitution ensures that those ruling apply the principles of rule of law. All the principles of the rule of law are specified in the constitution and serve as a way in which according to the rule of law, the government itself is subordinate of the law. This is because there must be set limits to what the government of the day can do with regard to the right of the individuals.\n\n\
3. Publication of the laws: The citizens of the country must be enlightened so that they can know their rights and the laws of the state. This means that the population should be literate so that they can read and know their rights and the laws of the country. The laws of the country should therefore not be shrouded in secrecy but must be published for the general public to know the laws that are used to administer the country.\n\n\
4. The laws that are made must be general which is not against any specific individuals or groups in the state. The application and interpretation of the laws must not favour certain individuals in the society because they belong to certain political party or because of their affiliation with certain people in power. The laws must be seen to operate without showing partiality.\n\n\
5. Press Freedom: A free and independent press or mass media is the press which is free from all governmental control and its dedicated to honest reporting and the defense of the rights of the masses. A free and independent mass media can expose the arbitrary actions of the government so that the political leaders may not conduct themselves in a manner that is inimical to the interest of the people. For example, the government cannot imprison anybody without trail beyond certain limits knowing very well that the press is there to protect the liberty of the individual.\n\n\
6. Rule of law provides for equal opportunity to the social, economic and political facilities existing in the state. The rule of law must ensure the provision of basic education, health facilities, equal opportunities for employment in the public sector, recreation and welfare schemes. The provision of these facilities helps the growth of every sector of the economy and helps the individual to contribute his quota to the country’s development.\n\n\
7. Availability of Legal Aid: The constitution of the country entrenches the fundamental human rights so that the government cannot temper with them. These rights can be protected if the government provides facilities such as free legal aid to people who are in dire need of legal advice but cannot afford the legal fee charged by lawyers. The provision of legal aid will help such people to seek redress at the law court.\n\n\
8. Press Freedom: A free and independent press or mass media is the press which is free from all governmental control and it’s dedicated to honest reporting and the defense of the rights of the masses. A free and independent mass media can expose the arbitrary actions of the government so that the political leaders may not conduct themselves in a manner that is inimical to the interest of the people. For example, the government cannot imprison anybody without trail beyond certain limits knowing very well that the press is there to protect the liberty of the individual."
},


{
id: "question3",
question: "3. Examine five responsibilities which an individual ought to fulfil in the society? [20 marks]",
definition: "The following are some of the responsibilities which an individual/citizen ought to fulfill in the society",
options: "\
1. To promote the good name of the society: Citizens of the country should have unqualified loyalty to the state and owe allegiance to it. If a person is not loyal or does not owe allegiance to his country of birth it implies he /she is not a good citizen of the country. He can leak state secrets to another country. Lack of loyalty on the part of the citizens to their country can cause insecurity in the country. For instance in Somalia, Liberia Sierra-Leone, lack of loyalty on the part of some citizens brought anarchy in their countries. One way of promoting the good name of the society is to respect the national flag of the country since the flag is the symbol for the country. When one does not respect the flag it means one does not respect the country. This is why many a time Palestinians when angered by Israelis carry Israel flag and set it on fire to indicate their disrespect for Israel. Also when the national anthem of a country is being played it is the duty of every citizen to stand up as it is a national song. By so doing one is showing respect and reverence and love for the country.\n\n\
2. Obedience to the laws of the state: It is the responsibility of a citizen to live in harmony with others by abiding by the rules and regulations of the society. It is therefore important citizens obey the laws of the society. If laws are not obeyed but flouted with impunity, the net result will be anarchy between individuals in the country as a whole. For peaceful co-existence and harmonious relationship to exist among citizens, it is obligatory for citizens to obey the laws of the country and this will enable the government to function well to ensure stability and citizens can enjoy their rights.\n\n\
3. Payment of Taxes: Taxes are levies exacted by the government or its agents on individuals, goods and services etc. to basically raise revenue for the development of the country. Taxation or payment of taxes is not a new phenomenon. It has been in existence throughout ages and our traditional set up or system has it. The bulk of revenue accruing to government is from taxes and it is that which is used for development projects such as construction of schools, clinics, markets etc. Thus the payment of taxes helps the government to fulfil its obligation to the citizens and non-payment will prevent the government from providing the needed social amenities to the citizens. It is therefore obligatory for all citizens to pay taxes to the government.\n\n\
4. Respecting the rights of other citizens: The citizen is expected to respect the rights, freedoms and legitimate interests of others; to refrain from doing acts that are detrimental to the welfare of other persons. The rights of a person are the duty of the other that is to say the rights of Kofi is the duty of Kwesi and vice versa. This means that for instance, if Kwesi has a property, it is the duty of Kofi to protect it and not to steal or destroy it to deprive Kwesi of his right to own such a property. If Kofi steals or destroys it, he would have interfered with the rights of Kwesi. For harmonious relationships to exist it is the duty of every citizen not to interfere with other peoples, property, security or personality.\n\n\
4. Protection of state property: Every citizen is expected to protect and preserve public property and expose the misuse of public funds. A citizen is expected to take proper care of the public or government buildings, equipment, furniture, documents etc so that they can last long. Poor maintenance and preservation of government properties means public funds which could be used to provide hospitals with drugs, provide water, electricity would have to be used to either replace the damaged government properties or ensure their regular maintenance.\n\n\
5. Maintenance of law and order: It is the duty of the individual to co-operate with lawful agencies in the maintenance of law and order. Every citizen must assist the lawful agencies to prevent criminal activities because they destroy the lives, peace and property of the society. It is therefore the responsibility of the citizen to report to the police people with suspicious actions that are likely to cause confusion in the society. Citizens must also endeavour to provide useful information that will help the police to investigate a crime and trace the hideout of criminals who terrorize innocent people.\n\n\
6. To take part in communal labor in his/her community. It is the duty of every citizen to participate in every social activity such as engaging in communal work and other development projects being undertaken by the community in which he resides. In this era of community participation in the development of social and economic activities, failure of an individual to take part in such communal work is an offence against the society and is punishable by fines or imprisonment or both. It is therefore obligatory or duty bound for every individual to take part in all social or community work.\n\n\
7. To protect and safeguard the environment: The citizen should advise people to stop the indiscriminate mining and felling of trees which have to effect of degrading the environment thus making it difficult for farming to take place. Again, the improper disposal of liquid and solid waste should be stopped to enable people live in clean environment. The burning of leaves, refuse and other solid wastes contributes to air pollution which is injurious to the health of people. The use of chemicals to catch fish in rivers and streams pollute the water bodies which kill the baby fish which increases the stock of new fish. It is therefore the responsibility of the individual to let people know that drinking water polluted with chemicals as well as eating fish caught from polluted rivers can cause cancer, rashes etc.\n\n\
8. Taking part in decision-making: The individual should take part in decision making at the community level and national level. The citizen can show his/her loyalty to the society by taking part in major levels of decision making and must also be prepared to support and defend his/her country at all times. When the individual takes part in initiating community-based project he/she can express such love by engaging in communal works and self-help projects such as constructing school blocks markets, places of convenience etc."
},


{
id: "question4a",
question: "4a. What are festivals? [4 marks]",
definition: "Festivals are periodic public celebrations to remember, give thanks, honour and renew allegiance and to commune with the ancestral spirits for guidance and protection e.g Harvest/Agricultural/Ancestral festivals etc. The following are some of the ways festivals important society:",
},


{
id: "question4b",
question: "4b. In what four ways are festivals important to society? [16 marks]",
options: "\
1. Period to portray the culture of the traditional area: Among some ethnic groups festivals are celebrated in remembrance of certain things that happened to their people a long time ago. For example, the Dagombas, the Nanombas and the Mamprusis celebrate the Bugum Festival. The festival is in remembrance of the day they found the lost son of their Great Chief. Some of the Ewes also celebrate the Hogbetsotso festival to commemorate the times their forefathers ran away from their cruel chief Agokoli\n\n\
2. Promotion of tradition activities. Festivals open up trading opportunities for members of the community. During festivals sellers get trade boom because people patronize the things they sell like shoes, dresses, clothes, T-shirts and other paraphernalia connected with the festival. Women who sell food get high patronage as well as restaurant operators which sell minerals and various types of beers and other liquors.\n\n\
3. Celebration of the harvest season: Festivals provide occasion for the people to see themselves as sharing a common cultural heritage and the need to cement unity. During festivals some ethnic groups in the north meet and give thanks to their ancestors for a good harvest (e.g. yam festival). This strengthens the bond of unity between the living and the dead.\n\n\
4. Moments for relaxation and joyful celebrations/ Family and clan re-union (Get together): Festivals now serve such important functions as periods of get-together. The life of the community is renewed, thus cementing their unity by bringing the people together e.g. through sporting activities, fun fairs etc. This is the time when people who work outside home return to establish reunion with their relations. It is a time when children who are born outside their hometowns are brought home to meet their relations. Festivals also serve as periods of reconciliation, settlement of disputes and differences. It means that people who may have been in some form of conflict during the year seek peace settlement and reconciliation during this period. Such periods are used to settle family and clan disputes.\n\n\
5. Festivals portray the religious beliefs and practices of the people. Festivals enable the chief and elders to give thank offering and remember the traditional deities and ancestral spirits as a way of spiritual renewal. People also use the occasion to offer sacrifices as a thank offering to the traditional deities and ancestral spirits for the previous year’s guidance and also ask for blessing and protection in their undertakings in the coming year through the pouring of libation. Stools and regalia are washed (white/red clay). Food and drinks are offered to the god by traditional heads and family heads serve for ritual cleansing. It is also a period of renewal of vows to the ancestors and a period to remember the dead.\n\n\
6. Presence of state officials and planning for development projects: Festivals are occasions when government officials come and explain government programmes and policies for the nation and the development projects the government has for that particular. In recent times festivals have become occasions when important developmental projects are discussed and planned. Among such\n\n\
6. Presence of state officials and planning for development projects: Festivals are occasions when government officials come and explain government programmes and policies for the nation and the development projects the government has for that particular. In recent times festivals have become occasions when important developmental projects are discussed and planned. Among such developmental projects that are normally planned are schools, provision of electricity, water, better sanitary conditions in the town and provision of K.V.K.6.P. toilets and road construction. Youth Organizations and Town Development Committees are usually inaugurated to oversee the development projects of the town or village. Government officials, who are invited to such occasions, use it to explain government policies to the people. As regards development, fund raising is carried out during this period to provide the necessary funds for the projects.\n\n\
7. Festival promotes tourism: This is a period of cultural revival as it attracts people from other countries to witness and appreciate the cultural heritage of the country. It also offers tourists the opportunity to appreciate the rich cultural diversity that exists in Ghana. The government is able to acquire foreign exchange from these tourists who come to witness the festival by visiting places of interest like Kakum National Park, the Castles.\n\n\
8. Festivals serve as a period for paying homage to the chief: During this occasion the chief or paramount chief takes the opportunity to re-assert his status as the father and the highest political leader of the community Politically, chiefs use the occasion to test the loyalty of their subjects. Divisional, sub-chiefs, village heads and the people renew their allegiance to the chief. Festivals are also periods when people who return home pay homage to their local chiefs. The celebration of festivals helps people to respect their customs and traditions and by so doing their culture is preserved for generations to come.\n\n\
9. To commemorate important historical events: Festivals provide the occasion for remembering the history of the people. This occasion enables the youth to know important historical events of their town in the past, like a period of hunger or abundance, deliverance from an epidemic or a devastating war or remembrance of some ancestral spirit or in honour of a local deity. For example, Hoggbetsotso of the Anlo-Ewe is celebrated to commemorate their escape from Notsie, etc."
},


{
id: "question5a",
question: "5a. What is self-identify? [4 marks]",
definition: "Self-identity implies how the individual sees, understands, knows, and feels about him/herself in relation to other people in the society.",
},


{
id: "question5b",
question: "5b. Examine four ways by which the individual can develop his/her capabilities [16 marks]",
options: "\
1. To make the individual aware of his weaknesses or deficiencies. The individual must know first know himself, his strengths and weaknesses and make amends. If the individual is made aware of his weaknesses and short comings e.g. pride, arrogance, laziness, drunkenness and stealing, he can be assisted to overcome or correct them so that he can become a good citizen in the society\n\n\
2. Appreciate other people views and perceptions, good role models: Through the process of role taking the individual learns to know himself by creating an image of himself and by identifying somebody as a role model. During child play one often sees children playing the role of a father, mother, doctor, teacher, soldier, etc. Through this process the individual learns to wield power and exert authority over those he/she finds as subordinates. Some of these children out of these primary leadership roles emerge to become renowned leaders in their future social life. The individual, therefore, by identifying himself or herself with inspiring and prominent people in the society tries to appreciate other people views and perceptions, take over certain characteristics or traits of these people, which invariably help to boost his/her ego and confidence in life.\n\n\
3. Self determination and self confidence: One can realize his capabilities through self determination and self confidence. The individual must have the self determination and desire and be prepared to take risk and venture into new areas. He should not run away from difficulties and problems but must be bold to face problems that may come his/her way since with determination and perseverance he/she can achieve his/her set goals. The individual must also have confidence in him/herself to handle problems and not rely on other people for solutions. The individual must always think of successes rather than failures and focus on his/her strengths rather than on her weaknesses or deficiencies to achieve his/her set goals.\n\n\
4. Education, training and retraining acquisition of skills: Education and training can help the individual to realize his capabilities. Education helps the individual to unearth and develop his/her intellectual/mental and creative abilities. Education also equips the individual with the necessary techniques to reason, create, invent and be able to solve problems. Education helps the individual to develop his capabilities in various professions like medicine, teaching, nursing, law, dressmaking, singing, carpentry etc.\n\n\
5. Enabling environment-provision of educational infrastructure and logistic: The government must create a sound environment, which will enable the individual to realise his capabilities. The government must provide facilities like schools, hospitals, water, recreation etc. for the proper development of the capabilities of the individual. The government must also institute laws to protect the rights and freedoms of children against child abuse, child labour, irresponsible behaviours of parents. The government must also pursue sound economic policies, which can enable parents to have sufficient incomes to provide the basic needs of their children.\n\n\
6. Self motivation and personal encouragement: The development of one’s capabilities can be realised through encouragement from parents, teachers, peers, etc. Parents and teachers can encourage children by praising, rewarding them etc. for performing a task. Weak children must be helped to catch up with the brighter ones through continuous exercises and suggestions. During speech days, open days, students who perform well can be given prizes to boost their morale and also serve as encouragement to other students.\n\n\
7. Guidance and Counselling: Guidance and counselling help the individual to develop one’s capabilities. Guidance and counselling can make the individual to make the right choices in life. For example, students can be guided to choose the right programme and course. Wrong choice of programmes and courses affect what the individual can do and also affect his/her later development in life. Guidance and counselling can also help the individual to develop a positive self-concept. This helps the individual to identify the good or positive qualities or potentialities that he/she has. Individuals can be helped to develop the potentiality of singing, dancing, reading, drumming, running, foot balling etc.\n\n\
8. Provision of Conducive Home Environment Support from parents, community etc.: Parents, siblings, guardians and family members have an important role in realising the capabilities of the individual. The love and encouragement that parents, siblings, family members give to the individual will enhance his image and strengthen his potential and equip him with the tools necessary for his/her future life. Parents must the right personal relations with their children by showing love, affection and understanding for them. Parents must also provide the needs of their children and ensure that their rights are protected. This will make them have confidence in themselves and their immediate relatives.\n\n\
9. Set a goal and have a vision and foresight/ should work towards self actualization: Vision involves having a sense of direction and goal setting. To achieve these goals one demands self awareness and foresight of what one can do in life. Once the individual’s capabilities are known, it becomes necessary for a step by step planning and right decisions to be made to achieve these potentials."
},


{
id: "question6a",
question: "6a. What is migration? [4 marks]",
definition: "Migration is the movement of people from one place to another e.g. region to region or country to country, to settle.",
},


{
id: "question6b",
question: "6b. Outline four negative effects of rural-urban migration in your country. [16 marks]",
options: "\
1. Pressure on accommodation: The migration of rural people to the urban centres in search of jobs creates accommodation problems. The problems arise because the accommodation available cannot cater for the large number of rural dwellers who flock to the urban centres in search of jobs and a place to stay. As a result, house owners charge exorbitant rent for rooms that they hire to people. Those who cannot afford the high rent find their way in the streets and in ramshackle structures.\n\n\
2. Family disorganization: The migration of rural dwellers to the urban centres disorganizes the family system. Husbands who leave the rural area for the urban centres to work with the hope of bringing something home for the upkeep of the family face may problems. They may find it difficult getting jobs as well as decent places to stay. As a result they may find it difficult sending remittances to family members left behind in the villages. In this situation, the woman in the rural area may find it difficult to cater for the children’s education and provide them with their daily needs. Again, the absence of the father from home may make it difficult for the mother alone to control the children and bring them up in God-fearing way. This can make the children to become wayward and difficult to control.\n\n\
3. Increase in social vices (prostitution etc: Rural urban drift has led to many youth to indulge in stealing and burglary with the result that many youths have become prisoners. The influx of many people from the rural areas to the urban centres has made many youth to become unemployed. This situation has made many youth to indulge in criminal acts to get money quickly. Many cases of armed robberies in the urban centres are committed by the youth who rob people at gun point for their money, cars, jewelry, bags, mobile phones and so on. In the urban centers many young girls, who leave the rural areas with the aim of looking for jobs end up becoming prostitutes. Many of the prostitutes have contracted AIDS/ H4.\n\n\
4. Pressure on available amenities: There is pressure on social amenities in the urban centers. As a result there is increase in government expenditure in the provision of facilities like water, electricity, sanitation, health, education etc. to the detriment of rural development due to the increased population.\n\n\
5. Environmental degradation: Rural – urban drift has brought about the problem of disposing human waste and garbage. The large numbers of people in the urban centres have led to environmental pollution resulting from smoke from factories and motor vehicles.\n\n\
6. Rural-urban migration results in the development of slums. Lack of proper accommodation for the large number of people in the urban towns has led to the creation of unauthorised structures as living places thereby creating shanty towns in the urban centres. The rise in urban population as a result of rural-urban migration creates problems like overcrowding, housing, transportation and so on. Accra, Tema and Kumasi are now facing these problems. As a result of the rapid growth of slums in the urban areas e.g. Nima, Accra Newtown there can be an outbreak of diseases due to poor sanitation. The government has to spend more money on medicine and environmental improvement.\n\n\
7. Urban unemployment: The unemployment rate is very high in the urban centres due to the influx of many people to the urban centres in search of non-existent job. Rural-Urban drift results in large proportion of the country’s labour force living in the cities. Since the number of people may be more than the jobs available in the urban centres, most of the youth become unemployed. In the urban centres there are many young girls and boys who have left the rural areas to find jobs. Many of these girls end up sleeping on the streets and in no time become pregnant and give birth to children without fathers. These innocent children grow up with their mothers on the streets and in no time become hardener criminals.\n\n\
8. Reduction in productivity in the rural areas (shortage of food): The movement of people from the rural areas to the urban centres will naturally reduce the number of people in the rural areas. The shortage of labour results in the low level of agricultural production. That is total production of farm produce like cocoa, cassava, yams, maize etc. will fall since the labour force is low.\n\n\
9. A slow-down in rural development/disintegration: There will be a general fall in the size of market for goods and services in the rural areas because of the migration of people from the rural areas to the urban centres. Producers are therefore not encouraged to produce on large scale for the rural areas. Low demand for goods and services further discourages rural investment."
},


{
id: "question7",
question: "7. Discuss any five ways of promoting integration among the ethnic groups in Ghana. [20 marks]",
options: "\
1. representation: To promote integration among the ethnic groups in Ghana, there must be involvement of all interest groups in decision making, have freedom of discussion and equal representation. The government must ensure that each tribe has a fair representation in the affairs of the country. This will help to reduce tension and political unrest caused by ethnic suppression. Besides, the government must allow free discussion of ideas on the radio, television and in the print .media. Decision making must not be the preserve of a few people but all identifiable groups must be consulted for their contribution and ideas. This will encourage national unity and stability.\n\n\
2. Equity of political appointments. The government should ensure that appointment to government positions should cut across cultural boundaries. This will help to dispel the idea that some ethnic groups are only fit to do donkey work while others are fit to enjoy good positions in government.\n\n\
3. Discouraging ethnicity/ethnocentrism in our society: Everything must be done by the government to control the belief that some tribes and their culture are the best and better than other tribes. The government must also ensure that conflict with one another or divisive tendencies like petty quarrels/classes, litigation on land, religious disputes and differences are avoided and eradicated. This will reduce\n\n\
4. Discouraging ethnicity/ethnocentrism in our society: Everything must be done by the government to control the belief that some tribes and their culture are the best and better than other tribes. The government must also ensure that conflict with one another or divisive tendencies like petty quarrels/classes, litigation on land, religious disputes and differences are avoided and eradicated. This will reduce prejudice, hatred, and dislike among the ethnic tribes and bring about national unity.\n\n\
5. The role of the Mass Media and Formal Education: The Mass Media especially the radio and the television should play patriotic songs such as, Yen ara y’asease ni. These songs should be translated into the languages of the ethnic groups and played every morning to remind all Ghanaians that we all belong to one nation. These songs should be taught in schools and sung at morning assembly. Formal education creates a healthy atmosphere in which boys and girls learn to live together irrespective of the ethnic group they come from. There is also close interaction of boys and girls of different ethnic backgrounds in the school and so they are prepared for a fruitful adult life in marriage, and as co workers in the same working environment.\n\n\
6. Encouraging full participation n social events like funerals, chietaincy, child-naming ceremonies (out- dooring), cultural fairs like NAFAC, etc. Outdooring is a cultural practice in all Ghanaian societies. In our traditional system, when a couple joins hands in marriage, the families of both the man and woman who may come from different ethnic groups unite as one family to see to the success of the marriage. They become closely inter-related. For instance, a Fante marrying an Ewe, a Ga marrying a Dagomba or an Akan marrying a Mamprusi or an Nzema. By this social cohesion is effected which finally affects integration in a nation. Music and dance project the cultural identity and heritage of Ghana. Schools can promote national integration in Ghana by inviting indigenous musicians, master drummers and dancers from different ethnic groups to assist teachers to teach indigenous music and dance in schools.\n\n\
7. Active participation of all in community based projects: The individual can express his support for his community by engaging in community initiated projects like the establishment of community library, clinic, football park, school, etc. Here the individual takes part in the self-help project because he is patriotic and therefore receives no money in return. Involvement of all interest groups in decision making, have freedom of discussion, and equal representation.\n\n\
8. Promotion of inter-tribe ethnic marriages: – Inter-marriages between different ethnic groups help foster unity between them. In Ghana, marriage is regarded as a union between two families other than between individuals. Marriage ceremonies therefore bring people of different ethnic backgrounds together and establish a strong bond of relationship between two families who may come from different ethnic group."
},


{
id: "question8",
question: "8. In what five ways can the youth of Ghana contribute to national development?",
definition: "The youth of Ghana can contribute to national development in the following ways:",
options: "\
1. Being patriotic/Readiness to respond to national call: The youth of Ghana should show interest in national issues. The youth should take part in activities that help in national development. One way of doing this is by accepting posting to the rural areas. The rural areas are the deprived areas of the country because of the lack of social amenities the youth do not want to work there. As a result they lack teachers, to teach in schools, nurses and doctors to work in clinics, health centres and hospitals. The youth should show patriotism by putting the national interest first d control personal interest by accepting posting to rural areas where their services are most needed. The youth must patronize locally produced goods e.g. food, leather works and clothes as this will go a long way to increase demand for these goods and also help to improve the quality of the goods through suggestions and comments they make to producers to improve the quality of the products.\n\n\
2. Participation in public education programmes e.g. literacy, HIV/AIDS, environmental degradation, immunization etc. The youth can organise themselves for literacy campaign through which they can educate their people on environmental cleanliness, protection of their environment against degradation through appropriate farming practices, prevention of certain illnesses like cholera, bilharzia, malaria, HIV/AIDS through proper hygienic practices and personal hygiene. The youth can also assist the local health centre in its programme of immunization against the six childhood killer diseases. The youth can also organise public film shows to highlight on its education campaigns. They can invite resource persons to talk to their people on the need to keep their environment.\n\n\
3. Maintaining and keeping the environment clean: The youth should advise people to stop the indiscriminate mining and felling of trees which have to effect of degrading the environment thus making it difficult for farming to take place. Again, the youth should let people know the dangers involved in littering the environment with plastic and metal wastes, refuse and papers. The youth should encourage people to adopt proper way of disposing liquid and solid waste (e.g. feaces). The burning of leaves, refuse and other solid wastes contributes to air pollution which is injurious to the health of people. The use of chemicals such as D. D. T to catch fish in rivers and streams pollutes the water bodies which kill the baby fish and eventually decreases the stock of new fish. It is therefore the responsibility of the youth to let people know that drinking water polluted with chemicals as well as eating fish caught from polluted rivers can cause cancer, rashes abdominal diseases etc.\n\n\
4. Payment of basic levies/ tolls/fees: Taxes are levies exacted by the government or its agents on individuals, goods and services etc. to basically raise revenue for the development of the country. Taxation or payment of taxes is not a new phenomenon. It has been in existence throughout ages and our traditional set up or system has it. The bulk of revenue accruing to government is from taxes and it is that which is used for development projects such as construction of schools, clinics, markets etc. Thus the payment of taxes helps the government to fulfill its obligation to the citizens and non payment will prevent the government from providing the needed social amenities to the citizens. It is therefore obligatory for all citizens to pay taxes to the government.\n\n\
5. Refraining from engaging in social vices: The individual must lead sound moral life in the community for the youth to follow. He must be courteous to the elderly and assist them where necessary. The individual must be loyal and law abiding and eschew self-interest. An individual who is loyal will stand up against acts like stealing, drug abuse, armed robbery etc which will disturb the stability of the community.\n\n\
6. Protection of state property: Every youth is expected to protect and preserve public property and expose the misuse of public funds. Every youth is expected to take proper care of the public or government buildings, equipment, furniture, documents etc. to ensure their safety so that they can last long. The youth is, therefore, duty bound to protect and maintain all properties that belong to the state. Poor maintenance and preservation of government properties means public funds which could be used to provide hospitals with drugs, provide water, electricity, markets, schools, clinics would have to be used to either replace the damaged government properties or ensure their regular maintenance.\n\n\
7. Taking part in decision-making: The youth should take part in decision making at the community level and national level. The youth can show his/her loyalty to the society by taking part in major levels of decision making and must also be prepared to support and defend his/her view point in the interest of his/her community. When the youth takes part in initiating community-based projects by contributing his ideas he/she can express such love by engaging in community. communal works and self-help projects such as constructing school blocks markets, places of convenience etc.\n\n\
8. Exhibiting positive attitude towards work; Many Ghanaian youth regard government’ employment as belonging to somebody else. They therefore adopt negative attitude like absenteeism, lateness, laziness, loitering, pilfering etc., which results in low productivity and a low standard of living. The youth should change their negative attitude to work by being punctual at work, using their working hours wisely and reducing waste so that labour productivity can increase to raise the standard of living of the people. The youth of Ghana should exhibit hard work, good inter-personal relations, honesty, loyalty, to increase productivity at the work place."
},


{
id: "question9a",
question: "9a. What do you understand by efficient use of human resources? [4 marks]",
definition: "Efficient use of human resources is the effective and productive way by which skilled and unskilled labour harnessed and revitalised for development.",
},


{
id: "question9b",
question: "9b. Highlight four measures that can be adopted to make human resource in Ghana more efficient.",
options: "\
1. Training and retraining of personnel to up-date-skills. Through training one acquires the practical skills for a job. The trainee is taught practically the rudiments of the trade or profession. Thus through training, one acquires knowledge, skills and attitude for a specific purpose or job. An individual needs to be trained by specialists in his chosen field to help him contribute effectively to national development. Someone who is interested in nursing can never become a professional nurse if he does not undergo training in a nursing school. Re-training is another way of improving the human resource of Ghana for national advancement. Human resource can be developed by retraining people who have been displaced from work to either obtain new jobs or be on their own. Retraining enables the worker to learn new jobs, new skills and broaden his outlook and understanding of job. For example, typists in many offices, which use manual typewriters must be re-trained to handle computers and other office machines.\n\n\
2. Putting qualified people at the various positions: The government should ensure that people who are employed have the requisite skills, knowledge and qualification necessary for the jobs they are employed to perform. Employers should eschew nepotism by ensuring that relatives and friends who do not have the requisite qualification are not employed to handle certain positions. If qualified people are employed at the various positions total output of goods and services would increase.\n\n\
3. Instilling initiative and creativity among workers: Ghanaian workers lack the ability to take initiative and also take decisions independently. For human resource to be more efficient Ghanaian workers should have the ability to create new ideas and initiative so that their performance at work place would increase their output. Again, Ghanaian workers should also have a sense of creativity so that they would be able to take decisions independently and contribute new ideas which would bring about sustainability of Ghanaian business.\n\n\
4. Creating job avenues in all sectors of the economy for practical utilization of workers’ skills. The government should establish entrepreneurial training institutions to assist job seekers to learn jobs like batik making, tie and dye, basket making, kente weaving, gari processing etc. so that after graduation they can establish their own businesses. The National Board for Small Scale Industries (NBSSI) has been pursuing an entrepreneurship development programme, which offers assistance to business creation. The Business Advisory Centres of the board at Cape Coast and Kumasi organise seminars for a number of young entrepreneurs to kindle in them the need for setting up their own business.\n\n\
5. Job oriented type of education: The government should increase the number of technical and vocational institutions in the country to enable as many people as possible to get the necessary training required. Such training will help to increase the number of skilled personnel in the country. Individuals can take to private investment for greater economic activity.\n\n\
6. Adequate remuneration and incentives: Adequate remuneration and incentives that would motivate workers should be provided to enable them adopt positive worker attitude. Workers should be given adequate salaries, wages and allowances so as to avoid the situation where workers leave their work places to do other jobs for additional income. This will in effect control pilfering, embezzlement, falsification of accounts and other malpractices. Workers should be adequately rewarded by their employers for their hard work and achievement with attractive incentive packages in the form of television sets, deep freezers, bonuses, scholarships for children of hard working workers, sponsorship for further training, promotions to high grades and good pension schemes.\n\n\
7. Providing the required inputs and equipment to enable workers to put in their best. The quality of the inputs such as land, machines and equipment with which labour has to work with is an important determinant of labour’s productivity. The greater the quantity and quality of the capital employed the greater will be the productivity of labour. The right type of tools, machinery, and equipment should be provided in all factories and in sufficient quantities to increase labour power or productivity. Also the fertility of the land, type of machines and equipment used in production factors, which affect the productivity of labour."
},


{
id: "question10a",
question: "10a. Who can be described as an entrepreneur? [4 narks)",
definition: "The entrepreneur is the forth factor of production. He combines other factors namely land, capital and labour in order to yield output. The entrepreneur bears all risk involved in production of goods and services. He owns and controls the business. Read pages 354-355 of the book for full answer to the",
},


{
id: "question10b",
question: "10b. Explain any four ways by which one can become a successful entrepreneur.",
definition: "For the entrepreneur to be successful, he must possess the following qualities:",
options: "\
1. Courage: bearing of risk, bold decision making, weathering success and failures in business\n\n\
2. Resourceful and knowledgeable: the entrepreneur should be able to organize efficiently utilize them efficiently in order to make profit in business resources\n\n\
3. Establishment of good management/worker relationship: Should be capable of fostering good interpersonal relationship to achieve the desired production objectives.\n\n\
4. Vision and foresight planning\n\n\
5. Long suffering/Persistence/Diligence\n\n\
6. Sound judgment: Ability to assess performances of workers and management as well as the entire business set up.\n\n\
7. Management Control: The entrepreneur should formulate policies which will minimize wastage of limited resources. The entrepreneur should set performance standards by measuring the day-to-day affairs of the organization to ensure that raw materials are not wasted but are judiciously used in the right amount and quantities to produce the required goods. This will ensure that workers who are not performing up to standard and creating wastage in business are eliminated to reduce cost"
}

]