import { SquareRoot, superscript, subscript, BoldText, ItalicText, Fraction, ShortFraction, LongFraction, MixedFraction, Isotopes } from "@/mathnotation"

const path = "@/assets/images/pastquestions-figures/integratedscience/integratedscienceA/integratedscience-"

export const INTEGRATEDSCIENCEA2022 = [

{
id: "question1",
question: "1. Organisms that capture energy from sun light for food production are called",
A: "autotrophs.",
B: "heterotrophs.",
C: "consumers.",
D: "secondary producers.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question2",
question: "2. Humus content of the soil can be improved through the application of",
A: "compost.",
B: "NPK.",
C: "urea.",
D: "sulphate of ammonia.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question3",
question: "3. Which of the following musical instruments is a wind instrument?",
A: "Cymbals",
B: "Guitar",
C: "Violin",
D: "Whistle",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question4",
question: "4. The following methods prevents rusting except",
A: "alloying.",
B: "cathodic protection.",
C: "greasing.",
D: "keeping metal in darkness.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question5",
question: "5. A fertilized egg found in the uterus of a farm animal is called",
A: "baby.",
B: "foetus.",
C: "ova.",
D: "zygote.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question6",
question: "6. A capacitor is an electronic corr.order.i I.at stores",
A: "chemical enerex",
B: "electrical enerm",
C: "magnetic energy.",
D: "gravitational energy.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question7",
question: "7. In most plants, food is transported in the form of",
A: "fructose.",
B: "glucose.",
C: "starch.",
D: "sucrose.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question8",
question: "8. The ball-and-ring apparatus is used in the laboratory to demonstrate",
A: "conduction of heat.",
B: "thermal expansion.",
C: "cooling effect in refrigeration.",
D: "evaporation in liquids.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question9",
question: "9. Fats and oils are examples of",
A: "alkanols.",
B: "alkanoates.",
C: "alkanoic acid.",
D: "alkenes.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question10",
question: "10. The s› stem » here pm!tm are alto› ed to run freely‘ over an area of fenced grassland is termed",
A: "barer  ca°e.",
B: "free range.",
C: "free running.",
D: "movable-fold unit.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question11",
question: "11. Which of the following statements about beta particles is/are correct? \nI.	They are negatively charged. \nII.	They are positively charged. \nIII.	They are electromagnetic rays.",
A: "I only",
B: "II only",
C: "III only",
D: "I and III only",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question12",
question: "12. The act of cutting the tail of a sheep to small size is termed",
A: "notching.",
B: "tagging.",
C: "tatooing.",
D: "docking.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question13",
question: "13. Which of the following methods of treating water would make it soft?",
A: "Chlorination",
B: "Filtration",
C: "Addition of alum",
D: "Ion exchange",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question14",
question: "14. A small powered device is rated 20 W. If the current through it is 2 A. determine the resistance of its filament.",
A: "2.0 H",
B: "4.0 D",
C: "5.0 D",
D: "10.0 f2",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question15",
question: "15. Which of the following methods is used for both seed sowing and application of fertilizer?",
A: "Drilling",
B: "Band placement",
C: "Side placement",
D: "Top dressing",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question16",
question: "16. An essential element responsible for blood clotting is",
A: "chloride.",
B: "calcium.",
C: "sulphate.",
D: "phosphate.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question17",
question: "17. An observer standing at a distance of 10 in from a tall plane mirror moves backwards 2 iii from his oi‘iuina1 position. What is the distance between the observer and his image?",
A: "2 in",
B: "10 m",
C: "12 m",
D: "24 m",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question18",
question: "18. The reason for mulching seedbeds does not include",
A: "moisture retention.",
B: "temperature regulation.",
C: "control of soil pests.",
D: "weed control.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question19",
question: "19. Which of the following statements is/are correct of a reverse biased p-n junction diode? \nI.	It has the p-type connected to the positive terminal of a cell. \nII.	It has the p-type connected to the negative terminal of a cell. \nIII.	It causes electric current to flow very well.",
A: "I only",
B: "II only",
C: "1 and III only",
D: "II and III only",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question20",
question: "20. Which of the following pairs of bones are part of the axial skeleton?",
A: "Scapula and femur",
B: "Ribs and phalanges",
C: "Skull and humerus",
D: "Skull and vertebral column",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question21",
question: "21. The number of ionizable hjdrogen at m in one molecule of an acid is its",
A: "acidity.",
B: "alkalinity.",
C: "atomicity .",
D: "basicity.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question22",
question: "22. Oxygenated blood is supplied to the body through",
A: "hepatic portal vein.",
B: "aorta.",
C: "hepatic artery.",
D: "hepatic vein.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question23",
question: "23. The main voltage in a house is 240 V. If the current delivered through 10 fluorescence tubes of equal resistance connected in series is 12 A, determine the resistance of each fluorescence tube.",
A: "0.05 O",
B: "2.00 CI",
C: "10.00 f2",
D: "20.00 II",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question24",
question: "24. What is the name for a group of ecosystem that have similar climates and organisms.",
A: "Community",
B: "Population",
C: "Biome",
D: "Biosphere",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question25",
question: "25. Magnesium is classified as a metal because it",
A: "is a solid at room temperature.",
B: "dissolves readily in strong bases.",
C: "is above hydrogen in the activity series.",
D: "ionizes by losing electrons.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question26",
question: "26. Electric power is transmitted at  \nI.	high voltage. \nII.	low voltage. \nIII.	high current.",
A: "lonly",
B: "IIonly",
C: "I and III only",
D: "II and III only",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question27",
question: "27. Which of the following statements is a reason for dehorning cattle?",
A: "For fast growth",
B: "To prevent injuries to workers",
C: "To remove odour",
D: "To prevent disease infections",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question28",
question: "28. The left ventricle is muscular and thick-walled because it contracts to pump blood to",
A: "all parts of the body.",
B: "the right lung.",
C: "the left lung.",
D: "the neck and the head.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question29",
question: "29. A body accelerates at the rate of 20 m s 2 for 25 s. Determine the change in velocity of the body.",
A: "5 m s’1",
B: "?00 m s”'",
C: "?:0 m s*’",
D: "500 m s",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question30",
question: "30. Potassium hydroxide and sodium hydroxide are both \nI.	bases. \nII.	alkalis. \nIII.	soluble in water. \nWhich of the statements above is/are correct?",
A: "I and II only",
B: "I and III only",
C: "II and III only",
D: "I, II and III",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question31",
question: "31. The post-harvest practices associated with maize production are",
A: "threshing and milling.",
B: "shelling and decortication.",
C: "dehusking and shelling.",
D: "decortication and dehusking.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question32",
question: "32. The enzyme required to convert polypeptides to amino acids is",
A: "pepsin.",
B: "inaltase.",
C: "erepsin.",
D: "diastase.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question33",
question: "33. Nñiii‘s few holds for a conductor at constant \nI.	temperature. \nlI.	length. \nIII.	diameter. \nWhich of the statements above is/are correct?",
A: "I only",
B: "II only",
C: "I and III only",
D: "1, lI and III",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question34",
question: "34. One of the effects of CFC's on the environment is that they",
A: "deplete the ozone layer.",
B: "reduce the effect of ultra violet rays.",
C: "reduce global warming.",
D: "increase the ozone layer.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question35",
question: "35. Which of the follow ing activities are pre- iaughter operations in fowls? \nI.	Starx ing for 24 hours \nII. Prox iding succulent fed \nIII. Pres isi‹›n of	ater",
A: "I and II only",
B: "I and III only",
C: "11 and III only",
D: "I, II and III",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question36",
question: "36. Which of the following organs is not part of the digestive system?",
A: "Pancreas",
B: "Spleen",
C: "Tongues",
D: "Gall bladder",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question37",
question: "37. A body displaces it own weight of the fluid in which it floals. ‘I‘his is the statement of",
A: "Boyle's law.",
B: "Charle's law.",
C: "law of flotation.",
D: "Ohm’s law.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question38",
question: "38. Which of the following electromagneti radiations have the shortest wavelength? A	X-rays	i",
B: "Violet light",
C: "Micro wax es",
D: "Radio waves",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question39",
question: "39. Which of the follow ing statements are correct of the greenhouse effect? \nI.	It is as a result of carbon(TY’) o.xide gas surrounding the earth. \nII.	It causes heat to be trapped in the atmosphere. \nIII.	lt takes place in a green house.",
A: "I and II only",
B: "I and III only",
C: "II and III only",
D: "I, II and III",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question40",
question: "40. The best way of reducing erosion in hilly areas is by",
A: "mulching the land.",
B: "erecting barrier.",
C: "practicing terracing.",
D: "applying organic fertilizer.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question41",
question: "41. Secondary sex characteristics in humans are",
A: "the only body features that distinguishes the sexes.",
B: "not essential for the reproductive process.",
C: "those structures that develop at puberty.",
D: "the only reproductive structures that are affected by hormones.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question42",
question: "42. Which of the following physical quantities is fundamental†",
A: "Molarity",
B: "Molar voliime",
C: "Mass concentration",
D: "ip	Masses	Turn over",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question43",
question: "43. Brownish colouration from the tips of mid-ribs of leaves of crops is an indication of deficiency of",
A: "copper.",
B: "nitrogen.",
C: "zinc.",
D: "phosphorus.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question44",
question: "44. The pan of the flowering plant mainly responsible for excretion is the",
A: "root.",
B: "leaf.",
C: "flower.",
D: "bud.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question45",
question: "45. Which of the following statements about direct current is/are correct? \nI.	It is produced by cells only. \nII.	It is produced by cells and some generators. \nIII.	It conventionally flows from the negative terminal to the positive terminal.",
A: "I only",
B: "II only",
C: "I and III only",
D: "II and III only",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question46",
question: "46. Liver fluke in farm animals could be controlled by",
A: "dipping.",
B: "drenching.",
C: "dusting.",
D: "hand picking",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question47",
question: "47. A man weighed 70 kg on a bathroom scale. Determine the weight of the man. [ g = 10 m s”2]",
A: "70N",
B: "l40N",
C: "350N",
D: "700N",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question48",
question: "48. The major difference between 503 and SOA*” is that SO3 is a",
A: "molecule while SO *‘ iS an atom.",
B: "radical while SO32‘ is a molecule.",
C: "molecule while SO3*” is a radical.",
D: "radical while SO32 is an atom.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question49",
question: "49. The organism that play the role in returning materials locked up in dead organisms are",
A: "primary consumers.",
B: "secondary consumers.",
C: "decomposers.",
D: "detritivores.",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question50",
question: "50. Which of the following methods car. pres ent bushfires efficiently? \nI.	Education about dangers c f bushfire \nII.	Formation of anti-bushfire squads \nIII.	Keeping bush wet at all times",
A: "1 and II only",
B: "I and III only",
C: "II and III only",
D: "I, II and III",
answer: "Z. zzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},



]