import { SquareRoot, superscript, subscript, BoldText, ItalicText, Fraction, ShortFraction, LongFraction, MixedFraction, Isotopes } from "@/mathnotation"

const path = "@/assets/images/pastquestions-figures/integratedscience/integratedscienceA/integratedscience-"

export const INTEGRATEDSCIENCEA2009 = [

{
id: "question1",
question: "1. The ultimate source of energy on the earth is",
A: "petroleum.",
B: "the sun.",
C: "the wind.",
D: "wood.",
answer: "B. the sun",
correctLetter: "B",
correctOption: 2,
},

{
id: "question2",
question: "2. The following gases are constituents of air except",
A: "carbon dioxide.",
B: "nitrogen.",
C: "oxygen.",
D: "Sulphur (lV) oxide",
answer: "D. sulphur(IV) oxide",
correctLetter: "D",
correctOption: 4,
},

{
id: "question3",
question: "3. Which of the following parts of a leaf is most photosynthetic?",
A: "Leaf epidermal tissue",
B: "Palisade mesophyll",
C: "Pericycle tissue",
D: "Vascular tissue",
answer: "B. Palisade mesophyll",
correctLetter: "B",
correctOption: 2,
},

{
id: "question4",
question: "4. The area between the like poles of two magnets where no lines of force appear is called",
A: "magnetic field.",
B: "neutral point.",
C: "north pole.",
D: "south pole.",
answer: "B. neutral point",
correctLetter: "B",
correctOption: 2,
},

{
id: "question5",
question: "5. It is better to wear white clothing in the tropics because white materials",
A: "reflect radiant heat.",
B: "absorb radiant heat.",
C: "conduct heat away more readily.",
D: "absorb sweat readily.",
answer: "A. reflect radiant heat",
correctLetter: "A",
correctOption: 1,
},

{
id: "question6",
question: "6. Objects are weightless in space because",
A: "there is negligible force of gravity.",
B: "the force of gravity exactly balances the weight of the objects.",
C: "there is no air.",
D: "the upthrust on the object is equal to the weight of the object.",
answer: "B. the force of gravity exactly balances the weight of the objects",
correctLetter: "B",
correctOption: 2,
},

{
id: "question7",
question: "7. The process of removing undigested food material out of the body is termed",
A: "egestion.",
B: "excretion.",
C: "ingestion.",
D: "secretion.",
answer: "A. egestion",
correctLetter: "A",
correctOption: 1,
},

{
id: "question8",
question: "8. The label of a fruit juice indicates that it contains 20% juice. The volume of fruit juice in a 250 ml pack of the product is",
A: "50 ml.",
B: "100 ml.",
C: "200 ml.",
D: "250 ml.",
answer: "A. 50ml",
correctLetter: "A",
correctOption: 1,
},

{
id: "question9",
question: "9. Which of the following radiations has the highest ionizing power?",
A: "Alpha rays",
B: "Beta rays",
C: "Gamma rays",
D: "X-rays",
answer: "A. Alpha rays",
correctLetter: "A",
correctOption: 1,
},

{
id: "question10",
question: "10. The malaria parasite is found in the saliva of",
A: "female anopheles.",
B: "female culex.",
C: "male aedes.",
D: "male anopheles.",
answer: "A. female anopheles",
correctLetter: "A",
correctOption: 1,
},

{
id: "question11",
question: "11. Duck rearing is often integrated with fish culture system in order to",
A: "check eutrophication.",
B: "control predation.",
C: "control growth of water weeds.",
D: "improve nutrition.",
answer: "D. improve nutrition",
correctLetter: "D",
correctOption: 4,
},

{
id: "question12",
question: "12. The amount of energy needed to push a weight of 45 N through a distance of 5 m is",
A: "9 J",
B: "40 J",
C: "50 J",
D: "225 J",
answer: "D. 225 J",
correctLetter: "D",
correctOption: 4,
},

{
id: "question13",
question: "13. Which of the following factors will quicken the rate at which microbial activity will turn milk sour?",
A: "Concentration",
B: "Particle size",
C: "Moisture content",
D: "Temperature",
answer: "D. Temperature",
correctLetter: "D",
correctOption: 4,
},

{
id: "question14",
question: "14. The ecological instrument suitable for collecting small animals living in cracks and crevices is the",
A: "pitfall trap.",
B: "pooter.",
C: "quadrat.",
D: "sweep net.",
answer: "B. pooter",
correctLetter: "B",
correctOption: 2,
},

{
id: "question15",
question: "15. Which of the following computer programme application is most suitable for the production of financial records?",
A: "Database management",
B: "Desktop publishing",
C: "Spreadsheet",
D: "Word processing",
answer: "C. Spreadsheet",
correctLetter: "C",
correctOption: 3,
},

{
id: "question16",
question: "16. The essential elements to consider in town planning are \nI.	provision of schools \nII.	human waste disposal system \nIII.	water supply",
A: "I and II only.",
B: "I and II only.",
C: "II and III only.",
D: "I, II and III.",
answer: "D. I, II and III",
correctLetter: "D",
correctOption: 4,
},

{
id: "question17",
question: "17. Which of the following solvents may be used as an antiseptic?",
A: "Caustic soda",
B: "Kerosene",
C: "Methylated spirit",
D: "Turpentine",
answer: "C. Methylated spirit",
correctLetter: "C",
correctOption: 3,
},

{
id: "question18",
question: "18. A body of mass 4 kg is dropped from a height of 10 m. Calculate the maximum energy of the body (g = 10 ms-2).",
A: "25 J",
B: "40 J",
C: "100 J",
D: "400 J",
answer: "D. 400J",
correctLetter: "D",
correctOption: 4,
},

{
id: "question19",
question: "19. The purpose of pricking out seeding is to",
A: "ensure quick germination.",
B: "protect the seedlings from direct sunlight.",
C: "prevent overcrowding in the nursery.",
D: "reduce rate of transpiration.",
answer: "C. prevent overcrowding in the nursery",
correctLetter: "C",
correctOption: 3,
},

{
id: "question20",
question: "20. In testing a leaf for the presence of starch, the leaf is first put into boiling water to",
A: "harden the leaf cells.",
B: "stop all chemical reactions in the leaf cells.",
C: "activate the enzymes in the leaf cells.",
D: "dissolve out the chlorophyll in the leaf cells.",
answer: "B. stop all chemical reactions in the lea f cells",
correctLetter: "B",
correctOption: 2,
},

{
id: "question21",
question: "21. Which of the following devices is a second class lever?",
A: "A pair of scissors",
B: "See-saw",
C: "A pair of tongs",
D: "Wheelbarrow",
answer: "D. Wheelbarrow",
correctLetter: "D",
correctOption: 4,
},

{
id: "question22",
question: "22. Chlorine is used in water treatment to",
A: "kill microbes.",
B: "kill weeds.",
C: "prevent growth of algae",
D: "coagulate fine particles in the water.",
answer: "A. kill microbes",
correctLetter: "A",
correctOption: 1,
},

{
id: "question23",
question: "23. Which of the following factors influence soil formation? \nI.	Biological \nII.	Chemical \nIII.	Physical",
A: "I and II only",
B: "1 and III only",
C: "II and III only",
D: "I, II and III",
answer: "D. I, II and III",
correctLetter: "D",
correctOption: 4,
},

{
id: "question24",
question: "24. Some waste products which are produced and stored within flowering plants are",
A: "excess water, carbon dioxide and oxygen.",
B: "excess water, tannins and carbon dioxide.",
C: "tannins, resins and lignin.",
D: "resins, lignin and oxygen.",
answer: "C. tannins, resins and lignin",
correctLetter: "C",
correctOption: 3,
},

{
id: "question25",
question: "25. A coin placed 10.0 cm below a liquid appeared to be 6.0 cm deep when observed from above Calculate the refractive index of the liquid.",
A: "0.60",
B: "1.67",
C: "4.00",
D: "16.00",
answer: "B. 1",
correctLetter: "B",
correctOption: 2,
},

{
id: "question26",
question: "26. The metal that can be obtained from bauxite if",
A: "aluminium",
B: "gold.",
C: "iron.",
D: "manganese.",
answer: "A. aluminium",
correctLetter: "A",
correctOption: 1,
},

{
id: "question27",
question: "27. The following livestock diseases are caused b; viruses except",
A: "anthrax.",
B: "foot and mouth disease",
C: "rinderpest.",
D: "swine fever.",
answer: "A. anthrax",
correctLetter: "A",
correctOption: 1,
},

{
id: "question28",
question: "28. Which of the following functions is performed by blood platelets?",
A: "Engulfing bacteria",
B: "Production of antibodies",
C: "Transportation of oxygen",
D: "Aiding blood clothing",
answer: "D. Aiding blood clothing",
correctLetter: "D",
correctOption: 4,
},

{
id: "question29",
question: "29. One characteristic that distinguishes between the same note played on a piano and an organ is the",
A: "beat.",
B: "loudness.",
C: "pitch.",
D: "quality.",
answer: "D. quality",
correctLetter: "D",
correctOption: 4,
},

{
id: "question30",
question: "30. Farm animals develop immunity to disease through",
A: "disinfection.",
B: "drenching.",
C: "quarantine",
D: "vaccination.",
answer: "D. vaccination",
correctLetter: "D",
correctOption: 4,
},

{
id: "question31",
question: "31. The blood vessel which carries digested food from the small intestine to the liver is the",
A: "hepatic artery.",
B: "hepatic portal vein.",
C: "posterior vena cava.",
D: "renal vein.",
answer: "B. hepatic portal vein",
correctLetter: "B",
correctOption: 2,
},

{
id: "question32",
question: "32. The following measuring instruments are length-measuring devices except",
A: "metre rule.",
B: "speedometer.",
C: "spherometer.",
D: "venier calliper.",
answer: "B. speedometer",
correctLetter: "B",
correctOption: 2,
},

{
id: "question33",
question: "33. Which of the following metals is obtained from haematite?",
A: "Aluminium",
B: "Copper",
C: "Iron",
D: "Zinc",
answer: "C. Iron",
correctLetter: "C",
correctOption: 3,
},

{
id: "question34",
question: "34. A rectangular block weighs 4000 N. Its mass is",
A: "4 kg",
B: "40 kg",
C: "400 kg",
D: "4000 kg",
answer: "C. 400 kg",
correctLetter: "C",
correctOption: 3,
},

{
id: "question35",
question: "35. Which of the following diseases has the greatest adverse effects on productivity in Ghana?",
A: "Malaria",
B: "Poliomyelitis",
C: "Smallpox",
D: "Yellow fever",
answer: "A. Malaria",
correctLetter: "A",
correctOption: 1,
},

{
id: "question36",
question: "36. The reaction: KAlSi3O8  + H2O → HAlSi3O8  + KOH, which occurs during the chemical weathering of rocks is referred to as",
A: "carbonation.",
B: "hydration.",
C: "hydrolysis.",
D: "oxidation.",
answer: "C. Hydrolysis",
correctLetter: "C",
correctOption: 3,
},

{
id: "question37",
question: "37. Which of the following human characteristics is inherited?",
A: "Baldness",
B: "Language",
C: "Scar",
D: "Skills",
answer: "A. Baldness",
correctLetter: "A",
correctOption: 1,
},

{
id: "question38",
question: "38. The speed of a body increased from 20.0 ms-1   to 35.0 ms-1   in 5.0 seconds. Calculate the average acceleration of the body.",
A: "3.0 ms-2",
B: "11.0 ms-2",
C: "15.0 ms-2",
D: "75.0 ms-2",
answer: "A. 3",
correctLetter: "A",
correctOption: 1,
},

{
id: "question39",
question: "39. Insoluble salts are prepared by the A. crystallization method.",
B: "dissolution method.",
C: "precipitation method.",
D: "titration method.",
answer: "C. precipitation method",
correctLetter: "C",
correctOption: 3,
},

{
id: "question40",
question: "40. Which of the following cell organelles is involved in the secretion and packaging of complex carbohydrates and proteins?",
A: "Endoplasmic recticulum",
B: "Golgi body",
C: "Lysosome",
D: "Ribosome",
answer: "B. Golgi body",
correctLetter: "B",
correctOption: 2,
},

{
id: "question41",
question: "41. Which of the following forces enables a mosquito larva to stick to the surface of water?",
A: "Adhesion",
B: "Capillarity",
C: "Gravity",
D: "Surface tension",
answer: "D. Surface tension",
correctLetter: "D",
correctOption: 4,
},

{
id: "question42",
question: "42. What mass of NaOH is contained in 0.2 M solution of NaOH? [Na = 23, O = 16, H = 1]",
A: "0.2 g",
B: "0.8 g",
C: "2.0 g",
D: "8.0 g",
answer: "D. 8",
correctLetter: "D",
correctOption: 4,
},

{
id: "question44",
question: "44. Which of the following statements about acids is incorrect? Acids",
A: "contain ionisable hydrogen.",
B: "turn blue litmus paper red.",
C: "are insoluble in water.",
D: "are neutralized by bases.",
answer: "C. are insoluble in water",
correctLetter: "C",
correctOption: 3,
},

{
id: "question45",
question: "45. Which of the following ranks in classification shows the least resemblance among organisms?",
A: "Class",
B: "Genus",
C: "Order",
D: "Species",
answer: "A. Class",
correctLetter: "A",
correctOption: 1,
},

{
id: "question46",
question: "46. A simple electrical circuit is connected to a voltage supply of 1.5 V. If a current of 0.5 A flows through the circuit, calculate the total resistance of the circuit.",
A: "0.75 Q",
B: "1.00 Q",
C: "2.00 Q",
D: "3.00 Q",
answer: "D. 3",
correctLetter: "D",
correctOption: 4,
},

{
id: "question43",
question: "43. Smut disease of maize is caused by",
A: "bacterium.",
B: "fungus.",
C: "protozoan.",
D: "virus.",
answer: "B. fungus",
correctLetter: "B",
correctOption: 2,
},

{
id: "question47",
question: "47. The following stages are involved in the process of childbirth except",
A: "stretching of the cervix of uterus.",
B: "continuous relaxation of the abdominal walls.",
C: "contractions of the walls of the uterus.",
D: "breaking of the embryonic membranes.",
answer: "B. continuous relaxation of the abdominal walls",
correctLetter: "B",
correctOption: 2,
},

{
id: "question48",
question: "48. Which of the following computer parts is not a storage device?",
A: "Floppy disk",
B: "Hard disk",
C: "Pen drive",
D: "Random Access Memory",
answer: "D. Random Access Memory",
correctLetter: "D",
correctOption: 4,
},

{
id: "question49",
question: "49. Sound waves are",
A: "longitudinal mechanical waves.",
B: "transverse mechanical waves.",
C: "longitudinal electromagnetic waves.",
D: "transverse electromagnetic waves.",
answer: "A. longitudinal mechanical waves",
correctLetter: "A",
correctOption: 1,
},

{
id: "question50",
question: "50. A physical method of suppressing growth of weeds is by",
A: "cover cropping .",
B: "hoeing.",
C: "mulching.",
D: "use of herbicides",
answer: "B. hoeing",
correctLetter: "B",
correctOption: 2,
},

{
id: "question51",
question: "51. Which of the following forms of energy cannot be transformed directly into heat energy?",
A: "Chemical energy",
B: "Electrical energy",
C: "Kinetic energy",
D: "Potential energy",
answer: "D. Potential energy",
correctLetter: "D",
correctOption: 4,
},

{
id: "question52",
question: "52. Essential substances contained in glomerular filtrate",
A: "accumulate in the ureter.",
B: "are reabsorbed into the blood.",
C: "sink into the loop of Henle.",
D: "are filtered out on the Bowman’s capsule.",
answer: "B. are reabsorbed into the blood",
correctLetter: "B",
correctOption: 2,
},

{
id: "question53",
question: "53. The south-east and north-east trade -winds are the direct result of",
A: "the rotation of the earth.",
B: "differential heating of the earth’s surface.",
C: "orbital motion of the earth.",
D: "gravitational attraction of the moon.",
answer: "B. differential heating of the earth ' s surface",
correctLetter: "B",
correctOption: 2,
},

{
id: "question54",
question: "54. A man survived stroke and noticed that he had become deaf. Which of the following explains his condition?",
A: "Part of the brain is damaged",
B: "Thyroid gland has ceased functioning",
C: "Eardrum is damaged",
D: "Spinal cord is damaged",
answer: "A. Part of the brain is damaged",
correctLetter: "A",
correctOption: 1,
},

{
id: "question55",
question: "55. A steel ball of mass 20.0 kg cools from 120°C to 80°C. If the specific heat capacity of steel is 435 J/kg, calculate the quantity of heat given out.",
A: "3.48 ×105   J",
B: "4.32 ×105   J",
C: "4.83 ×105   J",
D: "8.43 ×105   J",
answer: "A. 3",
correctLetter: "A",
correctOption: 1,
},

{
id: "question56",
question: "56. A seed develops from the",
A: "endosperm.",
B: "ovary wall.",
C: "ovule.",
D: "sepal.",
answer: "C. ovule",
correctLetter: "C",
correctOption: 3,
},

{
id: "question57",
question: "57. A voltage transformer in which the number of turns in the primary coil is greater than that of the secondary is known as a/an",
A: "analogue transformer.",
B: "distributing transformer.",
C: "step-down transformer.",
D: "step-up transformer.",
answer: "C. step-down transformer",
correctLetter: "C",
correctOption: 3,
},

{
id: "question58",
question: "58. The use of variegated leaf in photosynthesis experiments is to show that",
A: "light is essential in photosynthesis.",
B: "chlorophyll is essential in photosynthesis.",
C: "starch is formed during photosynthesis.",
D: "carbon dioxide is an ingredient of photosynthesis.",
answer: "B. chlorophyll is essential in photosynthesis",
correctLetter: "B",
correctOption: 2,
},

{
id: "question59",
question: "59. Rice grown on slopes of a hill is called",
A: "long-grain rice.",
B: "paddy rice.",
C: "swamp rice.",
D: "upland rice.",
answer: "D. upland rice",
correctLetter: "D",
correctOption: 4,
},

{
id: "question60",
question: "60. The advantages of the use of computers include \nI.	accuracy of details \nII.	cost saving \nIII.	increased speed of work \nIV.	security of documents",
A: "I, II and III only.",
B: "I. Ill and IV only.",
C: "II, III and IV only.",
D: "I, II, III and IV.",
answer: "D. I, II , III and IV",
correctLetter: "D",
correctOption: 4,
},



]