export const FOODANDNUTRITIONA2016 = [

{
id: "question1",
question:  "1. Which of the following is a cocktail dish?",
A: "Roast chicken",
B: "Boiled yam",
C: "Jollof rice",
D: "Chicken kebabs",
answer: "D. Chicken kebabs",
correctLetter: "D",
correctOption: 4,
},

{
id: "question2",
question:  "2. Table setting is either",
A: "Informal or simple",
B: "Formal or informal",
C: "Buffet or cocktail",
D: "Simple or complex",
answer: "B. Formal or informal",
correctLetter: "B",
correctOption: 2,
},

{
id: "question3",
question:  "3. *******************************",
A: "Compromise service",
B: "Buffet service",
C: "Plate service",
D: "English service",
answer: "D. English service",
correctLetter: "D",
correctOption: 4,
},

{
id: "question4",
question:  "4. Which of the following methods is used in the preparation of tea?",
A: "Extraction",
B: "Filtration",
C: "Infusion",
D: "Percolation",
answer: "C. Infusion",
correctLetter: "C",
correctOption: 3,
},

{
id: "question5",
question:  "5. The principle underlying tea preparation is the development of flavor and extraction of",
A: "Caffeine",
B: "Tannin",
C: "Theobromine",
D: "Pectin",
answer: "A. Caffeine",
correctLetter: "A",
correctOption: 1,
},

{
id: "question6",
question:  "6. Convenience foods refer to foods which are",
A: "Dried in the sun",
B: "Just cooked and served",
C: "Packed without processing",
D: "Pre-prepared for use",
answer: "D. Pre-prepared for use",
correctLetter: "D",
correctOption: 4,
},

{
id: "question7",
question:  "7. The dishes that are eaten by the indigenous people are called",
A: "Traditional dishes",
B: "Foreign dishes",
C: "Community dishes",
D: "Family dishes",
answer: "A. Traditional dishes",
correctLetter: "A",
correctOption: 1,
},

{
id: "question8",
question:  "8. Which of the following food service is best for wedding ceremony?",
A: "Tray service",
B: "Plate service",
C: "Buffet service",
D: "English service",
answer: "C. Buffet service",
correctLetter: "C",
correctOption: 3,
},

{
id: "question9",
question:  "9. Which of the following beverages is suitable for a growing child?",
A: "Coffee",
B: "Cocoa",
C: "Tea",
D: "Lemonade",
answer: "D. Lemonade",
correctLetter: "D",
correctOption: 4,
},

{
id: "question10",
question:  "10. One of the advantages of convenience foods is that they",
A: "Are expensive and scarce",
B: "Are difficult to store",
C: "May lack some nutrients",
D: "Save time and energy",
answer: "D. Save time and energy",
correctLetter: "D",
correctOption: 4,
},

{
id: "question11",
question:  "11. A fresh fish should have",
A: "Firm flesh",
B: "Brown gills",
C: "Dull eyes",
D: "Few scales",
answer: "A. Firm flesh",
correctLetter: "A",
correctOption: 1,
},

{
id: "question12",
question:  "12. The application of moist heat on starchy food results in",
A: "Coagulation",
B: "Dextrinization",
C: "Caramelization",
D: "Gelatinization",
answer: "D. Gelatinization",
correctLetter: "D",
correctOption: 4,
},

{
id: "question13",
question:  "13. Which of the following is not a reason for re-heating left-over food? To",
A: "Create variety in meals",
B: "Make them appetizing",
C: "Prepare new dish",
D: "Save time and money",
answer: "A. Create variety in meals",
correctLetter: "A",
correctOption: 1,
},

{
id: "question14",
question:  "14. To prevent food contamination, left-over foods must be stored when",
A: "Very hot",
B: "Very cold",
C: "Warm",
D: "Cool",
answer: "B. Very cold",
correctLetter: "B",
correctOption: 2,
},

{
id: "question15",
question:  "15. In a catering establishment, good work ethics helps to",
A: "Increase productivity",
B: "Increase output",
C: "Reduce patronage",
D: "Reduce tax",
answer: "A. Increase productivity",
correctLetter: "A",
correctOption: 1,
},

{
id: "question16",
question:  "16. A food is misbranded if",
A: "It is adulterated",
B: "Any ingredient is missing",
C: "It is wrongly labelled",
D: "It is unhygienic",
answer: "C. It is wrongly labelled",
correctLetter: "C",
correctOption: 3,
},

{
id: "question17",
question:  "17. Customer education involves",
A: "Purchasing items online",
B: "Returning bought articles",
C: "Enlightening the public about their rights",
D: "Keeping up with the neighbours",
answer: "C. Enlightening the public about their rights",
correctLetter: "C",
correctOption: 3,
},

{
id: "question18",
question:  "18. When a dish of fish in butter is eaten digestion starts from the",
A: "Mouth",
B: "Oesophagus",
C: "Stomach",
D: "Small intestines",
answer: "A. Mouth",
correctLetter: "A",
correctOption: 1,
},

{
id: "question19",
question:  "19. When developing a new recipe, the most important thing to improve on is",
A: "Texture",
B: "Taste",
C: "Colour",
D: "Appearance",
answer: "B. Taste",
correctLetter: "B",
correctOption: 2,
},

{
id: "question20",
question:  "20. In experimental cookery, information for local dishes can be obtained from",
A: "Hotels and canteens",
B: "Electronics and print media",
C: "People from different ethnic groups",
D: "People from different continents",
answer: "C. People from different ethnic groups",
correctLetter: "C",
correctOption: 3,
},

{
id: "question21",
question:  "21. A programme designed to persuade consumers to buy products is known as",
A: "Investment",
B: "Agreement",
C: "Repayment",
D: "Advertisement",
answer: "D. Advertisement",
correctLetter: "D",
correctOption: 4,
},

{
id: "question22",
question:  "22. In budgeting, it is important to make allowance for",
A: "Emergencies",
B: "Open current accounts",
C: "Make monthly contributions",
D: "Join cooperatives",
answer: "A. Emergencies",
correctLetter: "A",
correctOption: 1,
},

{
id: "question23",
question:  "23. The primary needs that a family should save for are",
A: "Food, clothing and shelter",
B: "Entertainment, education and clothing",
C: "Shelter, furniture and food",
D: "Education, entertainment and food",
answer: "A. Food, clothing and shelter",
correctLetter: "A",
correctOption: 1,
},

{
id: "question24",
question:  "24. The main reason for packing different types of biscuit separately is to prevent",
A: "Breakage",
B: "Discolouration",
C: "Chemical reactions",
D: "Transfer of flavours",
answer: "D. Transfer of flavours",
correctLetter: "D",
correctOption: 4,
},

{
id: "question25",
question:  "25. For an enterprise to progress the manager should",
A: "Pay workers when he likes",
B: "Appreciate workers’ efforts",
C: "Report to work late everyday",
D: "Be the sole decision maker",
answer: "B. Appreciate workers’ efforts",
correctLetter: "B",
correctOption: 2,
},

{
id: "question26",
question:  "26. The most effective method of collecting information on local recipe is through",
A: "Interview",
B: "Observation",
C: "Participation",
D: "Questionnaire",
answer: "A. Interview",
correctLetter: "A",
correctOption: 1,
},

{
id: "question27",
question:  "27. People who purchase items in large quantities directly from the industry are called",
A: "Manufacturers",
B: "Wholesalers",
C: "Consumers",
D: "Retailers",
answer: "B. Wholesalers",
correctLetter: "B",
correctOption: 2,
},

{
id: "question28",
question:  "28. Which of the following is the simplest type of carbohydrate?",
A: "Glucose",
B: "Lactose",
C: "Maltose",
D: "Galactose",
answer: "A. Glucose",
correctLetter: "A",
correctOption: 1,
},

{
id: "question29",
question:  "29. Which of the following amino acids are essential for infants?",
A: "Lysine and histidine",
B: "Arginine and leucine",
C: "Methionine and histidine",
D: "Histidine and arginine",
answer: "A. Lysine and histidine",
correctLetter: "A",
correctOption: 1,
},

{
id: "question30",
question:  "30. A meal containing all the necessary nutrients in their correct proportion is said to be",
A: "Tasty",
B: "Adequate",
C: "Nutritious",
D: "Nourishing",
answer: "C. Nutritious",
correctLetter: "C",
correctOption: 3,
},

{
id: "question31",
question:  "31. The effect of unripe fruit on the digestive system is that it",
A: "Preserves the system",
B: "Irritates the system",
C: "Flushes the system",
D: "Lubricates the system",
answer: "B. Irritates the system",
correctLetter: "B",
correctOption: 2,
},

{
id: "question32",
question:  "32. Before foods can be absorbed in the body, they must be",
A: "Partially broken down",
B: "Broken down and insoluble",
C: "In their simplest soluble form",
D: "In a semi solid form",
answer: "C. In their simplest soluble form",
correctLetter: "C",
correctOption: 3,
},

{
id: "question33",
question:  "33. Which of the following determines the health status of family members?",
A: "Eating habit",
B: "Spending habit",
C: "Level of wealth",
D: "Level of education",
answer: "A. Eating habit",
correctLetter: "A",
correctOption: 1,
},

{
id: "question34",
question:  "34. Which of the following is the most concentrated energy giving food?",
A: "Yam",
B: "Margarine",
C: "Meat",
D: "Sugar",
answer: "D. Sugar",
correctLetter: "D",
correctOption: 4,
},

{
id: "question35",
question:  "35. Pancake is cooked by",
A: "Braising",
B: "Roasting",
C: "Broiling",
D: "Frying",
answer: "D. Frying",
correctLetter: "D",
correctOption: 4,
},

{
id: "question36",
question:  "36. Where a drinking glass should be placed on a “cover”?",
A: "The right side of the plate",
B: "The left side of the serviette",
C: "The right and just above the tip of the knife",
D: "The left and just above the tip of the fork",
answer: "C. The right and just above the tip of the knife",
correctLetter: "C",
correctOption: 3,
},

{
id: "question37",
question:  "37. A good quality saucepan should be",
A: "Light coloured",
B: "Thick and heavy",
C: "Thin and light",
D: "Dark coloured",
answer: "B. Thick and heavy",
correctLetter: "B",
correctOption: 2,
},

{
id: "question38",
question:  "38. Which of the following chemical reactions occur when heat is applied to protein?",
A: "Coagulation",
B: "Dextrinization",
C: "Gelatinization",
D: "Caramelization",
answer: "A. Coagulation",
correctLetter: "A",
correctOption: 1,
},

{
id: "question39",
question:  "39. To bake “blind” means",
A: "Covering food before baking",
B: "Baking on a foil sheet",
C: "Baking pastry cases without filling",
D: "Baking in a pot with lid",
answer: "C. Baking pastry cases without filling",
correctLetter: "C",
correctOption: 3,
},

{
id: "question40",
question:  "40. Which of the following is a distilled beverage?",
A: "Cocoa",
B: "Gin",
C: "Tea",
D: "Beer",
answer: "B. Gin",
correctLetter: "B",
correctOption: 2,
},

{
id: "question41",
question:  "41. The addition of palm oil, carrot and fish liver oil in the diet of the elderly is to",
A: "Loose mineral salts",
B: "Repair broken tissue",
C: "Improve vision",
D: "Aid haemoglobin",
answer: "D. Aid haemoglobin",
correctLetter: "D",
correctOption: 4,
},

{
id: "question42",
question:  "42. Shredded fat is used in the preparation of",
A: "Puff pastry",
B: "Suet pastry",
C: "Short crust pastry",
D: "Choux pastry",
answer: "B. Suet pastry",
correctLetter: "B",
correctOption: 2,
},

{
id: "question43",
question:  "43. A kitchen sink is usually sited near the window in order to",
A: "Prevent bending while in use",
B: "Make for easy reach of the window",
C: "Make hand washing easy",
D: "Make plumbing and lighting easy",
answer: "A. Prevent bending while in use",
correctLetter: "A",
correctOption: 1,
},

{
id: "question44",
question:  "44. A comfortable working height in the kitchen is from",
A: "Hip down",
B: "Waist down",
C: "Chest down",
D: "Knee down",
answer: "C. Chest down",
correctLetter: "C",
correctOption: 3,
},

{
id: "question45",
question:  "45. The waste basket in the kitchen should be emptied",
A: "Daily",
B: "Weekly",
C: "Fortnightly",
D: "Monthly",
answer: "A. Daily",
correctLetter: "A",
correctOption: 1,
},

{
id: "question46",
question:  "46. When fruit juice containing acid is added to milk, the milk",
A: "Coagulates",
B: "Separates",
C: "Sours",
D: "Curdles",
answer: "D. Curdles",
correctLetter: "D",
correctOption: 4,
},

{
id: "question47",
question:  "47. Which of the following is a ready to eat convenience food?",
A: "Pasta",
B: "Corned beef",
C: "Yam flour",
D: "Semolina",
answer: "B. Corned beef",
correctLetter: "B",
correctOption: 2,
},

{
id: "question48",
question:  "48. In moist heat, collagen is changed to",
A: "Gelatine",
B: "Gluten",
C: "Albumen",
D: "Glycerol",
answer: "A. Gelatine",
correctLetter: "A",
correctOption: 1,
},

{
id: "question49",
question:  "49. In jam making, fruit is simmered in order to prevent",
A: "Sticking and burning",
B: "Preserve the colour and flavour",
C: "Reach boiling point early",
D: "Soften it and release pectin",
answer: "D. Soften it and release pectin",
correctLetter: "D",
correctOption: 4,
},

{
id: "question50",
question:  "50. The main sequence of work in food preparation is",
A: "Cooking, preparation, serving, cleaning up",
B: "Preparation, cooking, serving, cleaning up",
C: "Serving, preparation, cleaning up, cooking",
D: "cleaning up, cooking, preparation, serving",
answer: "B. Preparation, cooking, serving, cleaning up",
correctLetter: "B",
correctOption: 2,
},

{
id: "question51",
question:  "51. What proportion of egg to milk is required for a baked egg custard?",
A: "2 large eggs to 500 ml of milk",
B: "4 large eggs to 250 ml of milk",
C: "6 large eggs to 200 ml of milk",
D: "8 large eggs to 150 ml of milk",
answer: "A. 2 large eggs to 500 ml of milk",
correctLetter: "A",
correctOption: 1,
},

{
id: "question52",
question:  "52. Which of the following cooking methods uses all modes of heat transfer?",
A: "Steaming",
B: "Grilling",
C: "Baking",
D: "Boiling",
answer: "C. Baking",
correctLetter: "C",
correctOption: 3,
},

{
id: "question53",
question:  "53. The best sugar to use for a light cake is",
A: "Brown sugar",
B: "Castor sugar",
C: "Cube sugar",
D: "Cane sugar",
answer: "B. Castor sugar",
correctLetter: "B",
correctOption: 2,
},

{
id: "question54",
question:  "54. Information on new recipes should be passed onto the",
A: "Aged",
B: "Toddlers",
C: "Housemakers",
D: "Male adults",
answer: "C. Housemakers",
correctLetter: "C",
correctOption: 3,
},

{
id: "question55",
question:  "55. The separation of solid in baked egg custard is called",
A: "Setting",
B: "Curdling",
C: "Coagulation",
D: "Shrinkage",
answer: "B. Curdling",
correctLetter: "B",
correctOption: 2,
},

{
id: "question56",
question:  "56. Which of the following tools is appropriate for lifting cooked foods that are to be served?",
A: "Spoon",
B: "Tongs",
C: "Palette knife",
D: "Kitchen fork",
answer: "B. Tongs",
correctLetter: "B",
correctOption: 2,
},

{
id: "question57",
question:  "57. The most appropriate method for cooking fruits is",
A: "Steaming",
B: "Boiling",
C: "Stewing",
D: "Poaching",
answer: "D. Poaching",
correctLetter: "D",
correctOption: 4,
},

{
id: "question58",
question:  "58. The use of herbs and spices in cooking improves",
A: "Absorption of food",
B: "Palatability of food",
C: "Digestibility of food",
D: "Quality of food",
answer: "B. Palatability of food",
correctLetter: "B",
correctOption: 2,
},

{
id: "question59",
question:  "59. Which of the following types of knifes is used for decorating a cake?",
A: "Palette knife",
B: "Paring knife",
C: "Kitchen knife",
D: "Bread knife",
answer: "A. Palette knife",
correctLetter: "A",
correctOption: 1,
},

{
id: "question60",
question:  "60. Cooker tops are best cleaned when",
A: "Cold",
B: "Cool",
C: "Warm",
D: "Hot",
answer: "A. Cold",
correctLetter: "A",
correctOption: 1,
},


]