export const JEWELLERYA2020 = [

{
id: "question1",
question:  "1. A technique of thinning leather down to make it foldable is",
A: "burnishing.",
B: "skiving.",
C: "sticking.",
D: "thonging.",
answer: "B. skiving.",
correctLetter: "B",
correctOption: 2,
},

{
id: "question2",
question:  "2. In appreciation, the culture and socio economic significance of an artifact is considered under",
A: "criticism.",
B: "judgement.",
C: "inventory.",
D: "interpretation.",
answer: "D. interpretation.",
correctLetter: "D",
correctOption: 4,
},

{
id: "question3",
question:  "3. Identify the most direct risk in jewellery business.",
A: "Armed robbery",
B: "High interest rate on loans",
C: "Low demand for products",
D: "Fake materials",
answer: "A. Armed robbery",
correctLetter: "A",
correctOption: 1,
},

{
id: "question4",
question:  "4. When silver jewellery is exposed to damp environment over a long period, it",
A: "develops spirogyra.",
B: "develops verdigris.",
C: "becomes mouldy.",
D: "becomes rusty.",
answer: "B. develops verdigris.",
correctLetter: "B",
correctOption: 2,
},

{
id: "question5",
question:  "5. Select the major factor for enamelling jewellery.",
A: "For identification",
B: "Preservation of the surface",
C: "To reduce heat formation",
D: "To reduce shrinkage",
answer: "B. Preservation of the surface",
correctLetter: "B",
correctOption: 2,
},

{
id: "question6",
question:  "6. Mourners hardly wear gold ornaments at funerals because they",
A: "suggest joy and affluence.",
B: "do not show sorrow.",
C: "deepen their grief.",
D: "are attractixe to wear.",
answer: "A. suggest joy and affluence.",
correctLetter: "A",
correctOption: 1,
},

{
id: "question7",
question:  "7. Identify the pair which are jewellery ornaments.",
A: "Medallions and tiara",
B: "Ring and pail Ions",
C: "Pendant and pennant",
D: "Bangle and bust",
answer: "A. Medallions and tiara",
correctLetter: "A",
correctOption: 1,
},

{
id: "question8",
question:  "8. The size of the middle finger of a bridegroom is best determined by",
A: "micrometre.",
B: "graduated mandrels.",
C: "tape measure.",
D: "callipers.",
answer: "B. graduated mandrels.",
correctLetter: "B",
correctOption: 2,
},

{
id: "question9",
question:  "9. The layer of oxide formed on the surface of metal is best removed by",
A: "sawing.",
B: "etching.",
C: "annealing.",
D: "pickling.",
answer: "D. pickling.",
correctLetter: "D",
correctOption: 4,
},

{
id: "question10",
question:  "10. An alloy used for bonding two or more metals is referred to as",
A: "pumice.",
B: "solder.",
C: "tripoli.",
D: "bronze.",
answer: "B. solder.",
correctLetter: "B",
correctOption: 2,
},

{
id: "question11",
question:  "11. A metal becomes molten when",
A: "heated below melting point.",
B: "it is cold.",
C: "heating stops.",
D: "heated above melting point.",
answer: "D. heated above melting point.",
correctLetter: "D",
correctOption: 4,
},

{
id: "question12",
question:  "12. Select the technique used to decorate metal and wood jewellery.",
A: "Etching",
B: "Casting",
C: "Chasing",
D: "Engraving",
answer: "D. Engraving",
correctLetter: "D",
correctOption: 4,
},

{
id: "question13",
question:  "13. A ball-pein hammer is protected from rusting by",
A: "dusting and storing.",
B: "tying and drying.",
C: "wanning and polishing.",
D: "greasing and drying.",
answer: "D. greasing and drying.",
correctLetter: "D",
correctOption: 4,
},

{
id: "question14",
question:  "14. Select the best device which aids hard soldering.",
A: "Straight hatchet",
B: "Soldering iron",
C: "Blowtorch",
D: "Electric kiln",
answer: "C. Blowtorch",
correctLetter: "C",
correctOption: 3,
},

{
id: "question15",
question:  "15. Which of the following tools is used for cutting a metal plate in jewellery?",
A: "Bodkin",
B: "Pliers",
C: "Scriber",
D: "Shears",
answer: "D. Shears",
correctLetter: "D",
correctOption: 4,
},

{
id: "question16",
question:  "16. Choose the set of materials obtained from mineral, animal and plant sources.",
A: "Amber, cane and ruby",
B: "Sapphire, quartz and lead",
C: "Platinum, wood and ebony",
D: "Pebbles, bone and calabash",
answer: "D. Pebbles, bone and calabash",
correctLetter: "D",
correctOption: 4,
},

{
id: "question17",
question:  "17. The natural material from which metals are obtained is",
A: "gangue.",
B: "cellulose.",
C: "ore.",
D: "silica.",
answer: "C. ore.",
correctLetter: "C",
correctOption: 3,
},

{
id: "question18",
question:  "18. The person in charge of a jewellery enterprise is the",
A: "curator.",
B: "founder.",
C: "operator.",
D: "manager.",
answer: "D. manager.",
correctLetter: "D",
correctOption: 4,
},

{
id: "question19",
question:  "19. Identify the fuel burning tool used for applying flame and heat when annealing.",
A: "Blowtorch",
B: "Coal pot",
C: "Candle",
D: "Stove",
answer: "A. Blowtorch",
correctLetter: "A",
correctOption: 1,
},

{
id: "question20",
question:  "20. Identify the tool in the diagram.",
A: "File card",
B: "Charcoal block",
C: "Lead cake",
D: "Emery board",
answer: "C. Lead cake",
correctLetter: "C",
correctOption: 3,
},

{
id: "question21",
question:  "21. What is the function of the device in the diagram?",
A: "For cleaning files",
B: "As a support for embossed work",
C: "For cleaning pickled blank",
D: "For grinding enamelled piece",
answer: "B. As a support for embossed work",
correctLetter: "B",
correctOption: 2,
},

{
id: "question22",
question:  "22. The jeweller makes a mass production of an epaulette based on",
A: "template.",
B: "sketch model.",
C: "miniature.",
D: "working drawing.",
answer: "D. working drawing.",
correctLetter: "D",
correctOption: 4,
},

{
id: "question23",
question:  "23. The process of adding lustre to a metal is referred to as",
A: "muting.",
B: "texturing.",
C: "polishing.",
D: "piercing.",
answer: "C. polishing.",
correctLetter: "C",
correctOption: 3,
},

{
id: "question24",
question:  "24. Brass is sprayed with lacquer to make it",
A: "become conductible.",
B: "increase its malleability.",
C: "resist tarnishing.",
D: "raise its standard.",
answer: "C. resist tarnishing.",
correctLetter: "C",
correctOption: 3,
},

{
id: "question25",
question:  "25. Select the appropriate technique for defining surface details of a cast piece.",
A: "Chasing",
B: "Embossing",
C: "Stamping",
D: "Engraving",
answer: "A. Chasing",
correctLetter: "A",
correctOption: 1,
},

{
id: "question26",
question:  "26. Burnishing a metal surface enhances its",
A: "texture.",
B: "lustre.",
C: "sharpness.",
D: "malleability.",
answer: "B. lustre.",
correctLetter: "B",
correctOption: 2,
},

{
id: "question27",
question:  "27. The technique of using punch and hammer to create relief on metal surface is known as",
A: "repousse,",
B: "tooling,",
C: "enamelling,",
D: "etching.",
answer: "A. repousse,",
correctLetter: "A",
correctOption: 1,
},

{
id: "question28",
question:  "28. Acid solutions used for etching are referred to as",
A: "adhesives.",
B: "flux.",
C: "mordants.",
D: "solvents.",
answer: "C. mordants.",
correctLetter: "C",
correctOption: 3,
},

{
id: "question29",
question:  "29. Which of these materials is used for the high polishing of precious metal?",
A: "Emery paste",
B: "Rouge",
C: "Scratch brush",
D: "Tripoli",
answer: "B. Rouge",
correctLetter: "B",
correctOption: 2,
},

{
id: "question30",
question:  "30. What will cause a wedding ring to become disjointed after soldering?",
A: "When noble metals are used for fabrication",
B: "If there is a wide gap between the two ends",
C: "When borax flux is applied to the joint",
D: "When space between the edges is narrow",
answer: "B. If there is a wide gap between the two ends",
correctLetter: "B",
correctOption: 2,
},

{
id: "question31",
question:  "31. The best technique for producing several but the same pendant is",
A: "drawing.",
B: "casting.",
C: "engraving.",
D: "piercing.",
answer: "B. casting.",
correctLetter: "B",
correctOption: 2,
},

{
id: "question32",
question:  "32. Which of the following materials aids the fusion of silver?",
A: "Rosin",
B: "Tallow¬ed",
C: "Borax",
D: "Zinc chloride",
answer: "C. Borax",
correctLetter: "C",
correctOption: 3,
},

{
id: "question33",
question:  "33. Which of the following techniques is appropriate when filing",
A: "Holding work firmly in the hand",
B: "Using any size of tool for the work",
C: "Applying pressure on the forward stroke only",
D: "Fixing work firmly in a pitch",
answer: "D. Fixing work firmly in a pitch",
correctLetter: "D",
correctOption: 4,
},

{
id: "question34",
question:  "34. The formation of borax glass is caused by",
A: "inappropriate preparation of solder.",
B: "raising the temperature of the torch.",
C: "using a light weight support.",
D: "the application of low heat.",
answer: "B. raising the temperature of the torch.",
correctLetter: "B",
correctOption: 2,
},

{
id: "question35",
question:  "35. Select the common cut of gemstone in the options.",
A: "Cabochon and brillant",
B: "Marquise and diamond",
C: "Baguette and pentagon",
D: "Cameo and hexagon",
answer: "A. Cabochon and brillant",
correctLetter: "A",
correctOption: 1,
},

{
id: "question36",
question:  "36. Select the carat which contains more ingredient material.",
A: "24",
B: "22",
C: "12",
D: "8",
answer: "A. 24",
correctLetter: "A",
correctOption: 1,
},

{
id: "question37",
question:  "37. Choose the most appropriate material for fusing stronger joints of metal.",
A: "Nitric acid",
B: "Gum arabic",
C: "Paillion",
D: "Loam",
answer: "D. Loam",
correctLetter: "D",
correctOption: 4,
},

{
id: "question38",
question:  "38. Select the most permanent technique for finishing clay beads.",
A: "Lacquering",
B: "Painting",
C: "Burnishing",
D: "Glazing",
answer: "D. Glazing",
correctLetter: "D",
correctOption: 4,
},

{
id: "question39",
question:  "39. The most suitable tool used in cutting leather for jewellery is",
A: "blade.",
B: "chisel.",
C: "cutlass.",
D: "scissors.",
answer: "D. scissors.",
correctLetter: "D",
correctOption: 4,
},

{
id: "question40",
question:  "40. The purpose of using sequins in jewellery is to",
A: "enlongate chains.",
B: "join two or more units.",
C: "enhance the work.",
D: "shorten the piece.",
answer: "C. enhance the work.",
correctLetter: "C",
correctOption: 3,
},


]