import { SquareRoot, superscript, subscript, BoldText, ItalicText, Fraction, ShortFraction, LongFraction, MixedFraction, Isotopes } from "@/mathnotation"

const path = "@/assets/images/pastquestions-figures/integratedscience/integratedscienceA/integratedscience-"

export const INTEGRATEDSCIENCEA2012 = [

{
id: "question1",
question: "1. Interbreeding organisms are members of the same......................",
A: "class",
B: "family",
C: "genus",
D: "Species",
answer: "D. species",
correctLetter: "D",
correctOption: 4,
},

{
id: "question2",
question: "2. The pH value of solution is accurately determined by using .......................",
A: "litmus paper",
B: "methyl orange",
C: "phenolphthalein",
D: "universal indicator",
answer: "D. universal indicator",
correctLetter: "D",
correctOption: 4,
},

{
id: "question3",
question: "3. In which part of the leaf of a flowering plant is the greatest amount of glucose produced during photosynthesis?",
A: "Lower epidermal cells",
B: "Upper epidermal cells",
C: "Palisade cells",
D: "Spongy mesophyll cells",
answer: "C. Palisade cells",
correctLetter: "C",
correctOption: 3,
},

{
id: "question4",
question: "4. An advantage of the use of hay over silage in animal production is that hay ........................",
A: "is available throughout the year",
B: "has a laxative effect",
C: "has higher proportion of leaves, water and nutrients",
D: "is more palatable to livestock",
answer: "A. is available throughout the year",
correctLetter: "A",
correctOption: 1,
},

{
id: "question5",
question: "5. Which of the following types of teeth is absent in herbivores?",
A: "Canines",
B: "Incisors",
C: "Premolars",
D: "Molars",
answer: "A. Canines",
correctLetter: "A",
correctOption: 1,
},

{
id: "question6",
question: "6. A block and tackle system consists of three fived and two movable pulleys. Determine the velocity ratio of the system.",
A: "2",
B: "3",
C: "5",
D: "6",
answer: "C. 5",
correctLetter: "C",
correctOption: 3,
},

{
id: "question7",
question: "7. Pulmonary circulation in mammals involves the movement of blood from the ..................",
A: "heart to the body and back",
B: "lungs to the heart and back",
C: "heart to the lungs and back",
D: "lungs to the body and back",
answer: "C. heart to the lungs and back",
correctLetter: "C",
correctOption: 3,
},

{
id: "question8",
question: "8. Tides occur as a result of ................................",
A: "cool air at the poles flowing towards the equator",
B: "gravitational pull of the moon on the seas",
C: "differences in temperature between the land and the sea",
D: "the revolution of the earth",
answer: "B. gravitational pull of the moon on the seas",
correctLetter: "B",
correctOption: 2,
},

{
id: "question9",
question: "9. Identical twins look alike because they develop from...........................",
A: "one ovum fertilised by two sperms",
B: "two ova fertilized by one sperm",
C: "two ova fertilised by two sperms",
D: "one ovum fertilized by one sperm",
answer: "D. one ovum fertilized by one sperm",
correctLetter: "D",
correctOption: 4,
},

{
id: "question10",
question: "10. Which of the following equipment are used in poultry production? \nI. Burdizzo \nII. Debeaker \nIII. Hoover \nIV. Seine net",
A: "I and II only",
B: "I and III only",
C: "II and III only",
D: "III and IV only",
answer: "C. II and III only",
correctLetter: "C",
correctOption: 3,
},

{
id: "question11",
question: "11. One advantage of male circumcision is to ....................",
A: "reveal the strength in an individual",
B: "confer manhood on the individual",
C: "prevent infection of the tip of the penis",
D: "enable the penis to become erect",
answer: "C. prevent infection of the tip of the penis",
correctLetter: "C",
correctOption: 3,
},

{
id: "question12",
question: "12. The silvered walls of a thermos flask are to reduce heat outflow and inflow by..................... \n I. convection \nII. conduction \nIII. Radiation",
A: "I only",
B: "III only",
C: "I and II only",
D: "II and III only",
answer: "C. I and II only",
correctLetter: "C",
correctOption: 3,
},

{
id: "question13",
question: "13. Which of the following pairs of plants are rhizomes?",
A: "Cocoyam and cassava",
B: "Canna lily and ginger",
C: "Onion and garlic",
D: "Banana and plantain",
answer: "B. Canna lily and ginger",
correctLetter: "B",
correctOption: 2,
},

{
id: "question14",
question: "14. Rabbits are housed in a.........................",
A: "hutch",
B: "kraal",
C: "pen",
D: "sty",
answer: "A. hutch",
correctLetter: "A",
correctOption: 1,
},

{
id: "question15",
question: "15. A bond formed between two atoms is considered as ionic when .................",
A: "the two atoms share a pair of electrons",
B: "there is transfer of at least one electron from one atom to the other",
C: "both atoms transfer electrons to each other",
D: "no electron transfer occurs between the atoms",
answer: "B. there is transfer of at least one electron from one atom to the other",
correctLetter: "B",
correctOption: 2,
},

{
id: "question16",
question: "16. The correct path of air entering the lungs through the nostrils of a mammal is represented as",
A: "glottis –> trachea –> bronchi –> bronchioles –> lungs",
B: "trachea –> glottis –> bronchi –> bronchioles –> lungs",
C: "bronchi –> trachea –> glottis –> bronchioles –> lungs",
D: "bronchioles –> bronchi –> trachea –> glottis –> lungs",
answer: "A. glottis –> trachea –> bronchi –> bronchioles –> lungs",
correctLetter: "A",
correctOption: 1,
},

{
id: "question17",
question: "17. Which of the following cultural practices are carried out in the cultivation of tomatoes?  \n I. Pruning \nII. Shading \nIII. Staking",
A: "I and II only",
B: "I and III only",
C: "II and III only",
D: "I, II and III",
answer: "B. I and III only",
correctLetter: "B",
correctOption: 2,
},

{
id: "question18",
question: "18. Prenatal period in human growth and development is the period from...................",
A: "birth to adolescence",
B: "conception to birth",
C: "birth to childhood",
D: "adolescence to adulthood",
answer: "B. conception to birth",
correctLetter: "B",
correctOption: 2,
},

{
id: "question19",
question: "19. The mass of body remains constant at all places because .....................",
A: "of the tendency of the body to remain at rest",
B: "mass depends solely on distance between molecules of a body",
C: "mass does not depend on acceleration due to gravity",
D: "matter can neither be created nor destroyed",
answer: "C. mass does not depend on acceleration due to gravity",
correctLetter: "C",
correctOption: 3,
},

{
id: "question20",
question: "20. The taste buds in humans that are sensitive to sour taste are located at the...................",
A: "tip of the tongue",
B: "back of the tongue",
C: "sides of the tongue",
D: "middle of the tongue",
answer: "C. sides of the tongue",
correctLetter: "C",
correctOption: 3,
},

{
id: "question21",
question: "21. Duralumin is an alloy used in the construction of aircrafts because it........................",
A: "has a low melting point",
B: "is attractive in appearance",
C: "is very light and strong",
D: "is non-corrosive",
answer: "C. is very light and strong",
correctLetter: "C",
correctOption: 3,
},

{
id: "question22",
question: "22. Diffusion in mammals is demonstrated in the................................",
A: "movement of urine from the kidney into the urinary bladder",
B: "movement of saliva from the salivary glands into the buccal cavity",
C: "absorption of salts by the cells of the body",
D: "gaseous exchange in the alveoli",
answer: "D. gaseous exchange in the alveoli",
correctLetter: "D",
correctOption: 4,
},

{
id: "question23",
question: "23. Petroleum consists of a mixture of ...............................",
A: "alkanoic acids",
B: "esters",
C: "Hydrocarbons",
D: "polymers",
answer: "C. hydrocarbons",
correctLetter: "C",
correctOption: 3,
},

{
id: "question24",
question: "24. Emulsification of fats by the bile in the digestive system of mammal signifies the ...................",
A: "destruction of fats",
B: "convection of fats to fatty acids and glycerol",
C: "breaking down of large fat globules into small droplets",
D: "prevention of enzymes from digesting fats",
answer: "C. breaking down of large fat globules into small droplets",
correctLetter: "C",
correctOption: 3,
},

{
id: "question25",
question: "25. Which of the following chemical equations represents a neutralization reaction?",
A: "CaO + H2O –> Ca(OH)2",
B: "MnO2 + 4HCl –> MnCl2 + 2H20 + Cl2",
C: "Zn(OH)2 + 2HCl –> ZnCl2 + 2H2O",
D: "C2H2 + H2O –> C2H5OH",
answer: "C. Zn(OH)2 + 2HCl –> ZnCl2 + 2H2O",
correctLetter: "C",
correctOption: 3,
},

{
id: "question26",
question: "26. A characteristic feature of a wind-pollinated flower is the possession of..........................",
A: "brightly coloured petals",
B: "large petals",
C: "horny guider",
D: "large pendulous stamens",
answer: "D. large pendulous stamens",
correctLetter: "D",
correctOption: 4,
},

{
id: "question27",
question: "27. A body of mass 2 kg floats on water, If the density of water is 1000 kg m-3, determine the volume of the body.",
A: "2.0 x 10-1 m3",
B: "2.0 x 10-2 m3",
C: "2.0 x 10-3 m3",
D: "2.0 x 102 m3",
answer: "C. 2",
correctLetter: "C",
correctOption: 3,
},

{
id: "question28",
question: "28. Which of the following functions is common to the skin and the lungs of a mammal?",
A: "Conservation of energy",
B: "Removal of water",
C: "Reabsorption of glucose",
D: "Removal of nitrogenous waste from the body",
answer: "B. Removal of water",
correctLetter: "B",
correctOption: 2,
},

{
id: "question29",
question: "29. The major difference between a clayey soil and a sandy soil is in their........................",
A: "colour",
B: "humus content",
C: "mineral content",
D: "texture",
answer: "B. humus content",
correctLetter: "B",
correctOption: 2,
},

{
id: "question30",
question: "30. When a moving vehicle stops suddenly, the passengers jerk forward. This is due to the.................",
A: "wind surrounding the vehicle",
B: "force acting on the vehicle",
C: "reaction of the passengers",
D: "ability of the passengers continue in motion",
answer: "D. ability of the passengers continue in motion",
correctLetter: "D",
correctOption: 4,
},

{
id: "question31",
question: "31. The main reason for growing ornamental plants is ..........................",
A: "for them to serve as a fence",
B: "for their medicinal value",
C: "to provide shade",
D: "for their decorative effect",
answer: "D. for their decorative effect",
correctLetter: "D",
correctOption: 4,
},

{
id: "question32",
question: "32. The reaction between an alkanoic acid and an alkanol is known as......................",
A: "esterification",
B: "neutralization",
C: "polymerization",
D: "saponification",
answer: "A. esterification",
correctLetter: "A",
correctOption: 1,
},

{
id: "question33",
question: "33. A microscopic organism with the nucleus enclosed in membrane belongs to the Kingdom",
A: "Animalia",
B: "Plantae",
C: "Prokaryotae",
D: "Protoctista",
answer: "A. Animalia",
correctLetter: "A",
correctOption: 1,
},

{
id: "question34",
question: "34. An object placed between the optical centre and the principal focus of a converging lens. The image formed is.........................",
A: "magnified, virtual and erect",
B: "magnified, real and inverted",
C: "diminished, real and erect",
D: "diminished, virtual and erect",
answer: "A. magnified, virtual and erect",
correctLetter: "A",
correctOption: 1,
},

{
id: "question35",
instruction: "35. The diagram above illustrates a/an ..................................",
// question: "35. The diagram above illustrates a/an ..................................",
A: "Anemometer",
B: "Secchi disc",
C: "wind vane",
D: "Quadrat",
answer: "C. wind vane",
correctLetter: "C",
correctOption: 3,
questionFigure: require(path + "2012-A-Q-35.png"),
imageRatio: 1,
},

{
id: "question36",
question: "36. An example of substance that boils at 100 °C and at one atmosphere is.......................",
A: "a mixture of potassium chloride and distilled water",
B: "ice made from distilled water",
C: "ethanol mixed with 10% water",
D: "distilled water mixed with 10% alcohol",
answer: "B. ice made from distilled water",
correctLetter: "B",
correctOption: 2,
},

{
id: "question37",
question: "37. Which of the following statements about the uses of radioisotopes are correct? \nI. Preservation of food \nII. Killing of bacteria in water \n III. Sterilization of equipment \nIV. Treatment of cancer",
A: "I and II only",
B: "III and IV only",
C: "I, II and III only",
D: "I, II and IV only",
answer: "D. I, II and IV only",
correctLetter: "D",
correctOption: 4,
},

{
id: "question38",
question: "38. In which of the following media would sound travel fastest?",
A: "Air",
B: "Iron",
C: "Water",
D: "Wood",
answer: "B. Iron",
correctLetter: "B",
correctOption: 2,
},

{
id: "question39",
question: "39. A homozygous black mouse is mated to a white mouse. If black is dominant to white colour, what will be the colour of the young mice?",
A: "All will be white",
B: "All will be black",
C: "Some will be black and some will be white",
D: "Each of them will be partly black and partly white",
answer: "B. All will be black",
correctLetter: "B",
correctOption: 2,
},

{
id: "question40",
question: "40. Which of the following energy transformations represents the changes that takes place when a torchlight is switched on?",
A: "Chemical –> heat –> electrical –> light",
B: "Chemical –> heat –> light –> electrical",
C: "Chemical –> electrical –> heat –> light",
D: "Electrical –> chemical –> heat –> light",
answer: "C. Chemical –> electrical –> heat –> light",
correctLetter: "C",
correctOption: 3,
},

{
id: "question41",
question: "41. Fermentation of corn dough occurs as a result of the.....................",
A: "action of houseflies on the dough",
B: "action of microbes on the dough",
C: "presence of water in the dough",
D: "starch in the dough",
answer: "B. action of microbes on the dough",
correctLetter: "B",
correctOption: 2,
},

{
id: "question42",
instruction: "42. Determine the current through the electrical circuit above when the key is closed.",
// question: "42. Determine the current through the electrical circuit above when the key is closed.",
A: "0.2 A",
B: "0.8 A",
C: "2.5 A",
D: "5.0 A",
answer: "B. 0",
correctLetter: "B",
correctOption: 2,
questionFigure: require(path + "2012-A-Q-42.png"),
imageRatio: 1,
},

{
id: "question43",
question: "43. Which of the following statements about small-scale industry is correct? It .................",
A: "makes use of advance technology",
B: "is always sited in rural areas",
C: "is always capital intensive",
D: "operates with the minimum input of materials",
answer: "D. operates with the minimum input of materials",
correctLetter: "D",
correctOption: 4,
},

{
id: "question44",
question: "44. The most economical method of preserving fish in West Africa is......................",
A: "canning",
B: "drying",
C: "freezing",
D: "Smoking",
answer: "D. smoking",
correctLetter: "D",
correctOption: 4,
},

{
id: "question45",
question: "45. Evidence from comparative embryology in support of evolution shows that...................",
A: "embryos of different vertebrates have similar structures",
B: "embryos of different vertebrates have different structures",
C: "vertebrates evolved from different ancestors",
D: "bodies of different vertebrates have different body pain",
answer: "A. embryos of different vertebrates have similar structures",
correctLetter: "A",
correctOption: 1,
},

{
id: "question46",
question: "46. Consider the following hazards:  \nI. earthquake \nII. asbestos dust \nIII. Flooding \nIV. forest fires \n Which of the hazards are classified as natural hazards?",
A: "I and II only",
B: "III and IV only",
C: "I, II and III only",
D: "II, III and IV only",
answer: "C. I, II and III only",
correctLetter: "C",
correctOption: 3,
},

{
id: "question47",
question: "47. One of the reasons for using a capacitor in an electric circuit is to...................",
A: "amplify electronic signals",
B: "out of the current flowing from the emitter",
C: "omit inoculant narrow spectrum of light",
D: "differentiate between high frequency and low frequency signals",
answer: "D. differentiate between high frequency and low frequency signals",
correctLetter: "D",
correctOption: 4,
},

{
id: "question48",
question: "48. Which of the following statements explain why air is considered a mixture? \n I. There is no chemical formula for air \nII. The constituents of air are not in fixed proportions  \nIII. Air has weight and occupies volume  \nIV. The constituents of air can be separated by physical means",
A: "I and II only",
B: "III and IV only",
C: "I, II and III only",
D: "I, II and IV only",
answer: "D. I, II and IV only",
correctLetter: "D",
correctOption: 4,
},

{
id: "question49",
question: "49. An electronic device which allows an electric current to flow is one direction and blocks it in an opposite direction is called......................",
A: "capacitor",
B: "diode",
C: "inductor",
D: "transistor",
answer: "B. diode",
correctLetter: "B",
correctOption: 2,
},

{
id: "question50",
question: "50. Isotopes of a particular element have the same......................",
A: "atomic number",
B: "atomic mass",
C: "mass number",
D: "number of electrons",
answer: "A. atomic number",
correctLetter: "A",
correctOption: 1,
},



]