export const AGRICULTURALSCIENCEA2008 = [

{
id: "question1",
question:  "1. Which of the following benefits of agriculture is of least importance to the peasant farmer?",
A: "Materials for shelter",
B: "Employment",
C: "Foreign exchange",
D: "Income",
answer: "C. Foreign exchange",
correctLetter: "C",
correctOption: 3,
},

{
id: "question2",
question:  "2. Farmers who plant improved maize would harvest",
A: "pest-infested maize grains.",
B: "a high yield of maize.",
C: "plants with long stalks.",
D: "maize cobs with scattered grains.",
answer: "B. a high yield of maize.",
correctLetter: "B",
correctOption: 2,
},

{
id: "question3",
question:  "3. Which of the following land tenure systems allows the owner greatest freedom to dispose of the land as he wishes?",
A: "Communal",
B: "Free-hold",
C: "Lease-hold",
D: "Share-cropping",
answer: "B. Free-hold",
correctLetter: "B",
correctOption: 2,
},

{
id: "question4",
question:  "4. Which of the following is not a government agricultural programme?",
A: "Operation Feed the’ Nation",
B: "Agricultural Development Projects",
C: "Farm Settlement Schemes",
D: "West Africa Rice Development Agency",
answer: "D. West Africa Rice Development Agency",
correctLetter: "D",
correctOption: 4,
},

{
id: "question5",
question:  "5. The practice of planting one type of annual crop each season is referred to as",
A: "monoculture.",
B: "continuous cropping.",
C: "mono-cropping.",
D: "horticulture.",
answer: "C. mono-cropping.",
correctLetter: "C",
correctOption: 3,
},

{
id: "question6",
question:  "6. The most important use of land for agricultural production is",
A: "grazing paddocks.",
B: "botanical gardens.",
C: "game reserves.",
D: "farmstead construction.",
answer: "A. grazing paddocks.",
correctLetter: "A",
correctOption: 1,
},

{
id: "question7",
question:  "7. Which of the following biotic factors are usually used to control cassava mealybugs?",
A: "Parasites",
B: "Predators",
C: "Pests",
D: "Pathogens",
answer: "A. Parasites",
correctLetter: "A",
correctOption: 1,
},

{
id: "question8",
question:  "8. The following are types of sedimentary rocks except",
A: "granite.",
B: "limestone.",
C: "sandstone.",
D: "dolomite.",
answer: "A. granite.",
correctLetter: "A",
correctOption: 1,
},

{
id: "question9",
question:  "9. A reddish coloured soil indicates the presence of",
A: "copper.",
B: "sodium.",
C: "iron.",
D: "manganese.",
answer: "C. iron.",
correctLetter: "C",
correctOption: 3,
},

{
id: "question10",
question:  "10. The three most important physical factors that influence rock weathering are",
A: "colour, particle size and hardness of rock.",
B: "particle size, hardness and degree of cementation.",
C: "hardness, degree of cementation and colour.",
D: "particle size, temperature and colour.",
answer: "D. particle size, temperature and colour.",
correctLetter: "D",
correctOption: 4,
},

{
id: "question11",
question:  "11. Which of the following statements is not tine about waterlogged soils?",
A: "Such soils are heavily leached.",
B: "Denitrifying bacteria are more active in such soils than nitrifying bacteria.",
C: "Nitrosomonas yield best in such soils.",
D: "Soil temperature is usually low.",
answer: "C. Nitrosomonas yield best in such soils.",
correctLetter: "C",
correctOption: 3,
},

{
id: "question12",
question:  "12. Which of the following crops should be planted on a piece of land that has been repeatedly cropped with maize?",
A: "Guinea corn",
B: "Millet",
C: "Rice",
D: "Cowpea",
answer: "D. Cowpea",
correctLetter: "D",
correctOption: 4,
},

{
id: "question13",
question:  "13. Sources of nitrogen to the soil include the following except",
A: "lightning.",
B: "urea.",
C: "blue-green algae.",
D: "residues of burning activities.",
answer: "D. residues of burning activities.",
correctLetter: "D",
correctOption: 4,
},

{
id: "question14",
question:  "14. Which of the following statements about bush burning is false?",
A: "It releases mineral nutrients bound in plant tissues.",
B: "It encourages the growth of fresh grasses.",
C: "The heat generated destroys pests.",
D: "The heat generated increases the population of soil organisms.",
answer: "D. The heat generated increases the population of soil organisms.",
correctLetter: "D",
correctOption: 4,
},

{
id: "question15",
question:  "15. A farmer applied NPK 15: 11: 8 at planting. What is the percentage of potassium in the fertilizer?",
A: "23.53%",
B: "32.35%",
C: "33.33%",
D: "44.12%",
answer: "D. 44.12%",
correctLetter: "D",
correctOption: 4,
},

{
id: "question16",
question:  "16. The following equipment can be used for irrigation except",
A: "bucket.",
B: "watering can.",
C: "knapsack sprayer.",
D: "siphon tube.",
answer: "C. knapsack sprayer.",
correctLetter: "C",
correctOption: 3,
},

{
id: "question17",
question:  "17. Excessive drainage of soil water can be checked by the addition of adequate quantities of",
A: "N.P.K. 15-15-15.",
B: "sulphate of ammonia.",
C: "single superphosphate.",
D: "compost manure.",
answer: "D. compost manure.",
correctLetter: "D",
correctOption: 4,
},

{
id: "question18",
question:  "18. Considering all costs, the cheapest source of energy for domestic use is",
A: "electricity.",
B: "sunlight.",
C: "biogas.",
D: "water.",
answer: "C. biogas.",
correctLetter: "C",
correctOption: 3,
},

{
id: "question19",
question:  "19. The implement used for pulverising the soil is the",
A: "planter.",
B: "ridge r.",
C: "harrow.",
D: "plough.",
answer: "C. harrow.",
correctLetter: "C",
correctOption: 3,
},

{
id: "question20",
question:  "20. An incubator is important in supplying",
A: "heat for day-old chicks.",
B: "heat for embryo development.",
C: "light for candling eggs.",
D: "feed to chicks.",
answer: "B. heat for embryo development.",
correctLetter: "B",
correctOption: 2,
},

{
id: "question21",
question:  "21. A farm surveying equipment made of steel and used for measuring short distances is called",
A: "prismatic compass.",
B: "measuring tape.",
C: "gunter’s chain.",
D: "theodolite.",
answer: "B. measuring tape.",
correctLetter: "B",
correctOption: 2,
},

{
id: "question22",
question:  "22. Which of the following statements about farmstead planning is false?",
A: "Administrative blocks should not be located close to the entrance of the farmstead.",
B: "Waste disposal unit should be located far away from the main farm area.",
C: "All buildings should be well ventilated with good lightings.",
D: "Animal pens should not be located too close to the worker’s house.",
answer: "A. Administrative blocks should not be located close to the entrance of the farmstead.",
correctLetter: "A",
correctOption: 1,
},

{
id: "question23",
question:  "23. The term supplying in crop production means",
A: "pruning excess branches of crops.",
B: "spacing out crops during planting.",
C: "replacing ungerminated seeds on seedbeds.",
D: "adding enough fertilizer to the crops.",
answer: "B. spacing out crops during planting.",
correctLetter: "B",
correctOption: 2,
},

{
id: "question24",
question:  "24. During photosynthesis, green plants convert carbon dioxide to",
A: "chlorophyll.",
B: "carbohydrate.",
C: "protein.",
D: "carbonic acid.",
answer: "B. carbohydrate.",
correctLetter: "B",
correctOption: 2,
},

{
id: "question25",
question:  "25. Parboiling in the processing of rice",
A: "improves its digestibility.",
B: "increases grain mass.",
C: "reduces the percentage of breakage.",
D: "facilitates the polishing of rice.",
answer: "A. improves its digestibility.",
correctLetter: "A",
correctOption: 1,
},

{
id: "question26",
question:  "26. The main reason for removing the barks of cassava tubers before processing the tuber is to",
A: "reduce the water content.",
B: "improve the protein content of products.",
C: "improve the shelf life of products.",
D: "reduce the cyanide content of products.",
answer: "D. reduce the cyanide content of products.",
correctLetter: "D",
correctOption: 4,
},

{
id: "question27",
question:  "27. Curing is carried out in the processing of",
A: "cassava.",
B: "tobacco.",
C: "okro.",
D: "Tomato",
answer: "B. tobacco.",
correctLetter: "B",
correctOption: 2,
},

{
id: "question28",
question:  "28. Tomato plants are staked for the following reasons except to",
A: "produce clean fruits.",
B: "reduce pest damage to fruits.",
C: "increase the yield.",
D: "improve the taste.",
answer: "D. improve the taste.",
correctLetter: "D",
correctOption: 4,
},

{
id: "question29",
question:  "29. A vegetatively propagated citrus plant will produce fruits earlier than the one established from seeds because",
A: "it would not suffer from gummosis disease.",
B: "insect pests do not attack it.",
C: "it is more advanced at the time of establishment:",
D: "the flowers are wind pollinate",
answer: "C. it is more advanced at the time of establishment:",
correctLetter: "C",
correctOption: 3,
},

{
id: "question30",
question:  "30. Swollen shoot disease of cocoa is caused by",
A: "virus.",
B: "fungus.",
C: "bacteria.",
D: "nematode.",
answer: "A. virus.",
correctLetter: "A",
correctOption: 1,
},

{
id: "question31",
question:  "31. Groundnut grows best on a",
A: "well-drained, light sandy-loam soil.",
B: "well-drained, clayey friable soil.",
C: "swampy, sandy-clay soil.",
D: "well-drained, clayey-loam soil.",
answer: "A. well-drained, light sandy-loam soil.",
correctLetter: "A",
correctOption: 1,
},

{
id: "question32",
question:  "32. Which of the following characteristics is not true of a good pasture crop?",
A: "High palatability",
B: "High nutritive value",
C: "Resistance to trampling",
D: "Poor digestibility",
answer: "D. Poor digestibility",
correctLetter: "D",
correctOption: 4,
},

{
id: "question33",
question:  "33. The benefits of establishing forests do not include",
A: "derivation of medicine.",
B: "provision of food.",
C: "improvement of micro-climate.",
D: "shading of crops.",
answer: "D. shading of crops.",
correctLetter: "D",
correctOption: 4,
},

{
id: "question34",
question:  "34. Floriculture is a subdivision of horticulture which deals with the cultivation of",
A: "fruit crops.",
B: "vegetables.",
C: "ornamental plants.",
D: "spices.",
answer: "C. ornamental plants.",
correctLetter: "C",
correctOption: 3,
},

{
id: "question35",
question:  "35. Which of the following insect pests causes defoliation in crops?",
A: "Mirid",
B: "Grasshopper",
C: "Weevil",
D: "Aphid",
answer: "B. Grasshopper",
correctLetter: "B",
correctOption: 2,
},

{
id: "question36",
question:  "36. Which of the following pesticides effectively control maize stem borers?",
A: "Systemic insecticides",
B: "Contact poisons",
C: "Nematicides",
D: "Fumigants",
answer: "A. Systemic insecticides",
correctLetter: "A",
correctOption: 1,
},

{
id: "question37",
question:  "37. Which of the following combinations of practices best controls groundnut rosette disease?",
A: "Late planting and spraying of insecticide",
B: "Early planting and spraying of nematicide",
C: "Late planting and spraying of fungicide",
D: "Early planting and spraying of insecticide",
answer: "D. Early planting and spraying of insecticide",
correctLetter: "D",
correctOption: 4,
},

{
id: "question38",
question:  "38. Determine the number of bottles of a herbicide required to spray 25 hectares of farmland, if one bottle is needed to prepare 100 litres and the diluted product is applied at a rate of 20 litres per hectare.",
A: "2 bottles",
B: "5 bottles",
C: "8 bottles",
D: "11 bottles",
answer: "B. 5 bottles",
correctLetter: "B",
correctOption: 2,
},

{
id: "question39",
question:  "39. The milk secreting organ in cattle is the",
A: "dewlap.",
B: "udder.",
C: "comb.",
D: "muzzle.",
answer: "B. udder.",
correctLetter: "B",
correctOption: 2,
},

{
id: "question40",
question:  "40. A developing embryo derives its nutrition from the mother",
A: "through the blood vessels located in the placenta.",
B: "by sucking the mammary glands.",
C: "by direct diffusion through the blood vessels in the liver.",
D: "through the blood vessels located in the intestine of the mother.",
answer: "A. through the blood vessels located in the placenta.",
correctLetter: "A",
correctOption: 1,
},

{
id: "question41",
question:  "41. Birds stoic their food in the",
A: "crop.",
B: "gizzard.",
C: "provcntriculus.",
D: "cloaca.",
answer: "A. crop.",
correctLetter: "A",
correctOption: 1,
},

{
id: "question42",
question:  "42. The following are examples of natural mating methods except",
A: "pen mating.",
B: "flock mating.",
C: "hand mating.",
D: "block mating.",
answer: "D. block mating.",
correctLetter: "D",
correctOption: 4,
},

{
id: "question43",
question:  "43. The milk collection vessel of the mammary gland is the",
A: "alveolus.",
B: "gland cistern.",
C: "teat.",
D: "streak canal.",
answer: "B. gland cistern.",
correctLetter: "B",
correctOption: 2,
},

{
id: "question44",
question:  "44. Fertile eggs will be produced by breeders if the",
A: "laying units are well illuminated.",
B: "cocks are always kept with the hens.",
C: "hens are not allowed to brood.",
D: "eggs collected are kept at the correct temperature.",
answer: "B. cocks are always kept with the hens.",
correctLetter: "B",
correctOption: 2,
},

{
id: "question45",
question:  "45. The rabbit is able to utilize forages because",
A: "it has an enlarged caecum that digests fibre.",
B: "the small intestine is rich in microbes.",
C: "the mouth has large molars for grinding.",
D: "the length of the gut is relatively short.",
answer: "A. it has an enlarged caecum that digests fibre.",
correctLetter: "A",
correctOption: 1,
},

{
id: "question46",
question:  "46. If feed efficiency for egg production is defined as feed consumed per 10 eggs, what will be the feed efficiency for a layer that laid 230 eggs and consumed 26 kg feed?",
A: "0.88",
B: "1.13",
C: "1.76",
D: "2.23",
answer: "B. 1.13",
correctLetter: "B",
correctOption: 2,
},

{
id: "question47",
question:  "47. When birds are fed on a ration deficient in riboflavin, which of the following symptoms will they show?",
A: "Night blindness",
B: "Cataract",
C: "Curled-toe paralysis",
D: "Scurvy",
answer: "C. Curled-toe paralysis",
correctLetter: "C",
correctOption: 3,
},

{
id: "question48",
question:  "48. Livestock arc said to feed on the range when they cat",
A: "fresh herbage at the milking parlour.",
B: "fresh herbage directly from the pasture.",
C: "harvested herbage in a stall.",
D: "preserved herbage in the form of silage.",
answer: "B. fresh herbage directly from the pasture.",
correctLetter: "B",
correctOption: 2,
},

{
id: "question49",
question:  "49. Which of the following practices is not a method of improving rangeland?",
A: "Rotational grazing",
B: "Resecding of depleted forage species",
C: "Removal of weeds",
D: "Use of inorganic fertilizers",
answer: "D. Use of inorganic fertilizers",
correctLetter: "D",
correctOption: 4,
},

{
id: "question50",
question:  "50. Liverfluke infestation causes disturbance in lipid digestion because it",
A: "blocks the passage of fat to intestine.",
B: "blocks the bile duct and reduces secretion of bile.",
C: "destroys the lipase enzyme.",
D: "prevents fat excretion.",
answer: "B. blocks the bile duct and reduces secretion of bile.",
correctLetter: "B",
correctOption: 2,
},

{
id: "question51",
question:  "51. A farmer noticed that one of his cows has high fever, blood-stained diarrhoea and often grinds its teeth. This shows that the cow is infected by",
A: "rinderpest.",
B: "anthrax.",
C: "brucellosis.",
D: "aspergillosis.",
answer: "A. rinderpest.",
correctLetter: "A",
correctOption: 1,
},

{
id: "question52",
question:  "52. Temperature is an important factor in fish ponds because it",
A: "affects the metabolic processes in fish.",
B: "determines the sex of fishes.",
C: "encourages the growth of phytoplanktons.",
D: "affects the type of species of fish.",
answer: "A. affects the metabolic processes in fish.",
correctLetter: "A",
correctOption: 1,
},

{
id: "question53",
question:  "53. An illegal method of harvesting fish is by the use of",
A: "drag net.",
B: "potassium cyanide.",
C: "hook and line.",
D: "calcium carbonate.",
answer: "B. potassium cyanide.",
correctLetter: "B",
correctOption: 2,
},

{
id: "question54",
question:  "54. How can the offspring of a bull continue to be produced long after its death? By",
A: "using the preserved semen for artificial insemination",
B: "collecting the semen of the offspring for use in artificial insemination",
C: "crossing the male and female offspring",
D: "preserving the body of the dead animal",
answer: "A. using the preserved semen for artificial insemination",
correctLetter: "A",
correctOption: 1,
},

{
id: "question55",
question:  "55. Which of the following factors of production has profit as its reward?",
A: "Land",
B: "Labour",
C: "Capital",
D: "Management",
answer: "C. Capital",
correctLetter: "C",
correctOption: 3,
},

{
id: "question56",
question:  "56. A farm business makes profit when",
A: "total revenue equals total cost.",
B: "total cost exceeds total revenue.",
C: "total revenue exceeds total cost.",
D: "average cost equals total revenue.",
answer: "C. total revenue exceeds total cost.",
correctLetter: "C",
correctOption: 3,
},

{
id: "question57",
question:  "57. Agricultural business is difficult to insure in West Africa mainly because",
A: "agricultural production is not very profitable.",
B: "agricultural production is highly risky.",
C: "many farmers are very poor.",
D: "the premium is high.",
answer: "B. agricultural production is highly risky.",
correctLetter: "B",
correctOption: 2,
},

{
id: "question58",
question:  "58. A tractor with an expected life of 10 years was bought for Le 15.0m at the end of which it was to be sold for Le 1.0m. Its calculated depreciation is",
A: "Le 1.4m.",
B: "Le 1.5m.",
C: "Le 1.6m.",
D: "Le 1.7m.",
answer: "B. Le 1.4m.",
correctLetter: "B",
correctOption: 2,
},

{
id: "question59",
question:  "59. The aims and objectives of agricultural extension education do not include",
A: "educating farmers on the use of new tools.",
B: "educating farmers on governments’ annual budgets.",
C: "encouraging fanners to obtain loans for farming.",
D: "encouraging farmers to use meteorological information in farming.",
answer: "B. educating farmers on governments’ annual budgets.",
correctLetter: "B",
correctOption: 2,
},

{
id: "question60",
question:  "60. The process which a farmer goes through from the time he hears about a new idea till he finally accepts it, is referred to as",
A: "evolution.",
B: "revolution.",
C: "diffusion.",
D: "adoption.",
answer: "D. adoption.",
correctLetter: "D",
correctOption: 4,
},


]