export const AGRICULTURALSCIENCEA2021 = [

{
id: "question1",
question:  "1. The branch of crop science which deals with the study of insect pests is __________.",
A: "zoology",
B: "agronomy",
C: "entomology",
D: "pathology",
answer: "C. entomology",
correctLetter: "C",
correctOption: 3,
},

{
id: "question2",
question:  "2. Horse racing and polo are events where horses are used for _________.",
A: "wildlife conservation",
B: "recreation",
C: "dowry payment",
D: "transportation",
answer: "B. recreation",
correctLetter: "B",
correctOption: 2,
},

{
id: "question3",
question:  "3. The construction of rural feeder roads solves the following access problems in agriculture except _________.",
A: "marketing",
B: "transportation",
C: "extension services",
D: "land tenure system",
answer: "A. marketing",
correctLetter: "A",
correctOption: 1,
},

{
id: "question4",
question:  "4. The illustrated farm tool is used for ________.",
A: "making mounds",
B: "transplanting seedlings",
C: "cutting trees",
D: "pruning hedges",
answer: "A. making mounds",
correctLetter: "A",
correctOption: 1,
},

{
id: "question5",
question:  "5. The farm implement that could perform a similar function as the illustrated tool is _________.",
A: "plough",
B: "harrow",
C: "ridger",
D: "cultivator",
answer: "C. ridger",
correctLetter: "C",
correctOption: 3,
},

{
id: "question6",
question:  "6. A tractor-mounted sprayer used on large-scale farms is the  __________.",
A: "electrodyne sprayer",
B: "motorized sprayer",
C: "knapsack sprayer",
D: "boom sprayer",
answer: "B. motorized sprayer",
correctLetter: "B",
correctOption: 2,
},

{
id: "question7",
question:  "7. Which of the following types of farm power does not cause pollution?",
A: "Hydro",
B: "Electrical",
C: "Mechanical",
D: "Chemical",
answer: "A. Hydro",
correctLetter: "A",
correctOption: 1,
},

{
id: "question8",
question:  "8. In planning a farmstead, the structure which should be located on high elevation is the ___________.",
A: "fish pond",
B: "pigsty",
C: "farmhouse",
D: "processing shed",
answer: "A. fish pond",
correctLetter: "A",
correctOption: 1,
},

{
id: "question9",
question:  "9. The process labelled I is __________.",
A: "evaporation",
B: "absorption",
C: "respiration",
D: "transpiration",
answer: "D. transpiration",
correctLetter: "D",
correctOption: 4,
},

{
id: "question10",
question:  "10. The process labelled II is _________.",
A: "transpiration",
B: "condensation",
C: "evaporation",
D: "respiration",
answer: "C. evaporation",
correctLetter: "C",
correctOption: 3,
},

{
id: "question11",
question:  "11. The major source of water to the plants in the diagram is ________.",
A: "gravitational water",
B: "hygroscopic water",
C: "capillary water",
D: "surface water",
answer: "D. surface water",
correctLetter: "D",
correctOption: 4,
},

{
id: "question12",
question:  "12. The new rock formed when limestone is subjected to great heat and pressure is _________.",
A: "slate",
B: "graphite",
C: "marble",
D: "gneiss",
answer: "A. slate",
correctLetter: "A",
correctOption: 1,
},

{
id: "question13",
question:  "13. Which of the following pairs of raw materials is used in the canning industry?",
A: "Meat and Fish",
B: "Cotton and Tea",
C: "Hide and Skin",
D: "Pulpwood and cocoa",
answer: "A. Meat and Fish",
correctLetter: "A",
correctOption: 1,
},

{
id: "question14",
question:  "14. Micro-organisms that decompose organic matter will function best under __________.",
A: "waterlogged soil condition",
B: "anaerobic soil condition",
C: "low soil temperature",
D: "optimum soil pH",
answer: "B. anaerobic soil condition",
correctLetter: "B",
correctOption: 2,
},

{
id: "question15",
question:  "15. Calculate the weight of organic matter in the soil.",
A: "11g",
B: "22g",
C: "44g",
D: "78g",
answer: "B. 22g",
correctLetter: "B",
correctOption: 2,
},

{
id: "question16",
question:  "16. Determine the percentage of organic matter in the soil.",
A: "22%",
B: "44%",
C: "56%",
D: "60%",
answer: "B. 44%",
correctLetter: "B",
correctOption: 2,
},

{
id: "question17",
question:  "17. Which of the following practices will improve clay soil?",
A: "Use of acid-forming fertilizers",
B: "Bush burning",
C: "Addition of sodium chloride",
D: "Addition of organic material",
answer: "D. Addition of organic material",
correctLetter: "D",
correctOption: 4,
},

{
id: "question18",
question:  "18. A farmer practices crop rotation in order to __________.",
A: "reduce yield",
B: "improve soil texture",
C: "increase pest incidence",
D: "improve soil fertility",
answer: "D. improve soil fertility",
correctLetter: "D",
correctOption: 4,
},

{
id: "question19",
question:  "19. The phosphorous cycle is described as being sedimentary because phosphorous __________.",
A: "is a macroelement",
B: "is an earthbound element",
C: "is sold at room temperature",
D: "occurs in the atmosphere",
answer: "B. is an earthbound element",
correctLetter: "B",
correctOption: 2,
},

{
id: "question20",
question:  "20. The following factors are essential for maize production except ______.",
A: "high temperature",
B: "low temperature",
C: "relative humidity",
D: "adequate rainfall",
answer: "C. relative humidity",
correctLetter: "C",
correctOption: 3,
},

{
id: "question21",
question:  "21. Drying of newly harvested grains before storage helps to increase the  ________.",
A: "moisture content",
B: "pest incidence",
C: "seed viability",
D: "nutrient content",
answer: "A. moisture content",
correctLetter: "A",
correctOption: 1,
},

{
id: "question22",
question:  "22. Yams stored in a barn should be inspected at least once a week in order to _______.",
A: "remove irregular shaped tubers",
B: "control termite attack",
C: "prevent mouldiness in yam",
D: "remove sprouts and rotten tubers",
answer: "D. remove sprouts and rotten tubers",
correctLetter: "D",
correctOption: 4,
},

{
id: "question23",
question:  "23. The botanical name of onion is __________.",
A: "Zea mays",
B: "Oryza sativa",
C: "Carica papaya",
D: "Allium cepa",
answer: "D. Allium cepa",
correctLetter: "D",
correctOption: 4,
},

{
id: "question24",
question:  "24. Okro seeds are sown on 0.72hectares of farmland at a spacing of 60cm by 60cm. calculate the expected plant population.",
A: "3,600 plants",
B: "7,200 plants",
C: "10,000 plants",
D: "20,000 plants",
answer: "D. 20,000 plants",
correctLetter: "D",
correctOption: 4,
},

{
id: "question25",
question:  "25. A plot of land devoted to the cultivation of fruit trees is called ______.",
A: "orchard",
B: "farmstead",
C: "forest",
D: "ranch",
answer: "A. orchard",
correctLetter: "A",
correctOption: 1,
},

{
id: "question26",
question:  "26. Two species of kola grown for commercial purposes in West Africa are  __________.",
A: "Cola Acuminata and Cola Gigantea",
B: "Cola Nitida and Cola Verticillata",
C: "Cola Nitida and Cola Acuminata",
D: "Cola Verticillata and Cola Gigantea",
answer: "C. Cola Nitida and Cola Acuminata",
correctLetter: "C",
correctOption: 3,
},

{
id: "question27",
question:  "27. Propagation of ginger is generally done using its __________.",
A: "corm",
B: "rhizome",
C: "sucker",
D: "seed",
answer: "B. rhizome",
correctLetter: "B",
correctOption: 2,
},

{
id: "question28",
question:  "28. Elaeis guineensis and Arachis hypogaea are examples of ________.",
A: "latex crops",
B: "oil crops",
C: "fibre crops",
D: "fruit crops",
answer: "B. oil crops",
correctLetter: "B",
correctOption: 2,
},

{
id: "question29",
question:  "29. Which of the following statements is not a reason for carrying out the illustrated farm operation? To _________.",
A: "expose the leaves to sunlight",
B: "prevent damage by rodents",
C: "improve the yield of the crop",
D: "prevent lodging of the plants",
answer: "B. prevent damage by rodents",
correctLetter: "B",
correctOption: 2,
},

{
id: "question30",
question:  "30. Crops which require the illustrated farm operation are ________.",
A: "yam and cowpea",
B: "tomatoes and okro",
C: "okro and pepper",
D: "tomatoes and yam",
answer: "D. tomatoes and yam",
correctLetter: "D",
correctOption: 4,
},

{
id: "question31",
question:  "31. The basic importance of agriculture to a forester is to __________.",
A: "obtain honey",
B: "obtain food",
C: "acquire labour",
D: "procure timber",
answer: "D. procure timber",
correctLetter: "D",
correctOption: 4,
},

{
id: "question32",
question:  "32. A suitable grass for lawns is ____________.",
A: "Andropogon gayanus",
B: "Pennisetum purpureum",
C: "Cynodon dactylon",
D: "Panicum maximum",
answer: "D. Panicum maximum",
correctLetter: "D",
correctOption: 4,
},

{
id: "question33",
question:  "33. The causative organism of maize rust is a  ________.",
A: "bacterium",
B: "protozoon",
C: "virus",
D: "fungus",
answer: "D. fungus",
correctLetter: "D",
correctOption: 4,
},

{
id: "question34",
question:  "34. Which of the following group of insect pests damage crops by biting and chewing?",
A: "Cotton stainer, armyworm and cricket",
B: "Cricket, mealybug and whitefly",
C: "Armyworm, termite and grasshopper",
D: "Cotton stainer, mealybug and termite",
answer: "C. Armyworm, termite and grasshopper",
correctLetter: "C",
correctOption: 3,
},

{
id: "question35",
question:  "35. The breeds of cattle resistant to trypanosomiasis are ________.",
A: "N’dama and Muturu",
B: "White Fulani and Biu",
C: "Red Bororo and Adamawa",
D: "Wadara and Sokoto Gudali",
answer: "A. N’dama and Muturu",
correctLetter: "A",
correctOption: 1,
},

{
id: "question36",
question:  "36. Which of the following features is not a characteristic of a good layer?",
A: "Bright red comb and wattle",
B: "Long and curved beak",
C: "Bright and bulging eyes",
D: "Broad and flexible pelvic bone",
answer: "B. Long and curved beak",
correctLetter: "B",
correctOption: 2,
},

{
id: "question37",
question:  "37. The best way for a young animal to obtain colostrums is by _________.",
A: "giving it powdered milk",
B: "providing it with warm milk",
C: "injecting it with progesterone",
D: "allowing it to suckle the dam",
answer: "D. allowing it to suckle the dam",
correctLetter: "D",
correctOption: 4,
},

{
id: "question38",
question:  "38. Which of the following statements about slatted floors in livestock housing are true? They \nI. Lessen labour requirements \nII. Reduce odour in pens \nIII. Hamper movement of animals",
A: "I and II only",
B: "I and III only",
C: "II and III only",
D: "I, II and III",
answer: "D. I, II and III",
correctLetter: "D",
correctOption: 4,
},

{
id: "question39",
question:  "39. If 0.7kg of feed was fed to chicks per week, determine the cost of feeding the birds for 6 weeks. (1kg of feed costs N5)",
A: "N4.20",
B: "N11.70",
C: "N21.00",
D: "N30.00",
answer: "C. N21.00",
correctLetter: "C",
correctOption: 3,
},

{
id: "question40",
question:  "40. Feeds that have more than 18% fibre are classified as ________.",
A: "concentrates",
B: "additives",
C: "supplements",
D: "roughages",
answer: "C. supplements",
correctLetter: "C",
correctOption: 3,
},

{
id: "question41",
question:  "41. An advantage of zero-grazing is that it _________.",
A: "requires a lot of labour",
B: "prevents livestock from physical exercises",
C: "prevents depletion of pasture",
D: "increases the cost of pasture management",
answer: "D. increases the cost of pasture management",
correctLetter: "D",
correctOption: 4,
},

{
id: "question42",
question:  "42. The illustrated tool is _________.",
A: "an elastrator",
B: "a burdizzo",
C: "an electric dehorner",
D: "an artificial vagina",
answer: "D. an artificial vagina",
correctLetter: "D",
correctOption: 4,
},

{
id: "question43",
question:  "43. The illustrated tool is used for  __________.",
A: "castrating the bull calf",
B: "cutting the horns of the animal",
C: "collecting semen from the bull",
D: "identifying the animal",
answer: "C. collecting semen from the bull",
correctLetter: "C",
correctOption: 3,
},

{
id: "question44",
question:  "44. Formation of blisters on the mouth and the skin around the hoof of farm animals is a symptom of __________.",
A: "rinderpest",
B: "anthrax",
C: "Newcastle disease",
D: "foot and mouth disease",
answer: "D. foot and mouth disease",
correctLetter: "D",
correctOption: 4,
},

{
id: "question45",
question:  "45. In sheep production, tapeworm could be controlled by ________.",
A: "dusting",
B: "spraying",
C: "dipping",
D: "drenching",
answer: "D. drenching",
correctLetter: "D",
correctOption: 4,
},

{
id: "question46",
question:  "46. The percentage change in quantity supplied for maize is ________.",
A: "16.7%",
B: "20%",
C: "80%",
D: "83.3%",
answer: "A. 16.7%",
correctLetter: "A",
correctOption: 1,
},

{
id: "question47",
question:  "47. Calculate the percentage change in price for maize.",
A: "8.0%",
B: "33.3%",
C: "50.0%",
D: "66.7%",
answer: "B. 33.3%",
correctLetter: "B",
correctOption: 2,
},

{
id: "question48",
question:  "48. Determine the elasticity of supply for maize.",
A: "0.3",
B: "0.4",
C: "0.5",
D: "0.6",
answer: "C. 0.5",
correctLetter: "C",
correctOption: 3,
},

{
id: "question49",
question:  "49. A long loan for an agricultural enterprise could be obtained from ________.",
A: "microfinance bank",
B: "commercial bank",
C: "money lenders",
D: "cooperative societies",
answer: "B. commercial bank",
correctLetter: "B",
correctOption: 2,
},

{
id: "question50",
question:  "50. Which of the following problems of agriculture could be solved through farmers’ adoption of research findings?",
A: "Unpredictable climate",
B: "Environmental degradation",
C: "Poor extension services",
D: "Insufficient basic amenities",
answer: "C. Poor extension services",
correctLetter: "C",
correctOption: 3,
},


]