export const AGRICULTURALSCIENCEA2006 = [

{
id: "question1",
question:  "1. An important role of agriculture to national economy is the provision of",
A: "new and improved plant varieties.",
B: "feeder roads linking farms and urban centres.",
C: "raw materials for industries.",
D: "storage facilities for farm produce.",
answer: "C. Raw materials for industries",
correctLetter: "C",
correctOption: 3,
},

{
id: "question2",
question:  "2. Which of the following statements is true about subsistence fanning? It",
A: "provides surplus capital for investment.",
B: "provides enough food for the family.",
C: "encourages industrialization.",
D: "encourages farm mechanization.",
answer: "B. Provides enough food for the family",
correctLetter: "B",
correctOption: 2,
},

{
id: "question3",
question:  "3. What is the purpose of wildlife conservation?",
A: "Keeping animals in forests",
B: "Preventing the extinction of some wild animals",
C: "Ensuring that hunters always have some games",
D: "Preventing wild animals from destroying crops",
answer: "B. Preventing the extinction of some wild animals",
correctLetter: "B",
correctOption: 2,
},

{
id: "question4",
question:  "4. Governments of West African countries can promote the production of cash crops by",
A: "promoting the traditional farming methods.",
B: "offering higher prices to producers.",
C: "trimming down the number of farmers.",
D: "restricting the importation of food crops.",
answer: "B. Offering higher prices to producers",
correctLetter: "B",
correctOption: 2,
},

{
id: "question5",
question:  "5. Which of the following statements is not a problem of communal land tenure system?",
A: "Redemption of the land",
B: "Lack of permanent ownership of land",
C: "Disagreement among family members",
D: "Excessive fragmentation of land",
answer: "A. Redemption of the land",
correctLetter: "A",
correctOption: 1,
},

{
id: "question6",
question:  "6. Which of the following uses of land should be given priority in environmental protection?",
A: "Recreation",
B: "Forestry",
C: "Siting industries",
D: "Road construction",
answer: "B. Forestry",
correctLetter: "B",
correctOption: 2,
},

{
id: "question7",
question:  "7. The following factors influence the use of land for extensive sheep rearing except",
A: "rainfall.",
B: "light intensity.",
C: "population density.",
D: "topography.",
answer: "B. Light intensity",
correctLetter: "B",
correctOption: 2,
},

{
id: "question8",
question:  "8. Which of the following factors will not affect availability of land for agriculture?",
A: "Population density",
B: "Expansion of industries",
C: "Topography",
D: "Climate",
answer: "D. Climate",
correctLetter: "D",
correctOption: 4,
},

{
id: "question9",
question:  "9. Which of the following conditions will cause the greatest discomfort in livestock?",
A: "High temperature and high humidity",
B: "Low temperature and high humidity",
C: "High temperature and high rainfall",
D: "Low temperature and low pressure",
answer: "A. High temperature and high humidity",
correctLetter: "A",
correctOption: 1,
},

{
id: "question10",
question:  "10. An important biotic factor which influences agricultural production is",
A: "soil structure.",
B: "wind.",
C: "temperature.",
D: "predators.",
answer: "D. Predators",
correctLetter: "D",
correctOption: 4,
},

{
id: "question11",
question:  "11. In soil formation, the main factor that determines texture is",
A: "vegetation.",
B: "topography.",
C: "climate.",
D: "parent rock.",
answer: "D. Parent rock",
correctLetter: "D",
correctOption: 4,
},

{
id: "question12",
question:  "12. The term topography refers to the",
A: "altitude of a land.",
B: "type of vegetation on a land.",
C: "soil profile.",
D: "shape of a land.",
answer: "D. Shape of a land",
correctLetter: "D",
correctOption: 4,
},

{
id: "question13",
question:  "13. The following are types of soil structure except",
A: "platy.",
B: "granular.",
C: "prismatic.",
D: "gravel.",
answer: "D. Gravel",
correctLetter: "D",
correctOption: 4,
},

{
id: "question14",
question:  "14. Rhizobium bacteria are important in the nitrogen cycle because they",
A: "burrow into the soil and enhance percolation.",
B: "destroy the roots of legumes to release nitrogen.",
C: "fix atmospheric nitrogen in the soil.",
D: "cause root-knots in legumes.",
answer: "C. Fix atmospheric nitrogen in the soil",
correctLetter: "C",
correctOption: 3,
},

{
id: "question15",
question:  "15. The chemical component of wood ash are",
A: "potassium and carbonate.",
B: "calcium and chloride.",
C: "potassium and chloride.",
D: "calcium and carbonate.",
answer: "A. Potassium and carbonate",
correctLetter: "A",
correctOption: 1,
},

{
id: "question16",
question:  "16. Which of the following statements about crop rotation is not true?",
A: "Use of fertilizer is of paramount importance.",
B: "The land is put under continuous cultivation.",
C: "Legume is always included in the rotation.",
D: "Plants are at minimal level of pest and disease attack.",
answer: "A. Use of fertilizer is of paramount importance",
correctLetter: "A",
correctOption: 1,
},

{
id: "question17",
question:  "17. The growing of the same crop on the same piece of land every year is referred to as",
A: "monoculture.",
B: "ley farming.",
C: "mixed farming.",
D: "inter-cropping.",
answer: "A. Monoculture",
correctLetter: "A",
correctOption: 1,
},

{
id: "question18",
question:  "18. Which source of farm power is most flexible and adaptable to farm operations?",
A: "Animal",
B: "Wind",
C: "Human",
D: "Solar",
answer: "C. Human",
correctLetter: "C",
correctOption: 3,
},

{
id: "question19",
question:  "19. A farm tool that is not required in the construction of a nesting box is",
A: "the hammer.",
B: "the spade.",
C: "a drill.",
D: "a chisel.",
answer: "B. The spade",
correctLetter: "B",
correctOption: 2,
},

{
id: "question20",
question:  "20. A tractor derives its power from",
A: "an internal combustion engine.",
B: "an external combustion engine.",
C: "a standby generator.",
D: "an electric motor.",
answer: "A. An internal combustion engine",
correctLetter: "A",
correctOption: 1,
},

{
id: "question21",
question:  "21. Which of the following is not used for farm survey?",
A: "Measuring tape",
B: "Lenses",
C: "Offset staff",
D: "Theodolite",
answer: "B. Lenses",
correctLetter: "B",
correctOption: 2,
},

{
id: "question22",
question:  "22. A farmer conducts surveying for the following reasons except",
A: "determining the location of agricultural structures.",
B: "locating sites for drainage canals.",
C: "setting out areas of farm land.",
D: "determining the height of farmstead.",
answer: "D. Determining the height of farmstead",
correctLetter: "D",
correctOption: 4,
},

{
id: "question23",
question:  "23. Which of the following groups of crops comprises only oil crops?",
A: "Groundnut, jute and sunflower",
B: "Soyabean, coconut and groundnut",
C: "Sunflower, cotton and jute",
D: "Coconut, cotton and sisal hemp",
answer: "B. Soyabean, coconut, and groundnut",
correctLetter: "B",
correctOption: 2,
},

{
id: "question24",
question:  "24. The yield of latex from a rubber tree depends on the following factors except",
A: "skill of tapping.",
B: "amount of bark removed at each tapping.",
C: "age of the tree.",
D: "prevailing environmental conditions.",
answer: "D. Prevailing environmental conditions",
correctLetter: "D",
correctOption: 4,
},

{
id: "question25",
question:  "25. The best time for transplanting rice seedlings is in the morning or evening hours because",
A: "photosynthesis can only take place at these periods.",
B: "there is less heat in the mornings and evenings.",
C: "there is less moisture in the soil at those times of the day.",
D: "transpirational losses are minimal then.",
answer: "B. There is less heat in the mornings and evenings",
correctLetter: "B",
correctOption: 2,
},

{
id: "question26",
question:  "26. The characteristics of a good pasture include the following except",
A: "ability to withstand extremes of climate.",
B: "ability to produce high quality fresh leaves.",
C: "high palatability.",
D: "high stem to leave ratio.",
answer: "D. High stem-to-leaf ratio",
correctLetter: "D",
correctOption: 4,
},

{
id: "question27",
question:  "27. Which of the following maintenance practices will ensure proper utilization of a cultivated pastun",
A: "Allowing animals to graze pasture freely",
B: "Burning pasture periodically",
C: "Allowing forage crops to overgrow",
D: "Regulating grazing by animals",
answer: "D. Regulating grazing by animals",
correctLetter: "D",
correctOption: 4,
},

{
id: "question28",
question:  "28. Which of the following is not a protective function of a forest?",
A: "Wind break",
B: "Soil conservation",
C: "Purification of air",
D: "Reducing impact of raindrops",
answer: "C. Purification of air",
correctLetter: "C",
correctOption: 3,
},

{
id: "question29",
question:  "29. The growing of forest trees and arable crops on the same piece of land at the same time is termed",
A: "ley cropping.",
B: "mixed farming.",
C: "afforestation.",
D: "taungya system.",
answer: "D. Taungya system",
correctLetter: "D",
correctOption: 4,
},

{
id: "question30",
question:  "30. The most effective way of controlling fusarium wilt disease in tomatoes is by",
A: "fumigating the soil.",
B: "removing weeds.",
C: "spraying plants with insecticides.",
D: "rouging affected plants.",
answer: "D. Rouging affected plants",
correctLetter: "D",
correctOption: 4,
},

{
id: "question31",
question:  "31. Which of the following plant diseases is correctly matched with its causal organism?",
A: "Damping off-bacteria",
B: "Rosette-virus",
C: "Swollen shoot-fungus",
D: "Leaf mosaic-fungus",
answer: "B. Rosette-virus",
correctLetter: "B",
correctOption: 2,
},

{
id: "question32",
question:  "32. The red-rot disease of sugar cane is caused by",
A: "virus.",
B: "aphid.",
C: "fungus.",
D: "protozoon.",
answer: "C. Fungus",
correctLetter: "C",
correctOption: 3,
},

{
id: "question33",
question:  "33. Which of the following insect-pests has piercing and sucking mouthparts?",
A: "Cotton stainer",
B: "Caterpillar",
C: "Beetle",
D: "Grasshopper",
answer: "A. Cotton stainer",
correctLetter: "A",
correctOption: 1,
},

{
id: "question34",
question:  "34. The disease control practice that relies on the introduction of parasites and predators is",
A: "cultural.",
B: "chemical.",
C: "biological.",
D: "host resistance.",
answer: "C. Biological",
correctLetter: "C",
correctOption: 3,
},

{
id: "question35",
question:  "35. The term instar refers to a developmental stage of a/an",
A: "fish.",
B: "insect.",
C: "plant.",
D: "rabbit.",
answer: "B. Insect",
correctLetter: "B",
correctOption: 2,
},

{
id: "question36",
question:  "36. The major field pests of rice are",
A: "birds.",
B: "army worms.",
C: "rodents.",
D: "grasshoppers.",
answer: "A. Birds",
correctLetter: "A",
correctOption: 1,
},

{
id: "question37",
question:  "37. From the cross between a white maize and a yellow maize, a white maize was produced, tl indicates that the gene for white colour is",
A: "heterozygous.",
B: "recessive.",
C: "dominant.",
D: "homozygous.",
answer: "C. Dominant",
correctLetter: "C",
correctOption: 3,
},

{
id: "question38",
question:  "38. The genotype of the maize plant resulting from the cross is",
A: "Wwy.",
B: "ww.",
C: "Wy.",
D: "yy.",
answer: "A. Ww",
correctLetter: "A",
correctOption: 1,
},

{
id: "question39",
question:  "39. The gametes from the parent white maize plant are",
A: "W and W.",
B: "y and y.",
C: "W and y.",
D: "y and W.",
answer: "A. W and W",
correctLetter: "A",
correctOption: 1,
},

{
id: "question40",
question:  "40. The length of the oestrous cycle in sow is",
A: "7 days.",
B: "14 days.",
C: "21 days.",
D: "28 days.",
answer: "C. 21 days",
correctLetter: "C",
correctOption: 3,
},

{
id: "question41",
question:  "41. When the vulva of a farm animal is observed to be red and swollen with mucous discharge, it should be",
A: "introduced to a mature male animal.",
B: "treated for sexually transmitted disease.",
C: "treated for mastitis.",
D: "slaughtered and buried.",
answer: "A. Introduced to a mature male animal",
correctLetter: "A",
correctOption: 1,
},

{
id: "question42",
question:  "42. Progesterone is otherwise called",
A: "pregnancy hormone.",
B: "placental hormone.",
C: "oestrus hormone.",
D: "follicle stimulating hormone.",
answer: "A. Pregnancy hormone",
correctLetter: "A",
correctOption: 1,
},

{
id: "question43",
question:  "43. A cattle breed with huge and bulbous horns found around Lake Chad is the",
A: "Bororo.",
B: "Bornu Red.",
C: "White Fulani.",
D: "Kuri.",
answer: "D. Kuri",
correctLetter: "D",
correctOption: 4,
},

{
id: "question44",
question:  "44. Which of the following is not a breed of rabbit?",
A: "New Zealand white",
B: "California white",
C: "N’dama",
D: "Chinchilla",
answer: "C. N’dama",
correctLetter: "C",
correctOption: 3,
},

{
id: "question45",
question:  "45. Which of the following farm animals is not a castrate?",
A: "Bullock",
B: "Wether",
C: "Hog",
D: "Buck",
answer: "D. Buck",
correctLetter: "D",
correctOption: 4,
},

{
id: "question46",
question:  "46. Ruminants should be fed hay ration before turning them onto lush pasture to prevent",
A: "ricket.",
B: "bloat.",
C: "red-water disease.",
D: "pleuropneumonia.",
answer: "B. Bloat",
correctLetter: "B",
correctOption: 2,
},

{
id: "question47",
question:  "47. The two blind sacs at the junction of the small and large intestines of birds is/are known as",
A: "caeca.",
B: "colon.",
C: "jejunum.",
D: "cloaca.",
answer: "A. Caeca",
correctLetter: "A",
correctOption: 1,
},

{
id: "question48",
question:  "48. The process by which grasses are cut, fermented and later fed to livestock is termed",
A: "composting.",
B: "hay-making",
C: "ensiling.",
D: "green manuring.",
answer: "C. Ensiling",
correctLetter: "C",
correctOption: 3,
},

{
id: "question49",
question:  "49. The number of animals that can be conveniently fed on a hectare of pasture in a given time is known as …",
A: "carrying capacity.",
B: "stocking density.",
C: "herd size.",
D: "stock distribution.",
answer: "A. Carrying capacity",
correctLetter: "A",
correctOption: 1,
},

{
id: "question50",
question:  "50. Which of the following insects is a vector of Trypanosomiasis?",
A: "Housefly",
B: "Mosquito",
C: "Tsetsefly",
D: "Blackfly",
answer: "C. Tsetse fly",
correctLetter: "C",
correctOption: 3,
},

{
id: "question51",
question:  "51. Which of the following livestock parasites possesses proglottides?",
A: "Roundworm",
B: "Tick",
C: "Tapeworm",
D: "Liver fluke",
answer: "C. Tapeworm",
correctLetter: "C",
correctOption: 3,
},

{
id: "question52",
question:  "52. The term Fingerling refers to a young",
A: "rabbit.",
B: "duck.",
C: "fish.",
D: "goat.",
answer: "C. Fish",
correctLetter: "C",
correctOption: 3,
},

{
id: "question53",
question:  "53. The practice of mating a sire to its female offspring is known as",
A: "inbreeding.",
B: "cross breeding.",
C: "line-breeding.",
D: "out-breeding.",
answer: "A. Inbreeding",
correctLetter: "A",
correctOption: 1,
},

{
id: "question54",
question:  "54. Cross breeding in livestock results in the following effects except",
A: "suppression of recessive genes.",
B: "production of hybrid vigour in offspring.",
C: "higher yield in offspring than the parents.",
D: "complete removal of recessive genes from a herd.",
answer: "D. Complete removal of recessive genes from a herd",
correctLetter: "D",
correctOption: 4,
},

{
id: "question55",
question:  "55. In a farm enterprise, which of the following is a fixed capital?",
A: "Drums of insecticide",
B: "Labour force on the farm",
C: "Money for running the farm",
D: "Combine harvester",
answer: "D. Combine harvester",
correctLetter: "D",
correctOption: 4,
},

{
id: "question56",
question:  "56. In agricultural production, the law of diminishing returns sets in when",
A: "an increase in the variable factor leads to a decrease in the marginal returns.",
B: "an increase in the variable factor leads to an increase in the marginal returns.",
C: "the total product increases as more variable factor is added.",
D: "there is no change in the farmer’s revenue.",
answer: "A. An increase in the variable factor leads to a decrease in the marginal returns",
correctLetter: "A",
correctOption: 1,
},

{
id: "question57",
question:  "57. From the diagram below, determine the equilibrium price",
A: "01.00",
B: "02.00",
C: "03.00",
D: "04.00",
answer: "C. (Provide diagram details for precise answer.)",
correctLetter: "C",
correctOption: 3,
},

{
id: "question58",
question:  "58. Determine the equilibrium quantity of the produce from the diagram above in question 57",
A: "4.00 kg.",
B: "3.00 kg.",
C: "2.00 kg.",
D: "1.00",
answer: "C. (Provide diagram details for precise answer.)",
correctLetter: "C",
correctOption: 3,
},

{
id: "question59",
question:  "59. The flow of farm produce from farmers to consumers can be referred to as",
A: "financing.",
B: "marketing.",
C: "extension.",
D: "promotion.",
answer: "B. Marketing",
correctLetter: "B",
correctOption: 2,
},

{
id: "question60",
question:  "60. The best method of introducing a new herbicide to rural farmers is through",
A: "mass media.",
B: "farmers’ cooperatives.",
C: "demonstration.",
D: "circular letters.",
answer: "C. Demonstration",
correctLetter: "C",
correctOption: 3,
},


]