export const GOVERNMENTA2014 = [

{
id: "question1",
question:  "1. Government protects the lives and property of the citizens of a state through the",
A: "courts and the police",
B: "legislature and prisons",
C: "ministers and the police",
D: "customs and the police",
answer: "A. courts and the police",
correctLetter: "A",
correctOption: 1,
},

{
id: "question2",
question:  "2. Political power could be acquired through",
A: "persuasion",
B: "election",
C: "sanction",
D: "nomination",
answer: "B. election",
correctLetter: "B",
correctOption: 2,
},

{
id: "question3",
question:  "3. Which of the following countries in Africa practised socialism?",
A: "Nigeria",
B: "Togo",
C: "Tanzania",
D: "Kenya",
answer: "C. Tanzania",
correctLetter: "C",
correctOption: 3,
},

{
id: "question4",
question:  "4. Nazism was introduced by",
A: "Adolf Hitler",
B: "Tsar Nichilas ll",
C: "Karl Marx",
D: "Mao-Tse-Tung",
answer: "A. Adolf Hitler",
correctLetter: "A",
correctOption: 1,
},

{
id: "question5",
question:  "5. The following are merits of separation of powers except",
A: "abuse of power",
B: "freedom and liberty",
C: "stable political system",
D: "absence of dominance",
answer: "A. abuse of power",
correctLetter: "A",
correctOption: 1,
},

{
id: "question6",
question:  "6. Which of the following is not a merit of checks and balances?",
A: "prevents excessive use of power",
B: "has respect for human rights",
C: "encourages the use of veto power",
D: "prevents dictatorship",
answer: "C. encourages the use of veto power",
correctLetter: "C",
correctOption: 3,
},

{
id: "question7",
question:  "7. Representative government is alternatively called",
A: "rule of law",
B: "indirect democracy",
C: "separation of powers",
D: "classical democracy",
answer: "B. indirect democracy",
correctLetter: "B",
correctOption: 2,
},

{
id: "question8",
question:  "8. A constitution is a",
A: "set of regulations and customs",
B: "body of doctrine and principles",
C: "set of principles and customs",
D: "body of rules, regulations and conventions",
answer: "D. body of rules, regulations and conventions",
correctLetter: "D",
correctOption: 4,
},

{
id: "question9",
question:  "9. A feature of rigid constitution is that it requires",
A: "amendment by the judiciary",
B: "one-third majority for its amendment",
C: "special amendment procedures",
D: "the votes of electorate for its amendment",
answer: "C. special amendment procedures",
correctLetter: "C",
correctOption: 3,
},

{
id: "question10",
question:  "10. A characteristic of a federal system of government is that power is",
A: "shared between the central and unit governments",
B: "shared between the component units of government",
C: "held by the national government",
D: "held by the state government",
answer: "A. shared between the central and unit governments",
correctLetter: "A",
correctOption: 1,
},

{
id: "question11",
question:  "11. In a federal system of government, education and health are examples of",
A: "separation of powers",
B: "reserved powers",
C: "concurrent powers",
D: "exclusive powers",
answer: "C. concurrent powers",
correctLetter: "C",
correctOption: 3,
},

{
id: "question12",
question:  "12. Which of the following is not a function of the judiciary?",
A: "settlement of disputes",
B: "maintenance of law and order",
C: "interpretation of law",
D: "protection of right",
answer: "B. maintenance of law and order (This is primarily a function of law enforcement agencies, not the judiciary.)",
correctLetter: "B",
correctOption: 2,
},

{
id: "question13",
question:  "13. Statutes are",
A: "bills passed by local governments",
B: "laws passed by the judiciary",
C: "bills passed by the executive",
D: "laws passed by the parliament",
answer: "D. laws passed by the parliament",
correctLetter: "D",
correctOption: 4,
},

{
id: "question14",
question:  "14. Slander limits a citizen’s freedom of",
A: "expression",
B: "movement",
C: "association",
D: "religion",
answer: "A. expression",
correctLetter: "A",
correctOption: 1,
},

{
id: "question15",
question:  "15. Which of the following bodies has the right to change the laws of the country? The",
A: "Judiciary",
B: "Ombudsman",
C: "Legislature",
D: "Executive",
answer: "C. Legislature",
correctLetter: "C",
correctOption: 3,
},

{
id: "question16",
question:  "16. All the following are sources of revenue of a political party except",
A: "payment of dues",
B: "donations",
C: "custom duties",
D: "fundraising",
answer: "C. custom duties",
correctLetter: "C",
correctOption: 3,
},

{
id: "question17",
question:  "17. Party manifesto is important in the following ways except to",
A: "evaluate the party",
B: "limit choice",
C: "attract people",
D: "guide the party",
answer: "B. limit choice",
correctLetter: "B",
correctOption: 2,
},

{
id: "question18",
question:  "18. Coalition government can be defined as parties coming together",
A: "to appoint a leader",
B: "to form a government",
C: "with a common manifesto",
D: "to oppose the government",
answer: "B. to form a government",
correctLetter: "B",
correctOption: 2,
},

{
id: "question19",
question:  "19. Which of the following West African countries practised a one-party system?",
A: "Benin",
B: "Nigeria",
C: "Ghana",
D: "Liberia",
answer: "C. Ghana",
correctLetter: "C",
correctOption: 3,
},

{
id: "question20",
question:  "20. In a limited franchise, restriction on voting can be based on",
A: "height",
B: "property",
C: "strength",
D: "exposure",
answer: "B. property",
correctLetter: "B",
correctOption: 2,
},

{
id: "question21",
question:  "21. Which of the following is a limitation to Universal Adult Suffrage?",
A: "Wealth",
B: "Age",
C: "Race",
D: "Sex",
answer: "B. Age",
correctLetter: "B",
correctOption: 2,
},

{
id: "question22",
question:  "22. Which of the following is an example of a general election?",
A: "Bye-election",
B: "Presidential election",
C: "Local election",
D: "Student union election",
answer: "B. Presidential election",
correctLetter: "B",
correctOption: 2,
},

{
id: "question23",
question:  "23. The purpose of an election is to",
A: "allow people to participate in choosing their leaders",
B: "provide social amenities for the electorate",
C: "give political education to the rich",
D: "allow the counting of votes in public",
answer: "A. allow people to participate in choosing their leaders",
correctLetter: "A",
correctOption: 1,
},

{
id: "question24",
question:  "24. Universal Adult Suffrage is popular because it",
A: "allows for equal political representation",
B: "allows for greater political participation",
C: "encourages a multi-party system",
D: "ensures equal performance of all poltical parties",
answer: "B. allows for greater political participation",
correctLetter: "B",
correctOption: 2,
},

{
id: "question25",
question:  "25. Which of the following is not a factor that promotes democratic electoral system?",
A: "political consciousness",
B: "periodic election",
C: "up-to-date electoral register",
D: "popularity of the governor",
answer: "D. popularity of the governor (The popularity of a governor is not a determinant of a democratic electoral system.)",
correctLetter: "D",
correctOption: 4,
},

{
id: "question26",
question:  "26. Which of the following is not a factor that promotes democratic electoral system?",
A: "political consciousness",
B: "periodic election",
C: "up-to-date electoral register",
D: "popularity of the governor",
answer: "D. popularity of the governor (The popularity of a governor is not a determinant of a democratic electoral system.)",
correctLetter: "D",
correctOption: 4,
},

{
id: "question27",
question:  "27. A factor that could make elections to be free and fair is the",
A: "existence of dependent electoral commission",
B: "adoption of a flexible consitution",
C: "opportunity for people to vote twice",
D: "registration of eligible voters",
answer: "D. registration of eligible voters",
correctLetter: "D",
correctOption: 4,
},

{
id: "question28",
question:  "28. The body responsible for conducting and supervising elections in West African countries is called",
A: "ombudsman",
B: "electoral commission",
C: "election observers",
D: "constituent assembly",
answer: "B. electoral commission",
correctLetter: "B",
correctOption: 2,
},

{
id: "question29",
question:  "29. Which of the following is not an aim of pressure groups?",
A: "Contesting election",
B: "Agitating for interests",
C: "Influencing government decision",
D: "Educating their members",
answer: "A. Contesting election",
correctLetter: "A",
correctOption: 1,
},

{
id: "question30",
question:  "30. Which of the following is not a problem of an electoral commission in West Africa?",
A: "Electoral malpractices",
B: "Inadequate personnel",
C: "Inadequate funds",
D: "Registration of voters",
answer: "A. Electoral malpractices",
correctLetter: "A",
correctOption: 1,
},

{
id: "question31",
question:  "31. A pressure group formed only by teachers is",
A: "a promotional group",
B: "an occupational group",
C: "a religious group",
D: "an economic group",
answer: "B. an occupational group",
correctLetter: "B",
correctOption: 2,
},

{
id: "question32",
question:  "32. Neutrality in the civil service means that",
A: "the government can seek or replace top civil servants",
B: "officials can only be removed from office due to ill-health",
C: "civil servants should be loyal to the government and non-partisan",
D: "officials need to defend the budget in parliament",
answer: "C. civil servants should be loyal to the government and non-partisan",
correctLetter: "C",
correctOption: 3,
},

{
id: "question33",
question:  "33. Red-tapism in the civil service is a product of",
A: "democracy",
B: "autocracy",
C: "bureaucracy",
D: "theocracy",
answer: "C. bureaucracy",
correctLetter: "C",
correctOption: 3,
},

{
id: "question34",
question:  "34. The central government can reduce annual subventions to public corporations through",
A: "parliamentary control",
B: "ministerial control",
C: "judicial control",
D: "public control",
answer: "A. parliamentary control",
correctLetter: "A",
correctOption: 1,
},

{
id: "question35",
question:  "35. Collection of rates is a source of revenue to",
A: "civil servants",
B: "public corporation",
C: "local authorities",
D: "central government",
answer: "C. local authorities",
correctLetter: "C",
correctOption: 3,
},

{
id: "question36",
question:  "36. The money given by the central government to local authorities is known as",
A: "block grants",
B: "capital expenditure",
C: "loans",
D: "royalties",
answer: "A. block grants",
correctLetter: "A",
correctOption: 1,
},

{
id: "question37",
question:  "37. The laws of the pre-colonial African system were",
A: "written",
B: "codified",
C: "unwritten",
D: "rigid",
answer: "C. unwritten",
correctLetter: "C",
correctOption: 3,
},

{
id: "question38",
question:  "38. Auditing the accounts of public corporations amounts to",
A: "media control",
B: "judicial control",
C: "public control",
D: "financial control",
answer: "D. financial control",
correctLetter: "D",
correctOption: 4,
},

{
id: "question39",
question:  "39. The following were features of the French policy of Assimilation except",
A: "centralized administration",
B: "recognition of chieftaincy institution",
C: "limited education",
D: "indigent policy",
answer: "B. recognition of chieftaincy institution",
correctLetter: "B",
correctOption: 2,
},

{
id: "question40",
question:  "40. The recurrent coups in West African countries resulted in",
A: "dictatorship",
B: "politacal instability",
C: "nepotism",
D: "poor conditions in the army",
answer: "B. politacal instability",
correctLetter: "B",
correctOption: 2,
},

{
id: "question41",
question:  "41. Foreign policy refers to the",
A: "policy made by a foreign country",
B: "policy made by a country for foreigners",
C: "principles that govern a country when it is at war",
D: "principle that governs a state’s international behaviour",
answer: "D. principle that governs a state’s international behaviour",
correctLetter: "D",
correctOption: 4,
},

{
id: "question42",
question:  "42. Which of the following is a factor for the adoption of a unitary system of government in some West African countries?",
A: "Vast territories",
B: "small territories",
C: "Abundant resources",
D: "Heterogeneous culture",
answer: "B. small territories",
correctLetter: "B",
correctOption: 2,
},

{
id: "question43",
question:  "43. Which of the following countries is a permanent member of the Security Council of the United Nations Organization (UNO)?",
A: "Germany",
B: "Japan",
C: "Canada",
D: "Russia",
answer: "D. Russia",
correctLetter: "D",
correctOption: 4,
},

{
id: "question44",
question:  "44. The United Nations Organization (UNO)came into existence in",
A: "1945",
B: "1948",
C: "1950",
D: "1953",
answer: "A. 1945",
correctLetter: "A",
correctOption: 1,
},

{
id: "question45",
question:  "45. The Commonwealth is",
A: "an economic organization for the Caribbean",
B: "a political organization formed during the First World War",
C: "made up of all independent ex-colonies of Britain",
D: "made up of independent European Countries",
answer: "C. made up of all independent ex-colonies of Britain",
correctLetter: "C",
correctOption: 3,
},

{
id: "question46",
question:  "46. The head of the Commonwealth of Nations is",
A: "German Chancellor",
B: "President of America",
C: "Queen of England",
D: "British Prime Minister",
answer: "C. British Monarch",
correctLetter: "C",
correctOption: 3,
},

{
id: "question47",
question:  "47. A Commonwealth member that has no colonial link with the United Kingdom is",
A: "Nigeria",
B: "Kenya",
C: "Ghana",
D: "Mozambique",
answer: "D. Mozambique",
correctLetter: "D",
correctOption: 4,
},

{
id: "question48",
question:  "48. The meetings of the Commonwealth of Nations are held once every",
A: "six years",
B: "five years",
C: "three years",
D: "two years",
answer: "D. two years",
correctLetter: "D",
correctOption: 4,
},

{
id: "question49",
question:  "49. The ECOWAS Fund for Co-operation, Compensation and Development is located in",
A: "Togo",
B: "Nigeria",
C: "The Gambia",
D: "Sierra Leone.",
answer: "Z. zzzzzzzzzzzzzzzzz",
correctLetter: "Z",
correctOption: 9,
},

{
id: "question50",
question:  "50. The organ responsible for investigating internal disputes in the United Nations Organization (UNO) is the",
A: "General Assembly",
B: "Security Council",
C: "Secretariat",
D: "Economic and Social Councul",
answer: "B. Lagos",
correctLetter: "B",
correctOption: 2,
},


]